** 左联时期参加的三次论争
   :PROPERTIES:
   :CUSTOM_ID: chap3
   :END:

*** 「嘘」梁实秋
    :PROPERTIES:
    :CUSTOM_ID: chap3sec1
    :END:

**** 卢梭和胃口
     :PROPERTIES:
     :CUSTOM_ID: 19271227
     :END:

做过《民约论》的卢梭，自从他还未死掉的时候起，便受人们的责备和迫害，直到现在，责备终于没有完。连在和“民约”没有什么关系的中华民国，也难免这一幕了。

例如商务印书馆出版的《爱弥尔》中文译本的序文上，就说“……本书的第五编即女子教育，他的主张非但不彻底，而且不承认女子的人格，与前四编的尊重人类相矛盾。……所以在今日看来，他对于人类正当的主张，可说只树得一半……。”

然而复旦大学出版的《复旦旬刊》创刊号上梁实秋教授的意思，却“稍微有点不同”了。其实岂但“稍微”而已耶，乃是“卢梭论教育，无一是处，唯其论女子教育，的确精当。”

因为那是“根据于男女的性质与体格的差别而来”的。而近代生物学和心理学研究的结果，又证明著天下没有两个人是无差别。怎样的人就该施以怎样的教育。

所以，梁先生说——

“我觉得‘人’字根本的该从字典里永远注销，或由政府下令永禁行使。因为‘人’字的意义太糊涂了。聪明绝顶的人，我们叫他做人，蠢笨如牛的人，也一样的叫做人，弱不禁风的女子，叫做人，粗横强大的男人，也叫做人，人里面的三流九等，无一非人。近代的德谟克拉西的思想，平等的观念，其起源即由于不承认人类的差别。近代所谓的男女平等运动，其起源即由于不承认男女的差别。人格是一个抽象名词，是一个人的身心各方面的特点的总和。人的身心各方面的特点既有差别，实即人格上亦有差别。所谓侮辱人格的，即是不承认一个人特有的人格，卢梭承认女子有女子的人格，所以卢梭正是尊重女子的人格。抹杀女子所特有之特性者，才是侮辱女子人格。”

于是势必至于得到这样的结论——

“……正当的女子教育应该是使女子成为完全的女子。”

那么，所谓正当的教育者，也应该是使“弱不禁风”者，成为完全的“弱不禁风”，“蠢笨如牛”者，成为完全的“蠢笨如牛”，这才免于侮辱各人——此字在未经从字典里永远注销，政府下令永禁行使之前，暂且使用——的人格了。卢梭《爱弥尔》前四编的主张不这样，其“无一是处”，于是可以算无疑。

但这所谓“无一是处”者，也只是对于“聪明绝顶的人”而言；在“蠢笨如牛的人”，却是“正当”的教育。因为看了这样的议论，可以使他更渐近于完全“蠢笨如牛”。这也就是尊重他的人格。

然而这种议论还是不会完结的。为什么呢？一者，因为即使知道说“自然的不平等”，而不容易明白真“自然”和“因积渐的人为而似自然”之分。二者，因为凡有学说，往往“合吾人之胃口者则容纳之，且从而宣扬之”也。

上海一隅，前二年大谈亚诺德，今年大谈白璧德，恐怕也就是胃口之故罢。

许多问题大抵发生于“胃口”，胃口的差别，也正如“人”字一样的——其实这两字也应该呈请政府“下令永禁行使”。我且抄一段同是美国的UptonSinclair的，以尊重另一种人格罢——

“无论在那一个卢梭的批评家，都有首先应该解决的唯一的问题。为什么你和他吵闹的？要为他的到达点的那自由，平等，调协开路么？还是因为畏惧卢梭所发向世界上的新思想和新感情的激流呢？使对于他取了为父之劳的个人主义运动的全体怀疑，将我们带到子女服从父母，奴隶服从主人，妻子服从丈夫，臣民服从教皇和皇帝，大学生毫不发生疑问，而佩服教授的讲义的善良的古代去，乃是你的目的么？

“阿嶷夫人曰：‘最后的一句，好像是对于白璧德教授的一箭似的。’

“‘奇怪呀，’她的丈夫说。‘斯人也而有斯姓也……那一定是上帝的审判了。’”

不知道和原意可有错误，因为我是从日本文重译的。书的原名是《Mammon art》，在California的Pasadena作者自己出版，胃口相近的人们自己弄来看去罢。Mammon是希腊神话里的财神，art谁都知道是艺术。可以译作“财神艺术”罢。日本的译名是“拜金艺术”，也行。因为这一个字是作者生造的，政府既没有下令颁行，字典里也大概未曾注入，所以姑且在这里加一点解释。

**** 文学和出汗
     :PROPERTIES:
     :CUSTOM_ID: 19280114
     :END:


上海的教授對人講文學，以為文學當描寫永遠不變的人性，否則便不久長。例如英國，莎士比亞和別的一兩個人所寫的是永久不變的人性，所以至今流傳，其余的不這樣，就都消滅了雲。

這真是所謂“你不說我倒還明白，你越說我越胡塗”了。

英國有許多先前的文章不流傳，我想，這是總會有的，但竟沒有想到它們的消滅，乃因為不寫永久不變的人性。現在既然知道了這一層，卻更不解它們既已消滅，現在的教授何從看見，卻居然斷定它們所寫的都不是永久不變的人性了。

只要流傳的便是好文學，只要消滅的便是壞文學；搶得天下的便是王，搶不到天下的便是賊。莫非中國式的歷史論，也將溝通了中國人的文學論歟？

而且，人性是永久不變的麽？

類人猿，類猿人，原人，古人，今人，未來的人，……

如果生物真會進化，人性就不能永久不變。不說類猿人，就是原人的脾氣，我們大約就很難猜得著的，則我們的脾氣，恐怕未來的人也未必會明白。要寫永久不變的人性，實在難哪。

譬如出汗罷，我想，似乎於古有之，於今也有，將來一定暫時也還有，該可以算得較為“永久不變的人性”了。然而“弱不禁風”的小姐出的是香汗，“蠢笨如牛”的工人出的是臭汗。不知道倘要做長留世上的文字，要充長留世上的文學家，是描寫香汗好呢，還是描寫臭汗好？這問題倘不先行解決，則在將來文學史上的位置，委實是“岌岌乎殆哉”。

聽說，例如英國，那小說，先前是大抵寫給太太小姐們看的，其中自然是香汗多；到十九世紀後半，受了俄國文學的影響，就很有些臭汗氣了。那一種的命長，現在似乎還在不可知之數。

在中國，從道士聽論道，從批評家聽談文，都令人毛孔痙攣，汗不敢出。然而這也許倒是中國的“永久不變的人性”罷。

**** 「硬译」与「文学的阶级性」
     :PROPERTIES:
     :CUSTOM_ID: 19300301
     :END:

**一**

聽說《新月》月刊團體裏的人們在說，現在銷路好起來了。這大概是真的，以我似的交際極少的人，也在兩個年青朋友的手裏見過第二卷第六七號的合本。順便一翻，是爭“言論自由”的文字和小說居多。近尾巴處，則有梁實秋先生的一篇《論魯迅先生的“硬譯”》，以為“近於死譯”。而“死譯之風也斷不可長”，就引了我的三段譯文，以及在《文藝與批評》的後記裏所說：“但因為譯者的能力不夠，和中國文本來的缺點，譯完一看，晦澀，甚而至於難解之處也真多；倘將仂句拆下來呢，又失了原來的語氣。在我，是除了還是這樣的硬譯之外，只有束手這一條路了，所余的惟一的希望，只在讀者還肯硬著頭皮看下去而已”這些話，細心地在字旁加上圓圈，還在“硬譯”兩字旁邊加上套圈，於是“嚴正”地下了“批評”道：“我們‘硬著頭皮看下去’了，但是無所得。‘硬譯’和‘死譯’有什麽分別呢？”

新月社的聲明中，雖說並無什麽組織，在論文裏，也似乎痛惡無產階級式的“組織”，“集團”這些話，但其實是有組織的，至少，關於政治的論文，這一本裏都互相“照應”；關於文藝，則這一篇是登在上面的同一批評家所作的《文學是有階級性的嗎？》的余波。在那一篇裏有一段說：“……但是不幸得很，沒有一本這類的書能被我看懂。……最使我感得困難的是文字，……簡直讀起來比天書還難。……現在還沒有一個中國人，用中國人所能看得懂的文字，寫一篇文章告訴我們無產文學的理論究竟是怎麽一回事。”字旁也有圓圈，怕排印麻煩，恕不照畫了。總之，梁先生自認是一切中國人的代表，這些書既為自己所不懂，也就是為一切中國人所不懂，應該在中國斷絕其生命，於是出示曰“此風斷不可長”雲。

別的“天書”譯著者的意見我不能代表，從我個人來看，則事情是不會這樣簡單的。第一，梁先生自以為“硬著頭皮看下去”了，但究竟硬了沒有，是否能夠，還是一個問題。以硬自居了，而實則其軟如棉，正是新月社的一種特色。第二，梁先生雖自來代表一切中國人了，但究竟是否全國中的最優秀者，也是一個問題。這問題從《文學是有階級性的嗎？》這篇文章裏，便可以解釋。Proletary這字不必譯音，大可譯義，是有理可說的。但這位批評家卻道：“其實翻翻字典，這個字的涵義並不見得體面，據《韋白斯特大字典》，Proletary的意思就是：Acitizen of the lowest class who served the state not with property, but only by having children。……普羅列塔利亞是國家裏只會生孩子的階級！（至少在羅馬時代是如此）”其實正無須來爭這“體面”，大約略有常識者，總不至於以現在為羅馬時代，將現在的無產者都看作羅馬人的。這正如將Chemie譯作“舍密學”，讀者必不和埃及的“煉金術”混同，對於“梁”先生所作的文章，也決不會去考查語源，誤解為“獨木小橋”竟會動筆一樣。連“翻翻字典”（《韋白斯特大字典》！）也還是“無所得”，一切中國人未必全是如此的罷。

**二**

但於我最覺得有興味的，是上節所引的梁先生的文字裏，有兩處都用著一個“我們”，頗有些“多數”和“集團”氣味了。自然，作者雖然單獨執筆，氣類則決不只一人，用“我們”來說話，是不錯的，也令人看起來較有力量，又不至於一人雙肩負責。然而，當“思想不能統一”時，“言論應該自由”時，正如梁先生的批評資本制度一般，也有一種“弊病”。就是，既有“我們”便有我們以外的“他們”，於是新月社的“我們”雖以為我的“死譯之風斷不可長”了，卻另有讀了並不“無所得”的讀者存在，而我的“硬譯”，就還在“他們”之間生存，和“死譯”還有一些區別。

我也就是新月社的“他們”之一，因為我的譯作和梁先生所需的條件，是全都不一樣的。

那一篇《論硬譯》的開頭論誤譯勝於死譯說：“一部書斷斷不會完全曲譯……部分的曲譯即使是錯誤，究竟也還給你一個錯誤，這個錯誤也許真是害人無窮的，而你讀的時候究竟還落個爽快。”末兩句大可以加上夾圈，但我卻從來不幹這樣的勾當。我的譯作，本不在博讀者的“爽快”，卻往往給以不舒服，甚而至於使人氣悶，憎惡，憤恨。讀了會“落個爽快”的東西，自有新月社的人們的譯著在：徐誌摩先生的詩，沈從文，淩叔華先生的小說，陳西瀅（即陳源）先生的閑話，梁實秋先生的批評，潘光旦先生的優生學，還有白璧德先生的人文主義。

所以，梁先生後文說：“這樣的書，就如同看地圖一般，要伸著手指來尋找句法的線索位置”這些話，在我也就覺得是廢話，雖說猶如不說了。是的，由我說來，要看“這樣的書”就如同看地圖一樣，要伸著手指來找尋“句法的線索位置”的。看地圖雖然沒有看《楊妃出浴圖》或《歲寒三友圖》那麽“爽快”，甚而至於還須伸著手指（其實這恐怕梁先生自己如此罷了，看慣地圖的人，是只用眼睛就可以的），但地圖並不是死圖；所以“硬譯”即使有同一之勞，照例子也就和“死譯”有了些“什麽區別”。識得ABCD者自以為新學家，仍舊和化學方程式無關，會打算盤的自以為數學家，看起筆算的演草來還是無所得。現在的世間，原不是一為學者，便與一切事都會有緣的。

然而梁先生有實例在，舉了我三段的譯文，雖然明知道“也許因為沒有上下文的緣故，意思不能十分明了”。在《文學是有階級性的嗎？》這篇文章中，也用了類似手段，舉出兩首譯詩來，總評道：“也許偉大的無產文學還沒有出現，那麽我願意等著，等著，等著。”這些方法，誠然是很“爽快”的，但我可以就在這一本《新月》月刊裏的創作——是創作呀！——《搬家》第八頁上，舉出一段文字來——

“小雞有耳朵沒有？”

“我沒看見過小雞長耳朵的。”

“它怎樣聽見我叫它呢？”她想到前天四婆告訴她的耳朵是管聽東西，眼是管看東西的。

“這個蛋是白雞黑雞？”枝兒見四婆沒答她，站起來摸著蛋子又問。

“現在看不出來，等孵出小雞才知道。”

“婉兒姊說小雞會變大雞，這些小雞也會變大雞麽？”

“好好的餵它就會長大了，像這個雞買來時還沒有這樣大吧？”

也夠了，“文字”是懂得的，也無須伸出手指來尋線索，但我不“等著”了，以為就這一段看，是既不“爽快”，而且和不創作是很少區別的。

臨末，梁先生還有一個詰問：“中國文和外國文是不同的，……翻譯之難即在這個地方。假如兩種文中的文法句法詞法完全一樣，那麽翻譯還成為一件工作嗎？……我們不妨把句法變換一下，以使讀者能懂為第一要義，因為‘硬著頭皮’不是一件愉快的事，並且‘硬譯’也不見得能保存‘原來的精悍的語氣’。假如‘硬譯’而還能保存‘原來的精悍的語氣’，那真是一件奇跡，還能說中國文是有‘缺點’嗎？”我倒不見得如此之愚，要尋求和中國文相同的外國文，或者希望“兩種文中的文法句法詞法完全一樣”。我但以為文法繁復的國語，較易於翻譯外國文，語系相近的，也較易於翻譯，而且也是一種工作。荷蘭翻德國，俄國翻波蘭，能說這和並不工作沒有什麽區別麽？日本語和歐美很“不同”，但他們逐漸添加了新句法，比起古文來，更宜於翻譯而不失原來的精悍的語氣，開初自然是須“找尋句法的線索位置”，很給了一些人不“愉快”的，但經找尋和習慣，現在已經同化，成為己有了。中國的文法，比日本的古文還要不完備，然而也曾有些變遷，例如《史》《漢》不同於《書經》，現在的白話文又不同於《史》《漢》；有添造，例如唐譯佛經，元譯上諭，當時很有些“文法句法詞法”是生造的，一經習用，便不必伸出手指，就懂得了。現在又來了“外國文”，許多句子，即也須新造，——說得壞點，就是硬造。據我的經驗，這樣譯來，較之化為幾句，更能保存原來的精悍的語氣，但因為有待於新造，所以原先的中國文是有缺點的。有什麽“奇跡”，幹什麽“嗎”呢？但有待於“伸出手指”，“硬著頭皮”，於有些人自然“不是一件愉快的事”。不過我是本不想將“爽快”或“愉快”來獻給那些諸公的，只要還有若干的讀者能夠有所得，梁實秋先生“們”的苦樂以及無所得，實在“於我如浮雲”。

但梁先生又有本不必求助於無產文學理論，而仍然很不了了的地方，例如他說，“魯迅先生前些年翻譯的文學，例如廚川白村的《苦悶的象征》，還不是令人看不懂的東西，但是最近翻譯的書似乎改變風格了。”只要有些常識的人就知道：“中國文和外國文是不同的”，但同是一種外國文，因為作者各人的做法，而“風格”和“句法的線索位置”也可以很不同。句子可繁可簡，名詞可常可專，決不會一種外國文，易解的程度就都一式。我的譯《苦悶的象征》，也和現在一樣，是按板規逐句，甚而至於逐字譯的，然而梁實秋先生居然以為不能看懂者，乃是原文原是易解的緣故，也因為梁實秋先生是中國新的批評家了的緣故，也因為其中硬造的句法，是比較地看慣了的緣故。若在三家村裏，專讀《古文觀止》的學者們，看起來又何嘗不比“天書”還難呢。

**三**

但是，這回的“比天書還難”的無產文學理論的譯本們，卻給了梁先生不小的影響。看不懂了，會有影響，雖然好像滑稽，然而是真的，這位批評家在《文學是有階級性的嗎？》裏說：“我現在批評所謂無產文學理論，也只能根據我所能了解的一點材料而已。”這就是說：因此而對於這理論的知識，極不完全了。

但對於這罪過，我們（包含一切“天書”譯者在內，故曰“們”）也只能負一部分的責任，一部分是要作者自己的胡塗或懶惰來負的。“什麽盧那卡爾斯基，蒲力汗諾夫”的書我不知道，若夫“婆格達諾夫之類”的三篇論文和托羅茲基的半部《文學與革命》，則確有英文譯本的了。英國沒有“魯迅先生”，譯文定該非常易解。梁先生對於偉大的無產文學的產生，曾經顯示其“等著，等著，等著”的耐心和勇氣，這回對於理論，何不也等一下子，尋來看了再說呢。不知其有而不求曰胡塗，知其有而不求曰懶惰，如果單是默坐，這樣也許是“爽快”的，然而開起口來，卻很容易咽進冷氣去了。

例如就是那篇《文學是有階級性的嗎？》的高文，結論是並無階級性。要抹殺階級性，我以為最幹凈的是吳稚暉先生的“什麽馬克斯牛克斯”以及什麽先生的“世界上並沒有階級這東西”的學說。那麽，就萬喙息響，天下太平。但梁先生卻中了一些“什麽馬克斯”毒了，先承認了現在許多地方是資產制度，在這制度之下則有無產者。不過這“無產者本來並沒有階級的自覺。是幾個過於富同情心而又態度褊激的領袖把這個階級觀念傳授了給他們”，要促起他們的聯合，激發他們爭鬥的欲念。不錯，但我以為傳授者應該並非由於同情，卻因了改造世界的思想。況且“本無其物”的東西，是無從自覺，無從激發的，會自覺，能激發，足見那是原有的東西。原有的東西，就遮掩不久，即如格裏萊阿說地體運動，達爾文說生物進化，當初何嘗不或者幾被宗教家燒死，或者大受保守者攻擊呢，然而現在人們對於兩說，並不為奇者，就因為地體終於在運動，生物確也在進化的緣故。承認其有而要掩飾為無，非有絕技是不行的。

但梁先生自有消除鬥爭的辦法，以為如盧梭所說：“資產是文明的基礎”，“所以攻擊資產制度，即是反抗文明”，“一個無產者假如他是有出息的，只消辛辛苦苦誠誠實實的工作一生，多少必定可以得到相當的資產。這才是正當的生活鬥爭的手段。”我想，盧梭去今雖已百五十年，但當不至於以為過去未來的文明，都以資產為基礎。（但倘說以經濟關系為基礎，那自然是對的。）希臘印度，都有文明，而繁盛時俱非在資產社會，他大概是知道的；倘不知道，那也是他的錯誤。至於無產者應該“辛辛苦苦”爬上有產階級去的“正當”的方法，則是中國有錢的老太爺高興時候，教導窮工人的古訓，在實際上，現今正在“辛辛苦苦誠誠實實”想爬上一級去的“無產者”也還多。然而這是還沒有人“把這個階級觀念傳授了給他們”的時候。一經傳授，他們可就不肯一個一個的來爬了，誠如梁先生所說，“他們是一個階級了，他們要有組織了，他們是一個集團了，於是他們便不循常軌的一躍而奪取政權財權，一躍而為統治階級。”但可還有想“辛辛苦苦誠誠實實工作一生，多少必定可以得到相當的資產”的“無產者”呢？自然還有的。然而他要算是“尚未發財的有產者”了。梁先生的忠告，將為無產者所嘔吐了，將只好和老太爺去互相贊賞而已了。

那麽，此後如何呢？梁先生以為是不足慮的。因為“這種革命的現象不能是永久的，經過自然進化之後，優勝劣敗的定律又要證明了，還是聰明才力過人的人占優越的地位，無產者仍是無產者”。但無產階級大概也知道“反文明的勢力早晚要被文明的勢力所征服”，所以“要建立所謂‘無產階級文化’，……這裏面包括文藝學術”。

自此以後，這才入了文藝批評的本題。

**四**

梁先生首先以為無產者文學理論的錯誤，是“在把階級的束縛加在文學上面”，因為一個資本家和一個勞動者，有不同的地方，但還有相同的地方，“他們的人性（這兩字原本有套圈）並沒有兩樣”，例如都有喜怒哀樂，都有戀愛（但所“說的是戀愛的本身，不是戀愛的方式”），“文學就是表現這最基本的人性的藝術”。這些話是矛盾而空虛的。既然文明以資產為基礎，窮人以竭力爬上去為“有出息”，那麽，爬上是人生的要諦，富翁乃人類的至尊，文學也只要表現資產階級就夠了，又何必如此“過於富同情心”，一並包括“劣敗”的無產者？況且“人性”的“本身”，又怎樣表現的呢？譬如原質或雜質的化學底性質，有化合力，物理學底性質有硬度，要顯示這力和度數，是須用兩種物質來表現的，倘說要不用物質而顯示化合力和硬度的單單“本身”，無此妙法；但一用物質，這現象即又因物質而不同。文學不借人，也無以表示“性”，一用人，而且還在階級社會裏，即斷不能免掉所屬的階級性，無需加以“束縛”，實乃出於必然。自然，“喜怒哀樂，人之情也”，然而窮人決無開交易所折本的懊惱，煤油大王那會知道北京檢煤渣老婆子身受的酸辛，饑區的災民，大約總不去種蘭花，像闊人的老太爺一樣，賈府上的焦大，也不愛林妹妹的。“汽笛呀！”“列寧呀！”固然並不就是無產文學，然而“一切東西呀！”“一切人呀！”“可喜的事來了，人喜了呀！”也不是表現“人性”的“本身”的文學。倘以表現最普通的人性的文學為至高，則表現最普遍的動物性——營養，呼吸，運動，生殖——的文學，或者除去“運動”，表現生物性的文學，必當更在其上。倘說，因為我們是人，所以以表現人性為限，那麽，無產者就因為是無產階級，所以要做無產文學。

其次，梁先生說作者的階級，和作品無關。托爾斯泰出身貴族，而同情於貧民，然而並不主張階級鬥爭；馬克斯並非無產階級中的人物；終身窮苦的約翰孫博士，誌行吐屬，過於貴族。所以估量文學，當看作品本身，不能連累到作者的階級和身分。這些例子，也全不足以證明文學的無階級性的。托爾斯泰正因為出身貴族，舊性蕩滌不盡，所以只同情於貧民而不主張階級鬥爭。馬克斯原先誠非無產階級中的人物，但也並無文學作品，我們不能懸擬他如果動筆，所表現的一定是不用方式的戀愛本身。至於約翰孫博士終身窮苦，而誌行吐屬，過於王侯者，我卻實在不明白那緣故，因為我不知道英國文學和他的傳記。也許，他原想“辛辛苦苦誠誠實實的工作一生，多少必定可以得到相當的資產”，然後再爬上貴族階級去，不料終於“劣敗”，連相當的資產也積不起來，所以只落得擺空架子，“爽快”了罷。

其次，梁先生說，“好的作品永遠是少數人的專利品，大多數永遠是蠢的，永遠是和文學無緣”，但鑒賞力之有無卻和階級無幹，因為“鑒賞文學也是天生的一種福氣”，就是，雖在無產階級裏，也會有這“天生的一種福氣”的人。由我推論起來，則只要有這一種“福氣”的人，雖窮得不能受教育，至於一字不識，也可以賞鑒《新月》月刊，來作“人性”和文藝“本身”原無階級性的證據。但梁先生也知道天生這一種福氣的無產者一定不多，所以另定一種東西（文藝？）來給他們看，“例如什麽通俗的戲劇，電影，偵探小說之類”，因為“一般勞工勞農需要娛樂，也許需要少量的藝術的娛樂”的緣故。這樣看來，好像文學確因階級而不同了，但這是因鑒賞力之高低而定的，這種力量的修養和經濟無關，乃是上帝之所賜——“福氣”。所以文學家要自由創造，既不該為皇室貴族所雇用，也不該受無產階級所威脅，去做謳功頌德的文章。這是不錯的，但在我們所見的無產文學理論中，也並未見過有誰說或一階級的文學家，不該受皇室貴族的雇用，卻該受無產階級的威脅，去做謳功頌德的文章，不過說，文學有階級性，在階級社會中，文學家雖自以為“自由”，自以為超了階級，而無意識底地，也終受本階級的階級意識所支配，那些創作，並非別階級的文化罷了。例如梁先生的這篇文章，原意是在取消文學上的階級性，張揚真理的。但以資產為文明的祖宗，指窮人為劣敗的渣滓，只要一瞥，就知道是資產家的鬥爭的“武器”，——不，“文章”了。無產文學理論家以主張“全人類”“超階級”的文學理論為幫助有產階級的東西，這裏就給了一個極分明的例證。至於成仿吾先生似的“他們一定勝利的，所以我們去指導安慰他們去”，說出“去了”之後，便來“打發”自己們以外的“他們”那樣的無產文學家，那不消說，是也和梁先生一樣地對於無產文學的理論，未免有“以意為之”的錯誤的。

又其次，梁先生最痛恨的是無產文學理論家以文藝為鬥爭的武器，就是當作宣傳品。他“不反對任何人利用文學來達到另外的目的”，但“不能承認宣傳式的文字便是文學”。我以為這是自擾之談。據我所看過的那些理論，都不過說凡文藝必有所宣傳，並沒有誰主張只要宣傳式的文字便是文學。誠然，前年以來，中國確曾有許多詩歌小說，填進口號和標語去，自以為就是無產文學。但那是因為內容和形式，都沒有無產氣，不用口號和標語，便無從表示其“新興”的緣故，實際上也並非無產文學。今年，有名的“無產文學底批評家”錢杏邨先生在《拓荒者》上還在引盧那卡爾斯基的話，以為他推重大眾能解的文學，足見用口號標語之未可厚非，來給那些“革命文學”辯護。但我覺得那也和梁實秋先生一樣，是有意的或無意的曲解。盧那卡爾斯基所謂大眾能解的東西，當是指托爾斯泰做了分給農民的小本子那樣的文體，工農一看便會了然的語法，歌調，詼諧。只要看臺明·培特尼（DemianBednii）曾因詩歌得到赤旗章，而他的詩中並不用標語和口號，便可明白了。

最後，梁先生要看貨色。這不錯的，是最切實的辦法；但抄兩首譯詩算是在示眾，是不對的。《新月》上就曾有《論翻譯之難》，何況所譯的文是詩。就我所見的而論，盧那卡爾斯基的《被解放的堂·吉訶德》，法兌耶夫的《潰滅》，格拉特珂夫的《水門汀》，在中國這十一年中，就並無可以和這些相比的作品。這是指“新月社”一流的蒙資產文明的余蔭，而且衷心在擁護它的作家而言。於號稱無產作家的作品中，我也舉不出相當的成績。但錢杏邨先生也曾辯護，說新興階級，於文學的本領當然幼稚而單純，向他們立刻要求好作品，是“布爾喬亞”的惡意。這話為農工而說，是極不錯的。這樣的無理要求，恰如使他們凍餓了好久，倒怪他們為什麽沒有富翁那麽肥胖一樣。但中國的作者，現在卻實在並無剛剛放下鋤斧柄子的人，大多數都是進過學校的智識者，有些還是早已有名的文人，莫非克服了自己的小資產階級意識之後，就連先前的文學本領也隨著消失了麽？不會的。俄國的老作家亞歷舍·托爾斯泰和威壘賽耶夫，普理希文，至今都還有好作品。中國的有口號而無隨同的實證者，我想，那病根並不在“以文藝為階級鬥爭的武器”，而在“借階級鬥爭為文藝的武器”，在“無產者文學”這旗幟之下，聚集了不少的忽翻筋鬥的人，試看去年的新書廣告，幾乎沒有一本不是革命文學，批評家又但將辯護當作“清算”，就是，請文學坐在“階級鬥爭”的掩護之下，於是文學自己倒不必著力，因而於文學和鬥爭兩方面都少關系了。

但中國目前的一時現象，當然毫不足作無產文學之新興的反證的。梁先生也知道，所以他臨末讓步說，“假如無產階級革命家一定要把他的宣傳文學喚做無產文學，那總算是一種新興文學，總算是文學國土裏的新收獲，用不著高呼打倒資產的文學來爭奪文學的領域，因為文學的領域太大了，新的東西總有它的位置的。”但這好像“中日親善，同存共榮”之說，從羽毛未豐的無產者看來，是一種欺騙。願意這樣的“無產文學者”，現在恐怕實在也有的罷，不過這是梁先生所謂“有出息”的要爬上資產階級去的“無產者”一流，他的作品是窮秀才未中狀元時候的牢騷，從開手到爬上以及以後，都決不是無產文學。無產者文學是為了以自己們之力，來解放本階級並及一切階級而鬥爭的一翼，所要的是全般，不是一角的地位。就拿文藝批評界來比方罷，假如在“人性”的“藝術之宮”（這須從成仿吾先生處租來暫用）裏，向南面擺兩把虎皮交椅，請梁實秋錢杏邨兩位先生並排坐下，一個右執“新月”，一個左執“太陽”，那情形可真是“勞資”媲美了。

**五**

到這裏，又可以談到我的“硬譯”去了。

推想起來，這是很應該跟著發生的問題：無產文學既然重在宣傳，宣傳必須多數能懂，那麽，你這些“硬譯”而難懂的理論“天書”，究竟為什麽而譯的呢？不是等於不譯麽？

我的回答，是：為了我自己，和幾個以無產文學批評家自居的人，和一部分不圖“爽快”，不怕艱難，多少要明白一些這理論的讀者。

從前年以來，對於我個人的攻擊是多極了，每一種刊物上，大抵總要看見“魯迅”的名字，而作者的口吻，則粗粗一看，大抵好像革命文學家。但我看了幾篇，竟逐漸覺得廢話太多了。解剖刀既不中腠理，子彈所擊之處，也不是致命傷。例如我所屬的階級罷，就至今還未判定，忽說小資產階級，忽說“布爾喬亞”，有時還升為“封建余孽”，而且又等於猩猩（見《創造月刊》上的“東京通信”）；有一回則罵到牙齒的顏色。在這樣的社會裏，有封建余孽出風頭，是十分可能的，但封建余孽就是猩猩，卻在任何“唯物史觀”上都沒有說明，也找不出牙齒色黃，即有害於無產階級革命的論據。我於是想，可供參考的這樣的理論，是太少了，所以大家有些胡塗。對於敵人，解剖，咬嚼，現在是在所不免的，不過有一本解剖學，有一本烹飪法，依法辦理，則構造味道，總還可以較為清楚，有味。人往往以神話中的Prometheus比革命者，以為竊火給人，雖遭天帝之虐待不悔，其博大堅忍正相同。但我從別國裏竊得火來，本意卻在煮自己的肉的，以為倘能味道較好，庶幾在咬嚼者那一面也得到較多的好處，我也不枉費了身軀：出發點全是個人主義，並且還夾雜著小市民性的奢華，以及慢慢地摸出解剖刀來，反而刺進解剖者的心臟裏去的“報復”。梁先生說“他們要報復！”其實豈只“他們”，這樣的人在“封建余孽”中也很有的。然而，我也願意於社會上有些用處，看客所見的結果仍是火和光。這樣，首先開手的就是《文藝政策》，因為其中含有各派的議論。鄭伯奇先生現在是開書鋪，印Hauptmann和Gregory夫人的劇本了，那時他還是革命文學家，便在所編的《文藝生活》上，笑我的翻譯這書，是不甘沒落，而可惜被別人著了先鞭。翻一本書便會浮起，做革命文學家真太容易了，我並不這樣想。有一種小報，則說我的譯《藝術論》是“投降”。是的，投降的事，為世上所常有。但其時成仿吾元帥早已爬出日本的溫泉，住進巴黎的旅館了，在這裏又向誰去輸誠呢。今年，說法又兩樣了，在《拓荒者》和《現代小說》上，都說是“方向轉換”。我看見日本的有些雜誌中，曾將這四字加在先前的新感覺派片岡鐵兵上，算是一個好名詞。其實，這些紛紜之談，也還是只看名目，連想也不肯想的老病。譯一本關於無產文學的書，是不足以證明方向的，倘有曲譯，倒反足以為害。我的譯書，就也要獻給這些速斷的無產文學批評家，因為他們是有不貪“爽快”，耐苦來研究這些理論的義務的。

但我自信並無故意的曲譯，打著我所不佩服的批評家的傷處了的時候我就一笑，打著我的傷處了的時候我就忍疼，卻決不肯有所增減，這也是始終“硬譯”的一個原因。自然，世間總會有較好的翻譯者，能夠譯成既不曲，也不“硬”或“死”的文章的，那時我的譯本當然就被淘汰，我就只要來填這從“無有”到“較好”的空間罷了。

然而世間紙張還多，每一文社的人數卻少，誌大力薄，寫不完所有的紙張，於是一社中的職司克敵助友，掃蕩異類的批評家，看見別人來塗寫紙張了，便喟然興嘆，不勝其搖頭頓足之苦。上海的《申報》上，至於稱社會科學的翻譯者為“阿狗阿貓”，其憤憤有如此。在“中國新興文學的地位，早為讀者所共知”的蔣光Z先生，曾往日本東京養病，看見藏原惟人，談到日本有許多翻譯太壞，簡直比原文還難讀……他就笑了起來，說：“……那中國的翻譯界更要莫名其妙了，近來中國有許多書籍都是譯自日文的，如果日本人將歐洲人那一國的作品帶點錯誤和刪改，從日文譯到中國去，試問這作品豈不是要變了一半相貌麽？……”（見《拓荒者》也就是深不滿於翻譯，尤其是重譯的表示。不過梁先生還舉出書名和壞處，蔣先生卻只嫣然一笑，掃蕩無余，真是普遍得遠了。藏原惟人是從俄文直接譯過許多文藝理論和小說的，於我個人就極有裨益。我希望中國也有一兩個這樣的誠實的俄文翻譯者，陸續譯出好書來，不僅自罵一聲“混蛋”就算盡了革命文學家的責任。

然而現在呢，這些東西，梁實秋先生是不譯的，稱人為“阿狗阿貓”的偉人也不譯，學過俄文的蔣先生原是最為適宜的了，可惜養病之後，只出了一本《一周間》，而日本則早已有了兩種的譯本。中國曾經大談達爾文，大談尼采，到歐戰時候，則大罵了他們一通，但達爾文的著作的譯本，至今只有一種，尼采的則只有半部，學英德文的學者及文豪都不暇顧及，或不屑顧及，拉倒了。所以暫時之間，恐怕還只好任人笑罵，仍從日文來重譯，或者取一本原文，比照了日譯本來直譯罷。我還想這樣做，並且希望更多有這樣做的人，來填一填徹底的高談中的空虛，因為我們不能像蔣先生那樣的“好笑起來”，也不該如梁先生的“等著，等著，等著”了。

**六**

我在開頭曾有“以硬自居了，而實則其軟如棉，正是新月社的一種特色”這些話，到這裏還應該簡短地補充幾句，就作為本篇的收場。

《新月》一出世，就主張“嚴正態度”，但於罵人者則罵之，譏人者則譏之。這並不錯，正是“即以其人之道，還治其人之身”，雖然也是一種“報復”，而非為了自己。到二卷六七號合本的廣告上，還說“我們都保持‘容忍’的態度（除了‘不容忍’的態度是我們所不能容忍以外），我們都喜歡穩健的合乎理性的學說”。上兩句也不錯，“以眼還眼，以牙還牙”，和開初仍然一貫。然而從這條大路走下去，一定要遇到“以暴力抗暴力”，這和新月社諸君所喜歡的“穩健”也不能相容了。

這一回，新月社的“自由言論”遭了壓迫，照老辦法，是必須對於壓迫者，也加以壓迫的，但《新月》上所顯現的反應，卻是一篇《告壓迫言論自由者》，先引對方的黨義，次引外國的法律，終引東西史例，以見凡壓迫自由者，往往臻於滅亡：是一番替對方設想的警告。

所以，新月社的“嚴正態度”，“以眼還眼”法，歸根結蒂，是專施之力量相類，或力量較小的人的，倘給有力者打腫了眼，就要破例，只舉手掩住自己的臉，叫一聲“小心你自己的眼睛！”

