*** 戳穿「第三种人」
    :PROPERTIES:
    :CUSTOM_ID: chap03sec03
    :END:

**** 关于《文新》与胡秋原的文艺论辩
     :PROPERTIES:
     :AUTHOR:   苏汶
     :CUSTOM_ID: 19320701
     :END:

首先要声明，我写这篇文章是并没有什么野心的，这是说，我并不是看别人“战”得有趣，于是自己也卷起袖子来一手；我更不敢有对任何方面挑“战”的意思。这一切，自己也很明白，都不配。不过，我如此见到，我便如此说。

近来，很少看书，尤其是很少看那些据说要销到七八千份以上的国内诸文艺杂志或报章。但是一个极碰巧的机会却终于使我看到了登在《读书杂志》第二卷第一期上的胡秋原先生的《钱杏邨理论之清算》和《文艺新闻》第五十六号上的没有署名的《自由人的文化运动》这两篇煌煌大文。这两篇表面上似乎没有多大连续性而实际上是十分针锋相对的文章上附的那句“标语”：马克思主义文艺理论之拥护。我记得，钱杏邨先生也是曾经把自己视为百分之百的马克思主义者的。

这是文艺舞台替我们排演的一出《新双包案》。

我呢，当然没有能力来判断哪一位包公是真，哪一位包公是假。在前台是看不出真假的。到后台去，不过后台也许还是看不出。

写到这里，我想起一个极陈旧的笑话来。

笑话本来就无聊，笑话而陈旧似乎更可以不必说。不过，被所有的党员都读熟了的《三民主义》里面的话都可在写给党员看的文章里被几百次几千次地引用，那么在我这篇狗屁不值钱的文章里说上一个陈旧的笑话似乎没有什么要紧吧。

从前有一个商人，一个秀才，一个富翁和一个乞丐同在一座庙里避雪。因为无聊，联句吧。题目不用说，是“雪”。这首诗的头三句是这样的：

#+BEGIN_EXAMPLE
大雪纷纷坠地（商人）
都是皇家瑞气（秀才）
再落三年何妨（富翁）
#+END_EXAMPLE

再落三年雪，那还得了。叫化子于是生了气，他忘记了诗题，便这样地破口大骂起来：

#+BEGIN_EXAMPLE
放你娘的狗屁！
#+END_EXAMPLE

我向排演《双包案》的戏场的后台偷看了几眼，结论是没有，我只想起这个笑话来。确实，这一次的文艺论战（也许每一次的文艺论战都如此）是和破庙里的联句活脱活像：文艺这东西便是那题目，于是，各人说各人的话，而且，要两方面都同意的结论是决不会有的。

孔夫子这个人确实没有很彻底的思想，尽可以不必硬拖进马克思祠堂，可是他却确实说过几句聪明话。他说：“道不同不相为谋。”我这篇文章平凡得很，只不过想发挥一些这句古话在这次文艺论战上的应用；因此，我这篇文章又名“道不同相为谋说”。

废话少讲，我们来看一看论战的来历。

起初当然是导源于俄罗斯。一些名字长得不容易记清楚的人们争论着，在我们还没有梦想到天下有这么一个问题的时候就争论着。后来闹到日本，日本人似乎没有俄罗斯人那么聪明，说来说去还是俄罗斯人所早就说过的这几句话，没有胡秋原先生所要求于钱杏邨先生的“独创”。假使转借胡先生向福禄特尔借来的话来说，那么日本人就已经做了第二个拿女人来比花的头等蠢才了。于是，这些同一的话又借道东京而来到上海，只用四角方方的文字一写，便俨然成为中国人自己的理论。

其实，说到理论，我们还不如老老实实，现现成成地向俄罗斯人批发些来倒不至于闹大笑话，至于说“新花样”，钱杏邨先生固然耍不出来，胡秋原先生也一样；不过胡先生还算能抱定从一而终主义，蒲力哈诺夫，而钱先生呢，不免要东拉拉，西扯扯。

这一点，左翼文坛的近来的指导者是高明得多了。他们不再提出那些“艺术的起源”或“艺术的定义”这些书呆子气的问题来，只看定目前的需要切实地，按部就班地讨论着，决定着又执行着。

可是左翼文坛自身的“奥伏赫变”到现在这地步也不是一朝一夕的事情。它在中国摆下擂台以来，第一个来打擂台的是鲁迅先生。他老人家说：“我们要理论。”于是有人便把蒲力哈诺夫和卢那却尔斯基译了些出来；虽然译得不十分看得懂，可是鲁迅先生满意了。接着茅盾先生又跳上擂台。“我们不要听十八句江湖诀，我们要看货色”，他说。货色纵然依旧没有拿出来，可是艺术的技巧的问题是开始被重视，被讨论。于是茅盾先生也满意了。而现在，想不到还有胡秋原先生会从谁也不敢显一显好身手的人群中跳将出来，而据说，他的拳头又是少林嫡派。当然，胡秋原先生将来会不会也像鲁迅先生和茅盾先生那样地满意而去是谁也不敢断言；但是在今日已经明显地立定了脚跟的左翼文坛再不会因这次论战而变换态度却可以料想得到。因此，据我个人愚见，这一场笔战是不会有使两方面都“满意”的结果。

何以见得？道不同不相为谋。

统观胡先生的大文，从他的蒲力哈诺夫崇拜，对文学的指导生活的理论或主张的非议，一切等等看来，我们可以认识他是一个绝对的非功利论者。反过来，左翼文坛的指导理论家们却正指出哪一种文学有用，哪一种文学没有用，我们要哪一种，我们不要哪一种。这两种马克思主义者之间的距离是不可以道理计的。

其实，我们单说左翼文坛是马克思主义者似乎还是不适当；我们应当说他们是“马克思列宁主义者”。这其间的分别就是他们现在没工夫来讨论什么真理不真理，他们只看目前的需要。是一种目前主义。我们与其把他们的主张当做学者式的理论，却还不如把它当做政治家式的策略，当做行动；而且这策略，这行动实际上也就是理论。目前的需要改变了，他们的主张便也随之而变；这才是，“辩证”。

你会不会称轻重？什么真理，什么文艺，假使比起整个的无产阶级解放运动来，还称得出几斤几两？亭子间里的真理吧！小资产阶级狗男女的文艺吧！你假使真是一个前进的战士，你便不会再要真理，再要文艺了。

譬如拿他们所提倡的文艺大众化这问题来说吧。他们鉴于现在劳动者没有东西看，在那里看陈旧的充满了封建气味的（这就是说，有害的）连环图画和唱本。于是他们便要作家们去写一些有利的连环图画和唱本来给劳动者们看。这个，像胡先生之类的批评家当然是要反对了；不但胡先生，恐怕每一个死抱住文学不肯放手的人都要反对。这样低级的形式还生产得出好的作品吗？确实，连环图画里是产生不出托尔斯泰，产生不出弗罗培尔来的。这一点难道左翼理论家们会不知道，他们断然不会那么蠢。但是，他们要弗罗培尔什么用呢？要托尔斯泰什么用呢？他们不但根本不会叫作家们去做成弗罗培尔或托尔斯泰，就是有了，他们也是不要，至少他们“目前”是不要。而且这不要是对的，辩证的。也许将来，也许将来他们会原谅，不过此是后话。

胡秋原先生把卢那却尔斯基称为“官僚，纨绔子，莫明其妙”，何其毒视之深！其实，从这里我们正可以看出胡先生是永远不会了解卢那却尔斯基的。卢那却尔斯基有一次曾经把托尔斯泰非议得很利害，但是在托氏百年祭时又把他恭维得很利害。他的话筒直有点如出二口。何其前后矛盾一至于此，何其不顾所谓“真理”一至于此！其实，托氏被“不要”于万方多难之秋，而旋又被“原谅”于国泰民安之日，是很有道理的。

你假使是真的马克思主义者便不该非难卢那却尔斯基。“莫明其妙”，说他太会变卦。变卦就是辩证法。有人说辩证法是中国古已有之，一部《易经》便是。可惜我对于辩证法和《易经》两者都没有深切的研究，不敢有所发挥。不过我知道，《易经》云胡哉？变卦而已。

话似乎愈说愈远了，应该拉回来。但是，我之所以如此说，无非是想说明左翼文坛的一切主张都无非是行动，并且一切行动都是活的。而胡秋原先生不明白。左翼文坛已经屡次向胡先生暗示了，甚至说明了，叫他不要空谈真理，离开行动是没有什么真理的。而胡先生还是不明白。胡先生固然会说，行动没有真理是不正确的行动；但左翼文坛也会说，真理没有行动便是不正确的真理。那么，这场论战会有什么结果呢？

胡秋原先生纵然以马克思主义相标榜；其实，他充其量不过是一个书呆子马克思主义者。这种马克思主义者老喜欢从最遥远，最难解决的问题说起，而据他们说，这是根本的问题。例如，一提起艺术便要谈到艺术的定义，不但谈到，而且定要把它当作“谈艺术的第一个问题”，如胡先生所说。固然，胡先生是继承了蒲力哈诺夫的道统把这么一个奥妙不堪的问题轻易地用“艺术是形象而思索”八个大字来解决了，似乎这便是天经地义似的，骂钱杏邨先生不懂得这个便不配谈艺术。其实天下哪有这样简单的事情！马克思的一部《资本论》里面你找得出资本的定义吗？这整整的三卷书才是资本的定义呢。真正的马克思主义者难道可以说马克思连资本的定义弄不清楚，不配谈经济问题吗？只有书呆子才会左来一个定义，右来一个定义。

耽误大事正就是这种类似定义的问题。一些热衷于真理的马克思主义者们不会把自己关在图书馆里。人类学，考古学。寒窗重检点，再读十年书。照这样，也难怪左翼文坛要说这是“教训民众等待主义了”。

严格地说，蒲力哈诺夫也不免带一些这种书呆子的气氛。你瞧，蒲力哈诺夫的政治理论是终于被列宁所攻击了；而现在，甚至他的艺术理论都据说有点站不住了。书呆子毕竟要不得，没有用。

记得从前章太炎曾经大大地宣传过书呆子主义，说世界上什么惊天动地的大事业都是书呆子做出来的。然而章太炎在政治上终于要不得，也就是书呆子主义在那里作祟。学院式的马克思主义者，其章太炎之流欤？

此之谓秀才造反，三年不成大事。

因此，我们纵然承认胡秋原先生的每一句话都是一百二十分地合乎马克思主义的，但左翼文坛在“能够行动”，这一点上就已经比这一百二十分的马克思主义者更合乎马克思主义一点了。纵然左翼文坛也承认胡秋原先生的每一句话都是一百二十分地合乎马克思主义的，但他们必然地还要攻击他，就像列宁攻击蒲力哈诺夫一样，因为他妨碍行动，而妨碍行动这一点就是反马克思主义的。胡先生纵然写十部洋洋四十万言的《唯物史观艺术论》也没有用，至少“目前”没有用，左翼文坛是依然要把他来非难的，因为现在还没有到列宁可以原谅蒲力哈诺夫，卢那却尔斯基可以原谅托尔斯泰的时候。

自己不站在“不自由的，有党派的”群众中，不说话是聪明的。

从这里，我们看出两个绝对不同的立场了。一方面重实践，另一方面只要书本；一方面负着政治的使命，另一方面却背着真理的招牌。于是这两种马克思主义是愈趋愈远，几乎背道而驰了。

萧伯纳说无产阶级的代表人是既懂得无产阶级又懂资产阶级的，而资产阶级的代言人是两者都不懂。让我来做一次“头等的蠢才”吧。我要模仿萧伯纳的口气来说。马克思列宁主义者是既懂得列宁主义又懂得马克思主义的；但书呆子马克思主义者，要是分析到终极，是既不懂列宁主义又不懂得马克思主义。

不过，胡先生听人说他不懂列宁主义便会跳起来，会反问我一声：“那么你自己懂不懂列宁主义呢？”那便真会把我问得哑口无言了。

确实，胡先生曾经指出过文艺上的“目的意识论不过是列宁之政治理论在文艺上之机械的适用”，话固然不错，但从“不过是”和“机械的”等字样上看来，胡先生至少是暗示着列宁主义也不过尔尔，是暗示着列宁主义用不到文艺上来。

万一不幸，胡先生是真懂得列宁主义的，说胡先生不懂的人自己倒做了天字第一号的傻瓜，那么我真不知胡先生是何居心了。难怪有人会说胡先生是故意把马克思主义从实际行动中“解放”出来，故意使它成为死的，书本的，缓冲革命运动的，而实际上是替无产阶级的敌人服务的马克思主义。

其实，胡先生还不如让人说书呆子吧。这样是比较有利，这样倒还有做一个蒲力哈诺夫的希望。也许将来的大学里会有“胡秋原学院”呢，就像俄罗斯的大学有“蒲力哈诺夫学院”一样。

在“智识阶级的自由人”和“不自由的，有党派的”阶级争着文坛的霸权的时候，最吃苦的，却是这两种人之外的第三种人。这种第三种人便是所谓作者之群。

作者，老实说，是多少带点我前面所说起的死抱住文学不肯放手的气味的；否则，他也决不会在成千成万的事业中选定了这个最没出息的事业（也许说职业好一点吧）来做。只要张开眼睛来看，不写东西的便罢，写一点东西的都斤斤乎艺术的价值便可知道。甚至如史铁儿先生所说“一举成名天下知”这一类下意识，平心而论，也人人多少有一点。究竟人非圣贤，同时也并非个个是马克思和列宁。

但是在现今这局面下，作者是处了怎样个地位呢？

最初，在根本还没有什么阶级文学的观念打到作者脑筋里去的时候，作者还在梦想文学是个纯洁的处女。但不久，有人告诉他说，她不但不是一个处女，甚至是一个人尽可夫的卖淫妇，她可以今天卖给资产阶级，明天又卖给无产阶级。这个，作者在刚听到的时候似乎就有点意外了；不过据说是事实，于是也就没有方法否认。既而，因为文学这卖淫妇似乎还长得不错，于是资产阶级想占有她，无产阶级也想占有她。于是文学便只能打算从良。从良以后呢？作者便“从此萧郎是路人”。

你瞧，不是有好多大大小小的作者是搁起了笔吗？

固然，有一部分作者还想把她从一个深如海的侯门中拉回来，而另一部分就索性爽爽快快陪嫁了过去。

前面那种作者是正在那儿被“不要”，可以不必说。对于后面那种作者呢，要是要的，可是规矩很严，要你做另外一种人。终于，文学不再是文学了，变为连环图画之类；而作者也不再是作者了，变为煽动家之类。死抱住文学不放的作者们是终于只能放手了。然而你说他们舍得放手吗？他们还在恋恋不舍地要艺术的价值。

我这样说，并不是怪左翼文坛不该这样霸占文学。他们这样办是对的，为革命，为阶级。不过他们有一点不爽快，不肯干脆说一声文学现在是不需要，至少暂时不需要。他们有时侯也会掮出艺术的价值来给所谓作者们尝一点甜头，可以让他安心地来陪嫁。其实，这样一来，却反把作者弄得手足无措了。为文学呢，为革命？还是两者都为？还是有时候为文学，有时候为革命？

在这一点上，我倒觉得启蒙时代的批评家李初梨先生诸人要痛快得多。他老实先问你，是为文学而革命呢，还是为革命而文学？肯定前半个问题的，走吧；肯定后半个问题的，到这儿来。

正因为有这一班无所适从的作者的存在，胡秋原先生便又以艺术保护者的资格而出现了。他叫人不要碰艺术。这种自由主义的创作理论应该是受作者的欢迎的。但不幸胡先生也不是一个彻底的自由主义者。他猛烈地攻击那种有目的意识的文学：照这看来，你还是不允许作者有整个的自由的。万一胡先生叫人不准碰艺术的态度是这样：你们不要碰，让我来；那可不是同样的不自由？

在人人都不肯让步的今日，诚哉，难乎其为作家？

人各有其道，人各以其道非他人之道。你说着我所不要听的话，我说着你所不要听的话。联句正联得起劲呢。只有作者，有其道而不敢言，更不敢拿来非他人之道。他只想替文学，不管是煽动的也好，暴露的也好，留着一线残存的生机，但是又怕被料事如神的指导者们算出命来，派定他是那一阶级的狗。

在“目前”这情形下，愚盲是幸福，而沉默是聪明的。

**** “第三种人”的出路”
     :PROPERTIES:
     :CUSTOM_ID: 19321001
     :AUTHOR:   苏汶
     :END:

     - Note taken on [2019-12-31 二 21:14] \\
       找不到好的文本，要是复制 epub 的文字，总会带上一堆中文双引号。


**** 論「第三種人」
     :PROPERTIES:
     :CUSTOM_ID: 19321101
     :END:

這三年來，關於文藝上的論爭是沉寂的，除了在指揮刀的保護之下，掛著「左翼」的招牌，在馬克斯主義裡發見了文藝自由論，列寧主義裡找到了殺盡共匪說的論客的「理論」之外，幾乎沒有人能夠開口，然而，倘是「為文藝而文藝」的文藝，卻還是「自由」的，因為他決沒有收了盧布的嫌疑。但在「第三種人」，就是「死抱住文學不放的人」又不免有一種苦痛的豫感：左翼文壇要說他是「資產階級的走狗」。

代表了這一種「第三種人」來鳴不平的，是《現代》雜誌第三和第六期上的蘇汶先生的文章（我在這裡先應該聲明：我為便利起見，且用了「代表」，「第三種人」這些字眼，雖然明知道蘇汶先生的「作家之群」，是也如拒絕「或者」，「多少」，「影響」這一類不十分決定的字眼一樣，不要固定的名稱的，因為名稱一固定，也就不自由了）。他以為左翼的批評家，動不動就說作家是「資產階級的走狗」，甚至於將中立者認為非中立，而一非中立，便有認為「資產階級的走狗」的可能，號稱「左翼作家」者既然「左而不作」，「第三種人」又要作而不敢，於是文壇上便沒有東西了。然而文藝據說至少有一部分是超出於階級鬥爭之外的，為將來的，就是「第三種人」所抱住的真的，永久的文藝。——但可惜，被左翼理論家弄得不敢作了，因為作家在未作之前，就有了被罵的豫感。

我相信這種豫感是會有的，而以「第三種人」自命的作家，也愈加容易有。我也相信作者所說，現在很有懂得理論，而感情難變的作家。然而感情不變，則懂得理論的度數，就不免和感情已變或略變者有些不同，而看法也就因此兩樣。蘇汶先生的看法，由我看來，是並不正確的。

自然，自從有了左翼文壇以來，理論家曾經犯過錯誤，作家之中，也不但如蘇汶先生所說，有「左而不作」的，並且還有由左而右，甚至於化為民族主義文學的小卒，書坊的老闆，敵黨的探子的，然而這些討厭左翼文壇了的文學家所遺下的左翼文壇，卻依然存在，不但存在，還在發展，克服自己的壞處，向文藝這神聖之地進軍。蘇汶先生問過：克服了三年，還沒有克服好麼？回答是：是的，還要克服下去，三十年也說不定。然而一面克服著，一面進軍著，不會做待到克服完成，然後行進那樣的傻事的。但是，蘇汶先生說過「笑話」：左翼作家在從資本家取得稿費；現在我來說一句真話，是左翼作家還在受封建的資本主義的社會的法律的壓迫，禁錮，殺戮。所以左翼刊物，全被摧殘，現在非常寥寥，即偶有發表，批評作品的也絕少，而偶有批評作品的，也並未動不動便指作家為「資產階級的走狗」，而且不要「同路人」。左翼作家並不是從天上掉下來的神兵，或國外殺進來的仇敵，他不但要那同走幾步的「同路人」，還要招致那站在路旁看看的看客也一同前進。

但現在要問：左翼文壇現在因為受著壓迫，不能發表很多的批評，倘一旦有了發表的可能，不至於動不動就指「第三種人」為「資產階級的走狗」麼？我想，倘若左翼批評家沒有宣誓不說，又只從壞處著想，那是有這可能的，也可以想得比這還要壞。不過我以為這種豫測，實在和想到地球也許有破裂之一日，而先行自殺一樣，大可以不必的。

然而蘇汶先生的「第三種人」，卻據說是為了這未來的恐怖而「擱筆」了。未曾身歷，僅僅因為心造的幻影而擱筆，「死抱住文學不放」的作者的擁抱力，又何其弱呢？兩個愛人，有因為豫防將來的社會上的斥責而不敢擁抱的麼？

其實，這「第三種人」的「擱筆」，原因並不在左翼批評的嚴酷。真實原因的所在，是在做不成這樣的「第三種人」，做不成這樣的人，也就沒有了第三種筆，擱與不擱，還談不到。

生在有階級的社會裡而要做超階級的作家，生在戰鬥的時代而要離開戰鬥而獨立，生在現在而要做給與將來的作品，這樣的人，實在也是一個心造的幻影，在現實世界上是沒有的。要做這樣的人，恰如用自己的手拔著頭髮，要離開地球一樣，他離不開，焦躁著，然而並非因為有人搖了搖頭，使他不敢拔了的緣故。

所以雖是「第三種人」，卻還是一定超不出階級的，蘇汶先生就先在豫料階級的批評了，作品裡又豈能擺脫階級的利害；也一定離不開戰鬥的，蘇汶先生就先以「第三種人」之名提出抗爭了，雖然「抗爭」之名又為作者所不願受；而且也跳不過現在的，他在創作超階級的，為將來的作品之前，先就留心於左翼的批判了。

這確是一種苦境。但這苦境，是因為幻影不能成為實有而來的。即使沒有左翼文壇作梗，也不會有這「第三種人」，何況作品。但蘇汶先生卻又心造了一個橫暴的左翼文壇的幻影，將「第三種人」的幻影不能出現，以至將來的文藝不能發生的罪孽，都推給它了。

左翼作家誠然是不高超的，連環圖畫，唱本，然而也不到蘇汶先生所斷定那樣的沒出息。左翼也要托爾斯泰，弗羅培爾。但不要「努力去創造一些屬於將來（因為他們現在是不要的）的東西」的托爾斯泰和弗羅培爾。他們兩個，都是為現在而寫的，將來是現在的將來，於現在有意義，才於將來會有意義。尤其是托爾斯泰，他寫些小故事給農民看，也不自命為「第三種人」，當時資產階級的多少攻擊，終於不能使他「擱筆」。左翼雖然誠如蘇汶先生所說，不至於蠢到不知道「連環圖畫是產生不出托爾斯泰，產生不出弗羅培爾來」，但卻以為可以產出密開朗該羅，達文希那樣偉大的畫手。而且我相信，從唱本說書裡是可以產生托爾斯泰，弗羅培爾的。現在提起密開朗該羅們的畫來，誰也沒有非議了，但實際上，那不是宗教的宣傳畫，《舊約》的連環圖畫麼？而且是為了那時的「現在」的。

總括起來說，蘇汶先生是主張「第三種人」與其欺騙，與其做冒牌貨，倒還不如努力去創作，這是極不錯的。「定要有自信的勇氣，才會有工作的勇氣！」這尤其是對的。

然而蘇汶先生又說，許多大大小小的「第三種人」們，卻又因為豫感了不祥之兆——左翼理論家的批評而「擱筆」了！「怎麼辦呢」？

**** 法国通信
     :PROPERTIES:
     :AUTHOR:   戴望舒
     :CUSTOM_ID: 19330601
     :END:
**** 又論「第三種人」
     :PROPERTIES:
     :CUSTOM_ID: 19330604
     :END:

戴望舒先生遠遠的從法國給我們一封通信，敘述著法國A.E.A.R.（革命文藝家協會）得了紀德的參加，在三月二十一日召集大會，猛烈的反抗德國法西斯諦的情形，並且紹介了紀德的演說，發表在六月號的《現代》上。法國的文藝家，這樣的仗義執言的舉動是常有的：較遠，則如左拉為德來孚斯打不平，法朗士當左拉改葬時候的講演；較近，則有羅曼羅蘭的反對戰爭。但這回更使我感到真切的歡欣，因為問題是當前的問題，而我也正是憎惡法西斯諦的一個。不過戴先生在報告這事實的同時，一併指明了中國左翼作家的「愚蒙」和像軍閥一般的橫暴，我卻還想來說幾句話。但希望不要誤會，以為意在辯解，希圖中國也從所謂「第三種人」得到對於德國的被壓迫者一般的聲援，——並不是的。中國的焚禁書報，封閉書店，囚殺作者，實在還遠在德國的白色恐怖以前，而且也得到過世界的革命的文藝家的抗議了。我現在要說的，不過那通然裡的必須指出的幾點。

那通信敘述過紀德的加入反抗運動之後，說道——

#+BEGIN_EXAMPLE

「在法國文壇中，我們可以說紀律是『第三種人』，……自從他在一八九一年……起，一直到現在為止，他始終是一個忠實於他的藝術的人。然而，忠實於自己的藝術的作者，不一定就是資產階級的『幫閒者』，法國的革命作家沒有這種愚蒙的見解（或者不如說是精明的策略），因此，在熱烈的歡迎之中，紀德便在群眾之間發言了。」
#+END_EXAMPLE

這就是說：「忠實於自己的藝術的作者」，就是「第三種人」，而中國的革命作家，卻「愚蒙」到指這種人為全是「資產階級的幫閒者」，現在已經由紀德證實，是「不一定」的了。這裡有兩個問題應該解答。

第一，是中國的左翼理論家是否真指「忠實於自己的藝術的作者」為全是「資產階級的幫閒者」？據我所知道，卻並不然。左翼理論家無論如何「愚蒙」，還不至於不明白「為藝術的藝術」在發生時，是對於一種社會的成規的革命，但待到新興的戰鬥的藝術出現之際，還拿著這老招牌來明明暗暗阻礙他的發展，那就成為反動，且不只是「資產階級的幫閒者」了。至於「忠實於自己的藝術的作者」，卻並未視同一律。因為不問那一階級的作家，都有一個「自己」，這「自己」，就都是他本階級的一分子，忠實於他自己的藝術的人，也就是忠實於他本階級的作者，在資產階級如此，在無產階級也如此。這是極顯明粗淺的事實，左翼理論家也不會不明白的。但這位——戴先生用「忠實於自己的藝術」來和「為藝術的藝術」掉了一個包，可真顯得左翼理論家的「愚蒙」透頂了。

第二，是紀德是否真是中國所謂的「第三種人」？我沒有讀過紀德的書，對於作品，沒有加以批評的資格。但我相信：創作和演說，形式雖然不同，所含的思想是決不會兩樣的。我可以引出戴先生所紹介的演說裡的兩段來——

#+BEGIN_EXAMPLE

「有人會對我說：『在蘇聯也是這樣的。』那是可能的事；但是目的卻是完全兩樣的，而且，為了要建設一個新社會起見，為了把發言權給與那些一向做著受壓迫者，一向沒有發言權的人們起見，不得已的矯枉過正也是免不掉的事。

「我為什麼並怎樣會在這裡贊同我在那邊所反對的事呢？那就是因為我在德國的恐怖政策中，見到了最可歎最可憎的過去底再演，在蘇聯的社會創設中，我卻見到一個未來的無限的允約。」
#+END_EXAMPLE

這說得清清楚楚，雖是同一手段，而他卻因目的之不同而分為贊成或反抗。蘇聯十月革命後，側重藝術的「綏拉比翁的兄弟們」這團體，也被稱為「同路人」，但他們卻並沒有這麼積極。中國關於「第三種人」的文字，今年已經匯印了一本專書，我們可以查一查，凡自稱為「第三種人」的言論，可有絲毫近似這樣的意見的麼？倘其沒有，則我敢決定地說，「不可以說紀德是『第三種人』」。

然而正如我說紀德不像中國的「第三種人」一樣，戴望舒先生也覺得中國的左翼作家和法國的大有賢愚之別了。他在參加大會，為德國的左翼藝術家同伸義憤之後，就又想起了中國左翼作家的愚蠢橫暴的行為。於是他臨末禁不住感慨——

#+BEGIN_EXAMPLE

「我不知道我國對於德國法西斯諦的暴行有沒有什麼表示。正如我們的軍閥一樣，我們的文藝者也是勇於內戰的。在法國的革命作家們和紀德攜手的時候，我們的左翼作家想必還在把所謂『第三種人』當作唯一的敵手吧！」
#+END_EXAMPLE

這裡無須解答，因為事實具在：我們這裡也曾經有一點表示，但因為和在法國兩樣，所以情形也不同；刊物上也久不見什麼「把所謂『第三種人』當作唯一的敵手」的文章，不再內戰，沒有軍閥氣味了。戴先生的豫料，是落了空的。

然而中國的左翼作家，這就和戴先生意中的法國左翼作家一樣賢明瞭麼？我以為並不這樣，而且也不應該這樣的。如果聲音還沒有全被削除的時候，對於「第三種人」的討論，還極有從新提起和展開的必要。戴先生看出了法國革命作家們的隱衷，覺得在這危急時，和「第三種人」攜手，也許是「精明的策略」。但我以為單靠「策略」，是沒有用的，有真切的見解，才有精明的行為，只要看紀德的講演，就知道他並不超然於政治之外，決不能貿貿然稱之為「第三種人」，加以歡迎，是不必別具隱衷的。不過在中國的所謂「第三種人」，卻還複雜得很。

所謂「第三種人」，原意只是說：站在甲乙對立或相鬥之外的人。但在實際上，是不能有的。人體有胖和瘦，在理論上，是該能有不胖不瘦的第三種人的，然而事實上卻並沒有，一加比較，非近於胖，就近於瘦。文藝上的「第三種人」也一樣，即使好像不偏不倚罷，其實是總有些偏向的，平時有意的或無意的遮掩起來，而一遇切要的事故，它便會分明的顯現。如紀德，他就顯出左向來了；別的人，也能從幾句話裡，分明的顯出。所以在這混雜的一群中，有的能和革命前進，共鳴；有的也能乘機將革命中傷，軟化，曲解。左翼理論家是有著加以分析的任務的。

如果這就等於「軍閥」的內戰，那麼，左翼理論家就必須更加繼續這內戰，而將營壘分清，拔去了從背後射來的毒箭！

**** 论「第三种人」
     :PROPERTIES:
     :CUSTOM_ID: 19340101
     :AUTHOR:   梁实秋
     :END:

     - Note taken on [2019-12-31 二 20:33] \\
       《一个都不宽恕》的复制上限到了，我无法在里面复制文章了。
     - Note taken on [2019-12-31 二 20:29] \\
       这篇文章收录在《偏见集》，但是我手头上没有这本书，互联网上也搜索不到，所以这个 CUSTOM_ID 并不准确。

鲁迅先生最近到北平，做过数次演讲，有一次讲题是“第三种人”。据报纸所记，其演讲的主旨大致是和他在《现代》二卷一期上所发表的那篇论文差不多，不过这一回花样略为翻新一些。这一回他举了一个譬喻说，胡适之先生所倡导的新文学运动，是穿着皮鞋踏入文坛，现在的普罗运动，是赤脚的也要闯入文坛。随后报纸上就有人批评说，鲁迅先生演讲的那天既未穿皮鞋亦未赤脚，而登着一双帆布胶皮鞋，正是“第三种人”。

非赤即白，非友即敌，非左即右，非普罗阶级即资产阶级，非革命即反革命——这一套的逻辑，我们是已经听过不少了。鲁迅先生之根本否认“第三种人”亦不过是此种逻辑运用到文学上的一例而已。

第一种人是普罗文学家，第二种人是资产阶级文学家，第三种人根本不存在。故文学家只有两种。第一种人是“新兴”，其成功是有“必然性”的；第二种人如无著作发表，则系“没落”，如有著作发表，则为“落伍”，如胆敢在理论上有所声辩，则系“作最后之挣扎”。这已经成为一种公式了。然而这只是一种分类法，以资产的有无来做标准，人类自然是可以分为两个阶级，没有“第三种人”存在的余地。但是若换一个标准，分类法也就随之而异了。例如：按照印度婆罗门教的规律，人是分为四个阶级了；按照批评家安诺德在《文化与混乱》里所讲，人是分为三个型类了；按照人类学家的方法，皮肤的颜色，头发的曲直，无不可为分类的标准；按照欧洲中古的星相学，人又可分为四类不同的气质；按照中国的算命先生，又有五行之说。总之，分来分去，人类还是人类。分类的标准不止一个，资产阶级与无产阶级之说只是一种分类法的结果。在这一种分类法之下，若没有第三种人的存在的可能，在另一种标准之下，也许不但有第三种人，还许有第四种人。

“以经济的眼光和阶级的立场来说明文艺的现象，自不失为一种新鲜的方法，于文艺背景之阐明有时是很有裨益的。但亦不是万灵。例如辛克莱尔的《拜金艺术》，他是想给文学以经济的解释的，但除了一部分中肯的解释以外，有时便牵强附会，更有时把难于自圆其说的材料略去不提。台恩的《英国文学史》想以科学方法解释一切文学，也遭遇了同样的失败。凡是在文艺范围之外另寻方法拿来做解释一切文学之万灵的钥匙者，大概都不免失败，虽然其失败有时是光荣的。”

“强分作家为两个阶级，或左右二翼，这对于文学的发展并没有什么利益。这也许是一种策略罢，大约是逼迫一般较易接受宣传的作家向左转的策略。如此，则第三种人之被否认，亦正是此策略之一部，使此种自称为“第三种人”者感觉惶惑不安，然后左转，以免于“没落”，而加厚无产阶级之势力。为阶级斗争计，此种策略是聪明的。为文学计，此种策略无利亦无害。”

“在资产上论，人有贫富之别，而在人性上论，根本上没有多大分别。“性相近，习相远”，这话是不错的。勤苦诚实，是劳动者的美德，资产阶级亦视为美德；欺诈取巧，是买办的劣点，工人也不是绝对没有。喜怒哀乐的常情，并不限于阶级。文学的对象就是这超阶级而存在的常情，所以文学不必有阶级性；如其文学反映出多少的阶级性，那也只是附带的一点色彩，其本质固在于人性之描写而不在于阶级性的表现。岂特第三种人不存在，第一种人第二”“种人亦无保存此区分之必要。穿皮鞋的，穿帆布胶皮鞋的，赤脚的，在文学里都有位置。能够沉静的观察人生，透澈的表现人性的一部，这就是文学家，他写的东西就是好作品，至于他是什么籍贯的人，他的出身是贵族抑是平民，他的牙齿是黄色是黑色，虽亦常为读者所乐知，究是无关紧要。讲到作者的个性，那是一个人一个样，岂但不仅三种，简直可以说有多少人便有多少种。文学的材料究竟有限，而文学家的个性不同，所以观点各异，人性相同而表现的方法不同，所以作风各异。文学家像狮子，他是独来独往，不像狐狸不像狗，他不成群结队。你说第三种人不存在么？他自己就是一种。”

