*** 撕开「民族主义文学」的假面
    :PROPERTIES:
    :CUSTOM_ID: chap3sec2
    :END:

    - Note taken on [2019-12-31 二 19:55] \\
      这一节，原书就编的非常混乱，所以我浅尝辄止，跳过部分章节。
**** 民族主义文艺运动宣言
     :PROPERTIES:
     :CUSTOM_ID: 19301010
     :AUTHOR:   傅彦长
     :END:

中国民族主义文艺运动者，于民国十九年六月一日，集会于上海，发表宣言如下：

**一**

中国的文艺界近来深深地陷入于畸形的病态的发展进程中。这种现象，在稍稍留意于我国今日的艺坛及文坛的人必不会否认。在今日，当前的现象，正是中国文艺的危机。

我们试一看我们今日的文坛艺坛，我们便可以发现这种混杂的局面。我们会看见在这新文坛时代下，还竟有人在保持残余的封建思想。中国新文艺运动底历史还不甚悠久，其被一般所接受，虽已不能否认，但从新文艺运动发生以后，至于今日，因为从事于新文艺运动的人，对于文艺的中心意识底缺乏，努力于形式的改革而忽略于内容的充实，致一切残余的封建思想，仍在那里无形地支配一切，这是无可讳言的。

同时我们看到那自命左翼的所谓无产阶级的文艺运动，他们将艺术“呈献给‘胜利不然就死’的血腥的斗争”。而以“……艺术不能不以无产阶级在这黑暗的阶级社会之‘中世纪’里面所感觉的感觉为内容……”同时，我们又看见那所谓左翼画家结合底运动，在他们的宣言里是：“诸君，请看那些拜金主义的画家们，他们除了为自己的名誉和黄金，除了为自己的地盘与奢华的生活以外，从没有为了我们谋利益吧！……青年美术家诸君，诸君应该认清他们的欺骗和榨取是他们压迫阶级一贯的政策。……”因此，在我们中国的旧文艺已倾圮，而新文艺建设的过程中却产生这类意识的阶级的艺术运动。

在这样的两个极端的思想中，我们还可以看见许多形形式式的局面。每一个小组织，各拥有一个主观的见解。因之，今日中国的新文坛艺坛上满呈着零碎的残局。在这样的局面下，对文艺的中心意识遂致不能形成，所以自有新文艺运动以至今日，我们在新文艺上甚少成就。

假如这种多型的文艺意识，各就其所意识到的去路而进展，则这种文艺上纷扰的残局永不会消失，其结果将致我们的新文艺运动永无发挥之日，而陷于必然的倾圮。当前的现象正是我们新文艺的危机。

但我们又如何而突破这个危机，使我们的新文艺运动演进至于灿烂辉煌之域？在前，我们认为现下中国文艺的危机是由于多型的对于文艺底见解，而在整个新文艺发展底进程中缺乏中心的意识。因此突破这个当前的危机底唯一方法，是在努力于新文艺演进进程中底中心意识底形成。

**二**

艺术，从它的最初的历史的纪录上，已经明示了我们它所负的使命。我们很明了，艺术作品在原始状态里，不是从个人的意识里产生而是从民族的立场所形成的生活意识里产生的，在艺术作品内所显示的不仅是那艺术家的才能，技术，风格和形式；同时，在艺术作品内显示的也正是那艺术家所属的民族底产物。这在艺术史上是很明显地告诉了我们了。

从那辽远的古代艺术上，我们便可以看出艺术之民族的基础。金字塔及人面兽之所以发现在埃及，因为这种艺术，是埃及的民族精神底展露，他们所显示的正是埃及的民族意识。金字塔是坟墓建筑，它之所以勃兴，足以映示埃及人对于死人观念的宗教信仰；人面兽及其他的艺术形态，均是埃及民族宗教底表示。希腊留下来的伟大的建筑物和雕刻，也正是希腊民族性底表示。因为希腊民族有勇猛活泼的精神，有美丽强健的身体，有兴奋热烈的感情，有物质享乐的要求，有现世思想而非出世思想的宗教观与人生观，有爱好运动兴趣；故在希腊艺术上所表现的正是希腊的民族精神；一般人所最易见的维娜丝像，正足以反映希腊民族象征人生底宗教观念；较普通的铁饼投手，也很明显希腊人爱好运动底精神。在希腊艺术上，我们看见希腊民族性底充分展布。即使就是在中古世，在那政治不安定，充满了封建主义而缺乏民族意识的中古世，在当时所流行的建筑，雕刻和绘画，也多少各有其民族的色彩。

艺术之民族色彩，益趋明显。当中古的封建制度底渐渐倾圮之时，民族的意识愈见勃长。文艺复兴的热烈运动，其所以为近代艺术开了端倪，便是它之从中古的峨特艺术底羁绊中，为民族艺术底创造。由于它，我们看见文艺复兴及其后的白罗克并罗哥哥艺术，都是新兴的民族意识底显露。

在文学上，文学之民族的要素，也和艺术一样地存在着。文学的原始形态，我们现在虽则很难断定其为何如，但可以深信的，它必基于民族底一般的意识。这我们在希腊的《伊里亚特》和《奥德赛》，日耳曼的《尼贝龙根》，英吉利的《皮华而夫》，法兰西的《罗兰歌》及我国的《诗经》《国风》上，很可以明了的。在西洋，民族文学底发展，必须有赖于支配拉丁语文的毁覆，及民族语文底行用。文艺复兴时代之所以为近代文学开了端倪，是因但丁及却塞各努力于把他们所属民族底民族语文为他们文学表现底手段，在英国，由于却塞底努力，我们看见有以利沙伯朝及其后底灿烂的文学时代。

由此我们很可以从这些文艺的纪录上明了文艺的起源——也就是文艺底最高的使命，是发挥它所属的民族精神和意识。换一句说：文艺的最高意义，就是民族主义。

**三**

民族主义文艺底充分发展，一方面须赖于政治上的民族意识底确立，一方面也直接影响于政治上民族主义的确立。

就前者言：民族文艺底充分发展必须有待于政治上的民族国家的建立，民族文艺底发展必伴随以民族国家底产生；所以我们在近代，看见民族文艺有充分的发展。

自从一八一五年的维也纳会议以后，欧洲各处都充满着民族主义的思想。那个时候，在欧洲的地图上还没有独立的有德意志、意大利、匈牙利、波兰、捷克斯拉夫、巨哥斯拉夫及芬兰等民族国家。所以在当时，民族主义的运动是非常澎湃。民族主义底目的，是在形成独立的民族国家。匈牙利是在海斯堡铁蹄之下；德意志充满了封建制度的遗风；在同一民族之下，有许多小小的封建的郡主；意大利仅仅是一个“地理上的名词”，施锦尼（Szechinyt）之流的匈牙利民族运动，终于被海斯堡所征服。海斯堡帝国是当时欧洲政局底霸主。在他的主宰之下，有匈牙利人，神圣罗马帝国所遗留下来的许多封建的郡主，所谓意大利的许多政治组织底单位。这种情形之下，努力于民族主义最烈的要推普鲁士及萨丁尼亚；我们在这里无须重复说明他们如何奋斗，至少自维也纳会议以后，欧洲的民族，已经认明他们唯一的出路是民族主义。他们开始向这方向跑，这条路不是康庄大道，当然是崎岖异常。

一八七一年是很可纪念的一年。在那一年不但是法国被德国打败得狼狈不堪，他之所以可纪念，是欧洲民族主义运动底成功，德意志自一八一五年以后，就认明这条民族主义的道路，因为小的郡主太多，不能不推出普鲁士来做他们民族运动的首领。结果便是德意志民族国家底建立。

一八七一年之所以值得纪念，还有意大利民族底产生。虽则意大利在这年前已经有民族国家底产生，但那时罗马还在法国占领之下。普法战争底结果，便是在罗马占领中的法国军队底召回，使民族的意大利国得以奠都于罗马——意大利的必然的首都。

自一八七一年以后，日耳曼人及意大利人虽则实现了他自一八七一年以后，日耳曼人及意大利人虽则实现了他们的民族运动，但欧洲的民族运动便不因此而停止。巴尔干问题自柏林会议以后，一直到现在不曾有满意各方的解决，而为战争酝酿的原因，便是在该处的民族运动。同时屈伏于海斯堡下的斯拉夫民族，自一八七一年后，便开始有政治的民族运动；一直到一九一四至一九一八年以后的欧战，才实现了他们的企图。欧战底结果，我们看见有更多民族国家底产生，和两大帝国底崩圮。在海斯堡铁蹄下的斯拉夫民族，实现了他们的企望；我们看见有巨哥斯拉夫、捷克斯洛夫基亚等民族国家底建立。

一九一七年十一月俄罗斯革命的结果，我们不但看见罗门诺夫帝国主义底倾覆，并且同时看见民族主义更多的成功。不但是芬兰、波兰、拉脱维亚、立陶宛及爱沙尼亚等民族的都已挣开了俄罗斯的羁绊羁而建立独立的民族国家，并且，我们看见乌克兰、白俄罗斯、南高加索、突厥和乌兹贝克各民族，都建立自主的民族国家，即俄罗斯社会主义苏维埃联邦共和国，也是由十一个自主国和十二个自主州所组成，于此足见民族主义的力量是恒久的伟大。

最近象中国的国民革命，土耳其共和国的建立，爱尔兰的自治运动，菲律宾的独立运动，朝鲜、印度、越南的独立运动，更充满了民族运动的记录。故近代文艺，因此也满呈着民族主义底运动，诚如政治上的出路是民族主义，故文艺发展底出路也是集中于民族主义。现代法兰西的艺术，最初的一名运动员是塞尚奈。他将当时流行于法国的各派艺术底主张，如印象派光的现象的注重，殷格莱（Ingres）底《画的万有说》，和柯尔贝（Courbert）底《实际论》，总合起来，而加添了他自己独创的主张——所谓自我的表现和线的形式的注重，演成所谓后来的立体主义；及野兽运动（Fauves）及最后演进于所谓“纯粹主义”；在这多种多样艺术界中，中心意识，却还只是一个，就是法兰西的民族意识。

在德国，德国人另有他的民族艺术，他们的运动集中于表现主义底旗帜之下，所谓表现主义，是日耳曼民族底民族精神，及民族意识底表露，故表现主义尤其富于浓厚的民族特征。诚如白令顿教授（Prof．Brinton）所言：“日耳曼人的现代艺术是所谓表现主义；满呈了日耳曼的民族特征。”

此外，意大利人对于民族艺术的努力是集中于未来主义，俄罗斯人对于民族艺术底努力是集中于原始主义。这种主义都是他们民族精神及民族意识底表露。如前所述，我们很可以明了，文艺底进展随着政治底进展。故民族文艺底确立，必有待于民族国家底建立。

就后者说，文艺上的民族运动，直接影响及于政治上的民族主义底确立。这我们在巨哥斯拉夫底发展上是明了的。巨哥斯拉夫底民族艺术运动较巨哥斯拉夫民族国家底诞生为先。巨哥斯拉夫底民族艺术运动集中于麦司屈洛维克（Mestrovic），一九零五年成立底南斯拉夫艺术家联盟，是巨哥斯拉夫民族艺术具体的组织的活动底开端，他们集中于他们表现于南斯拉夫民族底历史的烈风和其民族的意志。由于巨哥斯拉夫民族国家艺术的确立，我们在欧战后就看见有巨哥斯拉夫民族国家底出现。

艺术和文学，因之必须以民族为其基础，这事实是不容否认的了。但是民族主义的文艺所包含的内容又是什么呢？

**四**

民族是一咧人种的集团。这种人种的集团底形成，决定于文化的、历史的、体质的及心理的共同点，过去的共同奋斗，是民族形成唯一的先决条件。因之，民族主义的目的，不仅消极地在乎维系那一群人种底生存，并积极地发挥那一群人底力量和增长那一群人底光辉。

艺术和文学是属于某一民族的，为了某一民族，并由某一民族产生的，其目的不仅在表现那所属民族底民间思想，民间宗教，及民族的情趣；同时在排除一切阻碍民族进展的思想，在促进民族的向上发展底意志，在表现民族在增长自己的光辉底进程中一切奋斗的历史。因之，民族主义的文艺，不仅在表现那已经形成的民族意识；同时，并创造那民族底新生命。

属于第一义的民族艺术，表现民族的情趣，我们看见有现代德意志的表现主义，俄罗斯的原始主义，及法兰西的纯粹主义。

属于第二义的民族艺术，我们看见有意大利的未来主义及巨哥斯拉夫的现代艺术。未来主义的中心意识，在物质或机械文明的赞扬，我们看到意大利在西洋是物质文明落后的国家，唯其如此，所以未来主义出现于意大利；以创造意大利民族对于物质文明底意识。巨哥斯拉夫的民族艺术，在麦司屈洛维克领导之下，不仅表现了他们民族的过去的奋斗，并努力于南斯拉夫人民族国家底意识底建立。

**五**

现今我们中国文坛艺坛底当前的危机是对于文艺缺乏中心意识。那末，我们要突破这个危机，并促进我们的文艺底开展，势必在形成一个对于文艺底中心意识。从历史的教训，我们须集中我们此后的努力于民族主义的文学与艺术底创造。我们此后的文艺活动，应以我们的唤起民族意识为中心；同时，为促进民族的繁荣，我们须促进民族的向上发展的意志，创造民族的新生命。我们现在所负的，正是建立我们的民族主义文学与艺术重要伟大的使命。

**** 「民族主义文学」的任务和运命
     :PROPERTIES:
     :CUSTOM_ID: 19311023
     :END:

**一**

殖民政策是一定保护，养育流氓的。从帝国主义的眼睛看来，惟有他们是最要紧的奴才，有用的鹰犬，能尽殖民地人民非尽不可的任务：一面靠著帝国主义的暴力，一面利用 本国的传统之力，以除去“害群之马”，不安本分的“莠民”。所以，这流氓，是殖民地上的洋大人的宠儿，——不，宠犬，其地位虽在主人之下，但总在别的被统治者之上 的。上海当然也不会不在这例子里。巡警不进帮，小贩虽自有小资本，但倘不另寻一个流氓来做债主，付以重利，就很难立足。到去年，在文艺界上，竟也出现了“拜老头” 的“文学家”。

但这不过是一个最露骨的事实。其实是，即使并非帮友，他们所谓“文艺家”的许多人，是一向在尽“宠犬”的职分的，虽然所标的口号，种种不同，艺术至上主义呀，国粹 主义呀，民族主义呀，为人类的艺术呀，但这仅如巡警手里拿着前膛枪或后膛枪，来福枪，毛瑟枪的不同，那终极的目的却只一个：就是打死反帝国主义即反政府，亦即“反 革命”，或仅有些不平的人民。

那些宠犬派文学之中，锣鼓敲得最起劲的，是所谓“民族主义文学”。但比起侦探，巡捕，刽子手们的显著的勋劳来，却还有很多的逊色。这缘故，就因为他们还只在叫，未 行直接的咬，而且大抵没有流氓的剽悍，不过是飘飘荡荡的流尸。然而这又正是“民族主义文学”的特色，所以保持其“宠”的。

翻一本他们的刊物来看罢，先前标榜过各种主义的各种人，居然凑合在一起了。这是“民族主义”的巨人的手，将他们抓过来的么？并不，这些原是上海滩上久已沈沈浮浮的 流尸，本来散见于各处的，但经风浪一吹，就漂集一处，形成一个堆积，又因为各个本身的腐烂，就发出较浓厚的恶臭来了。

这“叫”和“恶臭”有能够较为远闻的特色，于帝国主义是有益的，这叫做“为王前驱”，所以流尸文学仍将与流氓政治同在。

**二**

但上文所说的风浪是什么呢？这是因无产阶级的勃兴而卷起的小风浪。先前的有些所谓文艺家，本未尝没有半意识的或无意识的觉得自身的溃败，于是就自欺欺人的用种种美 名来掩饰，曰高逸，曰放达（用新式话来说就是“颓废”），画的是裸女，静物，死，写的是花月，圣地，失眠，酒，女人。一到旧社会的崩溃愈加分明，阶级的斗争愈加锋 利的时候，他们也就看见了自己的死敌，将创造新的文化，一扫旧来的污秽的无产阶级，并且觉到了自己就是这污秽，将与在上的统治者同其运命，于是就必然漂集于为帝国 主义所宰制的民族中的顺民所竖起的“民族主义文学”的旗帜之下，来和主人一同做一回最后的挣扎了。

所以，虽然是杂碎的流尸，那目标却是同一的：和主人一样，用一切手段，来压迫无产阶级，以茍延残喘。不过究竟是杂碎，而且多带着先前剩下的皮毛，所以自从发出宣言 以来，看不见一点鲜明的作品，宣言是一小群杂碎胡乱凑成的杂碎，不足为据的。

但在《前锋月刊》第五号上，却给了我们一篇明白的作品，据编辑者说，这是“参加讨伐阎冯军事的实际描写”。描写军事的小说并不足奇，奇特的是这位“青年军人”的作 者所自述的在战场上的心绪，这是“民族主义文学家”的自画像，极有郑重引用的价值的——“每天晚上站在那闪烁的群星之下，手里执著马枪，耳中听着虫鸣，四周飞动着 无数的蚊子，那样都使人想到法国‘客军’在菲洲沙漠里与阿剌伯人争斗流血的生活。”（黄震遐：《陇海线上》）

原来中国军阀的混战，从“青年军人”，从“民族主义文学者”看来，是并非驱同国人民互相残杀，却是外国人在打别一外国人，两个国度，两个民族，在战地上一到夜里， 自己就飘飘然觉得皮色变白，鼻梁加高，成为腊丁民族的战士，站在野蛮的菲洲了。那就无怪乎看得周围的老百姓都是敌人，要一个一个的打死。法国人对于菲洲的阿剌伯人 ，就民族主义而论，原是不必爱惜的。仅仅这一节，大一点，则说明了中国军阀为什么做了帝国主义的爪牙，来毒害屠杀中国的人民，那是因为他们自己以为是“法国的客军 ”的缘故；小一点，就说明中国的“民族主义文学家”根本上只同外国主子休戚相关，为什么倒称“民族主义”，来朦混读者，那是因为他们自己觉得有时好像腊丁民族，条 顿民族了的缘故。

**三**

黄震遐先生写得如此坦白，所说的心境当然是真实的，不过据他小说中所显示的智识推测起来，却还有并非不知而故意不说的一点讳饰。这，是他将“法国的安南兵”含糊的 改作“法国的客军”了，因此就较远于“实际描写”，而且也招来了上节所说的是非。

但作者是聪明的，他听过“友人傅彦长君平时许多谈论……许多地方不可讳地是受了他的熏陶”，并且考据中外史传之后，接着又写了一篇较切“民族主义”这个题目的剧诗 ，这回不用法兰西人了，是《黄人之血》（《前锋月刊》七号）。

这剧诗的事迹，是黄色人种的西征，主将是成吉思汗的孙子拔都元帅，真正的黄色种。所征的是欧洲，其实专在斡罗斯（俄罗斯）——这是作者的目标；联军的构成是汉，鞑 靼，女真，契丹人——这是作者的计划；一路胜下去，可惜后来四种人不知“友谊”的要紧和“团结的力量”，自相残杀，竟为白种武士所乘了——这是作者的讽喻，也是作 者的悲哀。

但我们且看这黄色军的威猛和恶辣罢——

#+BEGIN_EXAMPLE
…………

恐怖呀，煎著尸体的沸油；

可怕呀，遍地的腐骸如何凶丑；

死神捉著白姑娘拼命地搂；

美人螓首变成狞猛的髑髅；

野兽般的生番在故宫里蛮争恶斗；

十字军战士的脸上充满了哀愁；

千年的棺材泄出它凶秽的恶臭；

铁蹄践著断骨，骆驼的鸣声变成怪吼；

上帝已逃，魔鬼扬起了火鞭复仇；

黄祸来了！黄祸来了！

亚细亚勇士们张大吃人的血口。
#+END_EXAMPLE

这德皇威廉因为要鼓吹“德国德国，高于一切”而大叫的“黄祸”，这一张“亚细亚勇士们张大”的“吃人的血口”，我们的诗人却是对着“斡罗斯”，就是现在无产者专政 的第一个国度，以消灭无产阶级的模范——这是“民族主义文学”的目标；但究竟因为是殖民地顺民的“民族主义文学”，所以我们的诗人所奉为首领的，是蒙古人拔都，不 是中华人赵构，张开“吃人的血口”的是“亚细亚勇士们”，不是中国勇士们，所希望的是拔都的统驭之下的“友谊”，不是各民族间的平等的友爱——这就是露骨的所谓“ 民族主义文学”的特色，但也是青年军人的作者的悲哀。

**四**

拔都死了；在亚细亚的黄人中，现在可以拟为那时的蒙古的只有一个日本。日本的勇士们虽然也痛恨苏俄，但也不爱抚中华的勇士，大唱“日支亲善”虽然也和主张“友谊” 一致，但事实又和口头不符，从中国“民族主义文学者”的立场上，在己觉得悲哀，对他加以讽喻，原是势所必至，不足诧异的。

果然，诗人的悲哀的豫感好像证实了，而且还坏得远。当“扬起火鞭”焚烧“斡罗斯”将要开头的时候，就像拔都那时的结局一样，朝鲜人乱杀中国人，日本人“张大吃人的 血口”，吞了东三省了。莫非他们因为未受傅彦长先生的熏陶，不知“团结的力量”之重要，竟将中国的“勇士们”也看成菲洲的阿剌伯人了吗？！

**五**

这实在是一个大打击。军人的作者还未喊出他勇壮的声音，我们现在所看见的是“民族主义”旗下的报章上所载的小勇士们的愤激和绝望。这也是势所必至，无足诧异的。理 想和现实本来易于冲突，理想时已经含了悲哀，现实起来当然就会绝望。于是小勇士们要打仗了——

#+BEGIN_EXAMPLE
战啊，下个最后的决心，

杀尽我们的敌人，

你看敌人的枪炮都响了，

快上前，把我们的肉体筑一座长城。

雷电在头上咆哮，

浪涛在脚下吼叫，

热血在心头燃烧，

我们向前线奔跑。

（苏凤：《战歌》。《民国日报》载。）
#+END_EXAMPLE

#+BEGIN_EXAMPLE
去，战场上去，

我们的热血在沸腾，

我们的肉身好像疯人，

我们去把热血锈住贼子的枪头，

我们去把肉身塞住仇人的炮口。

去，战场上去，

凭着我们一股勇气，

凭着我们一点纯爱的精灵，去把仇人驱逐，

不，去把仇人杀尽。

（甘豫庆：《去上战场去》。《申报》载。）
#+END_EXAMPLE

#+BEGIN_EXAMPLE
同胞，醒起来罢，

踢开了弱者的心，

踢开了弱者的脑。

看，看，看，

看同胞们的血喷出来了，

看同胞们的肉割开来了，

看同胞们的尸体挂起来了。

（邵冠华：《醒起来罢同胞》。同上。）
#+END_EXAMPLE

这些诗里很明显的是作者都知道没有武器，所以只好用“肉体”，用“纯爱的精灵”，用“尸体”。这正是《黄人之血》的作者的先前的悲哀，而所以要追随拔都元帅之后， 主张“友谊”的缘故。武器是主子那里买来的，无产者已都是自己的敌人，倘主子又不谅其衷，要加以“惩膺”，那么，惟一的路也实在只有一个死了——

#+BEGIN_EXAMPLE
我们是初训练的一队，

有坚卓的志愿，

有沸腾的热血，

来扫除强暴的歹类。

同胞们，亲爱的同胞们，

快起来准备去战，

快起来奋斗，

战死是我们生路。

（沙珊：《学生军》。同上。）
#+END_EXAMPLE

#+BEGIN_EXAMPLE
天在啸，

地在震，

人在冲，兽在吼，

宇宙间的一切在咆哮，朋友哟，

准备着我们的头颅去给敌人砍掉。

（徐之津：《伟大的死》。同上。）
#+END_EXAMPLE

一群是发扬踔厉，一群是慷慨悲歌，写写固然无妨，但倘若真要这样，却未免太不懂得“民族主义文学”的精义了，然而，却也尽了“民族主义文学”的任务。

**六**

《前锋月刊》上用大号字题目的《黄人之血》的作者黄震遐诗人，不是早已告诉我们过理想的元帅拔都了吗？这诗人受过傅彦长先生的熏陶，查过中外的史传，还知道“中世 纪的东欧是三种思想的冲突点”，岂就会偏不知道赵家末叶的中国，是蒙古人的淫掠场？拔都元帅的祖父成吉思皇帝侵入中国时，所至淫掠妇女，焚烧庐舍，到山东曲阜看见 孔老二先生像，元兵也要指著骂道：“说‘夷狄之有君，不如诸夏之无也’的，不就是你吗？”夹脸就给他一箭。这是宋人的笔记里垂涕而道的，正如现在常见于报章上的流 泪文章一样。黄诗人所描写的“斡罗斯”那“死神捉著白姑娘拼命地搂……”那些妙文，其实就是那时出现于中国的情形。但一到他的孙子，他们不就携手“西征”了吗？现 在日本兵“东征”了东三省，正是“民族主义文学家”理想中的“西征”的第一步，“亚细亚勇士们张大吃人的血口”的开场。不过先得在中国咬一口。因为那时成吉思皇帝 也像对于“斡罗斯”一样，先使中国人变成奴才，然后赶他打仗，并非用了“友谊”，送柬帖来敦请的。所以，这沈阳事件，不但和“民族主义文学”毫无冲突，而且还实现 了他们的理想境，倘若不明这精义，要去硬送头颅，使“亚细亚勇士”减少，那实在是很可惜的。

那么，“民族主义文学”无须有那些呜呼阿呀死死活活的调子吗？谨对曰：要有的，他们也一定有的。否则不抵抗主义，城下之盟，断送土地这些勾当，在沈静中就显得更加 露骨。必须痛哭怒号，摩拳擦掌，令人被这扰攘嘈杂所惑乱，闻悲歌而泪垂，听壮歌而愤泄，于是那“东征”即“西征”的第一步，也就悄悄的隐隐的跨过去了。落葬的行列 里有悲哀的哭声，有壮大的军乐，那任务是在送死人埋入土中，用热闹来掩过了这“死”，给大家接着就得到“忘却”。现在“民族主义文学”的发扬踔厉，或慷慨悲歌的文 章，便是正在尽著同一的任务的。

但这之后，“民族主义文学者”也就更加接近了他的哀愁。因为有一个问题，更加临近，就是将来主子是否不至于再蹈拔都元帅的覆辙，肯信用而且优待忠勇的奴才，不，勇 士们呢？这实在是一个很要紧，很可怕的问题，是主子和奴才能否“同存共荣”的大关键。

历史告诉我们：不能的。这，正如连“民族主义文学者”也已经知道一样，不会有这一回事。他们将只尽些送丧的任务，永含着恋主的哀愁，须到无产阶级革命的风涛怒吼起 来，刷洗山河的时候，这才能脱出这沈滞猥劣和腐烂的运命。


**** 不通两种
     :PROPERTIES:
     :CUSTOM_ID: 19330203
     :END:

人们每当批评文章的时候，凡是国文教员式的人，大概是着眼于“通”或“不通”，《中学生》杂志上还为此设立了病院。然而做中国文其实是很不容易“通”的，高手如太史公司马迁，倘将他的文章推敲起来，无论从文字，文法，修辞的任何一种立场去看，都可以发见“不通”的处所。

不过现在不说这些；要说的只是在笼统的一句“不通”之中，还可由原因而分为几种。大概的说，就是：有作者本来还没有通的，也有本可以通，而因了种种关系，不敢通，或不愿通的。

例如去年十月三十一日《大晚报》的记载“江都清赋风潮”，在《乡民二度兴波作浪》这一个巧妙的题目之下，述陈友亮之死云：

#+BEGIN_EXAMPLE

「陈友亮见官方军警中，有携手枪之刘金发，竟欲夺刘之手枪，当被子弹出膛，饮弹而毙，警察队亦开空枪一排，乡民始后退。……」

#+END_EXAMPLE


“军警”上面不必加上“官方”二字之类的费话，这里也且不说。最古怪的是子弹竟被写得好像活物，会自己飞出膛来似的。但因此而累得下文的“亦”字不通了。必须将上文改作“当被击毙”，才妥。倘要保存上文，则将末两句改为“警察队空枪亦一齐发声，乡民始后退”，这才铢两悉称，和军警都毫无关系。——虽然文理总未免有点希奇。

现在，这样的希奇文章，常常在刊物上出现。不过其实也并非作者的不通，大抵倒是恐怕“不准通”，因而先就“不敢通”了的缘故。头等聪明人不谈这些，就成了“为艺术的艺术”家；次等聪明人竭力用种种法，来粉饰这不通，就成了“民族主义文学”者，但两者是都属于自己“不愿通”，即“不肯通”这一类里的。

**** 「最通的」文艺
     :PROPERTIES:
     :CUSTOM_ID: 19330210
     :AUTHOR:   王平陵
     :END:

鲁迅先生最近常常用何家干的笔名，在黎烈文主编的的《申报》的《自由谈》，发表不到五百字长的短文。好久不看见他老先生的文了，那种富于幽默性的讽刺的味儿，在中国的作家之林，当然还没有人能超过鲁迅先生。

不过，听说现在的鲁迅先生已跑到十字街头，站在革命的队伍里去了。那么，像他这种有闲阶级的幽默的作风，严格言之，实在不革命。我以为也应该转变一下才是！譬如：鲁迅先生不喜欢第三种人，讨厌民族主义的文艺，他尽可痛快地直说，何必装腔做势，吞吞吐吐，打这么许多湾儿。在他最近所处的环境，自然是除了那些恭颂苏联德政的献词以外，便没有更通的文艺的。他认为第三种人不谈这些，是比较最聪明的人；民族主义文艺者故意找出理由来文饰自己的不通，是比较次聪明的人。其言可谓尽深刻恶毒之能事。不过，现在最通的文艺，是不是仅有那些对苏联当局摇尾求媚的献词，不免还是疑问。如果先生们真是为着解放劳苦大众而呐喊，犹可说也；假使，仅仅是为着个人的出路，故意制造一块容易招摇的金字商标，以资号召而已。那么，我就看不出先生们的苦心孤行，比到被你们所不齿的第三种人，以及民族主义文艺者，究竟是高多少。

其实，先生们个人的生活，由我看来，并不比到被你们痛骂的小资作家更穷苦些。当然，鲁迅先生是例外，大多数的所谓革命的作家，听说，常常在上海的大跳舞场，拉斐花园里，可以遇见他们伴着娇美的爱侣，一面喝香槟，一面吃朱古力，兴高采烈地跳着狐步舞，倦舞意懒，乘着雪亮的汽车，奔赴预定的香巢，度他们真个消魂的生活。明天起来，写工人呵！斗争呵！之类的东西，拿去向书贾们所办的刊物换取稿费，到晚上，照样是生活在红绿的灯光下，沉醉着，欢唱着，热爱着。像这种优裕的生活，我不懂先生们还要叫什么苦，喊什么冤，你们的猫哭耗子的仁慈，是不是能博得劳苦大众的同情，也许，在先生们自己都不免是绝大的疑问吧！

如果中国人不能从文化的本身上做一点基础的工夫，就这样大家空喊一阵口号，糊闹一阵，我想，把世界上无论那种最新颖最时髦的东西拿到中国来，都是毫无用处。我们承认现在的苏俄，确实是有了他相当的成功，但，这不是偶然。他们从前所遗留下来的一部分文化的遗产，是多么丰富，我们回溯到十月革命以前的俄国文学，音乐，美术，哲学，科学，那一件不是已经到达国际文化的水准。他们有了这些充实的根基，才能产生现在这些学有根蒂的领袖。我们仅仅渴慕人家的成功而不知道努力文化的根本的建树，再等十年百年，乃至千年万年，中国还是这样，也许比现在更坏。

不错，中国的文化运动，也已有二十年的历史了。但是，在这二十年中，在文化上究竟收获到什么。欧美的名著，在中国是否能有一册比较可靠的译本，文艺上的各种派别，各种主义，我们是否都拿得出一种代表作，其他如科学上的发明，思想上的创造，是否能有一种值得我们记忆。唉！中国的文化低落到这步田地，还谈得到什么呢！

要是中国的文艺工作者，如不能从今天起，大家立誓做一番基本的工夫，多多地转运一些文艺的粮食，多多地树艺一些文艺的种子，我敢断言：在现代的中国，决不会产生“最通的”文艺的。

**** 官话而已
     :PROPERTIES:
     :CUSTOM_ID: 19330211
     :END:

这位王平陵先生我不知道是真名还是笔名？但看他投稿的地方，立论的腔调，就明白是属于“官方”的。一提起笔，就向上司下属，控告了两个人，真是十足的官家派势。

说话弯曲不得，也是十足的官话。植物被压在石头底下，只好弯曲的生长，这时俨然自傲的是石头。什么“听说”，什么“如果”，说得好不自在。听了谁说？如果不“如果”呢？“对苏联的当局摇尾求媚的献词”是哪些篇，“倦舞意懒，乘着雪亮的汽车，奔赴预定的香巢”的“所谓革命作家”是哪些人呀？是的，曾经有人当开学之际，命大学生全体起立，向着鲍罗廷一鞠躬，拜得他莫名其妙；也曾经有人做过《孙中山与列宁》，说得他们俩真好像没有什么两样；至于聚敛享乐的人们之多，更是社会上大家周知的事实，但可惜那都并不是我们。平陵先生的“听说”和“如果”，都成了无的放矢，含血喷人了。

于是乎还要说到“文化的本身”上。试想就是几个弄弄笔墨的青年，就要遇到监禁，枪毙，失踪的灾殃，我做了六篇“不到五百字”的短评，便立刻招来了“听说”和“如果”的官话，叫作“先生们”，大有一网打尽之慨。则做“基本的工夫”者，现在舍官许的“第三种人”和“民族主义文艺者”之外还能靠谁呢？“唉！”

然而他们是做不出来的。现在只有我的“装腔作势，吞吞吐吐”的文章，倒正是这社会的产物。而平陵先生又责为“不革命”，好像他乃是真正老牌革命党，这可真是奇怪了。——但真正老牌的官话也正是这样的。


**** 但到底是不行的：这叫作愈出愈奇
     :PROPERTIES:
     :CUSTOM_ID: 19330224
     :END:

     - Note taken on [2019-12-30 一 22:29] \\
       关于「辣椒」这几篇的时间有点混乱。
斯德丁实在不可以代表整个的日耳曼的，北方也实在不可以代表全中国。然而北方的孩子不能用辣椒止哭，却是事实，也实在没有法子想。

吸鸦片的父母生育出来的婴孩，也有烟瘾，是的确的。然而嗜辣椒的父母生育出来的婴孩，却没有辣椒瘾，和嗜醋者的孩子，没有醋瘾相同。这也是事实，无论谁都没有法子想。

凡事实，靠发少爷脾气是还是改不过来的。格里莱阿说地球在回旋，教徒要烧死他，他怕死，将主张取消了。但地球仍然在回旋。为什么呢？就因为地球是实在在回旋的缘故。

所以，即使我不反对，倘将辣椒塞在哭着的北方（！）孩子的嘴里，他不但不止，还要哭得更加利害的。

**** 对战争的祈祷
     :PROPERTIES:
     :CUSTOM_ID: 19330228
     :END:

熱河的戰爭開始了。

三月一日——上海戰爭的結束的「紀念日」，也快到了。「民族英雄」的肖像一次又一次的印刷著，出賣著；而小兵們的血，傷痕，熱烈的心，還要被人糟蹋多少時候？回憶里的炮聲和几千里外的炮聲，都使得我們帶著無可如何的苦笑，去翻開一本無聊的，但是，倒也很有几句「警句」的閒書。這警句是：

#+BEGIN_EXAMPLE
「喂，排長，我們到底上那里去喲？」——其中的一個問。

「走吧。我也不曉得。」

「丟那媽，死光就算了，走什么！」

「不要吵，服從命令！」

「丟那媽的命令！」

然而丟那媽歸丟那媽，命令還是命令，走也當然還是走。四點鐘的時候，中山路复歸于沉寂，風和葉儿沙沙的響，月亮躲在青灰色的云海里，睡著，依舊不管人類的事。

這樣，十九路軍就向西退去。

（黃震遐：《大上海的毀滅》。）
#+END_EXAMPLE

什么時候「丟那媽」和「命令」不是這樣各歸各，那就得救了。

不然呢？還有「警句」可以回答這個問題：

#+BEGIN_EXAMPLE
十九路軍打，是告訴我們說，除掉空說以外，還有些事好做！

十九路軍胜利，只能增加我們苟且，偷安与驕傲的迷夢！

十九路軍死，是警告我們活得可怜，無趣！

十九路軍失敗，才告訴我們非努力，還是做奴隸的好！

（見同書。）
#+END_EXAMPLE

這是警告我們，非革命，則一切戰爭，命里注定的必然要失敗。現在，主戰是人人都會的了——這是一二八的十九路軍的經驗：打是一定要打的，然而切不可打胜，而打死也不好，不多不少剛剛适宜的辦法是失敗。「民族英雄」對于戰爭的祈禱是這樣的。而戰爭又的确是他們在指揮著，這指揮權是不肯讓給別人的。戰爭，禁得起主持的人預定著打敗仗的計畫么？好像戲台上的花臉和白臉打仗，誰輸誰贏是早就在后台約定了的。嗚呼，我們的「民族英雄」！

**** 不要乱咬人当心咬着辣椒
     :PROPERTIES:
     :AUTHOR:   王慈
     :CUSTOM_ID: 19330228
     :END:

上海近来多了赵大爷赵秀才一批的人，握了尺棒，拚命想找到“阿Q相”的人来出气。还好，这一批文人从有色的近视眼镜里望出来认为“阿Q相”的，偏偏不是真正的阿Q。

不知道是什么来历的何家干，看了我的《提倡辣椒救国》（见本刊十二号），认北方小孩的爱嗜辣椒，为“空前绝后”的“奇闻”。倘使我那位北方朋友告诉我，是吹的牛皮，那末，的确可以说空前。而何家干既不是数千年前的刘伯温，在某报上做文章，却是像在造《推背图》。北方小孩子爱嗜辣椒，若使可以算是“奇闻”，那么吸鸦片的父母，生育出来的婴孩，为什么也有烟瘾呢？

何家干既抓不到可以出气的对象，他在扑了一个空之后，却还要振振有词，说什么：“倘使是真的，中国人可实在是一种与众不同的特别民族了。”

敢问何家干，戴了有色近视眼镜捧读《提倡辣椒救国》的时候，有没有看见“北方”两个字？（何家干既把有这两个字的句子，录在他的谈话里，显然的是看到了。）既已看到了，那末，请问斯德丁是不是可以代表整个的日耳曼？亚伯丁是不是可以代表整个的不列颠群岛？

在这里我真怀疑，何家干的脑筋，怎的是这么简单？会前后矛盾到这个地步！

赵大爷和赵秀才一类的人，想结党来乱咬人。我可以先告诉他们：我和《辣椒与橄榄》的编者是素不相识的，我也从没有写过《黄人之血》，请何家干若使一定要咬我一口，我劝他再架一副可以透视的眼镜，认清了目标再咬。否则咬着了辣椒，哭笑不得的时候，我不能负责。


**** 提倡辣椒救國
     :PROPERTIES:
     :CUSTOM_ID: 19330312
     :AUTHOR:   王慈
     :END:

记得有一次跟着一位北方朋友上天津点心馆子里去，坐定了以后，堂倌跑过来问道：

“老乡！吃些什么东西？”

“两盘锅贴儿！”那位北方朋友用纯粹的北方口音说。

随着锅贴儿端来的，是一盆辣椒。

我看见那位北方朋友把锅贴和着多量的辣椒津津有味的送进嘴里去，触起了我的好奇心，探险般的把一个锅贴悄悄的蘸上一点儿辣椒，送下肚去，只觉得舌尖顿时麻木得失了知觉，喉间痒辣得怪难受，眼眶里不自主涌着泪水，这时，我大大的感觉到痛苦。

那位北方朋友看见了我这个样子，大笑了起来，接着他告诉我，北方人的善吃辣椒是出于天性，他们是抱着“饭菜可以不要，辣椒不能不吃”的主义的；他们对于辣椒已经是仿佛吸鸦片似的上了瘾！还有北方人自小在母亲怀里，大哭的时候，倘使母亲拿一只辣茄子给小儿咬，很灵验的可以立止大哭……

现在的中国，仿佛是一个大哭时的北方婴孩，倘使要制止他讨厌的哭声，只要多多的给辣茄子他咬。

中国的人们，等于我的那位北方朋友，不吃辣椒是不会兴奋的！

**** 止哭文学
     :PROPERTIES:
     :CUSTOM_ID: 19330324
     :END:

前三年，“民族主義文學”家敲著大鑼大鼓的時候，曾經有一篇《黃人之血》說明了最高的愿望是在追隨成吉思皇帝的孫子拔都元帥之后，去剿滅“斡羅斯”。斡羅斯者，今之蘇俄也。那時就有人指出，說是現在的拔都的大軍，就是日本的軍馬，而在“西征”之前，尚須先將中國征服，給變成從軍的奴才。

當自己們被征服時，除了极少數人以外，是很苦痛的。這實例，就如東三省的淪亡，上海的爆擊，凡是活著的人們，毫無悲憤的怕是很少很少罷。但這悲憤，于將來的“西征”是大有妨礙的。于是來了一部《大上海的毀滅》，用數目字告訴讀者以中國的武力，決定不如日本，給大家平平心；而且以為活著不如死亡（“十九路軍死，是警告我們活得可怜，無趣！”），但胜利又不如敗退（“十九路軍胜利，只能增加我們苟且，偷安与驕傲的迷夢！”）。總之，戰死是好的，但戰敗尤其好，上海之役，正是中國的完全的成功。

現在第二步開始了。据中央社消息，則日本已有与滿洲國簽訂一种“中華聯邦帝國密約”之陰謀。那方案的第一條是：“現在世界只有兩种國家，一种系資本主義，英，美，日，意，法，一种系共產主義，蘇俄。現在要抵制蘇俄，非中日聯合起來……不能成功”云（詳見三月十九日《申報》）。

要“聯合起來”了。這回是中日兩國的完全的成功，是從“大上海的毀滅”走到“黃人之血”路上去的第二步。

固然，有些地方正在爆擊，上海卻自從遭到爆擊之后，已經有了一年多，但有些人民不悟“西征”的必然的步法，竟似乎還沒有完全忘掉前年的悲憤。這悲憤，和目前的“聯合”就大有妨礙的。在這景況中，應運而生的是給人們一點爽利和慰安，好像“辣椒和橄欖”的文學。這也許正是一服苦悶的對症藥罷。為什么呢？就因為是“辣椒雖辣，辣不死人，橄欖雖苦，苦中有味”的。明乎此，也就知道苦力為什么吸鴉片。

而且不獨無聲的苦悶而已，還据說辣椒是連“討厭的哭聲”也可以停止的。王慈先生在《提倡辣椒救國》這一篇名文里告訴我們說：

“……還有北方人自小在母親怀里，大哭的時候，倘使母親拿一只辣茄子給小儿咬，很靈驗的可以立止大哭……“現在的中國，仿佛是一個在大哭時的北方嬰孩，倘使要制止他討厭的哭聲，只要多多的給辣茄子他咬。”（《大晚報》副刊第十二號）

辣椒可以止小儿的大哭，真是空前絕后的奇聞，倘是真的，中國人可實在是一种与眾不同的特別“民族”了。然而也很分明的看見了這种“文學”的企圖，是在給人一辣而不死，“制止他討厭的哭聲”，靜候著拔都元帥。

不過，這是無效的，遠不如哭則“格殺勿論”的靈驗。此后要防的是“道路以目”了，我們等待著遮眼文學罷。

*** 戳穿「第三种人」
    :PROPERTIES:
    :CUSTOM_ID: chap03sec03
    :END:

**** 論「第三種人」
     :PROPERTIES:
     :CUSTOM_ID: 19321101
     :END:

這三年來，關於文藝上的論爭是沉寂的，除了在指揮刀的保護之下，掛著「左翼」的招牌，在馬克斯主義裡發見了文藝自由論，列寧主義裡找到了殺盡共匪說的論客的「理論」之外，幾乎沒有人能夠開口，然而，倘是「為文藝而文藝」的文藝，卻還是「自由」的，因為他決沒有收了盧布的嫌疑。但在「第三種人」，就是「死抱住文學不放的人」又不免有一種苦痛的豫感：左翼文壇要說他是「資產階級的走狗」。

代表了這一種「第三種人」來鳴不平的，是《現代》雜誌第三和第六期上的蘇汶先生的文章（我在這裡先應該聲明：我為便利起見，且用了「代表」，「第三種人」這些字眼，雖然明知道蘇汶先生的「作家之群」，是也如拒絕「或者」，「多少」，「影響」這一類不十分決定的字眼一樣，不要固定的名稱的，因為名稱一固定，也就不自由了）。他以為左翼的批評家，動不動就說作家是「資產階級的走狗」，甚至於將中立者認為非中立，而一非中立，便有認為「資產階級的走狗」的可能，號稱「左翼作家」者既然「左而不作」，「第三種人」又要作而不敢，於是文壇上便沒有東西了。然而文藝據說至少有一部分是超出於階級鬥爭之外的，為將來的，就是「第三種人」所抱住的真的，永久的文藝。——但可惜，被左翼理論家弄得不敢作了，因為作家在未作之前，就有了被罵的豫感。

我相信這種豫感是會有的，而以「第三種人」自命的作家，也愈加容易有。我也相信作者所說，現在很有懂得理論，而感情難變的作家。然而感情不變，則懂得理論的度數，就不免和感情已變或略變者有些不同，而看法也就因此兩樣。蘇汶先生的看法，由我看來，是並不正確的。

自然，自從有了左翼文壇以來，理論家曾經犯過錯誤，作家之中，也不但如蘇汶先生所說，有「左而不作」的，並且還有由左而右，甚至於化為民族主義文學的小卒，書坊的老闆，敵黨的探子的，然而這些討厭左翼文壇了的文學家所遺下的左翼文壇，卻依然存在，不但存在，還在發展，克服自己的壞處，向文藝這神聖之地進軍。蘇汶先生問過：克服了三年，還沒有克服好麼？回答是：是的，還要克服下去，三十年也說不定。然而一面克服著，一面進軍著，不會做待到克服完成，然後行進那樣的傻事的。但是，蘇汶先生說過「笑話」：左翼作家在從資本家取得稿費；現在我來說一句真話，是左翼作家還在受封建的資本主義的社會的法律的壓迫，禁錮，殺戮。所以左翼刊物，全被摧殘，現在非常寥寥，即偶有發表，批評作品的也絕少，而偶有批評作品的，也並未動不動便指作家為「資產階級的走狗」，而且不要「同路人」。左翼作家並不是從天上掉下來的神兵，或國外殺進來的仇敵，他不但要那同走幾步的「同路人」，還要招致那站在路旁看看的看客也一同前進。

但現在要問：左翼文壇現在因為受著壓迫，不能發表很多的批評，倘一旦有了發表的可能，不至於動不動就指「第三種人」為「資產階級的走狗」麼？我想，倘若左翼批評家沒有宣誓不說，又只從壞處著想，那是有這可能的，也可以想得比這還要壞。不過我以為這種豫測，實在和想到地球也許有破裂之一日，而先行自殺一樣，大可以不必的。

然而蘇汶先生的「第三種人」，卻據說是為了這未來的恐怖而「擱筆」了。未曾身歷，僅僅因為心造的幻影而擱筆，「死抱住文學不放」的作者的擁抱力，又何其弱呢？兩個愛人，有因為豫防將來的社會上的斥責而不敢擁抱的麼？

其實，這「第三種人」的「擱筆」，原因並不在左翼批評的嚴酷。真實原因的所在，是在做不成這樣的「第三種人」，做不成這樣的人，也就沒有了第三種筆，擱與不擱，還談不到。

生在有階級的社會裡而要做超階級的作家，生在戰鬥的時代而要離開戰鬥而獨立，生在現在而要做給與將來的作品，這樣的人，實在也是一個心造的幻影，在現實世界上是沒有的。要做這樣的人，恰如用自己的手拔著頭髮，要離開地球一樣，他離不開，焦躁著，然而並非因為有人搖了搖頭，使他不敢拔了的緣故。

所以雖是「第三種人」，卻還是一定超不出階級的，蘇汶先生就先在豫料階級的批評了，作品裡又豈能擺脫階級的利害；也一定離不開戰鬥的，蘇汶先生就先以「第三種人」之名提出抗爭了，雖然「抗爭」之名又為作者所不願受；而且也跳不過現在的，他在創作超階級的，為將來的作品之前，先就留心於左翼的批判了。

這確是一種苦境。但這苦境，是因為幻影不能成為實有而來的。即使沒有左翼文壇作梗，也不會有這「第三種人」，何況作品。但蘇汶先生卻又心造了一個橫暴的左翼文壇的幻影，將「第三種人」的幻影不能出現，以至將來的文藝不能發生的罪孽，都推給它了。

左翼作家誠然是不高超的，連環圖畫，唱本，然而也不到蘇汶先生所斷定那樣的沒出息。左翼也要托爾斯泰，弗羅培爾。但不要「努力去創造一些屬於將來（因為他們現在是不要的）的東西」的托爾斯泰和弗羅培爾。他們兩個，都是為現在而寫的，將來是現在的將來，於現在有意義，才於將來會有意義。尤其是托爾斯泰，他寫些小故事給農民看，也不自命為「第三種人」，當時資產階級的多少攻擊，終於不能使他「擱筆」。左翼雖然誠如蘇汶先生所說，不至於蠢到不知道「連環圖畫是產生不出托爾斯泰，產生不出弗羅培爾來」，但卻以為可以產出密開朗該羅，達文希那樣偉大的畫手。而且我相信，從唱本說書裡是可以產生托爾斯泰，弗羅培爾的。現在提起密開朗該羅們的畫來，誰也沒有非議了，但實際上，那不是宗教的宣傳畫，《舊約》的連環圖畫麼？而且是為了那時的「現在」的。

總括起來說，蘇汶先生是主張「第三種人」與其欺騙，與其做冒牌貨，倒還不如努力去創作，這是極不錯的。「定要有自信的勇氣，才會有工作的勇氣！」這尤其是對的。

然而蘇汶先生又說，許多大大小小的「第三種人」們，卻又因為豫感了不祥之兆——左翼理論家的批評而「擱筆」了！「怎麼辦呢」？

**** 又論「第三種人」
     :PROPERTIES:
     :CUSTOM_ID: 19330604
     :END:

戴望舒先生遠遠的從法國給我們一封通信，敘述著法國A.E.A.R.（革命文藝家協會）得了紀德的參加，在三月二十一日召集大會，猛烈的反抗德國法西斯諦的情形，並且紹介了紀德的演說，發表在六月號的《現代》上。法國的文藝家，這樣的仗義執言的舉動是常有的：較遠，則如左拉為德來孚斯打不平，法朗士當左拉改葬時候的講演；較近，則有羅曼羅蘭的反對戰爭。但這回更使我感到真切的歡欣，因為問題是當前的問題，而我也正是憎惡法西斯諦的一個。不過戴先生在報告這事實的同時，一併指明了中國左翼作家的「愚蒙」和像軍閥一般的橫暴，我卻還想來說幾句話。但希望不要誤會，以為意在辯解，希圖中國也從所謂「第三種人」得到對於德國的被壓迫者一般的聲援，——並不是的。中國的焚禁書報，封閉書店，囚殺作者，實在還遠在德國的白色恐怖以前，而且也得到過世界的革命的文藝家的抗議了。我現在要說的，不過那通然裡的必須指出的幾點。

那通信敘述過紀德的加入反抗運動之後，說道——

#+BEGIN_EXAMPLE

「在法國文壇中，我們可以說紀律是『第三種人』，……自從他在一八九一年……起，一直到現在為止，他始終是一個忠實於他的藝術的人。然而，忠實於自己的藝術的作者，不一定就是資產階級的『幫閒者』，法國的革命作家沒有這種愚蒙的見解（或者不如說是精明的策略），因此，在熱烈的歡迎之中，紀德便在群眾之間發言了。」
#+END_EXAMPLE

這就是說：「忠實於自己的藝術的作者」，就是「第三種人」，而中國的革命作家，卻「愚蒙」到指這種人為全是「資產階級的幫閒者」，現在已經由紀德證實，是「不一定」的了。這裡有兩個問題應該解答。

第一，是中國的左翼理論家是否真指「忠實於自己的藝術的作者」為全是「資產階級的幫閒者」？據我所知道，卻並不然。左翼理論家無論如何「愚蒙」，還不至於不明白「為藝術的藝術」在發生時，是對於一種社會的成規的革命，但待到新興的戰鬥的藝術出現之際，還拿著這老招牌來明明暗暗阻礙他的發展，那就成為反動，且不只是「資產階級的幫閒者」了。至於「忠實於自己的藝術的作者」，卻並未視同一律。因為不問那一階級的作家，都有一個「自己」，這「自己」，就都是他本階級的一分子，忠實於他自己的藝術的人，也就是忠實於他本階級的作者，在資產階級如此，在無產階級也如此。這是極顯明粗淺的事實，左翼理論家也不會不明白的。但這位——戴先生用「忠實於自己的藝術」來和「為藝術的藝術」掉了一個包，可真顯得左翼理論家的「愚蒙」透頂了。

第二，是紀德是否真是中國所謂的「第三種人」？我沒有讀過紀德的書，對於作品，沒有加以批評的資格。但我相信：創作和演說，形式雖然不同，所含的思想是決不會兩樣的。我可以引出戴先生所紹介的演說裡的兩段來——

#+BEGIN_EXAMPLE

「有人會對我說：『在蘇聯也是這樣的。』那是可能的事；但是目的卻是完全兩樣的，而且，為了要建設一個新社會起見，為了把發言權給與那些一向做著受壓迫者，一向沒有發言權的人們起見，不得已的矯枉過正也是免不掉的事。

「我為什麼並怎樣會在這裡贊同我在那邊所反對的事呢？那就是因為我在德國的恐怖政策中，見到了最可歎最可憎的過去底再演，在蘇聯的社會創設中，我卻見到一個未來的無限的允約。」
#+END_EXAMPLE

這說得清清楚楚，雖是同一手段，而他卻因目的之不同而分為贊成或反抗。蘇聯十月革命後，側重藝術的「綏拉比翁的兄弟們」這團體，也被稱為「同路人」，但他們卻並沒有這麼積極。中國關於「第三種人」的文字，今年已經匯印了一本專書，我們可以查一查，凡自稱為「第三種人」的言論，可有絲毫近似這樣的意見的麼？倘其沒有，則我敢決定地說，「不可以說紀德是『第三種人』」。

然而正如我說紀德不像中國的「第三種人」一樣，戴望舒先生也覺得中國的左翼作家和法國的大有賢愚之別了。他在參加大會，為德國的左翼藝術家同伸義憤之後，就又想起了中國左翼作家的愚蠢橫暴的行為。於是他臨末禁不住感慨——

#+BEGIN_EXAMPLE

「我不知道我國對於德國法西斯諦的暴行有沒有什麼表示。正如我們的軍閥一樣，我們的文藝者也是勇於內戰的。在法國的革命作家們和紀德攜手的時候，我們的左翼作家想必還在把所謂『第三種人』當作唯一的敵手吧！」
#+END_EXAMPLE

這裡無須解答，因為事實具在：我們這裡也曾經有一點表示，但因為和在法國兩樣，所以情形也不同；刊物上也久不見什麼「把所謂『第三種人』當作唯一的敵手」的文章，不再內戰，沒有軍閥氣味了。戴先生的豫料，是落了空的。

然而中國的左翼作家，這就和戴先生意中的法國左翼作家一樣賢明瞭麼？我以為並不這樣，而且也不應該這樣的。如果聲音還沒有全被削除的時候，對於「第三種人」的討論，還極有從新提起和展開的必要。戴先生看出了法國革命作家們的隱衷，覺得在這危急時，和「第三種人」攜手，也許是「精明的策略」。但我以為單靠「策略」，是沒有用的，有真切的見解，才有精明的行為，只要看紀德的講演，就知道他並不超然於政治之外，決不能貿貿然稱之為「第三種人」，加以歡迎，是不必別具隱衷的。不過在中國的所謂「第三種人」，卻還複雜得很。

所謂「第三種人」，原意只是說：站在甲乙對立或相鬥之外的人。但在實際上，是不能有的。人體有胖和瘦，在理論上，是該能有不胖不瘦的第三種人的，然而事實上卻並沒有，一加比較，非近於胖，就近於瘦。文藝上的「第三種人」也一樣，即使好像不偏不倚罷，其實是總有些偏向的，平時有意的或無意的遮掩起來，而一遇切要的事故，它便會分明的顯現。如紀德，他就顯出左向來了；別的人，也能從幾句話裡，分明的顯出。所以在這混雜的一群中，有的能和革命前進，共鳴；有的也能乘機將革命中傷，軟化，曲解。左翼理論家是有著加以分析的任務的。

如果這就等於「軍閥」的內戰，那麼，左翼理論家就必須更加繼續這內戰，而將營壘分清，拔去了從背後射來的毒箭！

**** 关于《文新》与胡秋原的文艺论辩
     :PROPERTIES:
     :AUTHOR:   苏汶
     :CUSTOM_ID: 19320701
     :END:

首先要声明，我写这篇文章是并没有什么野心的，这是说，我并不是看别人“战”得有趣，于是自己也卷起袖子来一手；我更不敢有对任何方面挑“战”的意思。这一切，自己也很明白，都不配。不过，我如此见到，我便如此说。

近来，很少看书，尤其是很少看那些据说要销到七八千份以上的国内诸文艺杂志或报章。但是一个极碰巧的机会却终于使我看到了登在《读书杂志》第二卷第一期上的胡秋原先生的《钱杏邨理论之清算》和《文艺新闻》第五十六号上的没有署名的《自由人的文化运动》这两篇煌煌大文。这两篇表面上似乎没有多大连续性而实际上是十分针锋相对的文章上附的那句“标语”：马克思主义文艺理论之拥护。我记得，钱杏邨先生也是曾经把自己视为百分之百的马克思主义者的。

这是文艺舞台替我们排演的一出《新双包案》。

我呢，当然没有能力来判断哪一位包公是真，哪一位包公是假。在前台是看不出真假的。到后台去，不过后台也许还是看不出。

写到这里，我想起一个极陈旧的笑话来。

笑话本来就无聊，笑话而陈旧似乎更可以不必说。不过，被所有的党员都读熟了的《三民主义》里面的话都可在写给党员看的文章里被几百次几千次地引用，那么在我这篇狗屁不值钱的文章里说上一个陈旧的笑话似乎没有什么要紧吧。

从前有一个商人，一个秀才，一个富翁和一个乞丐同在一座庙里避雪。因为无聊，联句吧。题目不用说，是“雪”。这首诗的头三句是这样的：

#+BEGIN_EXAMPLE
大雪纷纷坠地（商人）
都是皇家瑞气（秀才）
再落三年何妨（富翁）
#+END_EXAMPLE

再落三年雪，那还得了。叫化子于是生了气，他忘记了诗题，便这样地破口大骂起来：

#+BEGIN_EXAMPLE
放你娘的狗屁！
#+END_EXAMPLE

我向排演《双包案》的戏场的后台偷看了几眼，结论是没有，我只想起这个笑话来。确实，这一次的文艺论战（也许每一次的文艺论战都如此）是和破庙里的联句活脱活像：文艺这东西便是那题目，于是，各人说各人的话，而且，要两方面都同意的结论是决不会有的。

孔夫子这个人确实没有很彻底的思想，尽可以不必硬拖进马克思祠堂，可是他却确实说过几句聪明话。他说：“道不同不相为谋。”我这篇文章平凡得很，只不过想发挥一些这句古话在这次文艺论战上的应用；因此，我这篇文章又名“道不同相为谋说”。

废话少讲，我们来看一看论战的来历。

起初当然是导源于俄罗斯。一些名字长得不容易记清楚的人们争论着，在我们还没有梦想到天下有这么一个问题的时候就争论着。后来闹到日本，日本人似乎没有俄罗斯人那么聪明，说来说去还是俄罗斯人所早就说过的这几句话，没有胡秋原先生所要求于钱杏邨先生的“独创”。假使转借胡先生向福禄特尔借来的话来说，那么日本人就已经做了第二个拿女人来比花的头等蠢才了。于是，这些同一的话又借道东京而来到上海，只用四角方方的文字一写，便俨然成为中国人自己的理论。

其实，说到理论，我们还不如老老实实，现现成成地向俄罗斯人批发些来倒不至于闹大笑话，至于说“新花样”，钱杏邨先生固然耍不出来，胡秋原先生也一样；不过胡先生还算能抱定从一而终主义，蒲力哈诺夫，而钱先生呢，不免要东拉拉，西扯扯。

这一点，左翼文坛的近来的指导者是高明得多了。他们不再提出那些“艺术的起源”或“艺术的定义”这些书呆子气的问题来，只看定目前的需要切实地，按部就班地讨论着，决定着又执行着。

可是左翼文坛自身的“奥伏赫变”到现在这地步也不是一朝一夕的事情。它在中国摆下擂台以来，第一个来打擂台的是鲁迅先生。他老人家说：“我们要理论。”于是有人便把蒲力哈诺夫和卢那却尔斯基译了些出来；虽然译得不十分看得懂，可是鲁迅先生满意了。接着茅盾先生又跳上擂台。“我们不要听十八句江湖诀，我们要看货色”，他说。货色纵然依旧没有拿出来，可是艺术的技巧的问题是开始被重视，被讨论。于是茅盾先生也满意了。而现在，想不到还有胡秋原先生会从谁也不敢显一显好身手的人群中跳将出来，而据说，他的拳头又是少林嫡派。当然，胡秋原先生将来会不会也像鲁迅先生和茅盾先生那样地满意而去是谁也不敢断言；但是在今日已经明显地立定了脚跟的左翼文坛再不会因这次论战而变换态度却可以料想得到。因此，据我个人愚见，这一场笔战是不会有使两方面都“满意”的结果。

何以见得？道不同不相为谋。

统观胡先生的大文，从他的蒲力哈诺夫崇拜，对文学的指导生活的理论或主张的非议，一切等等看来，我们可以认识他是一个绝对的非功利论者。反过来，左翼文坛的指导理论家们却正指出哪一种文学有用，哪一种文学没有用，我们要哪一种，我们不要哪一种。这两种马克思主义者之间的距离是不可以道理计的。

其实，我们单说左翼文坛是马克思主义者似乎还是不适当；我们应当说他们是“马克思列宁主义者”。这其间的分别就是他们现在没工夫来讨论什么真理不真理，他们只看目前的需要。是一种目前主义。我们与其把他们的主张当做学者式的理论，却还不如把它当做政治家式的策略，当做行动；而且这策略，这行动实际上也就是理论。目前的需要改变了，他们的主张便也随之而变；这才是，“辩证”。

你会不会称轻重？什么真理，什么文艺，假使比起整个的无产阶级解放运动来，还称得出几斤几两？亭子间里的真理吧！小资产阶级狗男女的文艺吧！你假使真是一个前进的战士，你便不会再要真理，再要文艺了。

譬如拿他们所提倡的文艺大众化这问题来说吧。他们鉴于现在劳动者没有东西看，在那里看陈旧的充满了封建气味的（这就是说，有害的）连环图画和唱本。于是他们便要作家们去写一些有利的连环图画和唱本来给劳动者们看。这个，像胡先生之类的批评家当然是要反对了；不但胡先生，恐怕每一个死抱住文学不肯放手的人都要反对。这样低级的形式还生产得出好的作品吗？确实，连环图画里是产生不出托尔斯泰，产生不出弗罗培尔来的。这一点难道左翼理论家们会不知道，他们断然不会那么蠢。但是，他们要弗罗培尔什么用呢？要托尔斯泰什么用呢？他们不但根本不会叫作家们去做成弗罗培尔或托尔斯泰，就是有了，他们也是不要，至少他们“目前”是不要。而且这不要是对的，辩证的。也许将来，也许将来他们会原谅，不过此是后话。

胡秋原先生把卢那却尔斯基称为“官僚，纨绔子，莫明其妙”，何其毒视之深！其实，从这里我们正可以看出胡先生是永远不会了解卢那却尔斯基的。卢那却尔斯基有一次曾经把托尔斯泰非议得很利害，但是在托氏百年祭时又把他恭维得很利害。他的话筒直有点如出二口。何其前后矛盾一至于此，何其不顾所谓“真理”一至于此！其实，托氏被“不要”于万方多难之秋，而旋又被“原谅”于国泰民安之日，是很有道理的。

你假使是真的马克思主义者便不该非难卢那却尔斯基。“莫明其妙”，说他太会变卦。变卦就是辩证法。有人说辩证法是中国古已有之，一部《易经》便是。可惜我对于辩证法和《易经》两者都没有深切的研究，不敢有所发挥。不过我知道，《易经》云胡哉？变卦而已。

话似乎愈说愈远了，应该拉回来。但是，我之所以如此说，无非是想说明左翼文坛的一切主张都无非是行动，并且一切行动都是活的。而胡秋原先生不明白。左翼文坛已经屡次向胡先生暗示了，甚至说明了，叫他不要空谈真理，离开行动是没有什么真理的。而胡先生还是不明白。胡先生固然会说，行动没有真理是不正确的行动；但左翼文坛也会说，真理没有行动便是不正确的真理。那么，这场论战会有什么结果呢？

胡秋原先生纵然以马克思主义相标榜；其实，他充其量不过是一个书呆子马克思主义者。这种马克思主义者老喜欢从最遥远，最难解决的问题说起，而据他们说，这是根本的问题。例如，一提起艺术便要谈到艺术的定义，不但谈到，而且定要把它当作“谈艺术的第一个问题”，如胡先生所说。固然，胡先生是继承了蒲力哈诺夫的道统把这么一个奥妙不堪的问题轻易地用“艺术是形象而思索”八个大字来解决了，似乎这便是天经地义似的，骂钱杏邨先生不懂得这个便不配谈艺术。其实天下哪有这样简单的事情！马克思的一部《资本论》里面你找得出资本的定义吗？这整整的三卷书才是资本的定义呢。真正的马克思主义者难道可以说马克思连资本的定义弄不清楚，不配谈经济问题吗？只有书呆子才会左来一个定义，右来一个定义。

耽误大事正就是这种类似定义的问题。一些热衷于真理的马克思主义者们不会把自己关在图书馆里。人类学，考古学。寒窗重检点，再读十年书。照这样，也难怪左翼文坛要说这是“教训民众等待主义了”。

严格地说，蒲力哈诺夫也不免带一些这种书呆子的气氛。你瞧，蒲力哈诺夫的政治理论是终于被列宁所攻击了；而现在，甚至他的艺术理论都据说有点站不住了。书呆子毕竟要不得，没有用。

记得从前章太炎曾经大大地宣传过书呆子主义，说世界上什么惊天动地的大事业都是书呆子做出来的。然而章太炎在政治上终于要不得，也就是书呆子主义在那里作祟。学院式的马克思主义者，其章太炎之流欤？

此之谓秀才造反，三年不成大事。

因此，我们纵然承认胡秋原先生的每一句话都是一百二十分地合乎马克思主义的，但左翼文坛在“能够行动”，这一点上就已经比这一百二十分的马克思主义者更合乎马克思主义一点了。纵然左翼文坛也承认胡秋原先生的每一句话都是一百二十分地合乎马克思主义的，但他们必然地还要攻击他，就像列宁攻击蒲力哈诺夫一样，因为他妨碍行动，而妨碍行动这一点就是反马克思主义的。胡先生纵然写十部洋洋四十万言的《唯物史观艺术论》也没有用，至少“目前”没有用，左翼文坛是依然要把他来非难的，因为现在还没有到列宁可以原谅蒲力哈诺夫，卢那却尔斯基可以原谅托尔斯泰的时候。

自己不站在“不自由的，有党派的”群众中，不说话是聪明的。

从这里，我们看出两个绝对不同的立场了。一方面重实践，另一方面只要书本；一方面负着政治的使命，另一方面却背着真理的招牌。于是这两种马克思主义是愈趋愈远，几乎背道而驰了。

萧伯纳说无产阶级的代表人是既懂得无产阶级又懂资产阶级的，而资产阶级的代言人是两者都不懂。让我来做一次“头等的蠢才”吧。我要模仿萧伯纳的口气来说。马克思列宁主义者是既懂得列宁主义又懂得马克思主义的；但书呆子马克思主义者，要是分析到终极，是既不懂列宁主义又不懂得马克思主义。

不过，胡先生听人说他不懂列宁主义便会跳起来，会反问我一声：“那么你自己懂不懂列宁主义呢？”那便真会把我问得哑口无言了。

确实，胡先生曾经指出过文艺上的“目的意识论不过是列宁之政治理论在文艺上之机械的适用”，话固然不错，但从“不过是”和“机械的”等字样上看来，胡先生至少是暗示着列宁主义也不过尔尔，是暗示着列宁主义用不到文艺上来。

万一不幸，胡先生是真懂得列宁主义的，说胡先生不懂的人自己倒做了天字第一号的傻瓜，那么我真不知胡先生是何居心了。难怪有人会说胡先生是故意把马克思主义从实际行动中“解放”出来，故意使它成为死的，书本的，缓冲革命运动的，而实际上是替无产阶级的敌人服务的马克思主义。

其实，胡先生还不如让人说书呆子吧。这样是比较有利，这样倒还有做一个蒲力哈诺夫的希望。也许将来的大学里会有“胡秋原学院”呢，就像俄罗斯的大学有“蒲力哈诺夫学院”一样。

在“智识阶级的自由人”和“不自由的，有党派的”阶级争着文坛的霸权的时候，最吃苦的，却是这两种人之外的第三种人。这种第三种人便是所谓作者之群。

作者，老实说，是多少带点我前面所说起的死抱住文学不肯放手的气味的；否则，他也决不会在成千成万的事业中选定了这个最没出息的事业（也许说职业好一点吧）来做。只要张开眼睛来看，不写东西的便罢，写一点东西的都斤斤乎艺术的价值便可知道。甚至如史铁儿先生所说“一举成名天下知”这一类下意识，平心而论，也人人多少有一点。究竟人非圣贤，同时也并非个个是马克思和列宁。

但是在现今这局面下，作者是处了怎样个地位呢？

最初，在根本还没有什么阶级文学的观念打到作者脑筋里去的时候，作者还在梦想文学是个纯洁的处女。但不久，有人告诉他说，她不但不是一个处女，甚至是一个人尽可夫的卖淫妇，她可以今天卖给资产阶级，明天又卖给无产阶级。这个，作者在刚听到的时候似乎就有点意外了；不过据说是事实，于是也就没有方法否认。既而，因为文学这卖淫妇似乎还长得不错，于是资产阶级想占有她，无产阶级也想占有她。于是文学便只能打算从良。从良以后呢？作者便“从此萧郎是路人”。

你瞧，不是有好多大大小小的作者是搁起了笔吗？

固然，有一部分作者还想把她从一个深如海的侯门中拉回来，而另一部分就索性爽爽快快陪嫁了过去。

前面那种作者是正在那儿被“不要”，可以不必说。对于后面那种作者呢，要是要的，可是规矩很严，要你做另外一种人。终于，文学不再是文学了，变为连环图画之类；而作者也不再是作者了，变为煽动家之类。死抱住文学不放的作者们是终于只能放手了。然而你说他们舍得放手吗？他们还在恋恋不舍地要艺术的价值。

我这样说，并不是怪左翼文坛不该这样霸占文学。他们这样办是对的，为革命，为阶级。不过他们有一点不爽快，不肯干脆说一声文学现在是不需要，至少暂时不需要。他们有时侯也会掮出艺术的价值来给所谓作者们尝一点甜头，可以让他安心地来陪嫁。其实，这样一来，却反把作者弄得手足无措了。为文学呢，为革命？还是两者都为？还是有时候为文学，有时候为革命？

在这一点上，我倒觉得启蒙时代的批评家李初梨先生诸人要痛快得多。他老实先问你，是为文学而革命呢，还是为革命而文学？肯定前半个问题的，走吧；肯定后半个问题的，到这儿来。

正因为有这一班无所适从的作者的存在，胡秋原先生便又以艺术保护者的资格而出现了。他叫人不要碰艺术。这种自由主义的创作理论应该是受作者的欢迎的。但不幸胡先生也不是一个彻底的自由主义者。他猛烈地攻击那种有目的意识的文学：照这看来，你还是不允许作者有整个的自由的。万一胡先生叫人不准碰艺术的态度是这样：你们不要碰，让我来；那可不是同样的不自由？

在人人都不肯让步的今日，诚哉，难乎其为作家？

人各有其道，人各以其道非他人之道。你说着我所不要听的话，我说着你所不要听的话。联句正联得起劲呢。只有作者，有其道而不敢言，更不敢拿来非他人之道。他只想替文学，不管是煽动的也好，暴露的也好，留着一线残存的生机，但是又怕被料事如神的指导者们算出命来，派定他是那一阶级的狗。

在“目前”这情形下，愚盲是幸福，而沉默是聪明的。

**** 论「第三种人」
     :PROPERTIES:
     :CUSTOM_ID: 19340101
     :AUTHOR:   梁实秋
     :END:

     - Note taken on [2019-12-31 二 20:33] \\
       《一个都不宽恕》的复制上限到了，我无法在里面复制文章了。
     - Note taken on [2019-12-31 二 20:29] \\
       这篇文章收录在《偏见集》，但是我手头上没有这本书，互联网上也搜索不到，所以这个 CUSTOM_ID 并不准确。

鲁迅先生最近到北平，做过数次演讲，有一次讲题是“第三种人”。据报纸所记，其演讲的主旨大致是和他在《现代》二卷一期上所发表的那篇论文差不多，不过这一回花样略为翻新一些。这一回他举了一个譬喻说，胡适之先生所倡导的新文学运动，是穿着皮鞋踏入文坛，现在的普罗运动，是赤脚的也要闯入文坛。随后报纸上就有人批评说，鲁迅先生演讲的那天既未穿皮鞋亦未赤脚，而登着一双帆布胶皮鞋，正是“第三种人”。

非赤即白，非友即敌，非左即右，非普罗阶级即资产阶级，非革命即反革命——这一套的逻辑，我们是已经听过不少了。鲁迅先生之根本否认“第三种人”亦不过是此种逻辑运用到文学上的一例而已。

第一种人是普罗文学家，第二种人是资产阶级文学家，第三种人根本不存在。故文学家只有两种。第一种人是“新兴”，其成功是有“必然性”的；第二种人如无著作发表，则系“没落”，如有著作发表，则为“落伍”，如胆敢在理论上有所声辩，则系“作最后之挣扎”。这已经成为一种公式了。然而这只是一种分类法，以资产的有无来做标准，人类自然是可以分为两个阶级，没有“第三种人”存在的余地。但是若换一个标准，分类法也就随之而异了。例如：按照印度婆罗门教的规律，人是分为四个阶级了；按照批评家安诺德在《文化与混乱》里所讲，人是分为三个型类了；按照人类学家的方法，皮肤的颜色，头发的曲直，无不可为分类的标准；按照欧洲中古的星相学，人又可分为四类不同的气质；按照中国的算命先生，又有五行之说。总之，分来分去，人类还是人类。分类的标准不止一个，资产阶级与无产阶级之说只是一种分类法的结果。在这一种分类法之下，若没有第三种人的存在的可能，在另一种标准之下，也许不但有第三种人，还许有第四种人。

To Be Continue

