** 与复古派的论争 
   :PROPERTIES:
   :CUSTOM_ID: chap1
   :END:

*** 估「学衡」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec1
    :END:
    - Note taken on [2019-11-05 二 22:22] \\
      [[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1%25E6%25B4%25BE][学衡派]]其实颇为松散，想不到陈寅恪也在其中。[[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1][《学衡》]]1922年创刊，1933年停刊，共发行79期。

**** 《学衡》弁言
     :PROPERTIES:
     :CUSTOME_ID: 19190101
     :END:

     - Note taken on [2019-11-05 二 23:19] \\
       原载《学衡》1922年1月第1期

杂志迩例。弁以宣言。综其旨要。不逾二辙。自则夸饰。斥人则底词。句必盈天。字或累万。同人优劣。谢未能也。出版之始。谨矢四义。

一诵述中西先哲之精言。以翼学。

二解析世宙名著之共性。以邮思。

三籀绎之作必趋雅音。以崇文。

四平心而言。不事谩骂。以培俗。

揭示真理不趋众好。自勉勉人。期于是而已。庄生有言。瞽者无以与乎文章之观。聋者无以与乎钟鼓之声。岂惟形骸聋盲哉。夫知亦有之。同人不敏。求知不敢懈。第祝斯志之出。不聋盲吾国人。则幸矣。

**** 《评尝试集》匡谬
     :PROPERTIES:
     :CUSTOM_ID: 19220204
     :END:

     - Note taken on [2019-11-05 二 23:21] \\
       原刊于一九二二年二月四日《晨报副刊》第三版。周作人作。
南京高师教员所办的《学衡》第一期里，有一篇胡先驌君的《评〈尝试集〉》，是对付胡适之个人而作的。听说这胡君便是胡适之在《新青年》上嘲笑过的「翡翠衾寒，鸳鸯瓦冷，..早丁字檐前，繁霜飞舞」的好词的著者，但现在却异其面目，据了中外古今的大道理，来批评新诗了。评新诗原很好，只可惜他太「聋盲吾国人」了，随意而言，很有几个背谬的处所，不合于「学者之精神」。我因此也不辞「翻胔剔骼」之讥，略加匡正，窃取「不事嫚骂」与「必趋雅音」之二义，题曰「《评〈尝试集〉》匡谬」。

一、梅光迪君在《评提倡新文化者》文中，痛骂「彼等」「言文学则袭晚近之堕落派」，而胡君的文章却劈头就引「辛蒙士」的议论。难道胡君竟不知辛蒙士正是一个大名鼎鼎的「堕落派」么？倘使胡君肯买一本辛蒙士的论文来一查，便不至于被同志的梅君掌嘴了。大约他只购求了 Eve-ryman’s Library里的一本《辜勒律己之文学传记》，一见卷头的序文，便以为定是一位文学正宗的老博士所作，赶忙引用起来，岂料他竟是威尔士的一个堕落派呢？于是便上了这一个老大的当了。像他那样于欧西文化有「广博精粹之研究」的学者，尚且不免「所知既浅…束书不观，中乃空虚无有。」可见「新文化」之真不易讲了。

二、胡君说，「乔路但时之英德意文。与今日之英德意文较，则与中国之周秦古文。与今日之文字较相若」。今日之「文字」是什么？是指用汉字所写的文言，还是指用汉字所写的白话呢？照道理讲起来，所说的当然是后者。但即使依彼等的「诡辩」，以为所谓今日之文字是指文言，那么正与今日之英德意人的不用乔路但时之英德意文「相若」，今日之中国人也应至少不用周秦古文了。然而《学衡》上《国学摭谭》的序里第一句便说「粤稽我炎夏」，请问这是什么时候的古文？胡君知道这粤字在今日之文字中只用作广东的别称么？

三、胡君说，「今日人提倡以日本文作文学，其谁能指其非。」我真料不到胡君会发这样通达之论，他明明是赞成胡适之的提倡废弃古文而用白话文了。因为日人提倡以日本文作文学，不但是废弃汉文，乃是废弃日本的古文而用日本的白话！这件事实也并非什么僻典，只要稍读日本近代文学史的都知道。胡君倘若预先一查英国阿斯敦的《日本文学史》（美国 Appleton书店有翻板），便不至于闹出这场笑话来了。刘伯明君在《学者之精神》上说，「真正学者，不敢自欺欺人，必俟确有把握，而后敢以问世。」这几句话很像是对于好朋友的诤言，看了不禁代为惶愧。我并不如梅君一样，贸贸然断定胡君是伪学者，不过忠告几句，万不可不有「学者之精神」，倘若他有志变成真学者。

四、胡君说，「陀司妥夫士忌戈尔忌之小说，死文学也，不以其轰动一时遂得不死不朽也。」我们倘要捏造一句不堪的话，用栽赃的文法去诬陷他，使他失了人格，再也不能想出比他自己所说的这一句更为厉害的话了。陀司妥夫士忌的文学，正是马相伯先生的所谓良心的结晶，凡是有良心的人都不能不敬爱他，正如人们之对于耶稣和佛陀，即使并不是他们的教徒。世上宣言反对陀司妥夫士忌的，只有俄帝国的「沙」与其检查官军警及法官——然而现在也没有了。我们对于胡君，觉得实在不忍下什么断语，虽然他自己已经招承了。

其馀还有什么话可说呢！

**** 估《学衡》
     :PROPERTIES:
     :CUSTOM_ID: 19220209
     :END:

     - Note taken on [2019-11-05 二 23:37] \\
       原载《晨报副刊》1922年2月9日，署名风声
我在二月四日的《晨报副刊》上看见式芬先生的[[#19220204][杂感]]，很诧异天下竟有这样拘迂的老先生，竟不知世故到这地步，还来同《学衡》诸公谈学理。夫所谓《学衡》者，据我看来，实不过聚在「聚宝之门」，左近的几个假古董所放的假毫光；虽然自称为「衡」，而本身的称星尚且未曾钉好，更何论于他所衡的轻重的是非。所以，决用不着较准，只要估一估就明白了。

《弁言》说，「籀绎之作必趋雅音以崇文」，「籀绎」如此，述作可知。夫文者，即使不能「载道」，却也应该「达意」，而不幸诸公虽然张皇国学，笔下却未免欠亨，不能自了，何以「衡」人。这实在是一个大缺点。看罢，诸公怎么说：《弁言》云，「杂志迩例弁以宣言」，按宣言即布告，而弁者，周人戴在头上的瓜皮小帽一般的帽子，明明是顶上的东西，所以「弁言」就是序，异于「杂志迩例」的宣言，并为一谈，太汗漫了。《评提倡新文化者》文中说，「或操笔以待。每一新书出版。必为之序。以尽其领袖后进之责。顾亭林曰。人之患在好为人序。其此之谓乎。故语彼等以学问之标准与良知。犹语商贾以道德。娼妓以贞操也。」原来做一篇序「以尽其领袖后进之责」，便有这样的大罪案。然而诸公又何以也「突而弁兮」的「言」了起来呢？照前文推论，那便是我的质问，却正是「语商贾以道德。娼妓以贞操也」了。《中国提倡社会主义之商榷》中说，「凡理想学说之发生。皆有其历史上之背影。决非悬空虚构。造乌托之邦。作无病之呻者也。」查「英吉之利」的摩耳，并未做 Pia of Uto，虽曰之乎者也，欲罢不能，但别寻古典，也非难事，又何必当中加楦呢。于古未闻「睹史之陀」，在今不云「宁古之塔」，奇句如此，真可谓「有病之呻」了。

《国学摭谭》中说，「虽三皇寥廓而无极。五帝搢绅先生难言之。」人而能「寥廓」，已属奇闻，而第二句尤为费解，不知是三皇之事，五帝和搢绅先生皆难言之，抑是五帝之事，从后说，然而太史公所谓「搢绅先生难言之」者，乃指「百家言黄帝」而并不指五帝，所以翻开《史记》，便是赫然的一篇《五帝本纪》，又何尝「难言之」。难道太史公在汉朝，竟应该算是下等社会中人么？

《记白鹿洞谈虎》中说，「诸父老能健谈。谈多称虎。当其摹示抉噬之状。闻者鲜不色变。退而记之。亦资诙噱之类也。」姑不论其「能」「健」「谈」「称」，床上安床，「抉噬之状」，终于未记，而「变色」的事，但「资诙噱」，也可谓太远于事情。倘使但「资诙噱」，则先前的闻而色变者，简直是呆子了。记又云，「伥者。新鬼而膏虎牙者也。」刚做新鬼，便「膏虎牙」，实在可悯。那么，虎不但食人，而且也食鬼了。这是古来未知的新发见。

《渔丈人行》的起首道：「楚王无道杀伍奢。覆巢之下无完家。」这「无完家」虽比「无完卵」新奇，但未免颇有语病。假如「家」就是鸟巢，那便犯了复，而且「之下」二字没有着落，倘说是人家，则掉下来的鸟巢未免太沉重了。除了大鹏金翅鸟（出《说岳全传》），断没有这样的大巢，能够压破彼等的房子。倘说是因为押韵，不得不然，那我敢说：这是「挂脚韵」。押韵至于如此，则翻开《诗韵合璧》的「六麻」来，写道「无完蛇」「无完瓜」「无完叉」，都无所不可的。

还有《浙江采集植物游记》，连题目都不通了。采集有所务，并非漫游，所以古人作记，务与游不并举，地与游才相连。匡庐〔13〕峨眉，山也，则曰纪游，采硫访碑，务也，则曰日记。虽说采集时候，也兼游览，但这应该包举在主要的事务里，一列举便不「古」了。例如这记中也说起吃饭睡觉的事，而题目不可作《浙江采集植物游食眠记》。

以上不过随手拾来的事，毛举起来，更要费笔费墨费时费力，犯不上，中止了。因此诸公的说理，便没有指正的必要，文且未亨，理将安托，穷乡僻壤的中学生的成绩，恐怕也不至于此的了。

总之，诸公掊击新文化而张皇旧学问，倘不自相矛盾，倒也不失其为一种主张。可惜的是于旧学并无门径，并主张也还不配。倘使字句未通的人也算在国粹的知己，则国粹更要惭惶然人！「衡」了一顿，仅仅「衡」出了自己的铢两来，于新文化无伤，于国粹也差得远。

我所佩服诸公的只有一点，是这种东西也居然会有发表的勇气。

*** 批「甲寅」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec2
    :END:

**** 评新文化运动（节选）
     :PROPERTIES:
     :CUSTOM_ID: 19230800
     :END:

夫语以耳辨。徒资口谈。文以目辨。更贵成诵。则其取音之繁简连截。有其自然。不可强混。如园有桃。笔之于书。词义俱完。今曰此于语未合也。必曰园里有桃子树。二桃杀三士。谱之于诗。节奏甚美。今曰此于白话无当也。必曰两个桃子杀了三个读书人。是亦不可以已乎。

**** 对于北京女子师范大学风潮宣言
     :PROPERTIES:
     :CUSTOM_ID: 19250527
     :END:

     - Note taken on [2019-11-10 日 14:30] \\
       署名的有：马裕藻，沈尹默，周树人，李泰棻，钱玄同，沈兼士，周作人

溯本校不安之状，盖已半载有余，时有隐显，以至现在，其间亦未见学校当局有所反省，竭诚处理，使之消弭，迨五月七日校内讲演时，学生劝校长杨荫榆先生退席后，杨先生乃于饭馆召集教员若干燕饮，继即以评议部名义，将学生自治会职员六人（文预科四人理预科一人国文系一人）揭示开除，由是全校然，有坚拒杨先生长校之事变，而杨先生亦遂遍送感言，又驰书学生家属，其文甚繁，第观其已经公表者，则大概谆谆以品学二字立言，使不谙此事始末者见之，一若此次风潮，为校长整饬风纪之所致，然品性学业，皆有可征，六人学业，俱非不良，至于品性一端，平素尤绝无惩戒记过之迹，以此与开除并论，而又若离若合，殊有混淆黑白之嫌，况六人俱为自治会职员，倘非长才，众人何由公举，不满于校长者倘非公意，则开除之后，全校何至然？所罚果当其罪，则本系之两主任何至事前并不与闻，继遂相率引退，可知公论尚在人心，曲直早经显见，偏私谬戾之举，究非空言曲说所能掩饰也，同人忝为教员，因知大概，义难默尔，敢布区区，惟关心教育者察焉。

**** 闲话（粉刷茅厕）
     :PROPERTIES:
     :CUSTOM_ID: 19250530
     :END:
     - Note taken on [2019-11-10 日 14:02] \\
       不知道是不是全文。来自[[https://www.zhihu.com/question/53888731/answer/276821126][知乎某个答案]]。



“以前学校闹风潮，学生几乎没有对的，现在学校闹风潮，学生几乎没有错的。这可以说是今昔言论界ia的一种信条。在我这种喜欢怀疑的人看来，这两种观念都无非是迷信。女师大的风潮，究竟学生是对的还是错的，反对校长的是少数还是多数，我们没有调查详细的事实，无从知道。我们只觉得这次闹得太不像样了。同系学生同时登两个相反的启事已经发现了。学生把守校门，误认了一个缓缓驶行的汽车为校长回校而群起包围它的笑话，也到处流传了。校长不能在校开会，不得不借邻近饭店招集教员会议的奇闻，也见于报章了，学校的丑态既然毕露，教育界的面目也就丢尽。到了这种时期，实在旁观的人也不能再让它酝酿下去，好像一个臭毛厕，人人都有扫除的义务。在这时候劝学生们不为过甚，或是劝校长辞职引退，都无非粉刷毛厕，并不能解决根本的问题。我们以为教育当局应当切实的调查这次风潮的内容，如果过在校长，自应立即更换，如果过在学生，也少不得加以相当的惩罚，万不可再敷衍姑息下去，以至将来要整顿也没有了办法。　　

闲话正要付印的时候，我们在报纸上看见女师大七教员的宣言。以前我们常常听说女师大的风潮，有在北京教育界占最大势力的某籍某系的人在暗中鼓励，可是我们总不敢相信。这个宣言语气措辞，我们看来，未免过于偏袒一方，不大平允，看文中最精彩的几句就知道了。　　

“至于品性一端，平素尤绝无惩戒记过之迹，以此与开除并论，而又若离若合，殊有混淆黑白之嫌，况六人俱为自治会职员，倘非长才，众人何由公举，不满于校长者倘非公意，则开除之后，全校何至哗然？所罚果当其罪，则本系之两主任何至事前并不与闻，继遂相率引退，可知公论尚在人心，曲直早经显见，偏私谬戾之举，究非空言曲说所能掩饰也。”　

这是很可惜的。我们自然还是不信我们平素所很尊敬的人会暗中挑剔风潮，但是这篇宣言一出，免不了流言更加传布得厉害了。”

**** 为北京女师大学生拟呈教育部文二件
     :PROPERTIES:
     :CUSTOM_ID: 19250603
     :END:

     - Note taken on [2019-11-10 日 14:32] \\
       本篇据手稿编入，原无标题、标点。第一件呈文曾发表于1925年6月3日北京女子师范大学学生自治会编辑出版的《驱杨运动特刊》，题为《学生自治会上教育部呈文》。第二件呈文鲁迅生前未曾发表。

***** 一

呈为校长溺职滥罚，全校冤愤，恳请迅速撤换，以安学校事。窃杨荫榆到校一载，毫无设施，本属尸位素餐，贻害学子，屡经呈明大部请予查办，并蒙派员莅校彻查在案。从此杨荫榆即忽现忽隐，不可究诘，自拥虚号，专恋惰金，校务遂愈形败坏，其无耻之行为，为生等久所不齿，亦早不觉尚有杨荫榆其人矣。不料“五七”国耻在校内讲演时，忽又然临席，生等婉劝退去，即老羞成怒，大呼警察，幸经教员阻止，始免流血之惨。下午即借宴客为名，在饭店召集不知是否合法之评议员数人，于杯盘狼藉之余，始以开除学生之事含糊相告，亦不言学生为何人。至九日，突有开除自治会职员……等六人之揭示贴校内。夫自治会职员，乃众所公推，代表全体，成败利钝，生等固同负其责。今乃倒行逆施，罚非其罪，欲乘学潮汹涌之时，施其险毒阴私之计，使世人不及注意，居心下劣，显然可知！继又停止已经预告之运动会，使本校失信于社会，又避匿不知所往，使生等无从与之辩诘，实属视学子如土芥，以大罚为儿戏，天良丧失，至矣尽矣！可知杨荫榆一日不去，即如刀俎在前，学生为鱼肉之不暇，更何论于学业！是以全体冤愤，公决自失踪之日起，即绝对不容其再入学校之门，以御横暴，而延残喘。为此续呈大部，恳即□□明令迅予撤换，拯本校于阽危，出学生于水火。不胜迫切待命之至！

***** 二

呈为续陈杨荫榆氏行踪诡秘，心术叵测，败坏学校，恳即另聘校长，迅予维持事。窃杨氏失踪，业已多日。曾干五月十二日具呈□□大部，将其阴险横暴实情，沥陈梗概，请予撤换在案。讵杨氏怙恶不悛，仍施诡计。先谋提前放假，又图停课考试。术既不售，乃愈设盛筵，多召党类，密画毁校之策，冀复失位之仇。又四出请托，广播谣诼，致函学生家长，屡以品性为言，与开除时之揭示，措辞不同，实属巧设谰言，阴伤人格，则其良心何在，不问可知。倘使一任诪张，诚为学界大辱，盖不独（生等）身受摧残，学校无可挽救而已。为此合词续恳即下明令，速任贤明，庶校务有主持之人，暴者失蹂躏之地，学校幸甚！教育幸甚！

谨呈

教育部总长

**** 停办北京女子师范大学呈文
     :PROPERTIES:
     :CUSTOM_ID: 19250808
     :END:

     - Note taken on [2019-11-06 三 13:42] \\
       原载《甲寅周刊》第1卷4号（1925年8月8日）。本文录自[[http://www.cnthinkers.com/thinkerweb/index][中国思想与文化名家数据库]]。
呈为国立大学，师生互哄，纷纠难理，拟恳查照术专门学校成例，将该大学暂行停办，以资整顿而维风纪事：北京女子师范大学校长杨荫榆，为校内一部分学生所反对，呈词互讦，由来已久。本部前任次长马叙伦、总长王九龄，均以办理棘手，迁延未决。迨士钊兼部，日在辞职或未实行负责之中，亦复未暇顾及。查此事之起，由于该校学生，设有自治会，倡言不认杨荫榆为校长，并于公开讲演之时，群起侮辱。该校长乃于素喜滋事之学生中，革除蒲振声、张平江、刘和珍、姜伯谛、许广平、郑德音等六人。该生等不服，联合校内男女各生，大施反抗运动。非但革生不肯出校，转而驱逐校长，锁闭办公室，阴止校长及办事人等入内，以致全校陷入无政府状态。由五月至今，三四月间，学生跳梁于内，校长侨置于外，为势僵然，一筹莫展。迩者士钊奉令调署，正拟切实查办，适该校长杨荫榆，拟具改组四班计划，请示前来。当以该校长职责所存，批令妥善办理。顷据该校长呈报：八月一日到校，顽劣学生，手持木棍砖石，志存殴辱，叫骂追逐，无所不至。又复撕毁布告，易以学生求援宣言，并派人驻守校门，禁阻校员出入，其余则乘坐汽车，四出求助。旋有男生多人，来校恫吓，并携带快镜，各处摄影。种种怪状，见者骇然等情。学生暴乱如此，迥出情理之外。窃思比年学风，嚣张已极。政府既乏长策，社会复无公评。四方不逞之徒，又从而扇发之，狙使青年男女，顽抗部校命令。是非颠例，一无准裁。该校长以一女流，明其职守，甘任劳怨，期有始终。虽其平时措置，未必尽当，平心而论，似亦为所难能。士钊每得该校长之谤书，思此辄为太息。或谓师生之情过伤，处置难期妥惬，原案虽不能易，人选似可通融。不知京师各校，以革除学生而谋逐校长，已非一次，其后因缘事变，借口调停，大抵革生留而校长去。胜负之数，伏于事先，横逆之生，惯如饮食，乖风流衍，以迄今兹，纲纪荡然，泰半由此。今若谬种相仍，再误三误，此其选软羞当世之士，其失小；公然纵子弟为恶，其失大。士钊详加考虑，此着断不可行。默察该校情形，各系教员，植党构扇，势甚强固，不可爬梳。而诸生荒学逾闲，恣为无忌，道路以目，亲者痛心。该校长任事以来，一切要害之政，并尚未能董理，而已怨毒之甚，一日难居。倘仍其旧贯，环境依然，即别求一人为继，度亦无能为役。士钊少负不羁之名，长习自由之说，名邦大学，负笈分驰，男女同班，亦尝亲与，所有社会交际、两性衔接之机缄缔构，一一考求。其中流以上之家，凡未成年之女子，殆无不惟家长阿保之命是从，文质彬彬，至可敬爱。从未见有不受检制，竟体忘形，啸聚男生，蔑视长上，家族不知所出，浪士从而推波，伪托文明，肆为驰骋，谨愿者尽丧所守，狡黠者毫无忌惮，学纪大紊，礼教全荒，如吾国今日女学之可悲叹者也。以此兴学，直是灭学。以此尊重女子，直是摧辱女子。钊念儿女乃家家所有，良用痛心，为政而人人悦之，亦无是理，该师范大学，号为全国女子最高学府，强自取柱，柔自取束，立表不正，其影可知。当此女教绝续之秋，宜为根本改图之计，拟请查照马前次长处理美术专门学校成例，将该大学暂行停办。该校长杨荫榆调部任用，一面遴选专家，妥速筹画。务期重立宏规，树之模楷，以副执政与民更始不遗女子之至意。是否有当，理合具文，仰祈钧鉴施行。再：该校学生，半由各省考送，家长戚族，未必在京，责令即时解散，亦未便操之过急。日者士钊曾偕部员，亲赴该校视察，见留校女生二十余人，起居饮食，诸感困苦。迹其行为，宜有惩罚，观其情态，亦甚可矜。当由部派员，商同各该保证人，妥为料理，无须警察干预。外传警察殴伤学生各节，全属讹言。此后校事部了，尤不至有学警冲突之虞。合并陈明。

**** 章士钊致段祺瑞呈文
     :PROPERTIES:
     :CUSTOM_ID: 19250812
     :END:


     - Note taken on [2019-11-06 三 22:37] \\
       此文1925年8月12日呈段祺瑞。实在搜不到，只能在《一个都不宽恕》里面复制粘贴。然后13日鲁迅就被免职。

敬折呈者，窃查官吏服务，首在恪守本分，服从命令。兹有本部佥事周树人，兼任国立女子师范大学教员，于本部下令停办该校以后，结合党徒，附和女生，倡设校务维持会，充任委员，似此违法抗令，殊属不合，应请明令免去本职，以示惩戒（并请补交高等文官惩戒委员会核议，以完法律手续）。是否有当，理合呈请鉴核施行。谨呈临时执政。

**** 鲁迅呈平政院状
     :PROPERTIES:
     :CUSTOM_ID: 19250822
     :END:
     - Note taken on [2019-11-06 三 22:40] \\
       1925年8月22日，鲁迅向平政院投递诉状，原文找不到，从《一个都不宽恕》中复制粘贴——然而《一》书本身就是从平政院的裁决书中抄的。

树人充教育部佥事，已十有四载，恪恭将事，故任职以来屡获奖叙。讵教育总长章士钊竟无故将树人呈请免职。查文官免职，系属惩戒处分之一。依《文官惩戒条例》第十八条之规定，须先交付惩戒始能依法执行。乃竟滥用职权，擅自处分，无故将树人免职，显违《文官惩戒条例》第一条及《文官保障法草案》第二条之规定。此种违法处分，实难自甘缄默。

**** 答KS君
     :PROPERTIES:
     :CUSTOM_ID: 19250828
     :END:
     - Note taken on [2019-11-06 三 22:58] \\
       董大中的[[https://books.google.com.hk/books?id=wY4BRZYJPwIC&pg=PA261&lpg=PA261&dq=%25E7%25AD%2594KS%25E5%2590%259B+%25E8%25B0%2581%25E6%2598%25AF+KS%25E5%2590%259B&source=bl&ots=UMX_1D7kuz&sig=ACfU3U0rghsRR2kYvkR17t3tApiC1vOW0g&hl=zh-CN&sa=X&redir_esc=y#v=onepage&q=%25E7%25AD%2594KS%25E5%2590%259B%2520%25E8%25B0%2581%25E6%2598%25AF%2520KS%25E5%2590%259B&f=false][《魯迅日記箋釋》]]也说 KS 君未详，我也就不考究了。原载《莽原》1925年8月28日周刊第19期

KS兄：

我很感谢你的殷勤的慰问，但对于你所愤慨的两点和几句结论，我却并不谓然，现在略说我的意见——

第一，章士钊将我免职，我倒并没有你似的觉得诧异，他那对于学校的手段，我也并没有你似的觉得诧异，因为我本就没有预期章士钊能做出比现在更好的事情来。我们看历史，能够据过去以推知未来，看一个人的已往的经历，也有一样的效用。你先有了一种无端的迷信，将章士钊当作学者或智识阶段的领袖看，于是从他的行为上感到失望，发生不平，其实是作茧自缚；他这人本来就只能这样，有着更好的期望倒是你自己的误谬。使我较为感到有趣的倒是几个向来称为学者或教授的人们，居然也渐次吞吞吐吐地来说微温话了，什么“政潮”咧，“党”咧，仿佛他们都是上帝一样，超然象外，十分公平似的。谁知道人世上并没有这样一道矮墙，骑着而又两脚踏地，左右稳妥，所以即使吞吞吐吐，也还是将自己的魂灵枭首通衢，挂出了原想竭力隐瞒的丑态。丑态，我说，倒还没有什么丢人，丑态而蒙着公正的皮，这才催人呕吐。但终于使我觉得有趣的是蒙着公正的皮的丑态，又自己开出帐来发表了。仿佛世界上还有光明，所以即便费尽心机，结果仍然是一个瞒不住。

第二，你这样注意于《甲寅周刊》，也使我莫明其妙。《甲寅》第一次出版时，我想，大约章士钊还不过熟读了几十篇唐宋八大家文，所以模仿吞剥，看去还近于清通。至于这一回，却大大地退步了，关于内容的事且不说，即以文章论，就比先前不通得多，连成语也用不清楚，如“每下愈况”之类。尤其害事的是他似乎后来又念了几篇骈文，没有融化，而急于挦撦，所以弄得文字庞杂，有如泥浆混着沙砾一样。即如他那《停办北京女子师范大学呈文》中有云，“钊念儿女乃家家所有良用痛心为政而人人悦之亦无是理”，旁加密圈，想是得意之笔了。但比起何《齐姜醉遣晋公子赋》的“公子固翩翩绝世未免有情少年而碌碌因人安能成事”来，就显得字句和声调都怎样陋弱可哂。何比他高明得多，尚且不能入作者之林，章士钊的文章更于何处讨生活呢？况且，前载公文，接着就是通信，精神虽然是自己广告性的半官报，形式却成了公报尺牍合璧了，我中国自有文字以来，实在没有过这样滑稽体式的著作。这种东西，用处只有一种，就是可以借此看看社会的暗角落里，有着怎样灰色的人们，以为现在是攀附显现的时候了，也都吞吞吐吐的来开口。至于别的用处，我委实至今还想不出来。倘说这是复古运动的代表，那可是只见得复古派的可怜，不过以此当作讣闻，公布文言文的气绝罢了。

所以，即使真如你所说，将有文言白话之争，我以为也该是争的终结，而非争的开头，因为《甲寅》不足称为敌手，也无所谓战斗。倘要开头，他们还得有一个更通古学，更长古文的人，才能胜对垒之任，单是现在似的每周印一回公牍和游谈的堆积，纸张虽白，圈点虽多，是毫无用处的。

**** 「碰壁」之餘
     :PROPERTIES:
     :CUSTOM_ID: 19250921
     :END:
     - Note taken on [2019-11-10 日 14:12] \\
       本文就是在怼陈西滢之余顺带提一笔章士钊，编在这一节其实不是很合适。
     - Note taken on [2019-11-10 日 14:10] \\
       高仁山　江苏江阴人，当时任北京大学教授。他在一九二五年五月三十一日《晨报》“时论”栏发表的《大家不管的女师大》一文中说：“最奇怪的就是女师大的专任及主任教授都那里去了？学校闹到这样地步，何以大家不出来设法维持？诸位专任及主任教授，顶好同学生联合起来，商议维持学校的办法，不要让教一点两点钟兼任教员来干涉你们诸位自己学校的事情。”
     - Note taken on [2019-11-10 日 14:08] \\
       想不到《女师大观剧的经验》的作者就是李四光，这篇也找不到。
     - Note taken on [2019-11-10 日 13:56] \\
       这是一篇署名为“一个女读者”给《现代评论》记者的信，载于该刊第一卷第十五期（一九二五年三月二十一日）。主要意思是说：女师大学生迭次驱杨的“那些宣言书中所列举杨氏的罪名，既大都不能成立罪名……而这回风潮的产生和发展，校内校外尚别有人在那里主使。”又说“女师大是中国唯一的女子大学；杨氏也是充任大学校长的唯一的中国女子……我们应否任她受教育当局或其他任何方面的排挤攻击？我们女子应否自己还去帮着摧残她？”
     - Note taken on [2019-11-10 日 13:55] \\
       从维基文库粘贴过来的，所以是繁体字。

女師大事件在北京似乎竟頗算一個問題，號稱「大報」如所謂《現代評論》者，居然也「評論」了好幾次。據我所記得的，是先有「一個女讀者」的一封信，無名小女卒，不在話下。此後是兩個作者的「評論」了：陳西瀅先生在[[*%E9%97%B2%E8%AF%9D%EF%BC%88%E7%B2%89%E5%88%B7%E8%8C%85%E5%8E%95%EF%BC%89][《闲话》]]之間評為「臭毛廁」，李仲揆先生的《在女師大觀劇的經驗》裡則比作戲場。我很吃驚於同是人，而眼光竟有這麼不同；但究竟同是人，所以意見也不無符合之點：都不將學校看作學校。這一點，也可以包括楊蔭榆女士的「學校猶家庭」和段祺瑞執政的「先父兄之教」。

陳西瀅先生是「久已夫非一日矣」的《閒話》作家，那大名我在報紙的廣告上早經看熟了，然而大概還是一位高人，所以遇有不合自意的，便一氣呵成屎橛，而世界上蛆蟲也委實太多。至於李仲揆先生其人也者，我在《女師風潮紀事》上才識大名，是八月一日擁楊蔭榆女士攻入學校的三勇士之一；到現在，卻又知道他還是一位達人了，庸人以為學潮的，到他眼睛裡就等於「觀劇」：這是何等逍遙自在。

據文章上說，這位李仲揆先生是和楊女士「不過見面兩次」，但卻被用電話邀去看「名振一時的文明新戲」去了，幸而李先生自有腳踏車，否則，還要用汽車來迎接哩。我真自恨福薄，一直活到現在，壽命已不可謂不長，而從沒有遇見過一個不大認識的女士來邀「觀劇」；對於女師大的事說了幾句話，尚且因為不過是教一兩點功課的講師，「碰壁之後」，還很恭聽了些高仁山先生在《晨報》上所發表的偉論。真的，世界上實在又有各式各樣的運氣，各式各樣的嘴，各式各樣的眼睛。

接著又是西瀅先生的《閒話》：「現在一部分報紙的篇幅，幾乎全讓女師風潮占去了。現在大部分愛國運動的青年的時間，也幾乎全讓女師風潮占去了。……女師風潮實在是了不得的大事情，實在有了不得的大意義。」臨末還有頗為俏皮的結論道：「外國人說，中國人是重男輕女的。我看不見得吧。」

我看也未必一定「見得」。正如人們有各式各樣的眼睛一樣，也有各式各樣的心思，手段。便是外國人的尊重一切女性的事，倘使好講冷話的人說起來，也許以為意在於一個女性。然而侮蔑若干女性的事，有時也就可以說意在於一個女性。偏執的弗羅特先生宣傳了「精神分析」之後，許多正人君子的外套都被撕碎了。但撕下了正人君子的外套的也不一定就是「小人」，只要並非自以為還鑽在外套裡的不顯本相的腳色。

我看也未必一定「見得」。中國人是「聖之時者也」教徒，況且活在二十世紀了，有華道理，有洋道理，輕重當然是都隨意而無不合於道的：重男輕女也行，重女輕男也行，為了一個女性而重一切女性或輕若干女性也行，為了一個男人而輕若干女性或男性也行……。所可惜的是自從西瀅先生看出底細之後，除了啞吧或半陰陽，就都墜入弗羅特先生所掘的陷坑裡去了。

自己墜下去的是自作自受，可恨者乃是還要帶累超然似的局外人，例如女師大——對不起，又是女師大——風潮，從有些眼睛看來，原是不值得提起的，但因為竟占去了許多可貴的東西，如「報紙的篇幅」「青年的時間」之類，所以，連《現代評論》的「篇幅」和西瀅先生的時間也被拖累著占去一點了，而尤其罪大惡極的是觸犯了什麼「重男輕女」重女輕男這些大秘密。倘不是西瀅先生首先想到，提出，大概是要被含胡過去了的。

我看，奧國的學者實在有些偏激，弗羅特就是其一，他的分析精神，竟一律看待，不讓誰站在超人間的上帝的地位上。還有那短命的Otto Weininger，他的痛駡女人，不但不管她是校長，學生，同鄉，親戚，愛人，自己的太太，太太的同鄉，簡直連自己的媽都罵在內。這實在和弗羅特說一樣，都使人難於利用。不知道咱們的教授或學者們，可有方法補救沒有？但是，我要先報告一個好消息：Weininger早用手槍自殺了。這已經有劉百昭率領打手痛打女師大——對不起，又是女師大——的「毛丫頭」一般「痛快」，他的話也就大可置之不理了罷。

還有一個好消息。「毛丫頭」打出之後，張崧年先生引「羅素之所信」道，「因世人之愚，許多問題或終於不免只有武力可以解決也！」（《京副》二五○號）又據楊蔭榆女士，章士釗總長者流之所說，則搗亂的「毛丫頭」是極少數，可見中國的聰明人還多著哩，這是大可以樂觀的。

忽而想談談我自己的事了。

我今年已經有兩次被封為「學者」，而發表之後，也就即刻取消。第一次是我主張中國的青年應當多看外國書，少看，或者竟不看中國書的時候，便有論客以為素稱學者的魯迅不該如此，而現在竟至如此，則不但決非學者，而且還有洋奴的嫌疑。第二次就是這回僉事免職之後，我在《莽原》上發表了答KS君信，論及章士釗的腳色和文章的時候，又有論客以為因失了「區區僉事」而反對章士釗，確是氣量狹小，沒有「學者的態度」；而且，豈但沒有「學者的態度」而已哉，還有「人格卑污」的嫌疑云。

其實，沒有「學者的態度」，那就不是學者嘍，而有些人偏要硬派我做學者。至於何時封贈，何時考定，卻連我自己也一點不知道。待到他們在報上說出我是學者，我自己也借此知道了原來我是學者的時候，則已經同時發表了我的罪狀，接著就將這體面名稱革掉了，雖然總該還要恢復，以便第三次的藉口。

據我想來，僉事——文士詩人往往誤作簽事，今據官書正定——這一個官兒倒也並不算怎樣「區區」，只要看我免職之後，就頗有些人在那裡鑽謀樸缺，便是一個老大的證據。至於又有些人以為無足重輕者，大約自己現在還不過做幾句「說不出」的詩文，所以不知不覺地就來「慷他人之慨」了罷，因為人的將來是想不到的。然而，慚愧我還不是「臣罪當誅兮天王聖明」式的理想奴才，所以竟不能「盡如人意」，已經在平政院對章士釗提起訴訟了。

提起訴訟之後，我只在答KS君信裡論及一回章士釗，但聽說已經要「人格卑污」了。然而別一論客卻道是並不大罵，所以魯迅究竟不足取。我所經驗的事委實有點希奇，每有「碰壁」一類的事故，平時回護我的大抵願我設法應付，甚至於暫圖苟全。平時憎惡我的卻總希望我做一個完人，即使敵手用了卑劣的流言和陰謀，也應該正襟危坐，毫無憤怨，默默地吃苦；或則戟指嚼舌，噴血而亡。為什麼呢？自然是專為顧全我的人格起見嘍。

夠了，我其實又何嘗「碰壁」，至多也不過遇見了「鬼打牆」罷了。

**** 章士钊答状
     :PROPERTIES:
     :CUSTOM_ID: 19251013
     :END:
     - Note taken on [2019-11-06 三 22:43] \\
       继续从《一个都不宽恕》中抄录，本答辩当年10月13日送到鲁迅处。

查周树人免职理由，本部上执政呈文业经声叙明白，兹更为贵院述之：本年八月十日，本部遵照执政训令停办国立女子师范大学，当委部员刘百昭等前往接收，不意本部佥事周树人，原系社会司第一科科长，地位职务均极重要，乃于本部执行令准停办该校，正属行政严重之时，竟敢勾结该校教员、捣乱分子及少数不良学生，谬托校务维持会名义，妄自主张，公然与所服务之官署悍然立于反抗地位。据接收委员会报告，入校办公时亲见该员盘踞校舍，集众开会，确有种种不合之行为。又该伪校务维持会，擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政，既情理之所难容，亦法律之所不许。查《官吏服务令》第一条：凡官吏应竭尽忠勤，服从法律命令以行职务。第二条：长官就其范围以内所发命令，属员有服从之义务。第四条：属官对于长官所发命令如有意见，得随时陈述。第二十九条：凡官吏有违上开各条者，该管长官依其情节，分别训告，或付惩戒。规定至为明切。今周树人既未将意见陈述，复以本部属员不服从本部长官命令，实已违反《文官服务令》第一第二第四各条之规定。本部原拟循例呈请交付惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈烈，难以平息，不得已于八月十二日呈请执政将周树人免职。十三日由执政明令照准，此周树人免职经过之实在情形也。查原诉状内有无故免职等语，系欲以无故二字遮掩其与女师大教习学生集会违令各行为，希图脱免。至追加理由所称本部呈请执政将周树人免职稿件倒填日月一节，实因此项免职事件情出非常，本部总长系于十二日面呈执政，即日明令发表，随后再将呈稿补发存案。即日补发，无所谓倒填，情势急迫，本部总长应有权执行此非常处分，周树人不得引为口实。兹特详叙事实答辩如右。

**** 鲁讯互辩书
     :PROPERTIES:
     :CUSTOM_ID: 19251016
     :END:

     - Note taken on [2019-11-06 三 22:46] \\
       鲁迅博物馆现存一份鲁迅亲自收藏的互辩书草稿。写作日期是1925年10月16日。节录如下。

一、查总长妄称□□（按“树人”二字。下同）以部员资格勾结该校教员捣乱分子及少数不良学生，谬托校务维持会名义，妄有主张等语，全不明言去勾结何等捣乱分子及不良学生何人，□□主张何事，信口虚捏，全无事实证据，殊不称长官体统，有玷人格。况各部职员兼任国立各校教员不下数百人，□□为女师大兼任教员之一。在部则为官吏，在校则为教员。两种资格，各有职责、不容牵混。……

二、□□平日品性人格，向不干预外事，社会共晓。此次女师大应否解散尤与□□无涉。故该总长对于该校举动是否合宜，□□从不过问。现该答辩内有“周树人既未将意见陈述”一言可知从未干预。至□□在女师大担任教员职务，一方关于教课，固为个人应负责；一方关于公众，又为团体共负之责。若由团体发表之事件，应由团体负责，尤不能涉及个人，更不能专诬□□一人而加以非法（处分）。譬如现北大与教育部脱离关系。公然反抗，是为团体行动，岂北大教员之兼教部职员者将共负其责耶？

三、该答辩称“据接收委员报告云确有种种不法行为”，试问报告委员何人？报告何在？□□盘踞何状？不合何事？概未明言，即入人罪。且说教员维持校务为伪托，伪者何在？抑凡为教员者于法不得维持校务耶？

四、答辩又称“该伪校务维持会擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政”。查校务维持会公举□□为委员，系在8月13日，而该总长呈请免职，据称在12日。岂预知将举□□为委员而先为免职之罪名耶？况他人公举□□何能为□□之罪？

五、……□□充教育部佥事、社会教育司科长，与女师大停办与否，职守上毫无关系，故对于女师大停办命令从未一字陈述意见，亦实无陈述之职责。既未陈述，既无违反命令举动及言论可知。乃章士钊反以未陈述意见指为抗违命令，其理由何在？且又以未陈述意见即为违反服务令第一、二、四等条，其理由又安在？殊不可解。岂官吏须出位陈述职守以外之意见方为遵守服务令耶？何悖谬至此！

六、该答辩谓“本部原拟循例呈请惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈恶，难以平息，不得已呈请免职。”查以教长权力整顿一女校，何至形势严重？依法免部员职，何至迫不及待？风潮难平，事系学界？何至用非常处分。此等饰词，殊属可笑。且所谓行政处分原以合法为范围。凡违法令之行政处分当然无效。此《官吏服务令》所明白规定者。今章士钊不依法惩戒，殊属身为长官，弁髦法令。

**** 从胡须说到牙齿（节录）
     :PROPERTIES:
     :CUSTOM_ID: 19251109
     :END:

     - Note taken on [2019-11-07 四 19:26] \\
       我觉得本文跟甲寅没有什么关系，只是刚好跟章士钊打官司，不放过攻击他的机会而已。《太阳晒屁股赋》现在是找不到了，如果去图书馆翻《晶报》的微缩胶片可能还能找到。

一翻《呐喊》，才又记起我曾在中华民国九年双十节的前几天做过一篇《头发的故事》；去年，距今快要一整年了罢，那时是《语丝》出世未久，我又曾为它写了一篇《说胡须》。

实在似乎很有些章士钊之所谓“每况愈下”了，——自然，这一句成语，也并不是章士钊首先用错的，但因为他既以擅长旧学自居，我又正在给他打官司，昕以就栽在他身上。当时就听说，——或者也是时行的“流言”，——一位北京大学的名教授就愤慨过，以为从胡须说起，一直说下去，将来就要说到屁股，则于是乎便和上海的《晶报》一样了。为什么呢？这须是熟精今典的人们才知道，后进的“束发小生”是不容易了然的。因为《晶报》上曾经登过一篇《太阳晒屁股赋》，屁股和胡须又都是人身的一部分，既说此部，即难免不说彼部，正如看见洗脸的人，敏捷而聪明的学者即能推见他一直洗下去，将来一定要洗到屁股。所以有志于做gentleman者，为防微杜渐起见，应该在背后给一顿奚落的。——如果说此外还有深意，那我可不得而知了。

昔者窃闻之：欧美的文明人讳言下体以及和下体略有渊源的事物。假如以生殖器为中心而画一正圆形，则凡在圆周以内者均在讳言之列；而圆之半径，则美国者大于英。中国的下等人，是不讳言的；古之上等人似乎也不讳，所以虽是公子而可以名为黑臀。讳之始，不知在什么时候；而将英美的半径放大，直至于口鼻之间或更在其上，则于一千九百二十四年秋。

文人墨客大概是感性太锐敏了之故罢，向来就很娇气，什么也给他说不得，见不得，听不得，想不得。道学先生于是乎从而禁之，虽然很像背道而驰，其实倒是心心相印。然而他们还是一看见堂客的手帕或者姨太太的荒冢就要做诗。我现在虽然也弄弄笔墨做做白话文，但才气却仿佛早经注定是该在“水平线”之下似的？所以看见手帕或荒冢之类，倒无动于中；只记得在解剖室里第一次要在女性的尸体上动刀的时候，可似乎略有做诗之意，——但是，不过“之意”而已，并没有诗，读者幸勿误会，以为我有诗集将要精装行世，传之其人，先在此预告。后来，也就连“之意”都没有了，大约是因为见惯了缘故罢，正如下等人的说惯一样。否则，也许现在不但不敢说胡须，而且简直非“人之初性本善论”或“天地玄黄赋”便不屑做。遥想土耳其革命后，撕去女人的面幕，是多么下等的事？呜呼，她们已将嘴巴露出，将来一定要光着屁股走路了！

**** 十四年的“读经”
     :PROPERTIES:
     :CUSTOM_ID: 19251127
     :END:

自从章士钊主张读经以来，论坛上又很出现了一些论议，如谓经不必尊，读经乃是开倒车之类。我以为这都是多事的，因为民国十四年的“读经”，也如民国前四年，四年，或将来的二十四年一样，主张者的意思，大抵并不如反对者所想像的那么一回事。

尊孔，崇儒，专经，复古，由来已经很久了。皇帝和大臣们，向来总要取其一端，或者“以孝治天下”，或者“以忠诏天下”，而且又“以贞节励天下”。但是，二十四史不现在么？其中有多少孝子，忠臣，节妇和烈女？自然，或者是多到历史上装不下去了；那么，去翻专夸本地人物的府县志书去。我可以说，可惜男的孝子和忠臣也不多的，只有节烈的妇女的名册却大抵有一大卷以至几卷。孔子之徒的经，真不知读到那里去了；倒是不识字的妇女们能实践。还有，欧战时候的参战，我们不是常常自负的么？但可曾用《论语》感化过德国兵，用《易经》咒翻了潜水艇呢？儒者们引为劳绩的，倒是那大抵目不识丁的华工！

所以要中国好，或者倒不如不识字罢，一识字，就有近乎读经的病根了。“瞰亡往拜”“出疆载质”的最巧玩艺儿，经上都有，我读熟过的。只有几个胡涂透顶的笨牛，真会诚心诚意地来主张读经。而且这样的脚色，也不消和他们讨论。他们虽说什么经，什么古，实在不过是空嚷嚷。问他们经可是要读到像颜回，子思，孟轲，朱熹，秦桧（他是状元），王守仁，徐世昌，曹锟；古可是要复到像清（即所谓“本朝”），元，金，唐，汉，禹汤文武周公，无怀氏，葛天氏？他们其实都没有定见。他们也知不清颜回以至曹锟为人怎样，“本朝”以至葛天氏情形如何；不过像苍蝇们失掉了垃圾堆，自不免嗡嗡地叫。况且既然是诚心诚意主张读经的笨牛，则决无钻营，取巧，献媚的手段可知，一定不会阔气；他的主张，自然也决不会发生什么效力的。

至于现在的能以他的主张，引起若干议论的，则大概是阔人。阔人决不是笨牛，否则，他早已伏处牖下，老死田间了。现在岂不是正值“人心不古”的时候么？则其所以得阔之道，居然可知。他们的主张，其实并非那些笨牛一般的真主张，是所谓别有用意；反对者们以为他真相信读经可以救国，真是“谬以千里”了！

我总相信现在的阔人都是聪明人；反过来说，就是倘使老实，必不能阔是也。至于所挂的招牌是佛学，是孔道，那倒没有什么关系。总而言之，是读经已经读过了，很悟到一点玩意儿，这种玩意儿，是孔二先生的先生老聃的大著作里就有的，此后的书本子里还随时可得。所以他们都比不识字的节妇，烈女，华工聪明；甚而至于比真要读经的笨牛还聪明。何也？曰：“学而优则仕”故也。倘若“学”而不“优”，则以笨牛没世，其读经的主张，也不为世间所知。

孔子岂不是“圣之时者也”么，而况“之徒”呢？现在是主张“读经”的时候了。武则天做皇帝，谁敢说“男尊女卑”？多数主义虽然现称过激派，如果在列宁治下，则共产之合于葛天氏，一定可以考据出来的。但幸而现在英国和日本的力量还不弱，所以主张亲俄者，是被卢布换去了良心。

我看不见读经之徒的良心怎样，但我觉得他们大抵是聪明人，而这聪明，就是从读经和古文得来的。我们这曾经文明过而后来奉迎过蒙古人满洲人大驾了的国度里，古书实在太多，倘不是笨牛，读一点就可以知道，怎样敷衍，偷生，献媚，弄权，自私，然而能够假借大义，窃取美名。再进一步，并可以悟出中国人是健忘的，无论怎样言行不符，名实不副，前后矛盾，撒诳造谣，蝇营狗苟，都不要紧，经过若干时候，自然被忘得干干净净；只要留下一点卫道模样的文字，将来仍不失为“正人君子”。况且即使将来没有“正人君子”之称，于目下的实利又何损哉？

这一类的主张读经者，是明知道读经不足以救国的，也不希望人们都读成他自己那样的；但是，耍些把戏，将人们作笨牛看则有之，“读经”不过是这一回耍把戏偶尔用到的工具。抗议的诸公倘若不明乎此，还要正经老实地来评道理，谈利害，那我可不再客气，也要将你们归入诚心诚意主张读经的笨牛类里去了。

以这样文不对题的话来解释“俨乎其然”的主张，我自己也知道有不恭之嫌，然而我又自信我的话，因为我也是从“读经”得来的。我几乎读过十三经。

衰老的国度大概就免不了这类现象。这正如人体一样，年事老了，废料愈积愈多，组织间又沉积下矿质，使组织变硬，易就于灭亡。一面，则原是养卫人体的游走细胞（Wanderzelle）渐次变性，只顾自己，只要组织间有小洞，它便钻，蚕食各组织，使组织耗损，易就于灭亡。俄国有名的医学者梅契尼珂夫（EliasMetschnikov）特地给他别立了一个名目：大嚼细胞（Fresserzelle）。据说，必须扑灭了这些，人体才免于老衰；要扑灭这些，则须每日服用一种酸性剂。他自己就实行着。

古国的灭亡，就因为大部分的组织被太多的古习惯教养得硬化了，不再能够转移，来适应新环境。若干分子又被太多的坏经验教养得聪明了，于是变性，知道在硬化的社会里，不妨妄行。单是妄行的是可与论议的，故意妄行的却无须再与谈理。惟一的疗救，是在另开药方：酸性剂，或者简直是强酸剂。

不提防临末又提到了一个俄国人，怕又有人要疑心我收到卢布了罢。我现在郑重声明：我没有收过一张纸卢布。因为俄国还未赤化之前，他已经死掉了，是生了别的急病，和他那正在实验的药的有效与否这问题无干。

**** 学界的三魂
     :PROPERTIES:
     :CUSTOM_ID: 19260201
     :END:

     - Note taken on [2019-11-07 四 19:34] \\
       这篇是从维基文库复制粘贴过来的，见 https://zh.wikisource.org/zh/%E5%AD%B8%E7%95%8C%E7%9A%84%E4%B8%89%E9%AD%82 。其实我觉得鲁迅在这里只是顺手骂章士钊而已。

從《京報副刊》上知道有一種叫《國魂》的期刊，曾有一篇文章說章士釗固然不好，然而反對章士釗的「學匪」們也應該打倒。我不知道大意是否真如我所記得？但這也沒有什麼關係，因為不過引起我想到一個題目，和那原文是不相干的。意思是，中國舊說，本以為人有三魂六魄，或云七魄；

國魂也該這樣。而這三魂之中，似乎一是「官魂」，一是「匪魂」，還有一個是什麼呢？也許是「民魂」罷，我不很能夠決定。又因為我的見聞很偏隘，所以未敢悉指中國全社會，只好縮而小之曰「學界」。

中國人的官癮實在深，漢重孝廉而有埋兒刻木，宋重理學而有高帽破靴，清重帖括而有「且夫」「然則」。總而言之：那魂靈就在做官，——行官勢，擺官腔，打官話。頂著一個皇帝做傀儡，得罪了官就是得罪了皇帝，於是那些人就得了雅號曰「匪徒」。學界的打官話是始於去年，凡反對章士釗的都得了「土匪」，「學匪」，「學棍」的稱號，但仍然不知道從誰的口中說出，所以還不外乎一種「流言」。

但這也足見去年學界之糟了，竟破天荒的有了學匪。以大點的國事來比罷，太平盛世，是沒有匪的；待到群盜如毛時，看舊史，一定是外戚，宦官，奸臣，小人當國，即使大打一通官話，那結果也還是「嗚呼哀哉」。當這「嗚呼哀哉」之前，小民便大抵相率而為盜，所以我相信源增先生的話：

「表面上看只是些土匪與強盜，其實是農民革命軍。」（《國民新報副刊》四三）那麼，社會不是改進了麼？並不，我雖然也是被諡為「土匪」之一，卻並不想為老前輩們飾非掩過。農民是不來奪取政權的，源增先生又道：「任三五熱心家將皇帝推倒，自己過皇帝癮去。」但這時候，匪便被稱為帝，除遺老外，文人學者卻都來恭維，又稱反對他的為匪了。

所以中國的國魂裡大概總有這兩種魂：官魂和匪魂。這也並非硬要將我輩的魂擠進國魂裡去，貪圖與教授名流的魂為伍，只因為事實仿佛是這樣。社會諸色人等，愛看《雙官誥》，也愛看《四傑村》，望偏安巴蜀的劉玄德成功，也願意打家劫舍的宋公明得法；至少，是受了官的恩惠時候則豔羨官僚，受了官的剝削時候便同情匪類。但這也是人情之常；

倘使連這一點反抗心都沒有，豈不就成為萬劫不復的奴才了？

然而國情不同，國魂也就兩樣。記得在日本留學時候，有些同學問我在中國最有大利的買賣是什麼，我答道：「造反。」

他們便大駭怪。在萬世一系的國度裡，那時聽到皇帝可以一腳踢落，就如我們聽說父母可以一棒打殺一般。為一部分士女所心悅誠服的李景林先生，可就深知此意了，要是報紙上所傳非虛。今天的《京報》即載著他對某外交官的談話道：

「予預計於舊曆正月間，當能與君在天津晤談；若天津攻擊竟至失敗，則擬俟三四月間捲土重來，若再失敗，則暫投土匪，徐養兵力，以待時機」云。但他所希望的不是做皇帝，那大概是因為中華民國之故罷。

所謂學界，是一種發生較新的階級，本該可以有將舊魂靈略加湔洗之望了，但聽到「學官」的官話，和「學匪」的新名，則似乎還走著舊道路。那末，當然也得打倒的。這來打倒他的是「民魂」，是國魂的第三種。先前不很發揚，所以一鬧之後，終不自取政權，而只「任三五熱心家將皇帝推倒，自己過皇帝癮去」了。

惟有民魂是值得寶貴的，惟有他發揚起來，中國才有真進步。但是，當此連學界也倒走舊路的時候，怎能輕易地發揮得出來呢？在烏煙瘴氣之中，有官之所謂「匪」和民之所謂匪；有官之所謂「民」和民之所謂民；有官以為「匪」而其實是真的國民，有官以為「民」而其實是衙役和馬弁。所以貌似「民魂」的，有時仍不免為「官魂」，這是鑒別魂靈者所應該十分注意的。

話又說遠了，回到本題去。去年，自從章士釗提了「整頓學風」的招牌，上了教育總長的大任之後，學界裡就官氣彌漫，順我者「通」，逆我者「匪」，官腔官話的餘氣，至今還沒有完。但學界卻也幸而因此分清了顏色；只是代表官魂的還不是章士釗，因為上頭還有「減膳」執政在，他至多不過做了一個官魄；現在是在天津「徐養兵力，以待時機」了。我不看《甲寅》，不知道說些什麼話：官話呢，匪話呢，民話呢，衙役馬弁話呢？……

附記

今天到東城去教書，在新潮社看見陳源教授的信，在北京大學門口看見《現代評論》，那《閒話》裡正議論著章士釗的《甲寅》，說「也漸漸的有了生氣了。可見做時事文章的人官實在是做不得的，……自然有些『土匪』不妨同時做官僚，……」這麼一來，我上文的「逆我者『匪』」，「官腔官話的餘氣」云云，就又有了「放冷箭」的嫌疑了。現在特地聲明：我原先是不過就一般而言，如果陳教授覺得痛了，那是中了流彈。要我在「至今還沒有完」之後，加一句「如陳源等輩就是」，自然也可以。至於「順我者『通』」的通字，卻是此刻所改的，那根據就在章士釗之曾稱陳源為「通品」。別人的褒獎，本不應拿來譏笑本人，然而陳源現就用著「土匪」的字樣。有一回的《閒話》（《現代評論》五十）道：「我們中國的批評家實在太宏博了。他們……在地上找尋竊賊，以致整大本的剽竊，他們倒往往視而不見。要舉個例嗎？還是不說吧，我實在不敢再開罪『思想界的權威』。」按照他這回的慷慨激昂例，如果要免於「卑劣」且有「半分人氣」，是早應該說明誰是土匪，積案怎樣，誰是剽竊，證據如何的。現在倘有記得那括弧中的「思想界的權威」六字，即曾見於《民報副刊》廣告上的我的姓名之上，就知道這位陳源教授的「人氣」有幾多。

從此，我就以別人所說的「東吉祥派」、「正人君子」、「通品」等字樣，加于陳源之上了，這回是用了一個「通」字；我要「以眼還眼以牙還牙」，或者以半牙，以兩牙還一牙，因為我是人，難於上帝似的銖兩悉稱。如果我沒有做，那是我的無力，並非我大度，寬恕了加害於我的敵人。還有，有些下賤東西，每以穢物擲人，以為人必不屑較，一計較，倒是你自己失了人格。我可要照樣的擲過去，要是他擲來。但對於沒有這樣舉動的人，我卻不肯先動手；而且也以文字為限，「捏造事實」和「散佈『流言』」的鬼蜮的長技，自信至今還不屑為。在馬弁們的眼裡雖然是「土匪」，然而「盜亦有道」的。記起一件別的事來了。

前幾天九校「索薪」的時候，我也當作一個代表，因此很會見了幾個前「公理維持會」即「女大後援會」中人。幸而他們倒並不將我捆送三貝子花園或運入深山，「投畀豺虎」，也沒有實行「割席」，將板凳鋸開。終於「學官」「學匪」，都化為「學丐」，同聚一堂，大討其欠帳，——

自然是討不來。記得有一個洋鬼子說過：中國先是官國，後來是土匪國，將來是乞丐國。單就學界而論，似乎很有點上這軌道了。想來一定有些人要後悔，去年竟抱了「有奶不是娘」主義，來反對章士釗的罷。

一月二十五日東壁燈下寫。

**** 国务总理贾德耀签署了给教育总长的训令（临时执政训令第十三号）
     :PROPERTIES:
     :CUSTOM_ID: 19260331
     :END:

     - Note taken on [2019-11-06 三 22:51] \\
       格式有点问题，「国务总理贾德耀教育总长」与「中华民国十五年三月三十一日」当右对齐。
据平政院院长汪大燮呈，审理前教育部佥事周树人陈诉不服教育部呈请免职之处分，指为违法，提起行政诉讼一案，依法裁决教育部之处分应予取消等语，著交教育部查照执行。

此令

国务总理贾德耀

教育总长

中华民国十五年三月三十一日


**** 再来一次
     :PROPERTIES:
     :CUSTOM_ID: 19260610
     :END:

去年编定《热风》时，还有绅士们所谓“存心忠厚”之意，很删削了好几篇。但有一篇，却原想编进去的，因为失掉了稿子，便只好从缺。现在居然寻出来了；待《热风》再版时，添上这篇，登一个广告，使迷信我的文字的读者们再买一本，于我倒不无裨益。但是，算了罢，这实在不很有趣。不如再登一次，将来收入杂感第三集，也就算作补遗罢。

这是关于章士钊先生的——两个桃子杀了三个读书人

章行严先生在上海批评他之所谓“新文化”说，“二桃杀三士”怎样好，“两个桃子杀了三个读书人”便怎样坏，而归结到新文化之“是亦不可以已乎？”

是亦大可以已者也！「[[#19230800][二桃杀三士]]」并非僻典，旧文化书中常见的。但既然是“谁能为此谋？相国齐晏子。”我们便看看《晏子春秋》罢。

《晏子春秋》现有上海石印本，容易入手的了，这古典就在该石印本的卷二之内。大意是“公孙接田开疆古冶子事景公，以勇力搏虎闻，晏子过而趋，三子者不起，”于是晏老先生以为无礼，和景公说，要除去他们了。那方法是请景公使人送他们两个桃子，说道：“你们三位就照着功劳吃桃罢。”呵，这可就闹起来了：

“公孙接仰天而叹曰，‘晏子，智人也，夫使公之计吾功者，不受桃，是无勇也。士众而桃寡，何不计功而食桃矣？接一搏猏而再搏虎，若接之功，可以食桃而无与人同矣。’援桃而起。

“古冶子曰，‘吾尝从君济于河，鼋衔左骖以入砥柱之流。当时也，冶少不能游，潜行逆流百步，顺流九里，得鼋杀之，左操骖尾，右挈鼋头，鹤跃而出。津人皆曰，河伯也；若冶视之，则大鼋之首。若冶之功，可以食桃而无与人同矣！二子何不反桃？’抽剑而起。”

钞书太讨厌。总而言之，后来那二士自愧功不如古冶子，自杀了；古冶子不愿独生，也自杀了：于是乎就成了“二桃杀三士”。

我们虽然不知道这三士于旧文化有无心得，但既然书上说是“以勇力闻”，便不能说他们是“读书人”。倘使《梁父吟》说是“二桃杀三勇士”，自然更可了然，可惜那是五言诗，不能增字，所以不得不作“二桃杀三士”，于是也就害了章行严先生解作“两个桃子杀了三个读书人”。

旧文化也实在太难解，古典也诚然太难记，而那两个旧桃子也未免太作怪：不但那时使三个读书人因此送命，到现在还使一个读书人因此出丑，“是亦不可以已乎”！

去年，因为“每下愈况”问题，我曾经很受了些自以为公平的青年的教训，说是因为他革去了我的“签事”，我便那么奚落他。现在我在此只得特别声明：这还是一九二三年九月所作，登在《晨报副刊》上的。那时的《晨报副刊》，编辑尚不是陪过泰戈尔先生的“诗哲”，也还未负有逼死别人，掐死自己的使命，所以间或也登一点我似的俗人的文章；而我那时和这位后来称为“孤桐先生”的，也毫无“睚眦之怨”。那“动机”，大概不过是想给白话的流行帮点忙。

在这样“祸从口出”之秋，给自己也辩护得周到一点罢。或者将曰，且夫这次来补遗，却有“打落水狗”之嫌，“动机”就很“不纯洁”了。然而我以为也并不。自然，和不多时以前，士钊秘长运筹帷幄，假公济私，谋杀学生，通辑异己之际，“正人君子”时而相帮讥笑着被缉诸人的逃亡，时而“孤桐先生”“孤桐先生”叫得热剌剌地的时候一比较，目下诚不免有落寞之感。但据我看来，他其实并未落水，不过“安住”在租界里而已：北京依旧是他所豢养过的东西在张牙舞爪，他所勾结着的报馆在颠倒是非，他所栽培成的女校在兴风作浪：依然是他的世界。

在“桃子”上给一下小打击，岂遂可与“打落水狗”同日而语哉？！

但不知怎的，这位“孤桐先生”竟在《甲寅》上辩起来了，以为这不过是小事。这是真的，不过是小事。弄错一点，又何伤乎？即使不知道晏子，不知道齐国，于中国也无损。农民谁懂得《梁父吟》呢，农业也仍然可以救国的。但我以为攻击白话的豪举，可也大可以不必了；将白话来代文言，即使有点不妥，反正也不过是小事情。

我虽然未曾在“孤桐先生”门下钻，没有看见满桌满床满地的什么德文书的荣幸，但偶然见到他所发表的“文言”，知道他于法律的不可恃，道德习惯的并非一成不变，文字语言的必有变迁，其实倒是懂得的。懂得而照直说出来的？便成为改革者；懂得而不说，反要利用以欺瞒别人的，便成为“孤桐先生”及其“之流”。他的保护文言，内骨子也不过是这样。

如果我的检验是确的，那么，“孤桐先生”大概也就染了《闲话》所谓“有些志士”的通病，为“老婆子女”所累了，此后似乎应该另买几本德文书，来讲究“节育”。


