#+STARTUP: showall
** 左联时期参加的三次论争
   :PROPERTIES:
   :CUSTOM_ID: chap3
   :END:

*** 「嘘」梁实秋
    :PROPERTIES:
    :CUSTOM_ID: chap3sec1
    :END:

**** 卢梭和胃口
     :PROPERTIES:
     :CUSTOM_ID: 19271227
     :END:

做过《民约论》的卢梭，自从他还未死掉的时候起，便受人们的责备和迫害，直到现在，责备终于没有完。连在和“民约”没有什么关系的中华民国，也难免这一幕了。

例如商务印书馆出版的《爱弥尔》中文译本的序文上，就说“……本书的第五编即女子教育，他的主张非但不彻底，而且不承认女子的人格，与前四编的尊重人类相矛盾。……所以在今日看来，他对于人类正当的主张，可说只树得一半……。”

然而复旦大学出版的《复旦旬刊》创刊号上梁实秋教授的意思，却“稍微有点不同”了。其实岂但“稍微”而已耶，乃是“卢梭论教育，无一是处，唯其论女子教育，的确精当。”

因为那是“根据于男女的性质与体格的差别而来”的。而近代生物学和心理学研究的结果，又证明著天下没有两个人是无差别。怎样的人就该施以怎样的教育。

所以，梁先生说——

“我觉得‘人’字根本的该从字典里永远注销，或由政府下令永禁行使。因为‘人’字的意义太糊涂了。聪明绝顶的人，我们叫他做人，蠢笨如牛的人，也一样的叫做人，弱不禁风的女子，叫做人，粗横强大的男人，也叫做人，人里面的三流九等，无一非人。近代的德谟克拉西的思想，平等的观念，其起源即由于不承认人类的差别。近代所谓的男女平等运动，其起源即由于不承认男女的差别。人格是一个抽象名词，是一个人的身心各方面的特点的总和。人的身心各方面的特点既有差别，实即人格上亦有差别。所谓侮辱人格的，即是不承认一个人特有的人格，卢梭承认女子有女子的人格，所以卢梭正是尊重女子的人格。抹杀女子所特有之特性者，才是侮辱女子人格。”

于是势必至于得到这样的结论——

“……正当的女子教育应该是使女子成为完全的女子。”

那么，所谓正当的教育者，也应该是使“弱不禁风”者，成为完全的“弱不禁风”，“蠢笨如牛”者，成为完全的“蠢笨如牛”，这才免于侮辱各人——此字在未经从字典里永远注销，政府下令永禁行使之前，暂且使用——的人格了。卢梭《爱弥尔》前四编的主张不这样，其“无一是处”，于是可以算无疑。

但这所谓“无一是处”者，也只是对于“聪明绝顶的人”而言；在“蠢笨如牛的人”，却是“正当”的教育。因为看了这样的议论，可以使他更渐近于完全“蠢笨如牛”。这也就是尊重他的人格。

然而这种议论还是不会完结的。为什么呢？一者，因为即使知道说“自然的不平等”，而不容易明白真“自然”和“因积渐的人为而似自然”之分。二者，因为凡有学说，往往“合吾人之胃口者则容纳之，且从而宣扬之”也。

上海一隅，前二年大谈亚诺德，今年大谈白璧德，恐怕也就是胃口之故罢。

许多问题大抵发生于“胃口”，胃口的差别，也正如“人”字一样的——其实这两字也应该呈请政府“下令永禁行使”。我且抄一段同是美国的UptonSinclair的，以尊重另一种人格罢——

“无论在那一个卢梭的批评家，都有首先应该解决的唯一的问题。为什么你和他吵闹的？要为他的到达点的那自由，平等，调协开路么？还是因为畏惧卢梭所发向世界上的新思想和新感情的激流呢？使对于他取了为父之劳的个人主义运动的全体怀疑，将我们带到子女服从父母，奴隶服从主人，妻子服从丈夫，臣民服从教皇和皇帝，大学生毫不发生疑问，而佩服教授的讲义的善良的古代去，乃是你的目的么？

“阿嶷夫人曰：‘最后的一句，好像是对于白璧德教授的一箭似的。’

“‘奇怪呀，’她的丈夫说。‘斯人也而有斯姓也……那一定是上帝的审判了。’”

不知道和原意可有错误，因为我是从日本文重译的。书的原名是《Mammon art》，在California的Pasadena作者自己出版，胃口相近的人们自己弄来看去罢。Mammon是希腊神话里的财神，art谁都知道是艺术。可以译作“财神艺术”罢。日本的译名是“拜金艺术”，也行。因为这一个字是作者生造的，政府既没有下令颁行，字典里也大概未曾注入，所以姑且在这里加一点解释。

**** 文学和出汗
     :PROPERTIES:
     :CUSTOM_ID: 19280114
     :END:


上海的教授對人講文學，以為文學當描寫永遠不變的人性，否則便不久長。例如英國，莎士比亞和別的一兩個人所寫的是永久不變的人性，所以至今流傳，其余的不這樣，就都消滅了雲。

這真是所謂“你不說我倒還明白，你越說我越胡塗”了。

英國有許多先前的文章不流傳，我想，這是總會有的，但竟沒有想到它們的消滅，乃因為不寫永久不變的人性。現在既然知道了這一層，卻更不解它們既已消滅，現在的教授何從看見，卻居然斷定它們所寫的都不是永久不變的人性了。

只要流傳的便是好文學，只要消滅的便是壞文學；搶得天下的便是王，搶不到天下的便是賊。莫非中國式的歷史論，也將溝通了中國人的文學論歟？

而且，人性是永久不變的麽？

類人猿，類猿人，原人，古人，今人，未來的人，……

如果生物真會進化，人性就不能永久不變。不說類猿人，就是原人的脾氣，我們大約就很難猜得著的，則我們的脾氣，恐怕未來的人也未必會明白。要寫永久不變的人性，實在難哪。

譬如出汗罷，我想，似乎於古有之，於今也有，將來一定暫時也還有，該可以算得較為“永久不變的人性”了。然而“弱不禁風”的小姐出的是香汗，“蠢笨如牛”的工人出的是臭汗。不知道倘要做長留世上的文字，要充長留世上的文學家，是描寫香汗好呢，還是描寫臭汗好？這問題倘不先行解決，則在將來文學史上的位置，委實是“岌岌乎殆哉”。

聽說，例如英國，那小說，先前是大抵寫給太太小姐們看的，其中自然是香汗多；到十九世紀後半，受了俄國文學的影響，就很有些臭汗氣了。那一種的命長，現在似乎還在不可知之數。

在中國，從道士聽論道，從批評家聽談文，都令人毛孔痙攣，汗不敢出。然而這也許倒是中國的“永久不變的人性”罷。

**** 「硬译」与「文学的阶级性」
     :PROPERTIES:
     :CUSTOM_ID: 19300301
     :END:

**一**

聽說《新月》月刊團體裏的人們在說，現在銷路好起來了。這大概是真的，以我似的交際極少的人，也在兩個年青朋友的手裏見過第二卷第六七號的合本。順便一翻，是爭“言論自由”的文字和小說居多。近尾巴處，則有梁實秋先生的一篇《論魯迅先生的“硬譯”》，以為“近於死譯”。而“死譯之風也斷不可長”，就引了我的三段譯文，以及在《文藝與批評》的後記裏所說：“但因為譯者的能力不夠，和中國文本來的缺點，譯完一看，晦澀，甚而至於難解之處也真多；倘將仂句拆下來呢，又失了原來的語氣。在我，是除了還是這樣的硬譯之外，只有束手這一條路了，所余的惟一的希望，只在讀者還肯硬著頭皮看下去而已”這些話，細心地在字旁加上圓圈，還在“硬譯”兩字旁邊加上套圈，於是“嚴正”地下了“批評”道：“我們‘硬著頭皮看下去’了，但是無所得。‘硬譯’和‘死譯’有什麽分別呢？”

新月社的聲明中，雖說並無什麽組織，在論文裏，也似乎痛惡無產階級式的“組織”，“集團”這些話，但其實是有組織的，至少，關於政治的論文，這一本裏都互相“照應”；關於文藝，則這一篇是登在上面的同一批評家所作的《文學是有階級性的嗎？》的余波。在那一篇裏有一段說：“……但是不幸得很，沒有一本這類的書能被我看懂。……最使我感得困難的是文字，……簡直讀起來比天書還難。……現在還沒有一個中國人，用中國人所能看得懂的文字，寫一篇文章告訴我們無產文學的理論究竟是怎麽一回事。”字旁也有圓圈，怕排印麻煩，恕不照畫了。總之，梁先生自認是一切中國人的代表，這些書既為自己所不懂，也就是為一切中國人所不懂，應該在中國斷絕其生命，於是出示曰“此風斷不可長”雲。

別的“天書”譯著者的意見我不能代表，從我個人來看，則事情是不會這樣簡單的。第一，梁先生自以為“硬著頭皮看下去”了，但究竟硬了沒有，是否能夠，還是一個問題。以硬自居了，而實則其軟如棉，正是新月社的一種特色。第二，梁先生雖自來代表一切中國人了，但究竟是否全國中的最優秀者，也是一個問題。這問題從《文學是有階級性的嗎？》這篇文章裏，便可以解釋。Proletary這字不必譯音，大可譯義，是有理可說的。但這位批評家卻道：“其實翻翻字典，這個字的涵義並不見得體面，據《韋白斯特大字典》，Proletary的意思就是：Acitizen of the lowest class who served the state not with property, but only by having children。……普羅列塔利亞是國家裏只會生孩子的階級！（至少在羅馬時代是如此）”其實正無須來爭這“體面”，大約略有常識者，總不至於以現在為羅馬時代，將現在的無產者都看作羅馬人的。這正如將Chemie譯作“舍密學”，讀者必不和埃及的“煉金術”混同，對於“梁”先生所作的文章，也決不會去考查語源，誤解為“獨木小橋”竟會動筆一樣。連“翻翻字典”（《韋白斯特大字典》！）也還是“無所得”，一切中國人未必全是如此的罷。

**二**

但於我最覺得有興味的，是上節所引的梁先生的文字裏，有兩處都用著一個“我們”，頗有些“多數”和“集團”氣味了。自然，作者雖然單獨執筆，氣類則決不只一人，用“我們”來說話，是不錯的，也令人看起來較有力量，又不至於一人雙肩負責。然而，當“思想不能統一”時，“言論應該自由”時，正如梁先生的批評資本制度一般，也有一種“弊病”。就是，既有“我們”便有我們以外的“他們”，於是新月社的“我們”雖以為我的“死譯之風斷不可長”了，卻另有讀了並不“無所得”的讀者存在，而我的“硬譯”，就還在“他們”之間生存，和“死譯”還有一些區別。

我也就是新月社的“他們”之一，因為我的譯作和梁先生所需的條件，是全都不一樣的。

那一篇《論硬譯》的開頭論誤譯勝於死譯說：“一部書斷斷不會完全曲譯……部分的曲譯即使是錯誤，究竟也還給你一個錯誤，這個錯誤也許真是害人無窮的，而你讀的時候究竟還落個爽快。”末兩句大可以加上夾圈，但我卻從來不幹這樣的勾當。我的譯作，本不在博讀者的“爽快”，卻往往給以不舒服，甚而至於使人氣悶，憎惡，憤恨。讀了會“落個爽快”的東西，自有新月社的人們的譯著在：徐誌摩先生的詩，沈從文，淩叔華先生的小說，陳西瀅（即陳源）先生的閑話，梁實秋先生的批評，潘光旦先生的優生學，還有白璧德先生的人文主義。

所以，梁先生後文說：“這樣的書，就如同看地圖一般，要伸著手指來尋找句法的線索位置”這些話，在我也就覺得是廢話，雖說猶如不說了。是的，由我說來，要看“這樣的書”就如同看地圖一樣，要伸著手指來找尋“句法的線索位置”的。看地圖雖然沒有看《楊妃出浴圖》或《歲寒三友圖》那麽“爽快”，甚而至於還須伸著手指（其實這恐怕梁先生自己如此罷了，看慣地圖的人，是只用眼睛就可以的），但地圖並不是死圖；所以“硬譯”即使有同一之勞，照例子也就和“死譯”有了些“什麽區別”。識得ABCD者自以為新學家，仍舊和化學方程式無關，會打算盤的自以為數學家，看起筆算的演草來還是無所得。現在的世間，原不是一為學者，便與一切事都會有緣的。

然而梁先生有實例在，舉了我三段的譯文，雖然明知道“也許因為沒有上下文的緣故，意思不能十分明了”。在《文學是有階級性的嗎？》這篇文章中，也用了類似手段，舉出兩首譯詩來，總評道：“也許偉大的無產文學還沒有出現，那麽我願意等著，等著，等著。”這些方法，誠然是很“爽快”的，但我可以就在這一本《新月》月刊裏的創作——是創作呀！——《搬家》第八頁上，舉出一段文字來——

“小雞有耳朵沒有？”

“我沒看見過小雞長耳朵的。”

“它怎樣聽見我叫它呢？”她想到前天四婆告訴她的耳朵是管聽東西，眼是管看東西的。

“這個蛋是白雞黑雞？”枝兒見四婆沒答她，站起來摸著蛋子又問。

“現在看不出來，等孵出小雞才知道。”

“婉兒姊說小雞會變大雞，這些小雞也會變大雞麽？”

“好好的餵它就會長大了，像這個雞買來時還沒有這樣大吧？”

也夠了，“文字”是懂得的，也無須伸出手指來尋線索，但我不“等著”了，以為就這一段看，是既不“爽快”，而且和不創作是很少區別的。

臨末，梁先生還有一個詰問：“中國文和外國文是不同的，……翻譯之難即在這個地方。假如兩種文中的文法句法詞法完全一樣，那麽翻譯還成為一件工作嗎？……我們不妨把句法變換一下，以使讀者能懂為第一要義，因為‘硬著頭皮’不是一件愉快的事，並且‘硬譯’也不見得能保存‘原來的精悍的語氣’。假如‘硬譯’而還能保存‘原來的精悍的語氣’，那真是一件奇跡，還能說中國文是有‘缺點’嗎？”我倒不見得如此之愚，要尋求和中國文相同的外國文，或者希望“兩種文中的文法句法詞法完全一樣”。我但以為文法繁復的國語，較易於翻譯外國文，語系相近的，也較易於翻譯，而且也是一種工作。荷蘭翻德國，俄國翻波蘭，能說這和並不工作沒有什麽區別麽？日本語和歐美很“不同”，但他們逐漸添加了新句法，比起古文來，更宜於翻譯而不失原來的精悍的語氣，開初自然是須“找尋句法的線索位置”，很給了一些人不“愉快”的，但經找尋和習慣，現在已經同化，成為己有了。中國的文法，比日本的古文還要不完備，然而也曾有些變遷，例如《史》《漢》不同於《書經》，現在的白話文又不同於《史》《漢》；有添造，例如唐譯佛經，元譯上諭，當時很有些“文法句法詞法”是生造的，一經習用，便不必伸出手指，就懂得了。現在又來了“外國文”，許多句子，即也須新造，——說得壞點，就是硬造。據我的經驗，這樣譯來，較之化為幾句，更能保存原來的精悍的語氣，但因為有待於新造，所以原先的中國文是有缺點的。有什麽“奇跡”，幹什麽“嗎”呢？但有待於“伸出手指”，“硬著頭皮”，於有些人自然“不是一件愉快的事”。不過我是本不想將“爽快”或“愉快”來獻給那些諸公的，只要還有若干的讀者能夠有所得，梁實秋先生“們”的苦樂以及無所得，實在“於我如浮雲”。

但梁先生又有本不必求助於無產文學理論，而仍然很不了了的地方，例如他說，“魯迅先生前些年翻譯的文學，例如廚川白村的《苦悶的象征》，還不是令人看不懂的東西，但是最近翻譯的書似乎改變風格了。”只要有些常識的人就知道：“中國文和外國文是不同的”，但同是一種外國文，因為作者各人的做法，而“風格”和“句法的線索位置”也可以很不同。句子可繁可簡，名詞可常可專，決不會一種外國文，易解的程度就都一式。我的譯《苦悶的象征》，也和現在一樣，是按板規逐句，甚而至於逐字譯的，然而梁實秋先生居然以為不能看懂者，乃是原文原是易解的緣故，也因為梁實秋先生是中國新的批評家了的緣故，也因為其中硬造的句法，是比較地看慣了的緣故。若在三家村裏，專讀《古文觀止》的學者們，看起來又何嘗不比“天書”還難呢。

**三**

但是，這回的“比天書還難”的無產文學理論的譯本們，卻給了梁先生不小的影響。看不懂了，會有影響，雖然好像滑稽，然而是真的，這位批評家在《文學是有階級性的嗎？》裏說：“我現在批評所謂無產文學理論，也只能根據我所能了解的一點材料而已。”這就是說：因此而對於這理論的知識，極不完全了。

但對於這罪過，我們（包含一切“天書”譯者在內，故曰“們”）也只能負一部分的責任，一部分是要作者自己的胡塗或懶惰來負的。“什麽盧那卡爾斯基，蒲力汗諾夫”的書我不知道，若夫“婆格達諾夫之類”的三篇論文和托羅茲基的半部《文學與革命》，則確有英文譯本的了。英國沒有“魯迅先生”，譯文定該非常易解。梁先生對於偉大的無產文學的產生，曾經顯示其“等著，等著，等著”的耐心和勇氣，這回對於理論，何不也等一下子，尋來看了再說呢。不知其有而不求曰胡塗，知其有而不求曰懶惰，如果單是默坐，這樣也許是“爽快”的，然而開起口來，卻很容易咽進冷氣去了。

例如就是那篇《文學是有階級性的嗎？》的高文，結論是並無階級性。要抹殺階級性，我以為最幹凈的是吳稚暉先生的“什麽馬克斯牛克斯”以及什麽先生的“世界上並沒有階級這東西”的學說。那麽，就萬喙息響，天下太平。但梁先生卻中了一些“什麽馬克斯”毒了，先承認了現在許多地方是資產制度，在這制度之下則有無產者。不過這“無產者本來並沒有階級的自覺。是幾個過於富同情心而又態度褊激的領袖把這個階級觀念傳授了給他們”，要促起他們的聯合，激發他們爭鬥的欲念。不錯，但我以為傳授者應該並非由於同情，卻因了改造世界的思想。況且“本無其物”的東西，是無從自覺，無從激發的，會自覺，能激發，足見那是原有的東西。原有的東西，就遮掩不久，即如格裏萊阿說地體運動，達爾文說生物進化，當初何嘗不或者幾被宗教家燒死，或者大受保守者攻擊呢，然而現在人們對於兩說，並不為奇者，就因為地體終於在運動，生物確也在進化的緣故。承認其有而要掩飾為無，非有絕技是不行的。

但梁先生自有消除鬥爭的辦法，以為如盧梭所說：“資產是文明的基礎”，“所以攻擊資產制度，即是反抗文明”，“一個無產者假如他是有出息的，只消辛辛苦苦誠誠實實的工作一生，多少必定可以得到相當的資產。這才是正當的生活鬥爭的手段。”我想，盧梭去今雖已百五十年，但當不至於以為過去未來的文明，都以資產為基礎。（但倘說以經濟關系為基礎，那自然是對的。）希臘印度，都有文明，而繁盛時俱非在資產社會，他大概是知道的；倘不知道，那也是他的錯誤。至於無產者應該“辛辛苦苦”爬上有產階級去的“正當”的方法，則是中國有錢的老太爺高興時候，教導窮工人的古訓，在實際上，現今正在“辛辛苦苦誠誠實實”想爬上一級去的“無產者”也還多。然而這是還沒有人“把這個階級觀念傳授了給他們”的時候。一經傳授，他們可就不肯一個一個的來爬了，誠如梁先生所說，“他們是一個階級了，他們要有組織了，他們是一個集團了，於是他們便不循常軌的一躍而奪取政權財權，一躍而為統治階級。”但可還有想“辛辛苦苦誠誠實實工作一生，多少必定可以得到相當的資產”的“無產者”呢？自然還有的。然而他要算是“尚未發財的有產者”了。梁先生的忠告，將為無產者所嘔吐了，將只好和老太爺去互相贊賞而已了。

那麽，此後如何呢？梁先生以為是不足慮的。因為“這種革命的現象不能是永久的，經過自然進化之後，優勝劣敗的定律又要證明了，還是聰明才力過人的人占優越的地位，無產者仍是無產者”。但無產階級大概也知道“反文明的勢力早晚要被文明的勢力所征服”，所以“要建立所謂‘無產階級文化’，……這裏面包括文藝學術”。

自此以後，這才入了文藝批評的本題。

**四**

梁先生首先以為無產者文學理論的錯誤，是“在把階級的束縛加在文學上面”，因為一個資本家和一個勞動者，有不同的地方，但還有相同的地方，“他們的人性（這兩字原本有套圈）並沒有兩樣”，例如都有喜怒哀樂，都有戀愛（但所“說的是戀愛的本身，不是戀愛的方式”），“文學就是表現這最基本的人性的藝術”。這些話是矛盾而空虛的。既然文明以資產為基礎，窮人以竭力爬上去為“有出息”，那麽，爬上是人生的要諦，富翁乃人類的至尊，文學也只要表現資產階級就夠了，又何必如此“過於富同情心”，一並包括“劣敗”的無產者？況且“人性”的“本身”，又怎樣表現的呢？譬如原質或雜質的化學底性質，有化合力，物理學底性質有硬度，要顯示這力和度數，是須用兩種物質來表現的，倘說要不用物質而顯示化合力和硬度的單單“本身”，無此妙法；但一用物質，這現象即又因物質而不同。文學不借人，也無以表示“性”，一用人，而且還在階級社會裏，即斷不能免掉所屬的階級性，無需加以“束縛”，實乃出於必然。自然，“喜怒哀樂，人之情也”，然而窮人決無開交易所折本的懊惱，煤油大王那會知道北京檢煤渣老婆子身受的酸辛，饑區的災民，大約總不去種蘭花，像闊人的老太爺一樣，賈府上的焦大，也不愛林妹妹的。“汽笛呀！”“列寧呀！”固然並不就是無產文學，然而“一切東西呀！”“一切人呀！”“可喜的事來了，人喜了呀！”也不是表現“人性”的“本身”的文學。倘以表現最普通的人性的文學為至高，則表現最普遍的動物性——營養，呼吸，運動，生殖——的文學，或者除去“運動”，表現生物性的文學，必當更在其上。倘說，因為我們是人，所以以表現人性為限，那麽，無產者就因為是無產階級，所以要做無產文學。

其次，梁先生說作者的階級，和作品無關。托爾斯泰出身貴族，而同情於貧民，然而並不主張階級鬥爭；馬克斯並非無產階級中的人物；終身窮苦的約翰孫博士，誌行吐屬，過於貴族。所以估量文學，當看作品本身，不能連累到作者的階級和身分。這些例子，也全不足以證明文學的無階級性的。托爾斯泰正因為出身貴族，舊性蕩滌不盡，所以只同情於貧民而不主張階級鬥爭。馬克斯原先誠非無產階級中的人物，但也並無文學作品，我們不能懸擬他如果動筆，所表現的一定是不用方式的戀愛本身。至於約翰孫博士終身窮苦，而誌行吐屬，過於王侯者，我卻實在不明白那緣故，因為我不知道英國文學和他的傳記。也許，他原想“辛辛苦苦誠誠實實的工作一生，多少必定可以得到相當的資產”，然後再爬上貴族階級去，不料終於“劣敗”，連相當的資產也積不起來，所以只落得擺空架子，“爽快”了罷。

其次，梁先生說，“好的作品永遠是少數人的專利品，大多數永遠是蠢的，永遠是和文學無緣”，但鑒賞力之有無卻和階級無幹，因為“鑒賞文學也是天生的一種福氣”，就是，雖在無產階級裏，也會有這“天生的一種福氣”的人。由我推論起來，則只要有這一種“福氣”的人，雖窮得不能受教育，至於一字不識，也可以賞鑒《新月》月刊，來作“人性”和文藝“本身”原無階級性的證據。但梁先生也知道天生這一種福氣的無產者一定不多，所以另定一種東西（文藝？）來給他們看，“例如什麽通俗的戲劇，電影，偵探小說之類”，因為“一般勞工勞農需要娛樂，也許需要少量的藝術的娛樂”的緣故。這樣看來，好像文學確因階級而不同了，但這是因鑒賞力之高低而定的，這種力量的修養和經濟無關，乃是上帝之所賜——“福氣”。所以文學家要自由創造，既不該為皇室貴族所雇用，也不該受無產階級所威脅，去做謳功頌德的文章。這是不錯的，但在我們所見的無產文學理論中，也並未見過有誰說或一階級的文學家，不該受皇室貴族的雇用，卻該受無產階級的威脅，去做謳功頌德的文章，不過說，文學有階級性，在階級社會中，文學家雖自以為“自由”，自以為超了階級，而無意識底地，也終受本階級的階級意識所支配，那些創作，並非別階級的文化罷了。例如梁先生的這篇文章，原意是在取消文學上的階級性，張揚真理的。但以資產為文明的祖宗，指窮人為劣敗的渣滓，只要一瞥，就知道是資產家的鬥爭的“武器”，——不，“文章”了。無產文學理論家以主張“全人類”“超階級”的文學理論為幫助有產階級的東西，這裏就給了一個極分明的例證。至於成仿吾先生似的“他們一定勝利的，所以我們去指導安慰他們去”，說出“去了”之後，便來“打發”自己們以外的“他們”那樣的無產文學家，那不消說，是也和梁先生一樣地對於無產文學的理論，未免有“以意為之”的錯誤的。

又其次，梁先生最痛恨的是無產文學理論家以文藝為鬥爭的武器，就是當作宣傳品。他“不反對任何人利用文學來達到另外的目的”，但“不能承認宣傳式的文字便是文學”。我以為這是自擾之談。據我所看過的那些理論，都不過說凡文藝必有所宣傳，並沒有誰主張只要宣傳式的文字便是文學。誠然，前年以來，中國確曾有許多詩歌小說，填進口號和標語去，自以為就是無產文學。但那是因為內容和形式，都沒有無產氣，不用口號和標語，便無從表示其“新興”的緣故，實際上也並非無產文學。今年，有名的“無產文學底批評家”錢杏邨先生在《拓荒者》上還在引盧那卡爾斯基的話，以為他推重大眾能解的文學，足見用口號標語之未可厚非，來給那些“革命文學”辯護。但我覺得那也和梁實秋先生一樣，是有意的或無意的曲解。盧那卡爾斯基所謂大眾能解的東西，當是指托爾斯泰做了分給農民的小本子那樣的文體，工農一看便會了然的語法，歌調，詼諧。只要看臺明·培特尼（DemianBednii）曾因詩歌得到赤旗章，而他的詩中並不用標語和口號，便可明白了。

最後，梁先生要看貨色。這不錯的，是最切實的辦法；但抄兩首譯詩算是在示眾，是不對的。《新月》上就曾有《論翻譯之難》，何況所譯的文是詩。就我所見的而論，盧那卡爾斯基的《被解放的堂·吉訶德》，法兌耶夫的《潰滅》，格拉特珂夫的《水門汀》，在中國這十一年中，就並無可以和這些相比的作品。這是指“新月社”一流的蒙資產文明的余蔭，而且衷心在擁護它的作家而言。於號稱無產作家的作品中，我也舉不出相當的成績。但錢杏邨先生也曾辯護，說新興階級，於文學的本領當然幼稚而單純，向他們立刻要求好作品，是“布爾喬亞”的惡意。這話為農工而說，是極不錯的。這樣的無理要求，恰如使他們凍餓了好久，倒怪他們為什麽沒有富翁那麽肥胖一樣。但中國的作者，現在卻實在並無剛剛放下鋤斧柄子的人，大多數都是進過學校的智識者，有些還是早已有名的文人，莫非克服了自己的小資產階級意識之後，就連先前的文學本領也隨著消失了麽？不會的。俄國的老作家亞歷舍·托爾斯泰和威壘賽耶夫，普理希文，至今都還有好作品。中國的有口號而無隨同的實證者，我想，那病根並不在“以文藝為階級鬥爭的武器”，而在“借階級鬥爭為文藝的武器”，在“無產者文學”這旗幟之下，聚集了不少的忽翻筋鬥的人，試看去年的新書廣告，幾乎沒有一本不是革命文學，批評家又但將辯護當作“清算”，就是，請文學坐在“階級鬥爭”的掩護之下，於是文學自己倒不必著力，因而於文學和鬥爭兩方面都少關系了。

但中國目前的一時現象，當然毫不足作無產文學之新興的反證的。梁先生也知道，所以他臨末讓步說，“假如無產階級革命家一定要把他的宣傳文學喚做無產文學，那總算是一種新興文學，總算是文學國土裏的新收獲，用不著高呼打倒資產的文學來爭奪文學的領域，因為文學的領域太大了，新的東西總有它的位置的。”但這好像“中日親善，同存共榮”之說，從羽毛未豐的無產者看來，是一種欺騙。願意這樣的“無產文學者”，現在恐怕實在也有的罷，不過這是梁先生所謂“有出息”的要爬上資產階級去的“無產者”一流，他的作品是窮秀才未中狀元時候的牢騷，從開手到爬上以及以後，都決不是無產文學。無產者文學是為了以自己們之力，來解放本階級並及一切階級而鬥爭的一翼，所要的是全般，不是一角的地位。就拿文藝批評界來比方罷，假如在“人性”的“藝術之宮”（這須從成仿吾先生處租來暫用）裏，向南面擺兩把虎皮交椅，請梁實秋錢杏邨兩位先生並排坐下，一個右執“新月”，一個左執“太陽”，那情形可真是“勞資”媲美了。

**五**

到這裏，又可以談到我的“硬譯”去了。

推想起來，這是很應該跟著發生的問題：無產文學既然重在宣傳，宣傳必須多數能懂，那麽，你這些“硬譯”而難懂的理論“天書”，究竟為什麽而譯的呢？不是等於不譯麽？

我的回答，是：為了我自己，和幾個以無產文學批評家自居的人，和一部分不圖“爽快”，不怕艱難，多少要明白一些這理論的讀者。

從前年以來，對於我個人的攻擊是多極了，每一種刊物上，大抵總要看見“魯迅”的名字，而作者的口吻，則粗粗一看，大抵好像革命文學家。但我看了幾篇，竟逐漸覺得廢話太多了。解剖刀既不中腠理，子彈所擊之處，也不是致命傷。例如我所屬的階級罷，就至今還未判定，忽說小資產階級，忽說“布爾喬亞”，有時還升為“封建余孽”，而且又等於猩猩（見《創造月刊》上的“東京通信”）；有一回則罵到牙齒的顏色。在這樣的社會裏，有封建余孽出風頭，是十分可能的，但封建余孽就是猩猩，卻在任何“唯物史觀”上都沒有說明，也找不出牙齒色黃，即有害於無產階級革命的論據。我於是想，可供參考的這樣的理論，是太少了，所以大家有些胡塗。對於敵人，解剖，咬嚼，現在是在所不免的，不過有一本解剖學，有一本烹飪法，依法辦理，則構造味道，總還可以較為清楚，有味。人往往以神話中的Prometheus比革命者，以為竊火給人，雖遭天帝之虐待不悔，其博大堅忍正相同。但我從別國裏竊得火來，本意卻在煮自己的肉的，以為倘能味道較好，庶幾在咬嚼者那一面也得到較多的好處，我也不枉費了身軀：出發點全是個人主義，並且還夾雜著小市民性的奢華，以及慢慢地摸出解剖刀來，反而刺進解剖者的心臟裏去的“報復”。梁先生說“他們要報復！”其實豈只“他們”，這樣的人在“封建余孽”中也很有的。然而，我也願意於社會上有些用處，看客所見的結果仍是火和光。這樣，首先開手的就是《文藝政策》，因為其中含有各派的議論。鄭伯奇先生現在是開書鋪，印Hauptmann和Gregory夫人的劇本了，那時他還是革命文學家，便在所編的《文藝生活》上，笑我的翻譯這書，是不甘沒落，而可惜被別人著了先鞭。翻一本書便會浮起，做革命文學家真太容易了，我並不這樣想。有一種小報，則說我的譯《藝術論》是“投降”。是的，投降的事，為世上所常有。但其時成仿吾元帥早已爬出日本的溫泉，住進巴黎的旅館了，在這裏又向誰去輸誠呢。今年，說法又兩樣了，在《拓荒者》和《現代小說》上，都說是“方向轉換”。我看見日本的有些雜誌中，曾將這四字加在先前的新感覺派片岡鐵兵上，算是一個好名詞。其實，這些紛紜之談，也還是只看名目，連想也不肯想的老病。譯一本關於無產文學的書，是不足以證明方向的，倘有曲譯，倒反足以為害。我的譯書，就也要獻給這些速斷的無產文學批評家，因為他們是有不貪“爽快”，耐苦來研究這些理論的義務的。

但我自信並無故意的曲譯，打著我所不佩服的批評家的傷處了的時候我就一笑，打著我的傷處了的時候我就忍疼，卻決不肯有所增減，這也是始終“硬譯”的一個原因。自然，世間總會有較好的翻譯者，能夠譯成既不曲，也不“硬”或“死”的文章的，那時我的譯本當然就被淘汰，我就只要來填這從“無有”到“較好”的空間罷了。

然而世間紙張還多，每一文社的人數卻少，誌大力薄，寫不完所有的紙張，於是一社中的職司克敵助友，掃蕩異類的批評家，看見別人來塗寫紙張了，便喟然興嘆，不勝其搖頭頓足之苦。上海的《申報》上，至於稱社會科學的翻譯者為“阿狗阿貓”，其憤憤有如此。在“中國新興文學的地位，早為讀者所共知”的蔣光Z先生，曾往日本東京養病，看見藏原惟人，談到日本有許多翻譯太壞，簡直比原文還難讀……他就笑了起來，說：“……那中國的翻譯界更要莫名其妙了，近來中國有許多書籍都是譯自日文的，如果日本人將歐洲人那一國的作品帶點錯誤和刪改，從日文譯到中國去，試問這作品豈不是要變了一半相貌麽？……”（見《拓荒者》也就是深不滿於翻譯，尤其是重譯的表示。不過梁先生還舉出書名和壞處，蔣先生卻只嫣然一笑，掃蕩無余，真是普遍得遠了。藏原惟人是從俄文直接譯過許多文藝理論和小說的，於我個人就極有裨益。我希望中國也有一兩個這樣的誠實的俄文翻譯者，陸續譯出好書來，不僅自罵一聲“混蛋”就算盡了革命文學家的責任。

然而現在呢，這些東西，梁實秋先生是不譯的，稱人為“阿狗阿貓”的偉人也不譯，學過俄文的蔣先生原是最為適宜的了，可惜養病之後，只出了一本《一周間》，而日本則早已有了兩種的譯本。中國曾經大談達爾文，大談尼采，到歐戰時候，則大罵了他們一通，但達爾文的著作的譯本，至今只有一種，尼采的則只有半部，學英德文的學者及文豪都不暇顧及，或不屑顧及，拉倒了。所以暫時之間，恐怕還只好任人笑罵，仍從日文來重譯，或者取一本原文，比照了日譯本來直譯罷。我還想這樣做，並且希望更多有這樣做的人，來填一填徹底的高談中的空虛，因為我們不能像蔣先生那樣的“好笑起來”，也不該如梁先生的“等著，等著，等著”了。

**六**

我在開頭曾有“以硬自居了，而實則其軟如棉，正是新月社的一種特色”這些話，到這裏還應該簡短地補充幾句，就作為本篇的收場。

《新月》一出世，就主張“嚴正態度”，但於罵人者則罵之，譏人者則譏之。這並不錯，正是“即以其人之道，還治其人之身”，雖然也是一種“報復”，而非為了自己。到二卷六七號合本的廣告上，還說“我們都保持‘容忍’的態度（除了‘不容忍’的態度是我們所不能容忍以外），我們都喜歡穩健的合乎理性的學說”。上兩句也不錯，“以眼還眼，以牙還牙”，和開初仍然一貫。然而從這條大路走下去，一定要遇到“以暴力抗暴力”，這和新月社諸君所喜歡的“穩健”也不能相容了。

這一回，新月社的“自由言論”遭了壓迫，照老辦法，是必須對於壓迫者，也加以壓迫的，但《新月》上所顯現的反應，卻是一篇《告壓迫言論自由者》，先引對方的黨義，次引外國的法律，終引東西史例，以見凡壓迫自由者，往往臻於滅亡：是一番替對方設想的警告。

所以，新月社的“嚴正態度”，“以眼還眼”法，歸根結蒂，是專施之力量相類，或力量較小的人的，倘給有力者打腫了眼，就要破例，只舉手掩住自己的臉，叫一聲“小心你自己的眼睛！”

**** 「喪家的」「資本家的乏走狗」
     :PROPERTIES:
     :CUSTOM_ID: 19300419
     :END:

梁實秋先生為了《拓荒者》上稱他為“資本家的走狗”，就做了一篇自雲“我不生氣”的文章。先據《拓荒者》第二期第六七二頁上的定義，“覺得我自己便有點像是無產階 級裏的一個”之後，再下“走狗”的定義，為“大凡做走狗的都是想討主子的歡心因而得到一點恩惠”，於是又因而發生疑問道——

“《拓荒者》說我是資本家的走狗，是那一個資本家，還是所有的資本家？我還不知道我的主子是誰，我若知道，我一定要帶著幾分雜誌去到主子面前表功，或者還許得到幾 個金鎊或盧布的賞賚呢。……我只知道不斷的勞動下去，便可以賺到錢來維持生計，至於如何可以做走狗，如何可以到資本家的帳房去領金鎊，如何可以到××黨去領盧布， 這一套本領，我可怎麽能知道呢？……”

這正是“資本家的走狗”的活寫真。凡走狗，雖或為一個資本家所豢養，其實是屬於所有的資本家的，所以它遇見所有的闊人都馴良，遇見所有的窮人都狂吠。不知道誰是它 的主子，正是它遇見所有闊人都馴良的原因，也就是屬於所有的資本家的證據。即使無人豢養，餓的精瘦，變成野狗了，但還是遇見所有的闊人都馴良，遇見所有的窮人都狂 吠的，不過這時它就愈不明白誰是主子了。

梁先生既然自敘他怎樣辛苦，好像“無產階級”（即梁先生先前之所謂“劣敗者”），又不知道“主子是誰”，那是屬於後一類的了，為確當計，還得添幾個字，稱為“喪家 的”“資本家的走狗”。

然而這名目還有些缺點。梁先生究竟是有智識的教授，所以和平常的不同。他終於不講“文學是有階級性的嗎？”了，在《答魯迅先生》那一篇裏，很巧妙地插進電桿上寫“ 武裝保護蘇聯”，敲碎報館玻璃那些句子去，在上文所引的一段裏又寫出“到××黨去領盧布”字樣來，那故意暗藏的兩個×，是令人立刻可以悟出的“共產”這兩字，指示 著凡主張“文學有階級性”，得罪了梁先生的人，都是在做“擁護蘇聯”，或“去領盧布”的勾當，和段祺瑞的衛兵槍殺學生，《晨報》卻道學生為了幾個盧布送命，自由大 同盟上有我的名字，《革命日報》的通信上便說為“金光燦爛的盧布所買收”，都是同一手段。在梁先生，也許以為給主子嗅出匪類（“學匪”），也就是一種“批評”，然 而這職業，比起“劊子手”來，也就更加下賤了。

我還記得，“國共合作”時代，通信和演說，稱贊蘇聯，是極時髦的，現在可不同了，報章所載，則電桿上寫字和“××黨”，捕房正在捉得非常起勁，那麽，為將自己的論 敵指為“擁護蘇聯”或“××黨”，自然也就髦得合時，或者還許會得到主子的“一點恩惠”了。但倘說梁先生意在要得“恩惠”或“金鎊”，是冤枉的，決沒有這回事，不 過想借此助一臂之力，以濟其“文藝批評”之窮罷了。所以從“文藝批評”方面看來，就還得在“走狗”之上，加上一個形容字：“乏”。

**** 新月社批評家的任務
     :PROPERTIES:
     :CUSTOM_ID: 19300101
     :END:

新月社中的批評家，是很憎惡嘲罵的，但只嘲罵一種人，是做嘲罵文章者。新月社中的批評家，是很不以不滿於現狀的人為然的，但只不滿於一種現狀，是現在竟有不滿於現狀者。

這大約就是「即以其人之道，還治其人之身」，揮淚以維持治安的意思。

譬如，殺人，是不行的。但殺掉「殺人犯」的人，雖然同是殺人，又誰能說他錯？打人，也不行的。但大老爺要打鬥毆犯人的屁股時，皂隸來一五一十的打，難道也算犯罪麼？新月社批評家雖然也有嘲罵，也有不滿，而獨能超然於嘲罵和不滿的罪惡之外者，我以為就是這一個道理

但老例，劊子手和皂隸既然做了這樣維持治安的任務，在社會上自然要得到幾分的敬畏，甚至於還不妨隨意說幾句話，在小百姓面前顯顯威風，只要不大妨害治安，長官向來也就裝作不知道了

現在新月社的批評家這樣盡力地維持了治安，所要的卻不過是「思想自由」，想想而已，決不實現的思想。而不料遇到了別一種維持治安法，竟連想也不准想了。從此以後，恐怕要不滿於兩種現狀了罷。


**** 卢梭论女子教育
     :PROPERTIES:
     :CUSTOM_ID: 19271101
     :AUTHOR:   梁实秋
     :END:

商务印书馆出版的卢梭杰作《爱弥尔》的中文译本序言里有下列一段话：

#+BEGIN_QUOTE
……本书的第五编即女子教育，他的主张非但不澈底：而且不承认女子的人格，和前四编的尊重人类相矛盾；此实感染千千余年来底潜势。虽遇天才，也不免受些影响呢。所以今日看来，他对于人类正当的主张，可说只树得一半……
#+END_QUOTE

我的意思稍微有点不同。我觉得本书第五编即女子教育，他的主张非但极澈底，而且是尊重女子的人格，和前四编的尊重人类前后一贯；此实足矫正近年来男女平等的学说，非遇天才曷克臻此？所以在今日看来，他在教育学说上所造的孽，可说只造得一半。…

卢梭论教育，无一是处，唯其论女子教育，的确精当。卢梭论女子教育是根据于男女的性质与体格的差别而来。他说：“男子和女子，因为他们的性质和体格不同，所以他们的教育也不能相同。”谁能承认男子和女人没有分别？如其教育是因人而设的，那么女子自然应有女子的教育。

近代生物学和心理学研究的结果，证明不但男子和女人是有差别的，就是男子和男子，女人和女人，又有差别。简而言之，天下就没有两个人是无差别的。什么样的人应该施以什么样的教育。

我觉得“人”字根本的该从字典里永远注销，或由政府下令永禁行使。因为“人”字的意义太糊涂了。聪明绝顶的人，我们叫他做人，蠢笨如牛的人，也一样的叫做人，弱不禁风的女子，叫做人，粗横强大的男人，也叫做人，人里面的三流九等，无一非人。近代的德谟克拉西的思想，平等的观念，其起源即由于不承认人类的差别。近代所谓的男女平等运动，其起源即由于不承认男女的差别。人格是一个抽象名词，是一个人的身心各方面的特点的总和。人的身心各方面的特点既有差别，实即人格上亦有差别。所谓侮辱人格者，即是不承认一个人特有的人格，卢梭承认女子有女子的人格，所以卢梭正是尊重女子的人格。抹杀女子所特有之特性者，才是侮辱女子人格。

男女平等的观念之影响于近代女子教育趋势者，至大且深。现代女子教育最显著的趋势，就是，把女子训练得愈像男子愈好。这样的教育，是否徒劳而无功，很是一疑问。卢梭说：“女人像一个女人，是好的，像一个男人，就不好。所以女人如养成她做女人的特性，那是正当的事情。但若要夺男子的威权，那么无论在什么地方，都将落后于男子。”（中译本第二三五页）现代时髦的女子，可以抽烟，可以比赛足球，可以做参议员，可以做省长，可以做任何男子可以做的事。即使女子做这些事可以比男子还做得好，但是她已失去了她的女子的特性。正当的女子教育应该是使女子成为完全的女子。

教育的范围很广，不仅指学校里的生活，更不仅书本上的训练，举凡一切身心各方面的发展，都在教育的范围以内。卢梭所最仰慕的女子教育是希腊的女子教育。希腊女子在结婚前注意身体的优美的发展，“不知男儿同队伍，而常现于公众的面前。差不多没有一个祝日，牺牲日，巡行日等。没有少女队或市长的少女队加入的时候。这般女人，戴花冠，唱圣诗，合成舞蹈的合唱，而携带蓝瓶献物等出外的游行，见者惝恍……”“但希腊的女人到结婚之后，便从公众生活隐退，而围于自己家庭四壁之中，埋于家事，为夫做事。这个是适于自然和理论女子底职分。”卢梭认定理家为女子分内的事，这在现今妇女运动家看来，直是谬误的思想。

卢梭说：“在法兰西，少女蛰居于家内，而妻反出行于世间。在古时正相反对；女子任意的游行，也有出行于公会的，结婚的妇女，隐居于家内。此种古风，比现代的为合理，且适合于维持社会道德。结婚前的少女可有一种娇爱术，她们的大部的时业，在于娱乐。但做了妻，必须为家庭的周旋，没有求夫的必要，所以当着实的去做事。”（第二五七页）为预备做妻起见，女子在婚前也不可不有相当的准备。卢梭主张女子教育应该注重女子服从心之养成，及柔和的性格。“男孩可使他尽量的吃饱，而女孩这样是不行的。”卢梭以为女孩处处都该受些束缚节制。

最后，卢梭认定女子到了适当的年龄是要结婚的，这是自然的法则，不可避免的。所以卢梭在《爱弥尔》的篇末一再的叮咛苏菲亚以配偶的选择。令女子有适当选择配偶的眼光与能力，乃是女子教育的很重要的一部分。现在的女子教育的趋势似乎有些注重女子经济独立的预备，驯致现代独身的女子一天比一天多，这实在是一件极不自然的事，也可说是现代女子教育的一点缺憾。

卢梭的根本哲学是“自然主义”。他论《爱弥尔》的教育一尚自然，论苏菲亚的教育固仍以“自然”为指归。卢梭主张平等，但是卢梭并不否认“自然的不平等”。此种思想已于其《民约论》及《不平等起源论》中见之。我们若从自然主义方面观察，则卢梭之论女子教育固与其向来主张一贯，毫无矛盾。今人喜欢卢梭的平等论，但大半的人并不如卢梭讲得那么彻底，凡卢梭学说之合吾人胃口者则容纳之，且从而宣扬之，其真有精采如论女子一章，反被世人轻视。卢梭讲平等论的时候，只要心目中不忘了“自然的不平等”，他的平等论便是最有价值的。自然的不平等，是件事实。卢梭之论女子教育，就是没有撇开事实的理论。承认男女的差别，便是承认自然的一部分。卢梭的女子教育论是卢梭的自然主义中最健全的一部，也是卢梭平等论中最难得的一个例外。从平等论方面观察，他的论女子教育，容或与他平素主张少有出入，从自然主义方面观察，则是顺理，成章，毫无矛盾。

**** 论批评的态度
     :PROPERTIES:
     :CUSTOM_ID: 19270719
     :AUTHOR:   梁实秋
     :END:

批评就是判断：批评者就是判断者。批评者在从事批评的时候有两点要注意：第一，是批评的根据；第二，是批评的态度。

所谓批评的根据，就是说，自己先要有一套的主张，自己先要确立自己的根本思想，然后再根据这个固定的出发点来衡量一切。批评者当然要以同情的态度来了解别人的思想和主张，但是他自己必须先认清自己的观察点，然后他的批评才能一贯，才有力量，才能令人懂。这就如同法院的审判官开庭审案一样，判官固然应该极力的了解被审者的言行，并且透澈的观察被审者的动机，但是最要紧的还是法官背后的那一套固定的法。没有法律，法官靠什么来定案呢？同样，批评者若是没有固定的思想主张，那么根据什么来批评呢？文学批评与法院审案不同的地方也是有的——法律是只有一套，批评的思想和主张则不只一端；法官是只有少数人做的，批评者则限制较宽，凡是有思想主张做根据的人全可以从事批评。然而根本的“判断的”的精神是一样的。

批评的态度另是一件事。但是有批评根据的批评者，他的态度也必是不会错的。惟独自己没有主张没有思想而要妄事批评的人，他们的态度最成问题。我这篇文章就是专要讨论批评者的态度的问题，关于批评的学说理论这里都不提起，为的是免除枝节。

批评的态度之最高的理想，说起来很简单，只是“严正”二字。然而这就不容易做到。现在流行的批评文字，真是五花八门，归纳起来，大概都是同“严正”的理想背道而驰的。一般的专事破坏以毁谤为目的的文字，固然不值得谈起，但是“不严正”的态度已经流传得很广，自命为“以忠实的态度力求对于国内新文化有所贡献的刊物”，以及自命为“思想界文艺界知名的先进作者”和“努力的青年”，有时也不能免于“不严正”。我现在把近来看见的批评文字中之不严正处标出几项来谈谈。

凡是“极有研究的价值”的“精到的批评”似乎不应该以专说俏皮话为能事，不应该不负责任的“胡凑”了事。说俏皮话，近来已成为风气了，其原因不外这几项：第一，在所谓“思想界文艺界知名的先进作者”当中，颇有几位能写一点幽默而讽刺的文章，这样文章当然有趣，当然令人爱读，于是“一些努力的青年”群起而模仿。其实，幽默而刺讽的文章是很不容易写的，大概也必要有这种天才的人才能写得好罢？我觉得中国人比较的不大能领略幽默讽刺，恶声相骂才是中国人的擅长。一般的中国人近来在各方面部太放肆，而要写幽默讽刺的文章绝对放肆不得。所以这种文章不是人人能尝试的。然而一般人偏要尝试，结果是无数无数的粗糙叫嚣的文字出现。说俏皮话，若是说很有趣，至少还可博得读者一笑。若是说得并不见好，那就只能令人难受了。俏皮话若是少说几句，还可算是文章上的一种点缀，若是连篇累牍的都是俏皮话，只有令人生厌而已。第二个原因是，一般青年对于现状不满因而都有一种激愤烦躁的心情，不知不觉的流露在文字里面，以说几句尖酸刻薄的俏皮话为发泄心里忧愤的方法。现在这个时代，你说是革命的罢，又像不是在革命；你说是不革命的罢，大家又都说是革命的。所谓“一些努力的青年”将何去何从，不能不兴徨之感了。“努力的青年”大概是要“血淋淋”的去实行革命的，可是他们在没革命的时候在纸面上也“血淋淋”了！有些人竟以“血淋淋”的说几句刻薄话便算得是“努力的青年”，其实这样就叫努力，还是不努力罢！只图一时口快，怎能就算革命，怎能令人信任，怎能“对于国内新文化有所贡献”呢？“先进作者”应该尽些责任领导领导“努力的青年”，教他们真做些“有所贡献”的事，莫把有用的精力浪费在无用的路上来“耗费印刷工人和几个读者的时间”。第三个原因是，专说下流的俏皮话的文章容易作。用严正的态度写几千字，多少要费一番思索；而截取别人的文章拿来断章取义的东打一拳西踢一脚，这是最容易不过的事。大学读过一两年书的人，白话文大概还可以写得通，提起笔来“胡凑”几千字，自然是有利可图的事，不过以这种态度来写的批评文字，绝对不能令人心服，不能令人信任，只是自己暴露自己的劣性而已。俏皮话若说得好顶多不过是有趣，若说得既不能令人痛又不能令人痒，还是不说了罢。

近来一般人批评态度的不严正，在另一方面又显露出来。似乎很有人把批评文字和攻击个人不能分开。要攻击个人也可以，索兴直爽的开列十项二十项罪状，若是不嫌涉讼，还可多说几句侮辱的话，但是千万不必说这是“精到的批评”。批评的文字要专从文章上着眼。某人是Gentleman，某人是流氓，某人是教授，某人是共产党人，某人是留学生，某人是大学生，某人是资产阶级，某人是无产阶级，——这都与他们的文字无关。文章好的便是好的，对的便是对的；你的朋友若是错了，你不必回护；你的敌人（或你的敌人的朋友）若是并不错，你也不能不公允的批评。文人相轻，这话并不假，可惜专靠了相轻，并不能就成为文人！不知为什么这个时代有这样多的变态现象？专从近一的批评文字讲，几乎处处表现出猜忌的态度，inferioritycomplex根深蒂固的盘据了堕落的青年的心，总以为别人占了优越的地位来压迫自己，以为别人是成群结伙有组织的来压迫自己。别人只消触动他一根毫毛，他便撒娇打滚的暴躁如雷；没人理会他，他也要设法找出一个对象来放刁。这是疯狂。

还有一种态度，也是不严正的，那便是专在字句上小的地方挑剔而不在根本思想上讨论，写出文章来是枝枝节节的“胡凑”了事。严正的批评者不肯浪费笔墨的，绝不肯在枝节上累赘。讲到这一点，大概是个人的艺术上的修养的问题了。近来的写文章的人似乎不知道“简练”的可贵，好像谁写的文章长便算是谁的理由足！文章太长，必定废话多，必定枝节多，使读者不能得到单纯的印象。我们理想中的批评文字，是要雅洁短练的文字。

“我们感到这沉沦的出版界里有提倡真正的批评之必要”，但是我们更感到，要提倡“真正的批评”，先要懂得什么叫做批评，然后才有资格来“提倡”。现在提倡的人太多了，实行的人太少了一些。“真正的批评”决不是下流的俏皮话“胡凑”起来的。态度不纠正，“真正的批评”永远不会实现。

**** 文学是有阶级性的吗？
     :PROPERTIES:
     :AUTHOR:   梁实秋
     :CUSTOM_ID: 19290901
     :END:

**一**

卢梭说：“资产是文明的基础。”但是卢梭也是最先攻击资产制度的一个人，因为他以为文明是罪恶的根源。所以攻击资产制度，即是反抗文明。有了资产然后才有文明，有了文明然后资产才能稳固。不肯公然反抗文明的人，决没有理由攻击资产制度。

资产制度有时可以造成不公平的现象，我们承认。资产的造成本来是由于人的聪明才力，所以资产本来是人的身心劳动的报酬；但是资产成为制度以后，往往富者愈富，贫者愈贫，富者不一定就是聪明才力过人者；贫者也不一定是聪明才力不如人者，这种人为的不公平的现象是有的。可是我们对于这种现象要冷静的观察。人的聪明才力既不能平等，人的生活当然是不能平等的，平等是个很美的幻梦，但是不能实现的。经济是决定生活的最要紧的原素之一，但是人类的生活并不是到处都受经济的支配，资本家不一定就是幸福的，无产者也常常自有他的乐趣。经济的差别虽然是显著的，但不是永久的，没有聪明才力的人虽然能侥幸得到资产，但是他的资产终于是要消散的，真有聪明才力的人虽然暂时忍受贫苦，但是不会长久埋没的，终久必定可以赢得相当资产。所以我们充分的承认资产制度的弊病，但是要拥护文明，便要拥护资产。

无产者本来并没有阶级的自觉。是几个过于富同情心而又态度偏激的领袖把这个阶级观念传授了给他们。阶级的观念是要促起无产者的联合，是要激发无产者的争斗欲念。一个无产者假如他是有出息的，只消辛辛苦苦诚诚实实的工作一生，多少必定可以得到相当的资产。这总是正当的生活争斗的手段。但是无产者联合起来之后，他们是一个阶级了，他们要有组织了，他们是一个集团了，于是他们便不循常轨的一跃而夺取政权，一跃而为统治阶级。他们是要报复！他们唯一的报复的工具就是靠了人多势众。“多数”“群众”“集团”这些就是无产阶级的暴动的武器。

无产阶级的暴动的主因是经济的。旧日统治阶级的窳败，政府的无能，真的领袖的缺乏，也是促成无产阶级的起来的原因。这种革命的现象不能是永久的，经过自然进化之后，优胜劣败的定律又要证明了，还是聪明才力过人的人占优越的位置，无产者仍是无产者。文明依然是要进化的。无产阶级大概也知道这一点，也知道单靠了目前经济的满足并不能永久的担保这个阶级的胜利。反文明的势力早晚还是要被文明的势力所征服的。所以无产阶级近来于高呼“打倒资本家”之外又有了新的工作，他们要建立所谓“无产阶级的文化”或“普罗列塔利亚的文化”，这里面包括文学艺术。

“普罗列塔利亚的文学”！多么崭新的一个名词。“普罗列塔利亚”这个名字并不新，是Proletariat的译音，不认识这个外国字的人听了这个中文的译音，难免不觉得新颖。新的当然就是好的，于是大家都谈起“普罗列塔利亚的文学”，其实翻翻字典，这个字的涵义并不见得体面，据韦白斯特大字典，Proletary的意思就是：Acitizen of the lowest class who serves the state not with property，but only by having children. 一个属于“普罗列塔利亚”的人就是“国家里最下阶级的国民，他是没有资产的，他向国家服务只是靠了生孩子”。普罗列塔利亚是国家里只会生孩子的阶级！（至少在罗马时代是如此）我看还是称做“无产阶级的文学”来得明白，比较的不像一个符咒。

无产阶级的运动是由政治的经济的更进而为文化的运动了，这是值得注意的一件事。我看近来在文学方面的宣传文字，似乎是有组织的有联络的，一方面宣传无产阶级的文学的理论，一方面攻击他们所认为是“资产阶级的文学”。无产阶级有他们的“科学的政治学”，“辩证法的唯物论”，“马克思的经济学”，现在又多出了一个“科学的艺术学”，一个“普罗列塔利亚的文学”！

我现在要彻底的问：文学是有阶级性的吗？

**二**

无产阶级文学理论方面的书翻成中文的我已经看见约十种了，专门宣传这种东西的杂志，我也看了两三种。我是想尽我的力量去懂他们的意思，但是不幸的很，没有一本这类的书能被我看得懂。内容深奥，也许是；那么便是我的学力不够。但是这一类宣传的书，如卢那卡尔斯基，蒲力汗诺夫，波格达诺夫之类，最使我感到困难的是文字。其文法之艰涩，句法之繁复，简直读起来比读天书还难。宣传无产文学理论的书而竟这样的令人难懂，恐怕连宣传品的资格都还欠缺，现在还没有一个中国人，用中国人所能看得懂的文字，写一篇文章告诉我们无产文学的理论究竟是怎样一回事。我现在批评所谓无产文学理论，也只能根据我所能了解的一点点的材料而已。

假定真有所谓“无产阶级的文学”这样一种东西，我们觉得这样的文学一定要有三个条件：

* （一）这种文学的题材应该以无产阶级的生活为主体，表现无产阶级的情感思想，描写无产阶级的生活的实况，赞颂无产阶级的伟大。
* （二）这种文学的作者一定是属于无产阶级或是极端同情于无产阶级的人。
* （三）这种文学不是为少数人（有资产的少数人，受过高等教育的少数人）看的，而是为大多数的劳工劳农及所谓无产阶级的人看的。

假如这三个条件拟得不错，我们还要追加上一个附带条件，上列三点必须同时具备才能成为无产文学，缺一而不可的。但是我们立刻就可发现这种理论的错误。错误在哪里？错误在把阶级的束缚加在文学上面。错误在把文学当做阶级斗争的工具而否认其本身的价值。

文学的国土是最宽泛的，在根本上和在理论上没有国界，更没有阶级的界限。一个资本家和一个劳动者，他们的不同的地方是有的，遗传不同，教育不同，经济的环境不同，因之生活状态也不同，但是他们还有同的地方。他们的人性并没有两样，他们都感到生老病死的无常，他们都有爱的要求，他们都有怜悯与恐怖的情绪，他们都有伦常的观念，他们都企求身心的愉快。文学就是表现这最基本的人性的艺术。无产阶级的生活的苦痛固然值得描写，但是这苦痛如其真是深刻的必定不是属于一阶级的。人生现象有许多方面都是超于阶级的。例如，恋爱（我说的是恋爱的本身，不是恋爱的方式）的表现，可有阶级的分别吗？例如，歌咏山水花草的美丽，可有阶级的分别吗？没有的。如其文学只是生活现象的外表的描写，那么，我们可以承认文学是有阶级性的，我们也可以了解无产文学是有它的理论根据；但是文学不是这样肤浅的东西，文学是从人心中最深处发出来的声音。如其“烟囱呀！”“汽笛呀！”“机轮呀！”“列宁呀！”便是无产文学，那么无产文学就用不着什么理论，由它自生自灭罢。我以为把文学的题材限于一个阶级的生活现象的范围之内，实在是把文学看得太肤浅太狭隘了。

文学家就是一个比别人感情丰富感觉敏锐想像发达艺术完美的人。他是属于资产阶级或无产阶级，这于他的作品有什么关系？托尔斯泰是出身贵族，但是他对于平民的同情真可说是无限量的，然而他并不主张阶级斗争；许多人奉为神明的马克思，他自己并不是什么无产阶级中的人物；终身穷苦的约翰孙博士，他的志行高洁吐属文雅比贵族还有过无不及。我们估量文学的性质与价值，是只就文学作品本身立论，不能连累到作者的阶级和身份。一个人的生活状况对于他的创作自然不能说没有影响，可是谁也不能肯定的讲凡无产阶级文学必定是无产阶级的人才能创作。

文学家创作之后当然希望一般人能够懂他，并且懂的人越多越好。但是，假如一部作品不能为大多数人所能了解，这毛病却不一定是在作品方面，而时常是大多数人自己的鉴赏的能力缺乏。好的作品永远是少数人的专利品，大多数永远是蠢的永远是与文学无缘的。不过鉴赏力之有无却不与阶级相干，贵族资本家尽有不知文学为何物者，无产的人也尽有赏鉴文学者。创造文学固是天才，鉴赏文学也是天生的一种福气。所以文学的价值决不能以读者数目多寡而定。一般劳工劳农需要娱乐，也许需要少量的艺术的娱乐，例如什么通俗的戏剧、电影、侦探小说之类。为大多数人读的文学必是逢迎群众的，必是俯就的，必是浅薄的；所以我们不该责令文学家来做这种的投机买卖。文学要在理性范围之内自由的创造，要忠于他自己的理想与观察，他所企求的是真，是美，是善。他不管世界上懂他的人是多数还是少数。皇室贵族雇用一班无聊文人来做讴功颂德的诗文，我们觉得讨厌，因为这种文学是虚伪的假造的；但是在无产阶级威胁之下便做对于无产阶级讴功颂德的文学，还不是一样的虚伪讨厌？文学家只知道聚精会神的创作，不能有时候考虑他的读者能有多少。真的文学家并不是人群中的寄生虫，他不能认定贵族资本家是他的主雇，他也不能认定无产阶级是他的主雇。谁能了解他，谁便是他的知音，不拘他是属于哪一阶级。文学是属于全人类的。我们希望人类中能了解文学的越来越多，但是我们不希望文学的质地降低了来俯就大多数的人。

无产文学理论家时常告诉我们，文艺是他们的斗争的“武器”。把文学当做“武器”！这意思很明白，就是说把文学当做宣传品，当做一种阶级斗争的工具。我们不反对任何人利用文学来达到另外的目的，这与文学本身无害的，但是我们不能承认宣传式的文字便是文学。例如，集团的观念是无产阶级革命家所最宝贵的一件东西，无产阶级的暴动最注重的就是组织，没有组织就没有力量，所以号称无产文学者也就竭力宣传这一点，竭力抑止个人的情绪的表现，竭力的鼓吹整个的阶级的意识。以文学的形式来做宣传的工具当然是再妙没有，但是，我们能承认这是文学吗？即使宣传文字果有文学意味，我们能说宣传作用是文学的主要任务吗？无产文学理论家说文学是武器，这句话虽不合理，却是一句老实话，足以暴露无产文学之根本的没有理论根据。

**三**

从文艺史上观察，我们就知道一种文艺产生不是由于几个理论家的摇旗呐喊便可成功，必定要有力量的文学作品来证明其自身的价值。无产文学的声浪很高，艰涩难懂的理论书也出了不少，但是我们要求给我们几部无产文学的作品读读。我们不要看广告，我们要看货色。我们但愿货色比广告所说的还好些。

我现在抄两首诗给大家看看：第一首诗题目是给一个新同志，作者是俄国的撒莫比特尼克，是从波格达诺夫的新艺术论里抄下来的。

#+BEGIN_EXAMPLE
看那旋转着的轮子，
看那在这儿舞蹈的疯狂的皮带……
同志，同志，不要怕！
让钢铁的混沌震响着，
虽然它底许多火是沉溺了
被眼泪底苦海所熄了……
不要怕，你已经从安静的地方，
和平的乡间和清爽的溪流边来了。
同志，同志，不要怕！
这儿无限是有了限止，
不可能的事情发生了……
这是未来的时代底黎明——
不要怕！
波浪底起水沫的冠毛震响着，
带了我们的幸运前来……
在我们底黑暗又惨淡的王国上，
一个新的太阳照下来，
比从前燃烧得更光明——
不要怕！
像一个雕在石上的巨人，
站在疯狂的皮带边把舵……
让轮子继续转下去，
现在行列是拉得更接近了——
你是熔在这里面的一个新的连系——
不要怕！
#+END_EXAMPLE

这是不是文学？是不是好的文学？请读者自己公正的品评罢。但是波格达诺夫先生对于这首诗的评语是：“在这首诗里，引起我们底注意的并不是技巧，最惊人的却是内容的纯粹。我觉得在感情和思想上，比这个更无产阶级的是没有的了。”

再引一首马林霍夫先生的十月，是从郭沫若译的新俄诗选里抄出来的。

#+BEGIN_EXAMPLE
我们把人伦的信条蹂躏，
帽子要顶在头上，
两脚要踏在棹子的当心。
你们不喜欢我们，
自从我们以流血为大笑，
自从我们不再洗浣那洗了万遍的褴褛的布条，
自从我们敢：王八蛋哟！这震耳的大叫。
是的，先生，这条脊骨，
俨如电话杆那般的直挺，

但不只区区一人，全露西亚人的脊骨，
已屈服了许多年辰。
地球，谁还比我们叫的大声？
你说：满院的疯人——
没有路标——没有火把——鬼闯鬼挺——。
礼拜堂的廊下，我们红色的跳舞几多光荣。
甚么，你不信？这儿有游牧的人群，
云彩的牧畜听从人的指挥，
青天如像一件女人的衣裳，
太阳也失掉了他的光威。
基督又钉在十字架上，巴拉巴司，
我们细嚼的护送着，送到退尔司柯依……
谁要来干涉，呀谁？这西叙亚的奔马？
提琴弹着马赛歌的音调？
这样的事情你从前曾经听过。
为地球打钢镯的铁匠，
要鹰扬的抽他粗糙的淡巴菰，
就和时常骑马的军官一样？
你问——这一下呢？
这一下要跳舞许多世纪。
我们敲遍处处的家，
不会再听见：王八蛋，滚开去！
我们！我们！我们随处都在：
在足光的面前在辉煌的舞台，
不是细腻的抒情诗人，
而是激昂的丑怪。
垃圾堆，把一切垃圾都堆成堆，
像萨服那洛拉，伴着颂主的歌声，
送入火中——我们怕谁？
灵魂纤弱的人造人已经成为了——世界。
我们的每天，都是圣经的新的篇章，
每页在千百代中都是伟大。
我们今要被后人称颂：
他们幸福者，生在一九一七年的年代。
而你们却还在大骂：该死的奴才？
你们依然在无限的悲啼。
蠹东西！不是昨天粉碎了，
像被汽车房中突然驰出的汽车，
压死了的一只鸽子？
#+END_EXAMPLE

这首诗恐怕是真正的无产文学了？题目是“十月”，而里面的词藻是何等的“无产阶级的”呀！也许伟大的无产文学还没有出现，那么我愿意等着，等着，等着。

**四**

文学界里本来已有了不少的纷争，无产文学呼声起来之后又添了一种纷争，因为无产文学家要攻击所谓资产阶级的文学。什么是资产阶级的文学，我实在是不知道；大概除了无产文学运动那一部分的文学以外，古今中外的文学都可以算做资产阶级文学罢。我们承认这个名词，我们也不懂资产阶级的文学为什么就要受攻击？是为里面没有马克思主义，唯物史观，阶级斗争？文学为什么一定要有这些东西呢？攻击资产阶级文学是没有理由的，等于攻击无产阶级文学一样的无理由，因为文学根本没有阶级的区别。假如无产阶级革命家一定要把他的宣传文字唤做无产阶级文学，那总算是一种新兴文学，总算是文学国土里的新收获，用不着高呼打倒资产的文学来争夺文学的领域，因为文学的领域太大了，新的东西总有它的位置的。假如无产阶级可以有“无产文学”，我也不懂资产阶级为什么便不可有“资产文学”？资产阶级不消灭，资产阶级的文学也永远不会被击倒的，文明一日不毁坏，资产也一日不会废除的。

无产文学家攻击资产文学的力量实在也是薄弱的很，因为他们只会用几个标语式口号式的名词来咒人，例如“小资产阶级”，“有闲阶级”，“绅士阶级”，“正人君子”，“名流教授”，“布尔乔亚”等等，他们从不确定，分析，辨别这些名词的涵意，只以为这些名词有辟邪的魔力，加在谁的头上谁就遭了打击。这实在是无聊的举动。

我的意思是：文学就没有阶级区别，“资产阶级文学”“无产阶级文学”都是实际革命家造出来的口号标语，文学并没有这种的区别，近年来所谓的无产阶级文学的运动，据我考查，在理论上尚不能成立，在实际上也并未成功。
