* 鲁迅笔仗集

** 前言
  :PROPERTIES:
  :CUSTOME_ID: intro
  :END:

[[https://book.douban.com/subject/1797710/][《一个都不宽恕》]]缺点有二——大缺点是编排不当，要互相比对鲁迅与论敌之间的交锋不容易，小缺点是编者立场出发的胡说八道。

我重新安排文章顺序，方便比对双方观点。但整体依然会按照《一个都不宽恕》的架构划分章节。

** 与复古派的论争 
   :PROPERTIES:
   :CUSTOM_ID: chap1
   :END:

*** 估「学衡」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec1
    :END:
    - Note taken on [2019-11-05 二 22:22] \\
      [[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1%25E6%25B4%25BE][学衡派]]其实颇为松散，想不到陈寅恪也在其中。[[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1][《学衡》]]1922年创刊，1933年停刊，共发行79期。

**** 《学衡》弁言
     :PROPERTIES:
     :CUSTOME_ID: chap1sec1art1
     :END:

     - Note taken on [2019-11-05 二 23:19] \\
       原载《学衡》1922年1月第1期

杂志迩例。弁以宣言。综其旨要。不逾二辙。自则夸饰。斥人则底词。句必盈天。字或累万。同人优劣。谢未能也。出版之始。谨矢四义。

一诵述中西先哲之精言。以翼学。

二解析世宙名著之共性。以邮思。

三籀绎之作必趋雅音。以崇文。

四平心而言。不事谩骂。以培俗。

揭示真理不趋众好。自勉勉人。期于是而已。庄生有言。瞽者无以与乎文章之观。聋者无以与乎钟鼓之声。岂惟形骸聋盲哉。夫知亦有之。同人不敏。求知不敢懈。第祝斯志之出。不聋盲吾国人。则幸矣。

**** 《评尝试集》匡谬
     :PROPERTIES:
     :CUSTOM_ID: chap1sec1art2
     :END:

     - Note taken on [2019-11-05 二 23:21] \\
       原刊于一九二二年二月四日《晨报副刊》第三版。周作人作。
南京高师教员所办的《学衡》第一期里，有一篇胡先驌君的《评〈尝试集〉》，是对付胡适之个人而作的。听说这胡君便是胡适之在《新青年》上嘲笑过的“翡翠衾寒，鸳鸯瓦冷，..早丁字檐前，繁霜飞舞”的好词的著者，但现在却异其面目，据了中外古今的大道理，来批评新诗了。评新诗原很好，只可惜他太“聋盲吾国人”了，随意而言，很有几个背谬的处所，不合于“学者之精神”。我因此也不辞“翻胔剔骼”之讥，略加匡正，窃取“不事嫚骂”与“必趋雅音”之二义，题曰“《评〈尝试集〉》匡谬”。

一、梅光迪君在《评提倡新文化者》文中，痛骂“彼等”“言文学则袭晚近之堕落派”，而胡君的文章却劈头就引“辛蒙士”的议论。难道胡君竟不知辛蒙士正是一个大名鼎鼎的“堕落派”么？倘使胡君肯买一本辛蒙士的论文来一查，便不至于被同志的梅君掌嘴了。大约他只购求了 Eve-ryman’s Library里的一本《辜勒律己之文学传记》，一见卷头的序文，便以为定是一位文学正宗的老博士所作，赶忙引用起来，岂料他竟是威尔士的一个堕落派呢？于是便上了这一个老大的当了。像他那样于欧西文化有“广博精粹之研究”的学者，尚且不免“所知既浅…束书不观，中乃空虚无有。”可见“新文化”之真不易讲了。

二、胡君说，“乔路但时之英德意文。与今日之英德意文较，则与中国之周秦古文。与今日之文字较相若”。今日之“文字”是什么？是指用汉字所写的文言，还是指用汉字所写的白话呢？照道理讲起来，所说的当然是后者。但即使依彼等的“诡辩”，以为所谓今日之文字是指文言，那么正与今日之英德意人的不用乔路但时之英德意文“相若”，今日之中国人也应至少不用周秦古文了。然而《学衡》上《国学摭谭》的序里第一句便说“粤稽我炎夏”，请问这是什么时候的古文？胡君知道这粤字在今日之文字中只用作广东的别称么？

三、胡君说，“今日人提倡以日本文作文学，其谁能指其非。”我真料不到胡君会发这样通达之论，他明明是赞成胡适之的提倡废弃古文而用白话文了。因为日人提倡以日本文作文学，不但是废弃汉文，乃是废弃日本的古文而用日本的白话！这件事实也并非什么僻典，只要稍读日本近代文学史的都知道。胡君倘若预先一查英国阿斯敦的《日本文学史》（美国 Appleton书店有翻板），便不至于闹出这场笑话来了。刘伯明君在《学者之精神》上说，“真正学者，不敢自欺欺人，必俟确有把握，而后敢以问世。”这几句话很像是对于好朋友的诤言，看了不禁代为惶愧。我并不如梅君一样，贸贸然断定胡君是伪学者，不过忠告几句，万不可不有“学者之精神”，倘若他有志变成真学者。

四、胡君说，“陀司妥夫士忌戈尔忌之小说，死文学也，不以其轰动一时遂得不死不朽也。”我们倘要捏造一句不堪的话，用栽赃的文法去诬陷他，使他失了人格，再也不能想出比他自己所说的这一句更为厉害的话了。陀司妥夫士忌的文学，正是马相伯先生的所谓良心的结晶，凡是有良心的人都不能不敬爱他，正如人们之对于耶稣和佛陀，即使并不是他们的教徒。世上宣言反对陀司妥夫士忌的，只有俄帝国的“沙”与其检查官军警及法官——然而现在也没有了。我们对于胡君，觉得实在不忍下什么断语，虽然他自己已经招承了。

其馀还有什么话可说呢！

**** 估《学衡》
     :PROPERTIES:
     :CUSTOM_ID: chap1sec1art3
     :END:

     - Note taken on [2019-11-05 二 23:37] \\
       原载《晨报副刊》1922年2月9日，署名风声
我在二月四日的《晨报副刊》上看见式芬先生的[[#chap1sec1art2][杂感]]，很诧异天下竟有这样拘迂的老先生，竟不知世故到这地步，还来同《学衡》诸公谈学理。夫所谓《学衡》者，据我看来，实不过聚在「聚宝之门」，左近的几个假古董所放的假毫光；虽然自称为“衡”，而本身的称星尚且未曾钉好，更何论于他所衡的轻重的是非。所以，决用不着较准，只要估一估就明白了。

《弁言》说，“籀绎之作必趋雅音以崇文”，“籀绎”如此，述作可知。夫文者，即使不能“载道”，却也应该“达意”，而不幸诸公虽然张皇国学，笔下却未免欠亨，不能自了，何以“衡”人。这实在是一个大缺点。看罢，诸公怎么说：《弁言》云，“杂志迩例弁以宣言”，按宣言即布告，而弁者，周人戴在头上的瓜皮小帽一般的帽子，明明是顶上的东西，所以“弁言”就是序，异于“杂志迩例”的宣言，并为一谈，太汗漫了。《评提倡新文化者》文中说，“或操笔以待。每一新书出版。必为之序。以尽其领袖后进之责。顾亭林曰。人之患在好为人序。其此之谓乎。故语彼等以学问之标准与良知。犹语商贾以道德。娼妓以贞操也。”原来做一篇序“以尽其领袖后进之责”，便有这样的大罪案。然而诸公又何以也“突而弁兮”的“言”了起来呢？照前文推论，那便是我的质问，却正是“语商贾以道德。娼妓以贞操也”了。《中国提倡社会主义之商榷》中说，“凡理想学说之发生。皆有其历史上之背影。决非悬空虚构。造乌托之邦。作无病之呻者也。”查“英吉之利”的摩耳，并未做 Pia of Uto，虽曰之乎者也，欲罢不能，但别寻古典，也非难事，又何必当中加楦呢。于古未闻“睹史之陀”，在今不云“宁古之塔”，奇句如此，真可谓“有病之呻”了。

《国学摭谭》中说，“虽三皇寥廓而无极。五帝搢绅先生难言之。”人而能“寥廓”，已属奇闻，而第二句尤为费解，不知是三皇之事，五帝和搢绅先生皆难言之，抑是五帝之事，从后说，然而太史公所谓“搢绅先生难言之”者，乃指“百家言黄帝”而并不指五帝，所以翻开《史记》，便是赫然的一篇《五帝本纪》，又何尝“难言之”。难道太史公在汉朝，竟应该算是下等社会中人么？

《记白鹿洞谈虎》中说，“诸父老能健谈。谈多称虎。当其摹示抉噬之状。闻者鲜不色变。退而记之。亦资诙噱之类也。”姑不论其“能”“健”“谈”“称”，床上安床，“抉噬之状”，终于未记，而“变色”的事，但“资诙噱”，也可谓太远于事情。倘使但“资诙噱”，则先前的闻而色变者，简直是呆子了。记又云，“伥者。新鬼而膏虎牙者也。”刚做新鬼，便“膏虎牙”，实在可悯。那么，虎不但食人，而且也食鬼了。这是古来未知的新发见。

《渔丈人行》的起首道：“楚王无道杀伍奢。覆巢之下无完家。”这“无完家”虽比“无完卵”新奇，但未免颇有语病。假如“家”就是鸟巢，那便犯了复，而且“之下”二字没有着落，倘说是人家，则掉下来的鸟巢未免太沉重了。除了大鹏金翅鸟（出《说岳全传》），断没有这样的大巢，能够压破彼等的房子。倘说是因为押韵，不得不然，那我敢说：这是“挂脚韵”。押韵至于如此，则翻开《诗韵合璧》的“六麻”来，写道“无完蛇”“无完瓜”“无完叉”，都无所不可的。

还有《浙江采集植物游记》，连题目都不通了。采集有所务，并非漫游，所以古人作记，务与游不并举，地与游才相连。匡庐〔13〕峨眉，山也，则曰纪游，采硫访碑，务也，则曰日记。虽说采集时候，也兼游览，但这应该包举在主要的事务里，一列举便不“古”了。例如这记中也说起吃饭睡觉的事，而题目不可作《浙江采集植物游食眠记》。

以上不过随手拾来的事，毛举起来，更要费笔费墨费时费力，犯不上，中止了。因此诸公的说理，便没有指正的必要，文且未亨，理将安托，穷乡僻壤的中学生的成绩，恐怕也不至于此的了。

总之，诸公掊击新文化而张皇旧学问，倘不自相矛盾，倒也不失其为一种主张。可惜的是于旧学并无门径，并主张也还不配。倘使字句未通的人也算在国粹的知己，则国粹更要惭惶然人！“衡”了一顿，仅仅“衡”出了自己的铢两来，于新文化无伤，于国粹也差得远。

我所佩服诸公的只有一点，是这种东西也居然会有发表的勇气。

**** 评论
     :PROPERTIES:
     :CUSTOM_ID: chap1sec1dis1
     :END:

《一个都不宽恕》只选了鲁迅的[[#chap1sec1art3][《估〈学衡〉》]]，但是从鲁迅原文看，其实他是在周作人的[[#chap1sec1art2][《〈评尝试集〉匡谬》]]之后写的，有点为弟弟摇旗呐喊的味道。不过相对周作人批评观点，鲁迅更多是直接攻击对方的知识水平，挑错之后说出了「我所佩服诸公的只有一点，是这种东西也居然会有发表的勇气」这句经典对白（所以我才说这不叫「论战」）。

《估〈学衡〉》中提到的其他文章，我没有找到对应的电子版，所以就不录在这里了，江苏古籍出版社出了[[https://book.douban.com/subject/1702850/][《学衡》]]全集，有兴趣的朋友，不妨去图书馆借来看看——毕竟定价3000元，买就不必了。

*** 批「甲寅」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec2
    :END:

**** 停办北京女子师范大学呈文
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art1
     :END:

     - Note taken on [2019-11-06 三 13:42] \\
       原载《甲寅周刊》第1卷4号（1925年8月8日）。本文录自[[http://www.cnthinkers.com/thinkerweb/index][中国思想与文化名家数据库]]。
呈为国立大学，师生互哄，纷纠难理，拟恳查照术专门学校成例，将该大学暂行停办，以资整顿而维风纪事：北京女子师范大学校长杨荫榆，为校内一部分学生所反对，呈词互讦，由来已久。本部前任次长马叙伦、总长王九龄，均以办理棘手，迁延未决。迨士钊兼部，日在辞职或未实行负责之中，亦复未暇顾及。查此事之起，由于该校学生，设有自治会，倡言不认杨荫榆为校长，并于公开讲演之时，群起侮辱。该校长乃于素喜滋事之学生中，革除蒲振声、张平江、刘和珍、姜伯谛、许广平、郑德音等六人。该生等不服，联合校内男女各生，大施反抗运动。非但革生不肯出校，转而驱逐校长，锁闭办公室，阴止校长及办事人等入内，以致全校陷入无政府状态。由五月至今，三四月间，学生跳梁于内，校长侨置于外，为势僵然，一筹莫展。迩者士钊奉令调署，正拟切实查办，适该校长杨荫榆，拟具改组四班计划，请示前来。当以该校长职责所存，批令妥善办理。顷据该校长呈报：八月一日到校，顽劣学生，手持木棍砖石，志存殴辱，叫骂追逐，无所不至。又复撕毁布告，易以学生求援宣言，并派人驻守校门，禁阻校员出入，其余则乘坐汽车，四出求助。旋有男生多人，来校恫吓，并携带快镜，各处摄影。种种怪状，见者骇然等情。学生暴乱如此，迥出情理之外。窃思比年学风，嚣张已极。政府既乏长策，社会复无公评。四方不逞之徒，又从而扇发之，狙使青年男女，顽抗部校命令。是非颠例，一无准裁。该校长以一女流，明其职守，甘任劳怨，期有始终。虽其平时措置，未必尽当，平心而论，似亦为所难能。士钊每得该校长之谤书，思此辄为太息。或谓师生之情过伤，处置难期妥惬，原案虽不能易，人选似可通融。不知京师各校，以革除学生而谋逐校长，已非一次，其后因缘事变，借口调停，大抵革生留而校长去。胜负之数，伏于事先，横逆之生，惯如饮食，乖风流衍，以迄今兹，纲纪荡然，泰半由此。今若谬种相仍，再误三误，此其选软羞当世之士，其失小；公然纵子弟为恶，其失大。士钊详加考虑，此着断不可行。默察该校情形，各系教员，植党构扇，势甚强固，不可爬梳。而诸生荒学逾闲，恣为无忌，道路以目，亲者痛心。该校长任事以来，一切要害之政，并尚未能董理，而已怨毒之甚，一日难居。倘仍其旧贯，环境依然，即别求一人为继，度亦无能为役。士钊少负不羁之名，长习自由之说，名邦大学，负笈分驰，男女同班，亦尝亲与，所有社会交际、两性衔接之机缄缔构，一一考求。其中流以上之家，凡未成年之女子，殆无不惟家长阿保之命是从，文质彬彬，至可敬爱。从未见有不受检制，竟体忘形，啸聚男生，蔑视长上，家族不知所出，浪士从而推波，伪托文明，肆为驰骋，谨愿者尽丧所守，狡黠者毫无忌惮，学纪大紊，礼教全荒，如吾国今日女学之可悲叹者也。以此兴学，直是灭学。以此尊重女子，直是摧辱女子。钊念儿女乃家家所有，良用痛心，为政而人人悦之，亦无是理，该师范大学，号为全国女子最高学府，强自取柱，柔自取束，立表不正，其影可知。当此女教绝续之秋，宜为根本改图之计，拟请查照马前次长处理美术专门学校成例，将该大学暂行停办。该校长杨荫榆调部任用，一面遴选专家，妥速筹画。务期重立宏规，树之模楷，以副执政与民更始不遗女子之至意。是否有当，理合具文，仰祈钧鉴施行。再：该校学生，半由各省考送，家长戚族，未必在京，责令即时解散，亦未便操之过急。日者士钊曾偕部员，亲赴该校视察，见留校女生二十余人，起居饮食，诸感困苦。迹其行为，宜有惩罚，观其情态，亦甚可矜。当由部派员，商同各该保证人，妥为料理，无须警察干预。外传警察殴伤学生各节，全属讹言。此后校事部了，尤不至有学警冲突之虞。合并陈明。

**** 章士钊致段祺瑞呈文
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art2
     :END:


     - Note taken on [2019-11-06 三 22:37] \\
       此文1925年8月12日呈段祺瑞。实在搜不到，只能在《一个都不宽恕》里面复制粘贴。然后13日鲁迅就被免职。

敬折呈者，窃查官吏服务，首在恪守本分，服从命令。兹有本部佥事周树人，兼任国立女子师范大学教员，于本部下令停办该校以后，结合党徒，附和女生，倡设校务维持会，充任委员，似此违法抗令，殊属不合，应请明令免去本职，以示惩戒（并请补交高等文官惩戒委员会核议，以完法律手续）。是否有当，理合呈请鉴核施行。谨呈临时执政。

**** 鲁迅呈平政院状
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art3
     :END:
     - Note taken on [2019-11-06 三 22:40] \\
       1925年8月22日，鲁迅向平政院投递诉状，原文找不到，从《一个都不宽恕》中复制粘贴——然而《一》书本身就是从平政院的裁决书中抄的。

树人充教育部佥事，已十有四载，恪恭将事，故任职以来屡获奖叙。讵教育总长章士钊竟无故将树人呈请免职。查文官免职，系属惩戒处分之一。依《文官惩戒条例》第十八条之规定，须先交付惩戒始能依法执行。乃竟滥用职权，擅自处分，无故将树人免职，显违《文官惩戒条例》第一条及《文官保障法草案》第二条之规定。此种违法处分，实难自甘缄默。

**** 章士钊答状
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art4
     :END:
     - Note taken on [2019-11-06 三 22:43] \\
       继续从《一个都不宽恕》中抄录，本答辩当年10月13日送到鲁迅处。

查周树人免职理由，本部上执政呈文业经声叙明白，兹更为贵院述之：本年八月十日，本部遵照执政训令停办国立女子师范大学，当委部员刘百昭等前往接收，不意本部佥事周树人，原系社会司第一科科长，地位职务均极重要，乃于本部执行令准停办该校，正属行政严重之时，竟敢勾结该校教员、捣乱分子及少数不良学生，谬托校务维持会名义，妄自主张，公然与所服务之官署悍然立于反抗地位。据接收委员会报告，入校办公时亲见该员盘踞校舍，集众开会，确有种种不合之行为。又该伪校务维持会，擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政，既情理之所难容，亦法律之所不许。查《官吏服务令》第一条：凡官吏应竭尽忠勤，服从法律命令以行职务。第二条：长官就其范围以内所发命令，属员有服从之义务。第四条：属官对于长官所发命令如有意见，得随时陈述。第二十九条：凡官吏有违上开各条者，该管长官依其情节，分别训告，或付惩戒。规定至为明切。今周树人既未将意见陈述，复以本部属员不服从本部长官命令，实已违反《文官服务令》第一第二第四各条之规定。本部原拟循例呈请交付惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈烈，难以平息，不得已于八月十二日呈请执政将周树人免职。十三日由执政明令照准，此周树人免职经过之实在情形也。查原诉状内有无故免职等语，系欲以无故二字遮掩其与女师大教习学生集会违令各行为，希图脱免。至追加理由所称本部呈请执政将周树人免职稿件倒填日月一节，实因此项免职事件情出非常，本部总长系于十二日面呈执政，即日明令发表，随后再将呈稿补发存案。即日补发，无所谓倒填，情势急迫，本部总长应有权执行此非常处分，周树人不得引为口实。兹特详叙事实答辩如右。

**** 鲁讯互辩书
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art5
     :END:

     - Note taken on [2019-11-06 三 22:46] \\
       鲁迅博物馆现存一份鲁迅亲自收藏的互辩书草稿。写作日期是1925年10月16日。节录如下。

一、查总长妄称□□（按“树人”二字。下同）以部员资格勾结该校教员捣乱分子及少数不良学生，谬托校务维持会名义，妄有主张等语，全不明言去勾结何等捣乱分子及不良学生何人，□□主张何事，信口虚捏，全无事实证据，殊不称长官体统，有玷人格。况各部职员兼任国立各校教员不下数百人，□□为女师大兼任教员之一。在部则为官吏，在校则为教员。两种资格，各有职责、不容牵混。……

二、□□平日品性人格，向不干预外事，社会共晓。此次女师大应否解散尤与□□无涉。故该总长对于该校举动是否合宜，□□从不过问。现该答辩内有“周树人既未将意见陈述”一言可知从未干预。至□□在女师大担任教员职务，一方关于教课，固为个人应负责；一方关于公众，又为团体共负之责。若由团体发表之事件，应由团体负责，尤不能涉及个人，更不能专诬□□一人而加以非法（处分）。譬如现北大与教育部脱离关系。公然反抗，是为团体行动，岂北大教员之兼教部职员者将共负其责耶？

三、该答辩称“据接收委员报告云确有种种不法行为”，试问报告委员何人？报告何在？□□盘踞何状？不合何事？概未明言，即入人罪。且说教员维持校务为伪托，伪者何在？抑凡为教员者于法不得维持校务耶？

四、答辩又称“该伪校务维持会擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政”。查校务维持会公举□□为委员，系在8月13日，而该总长呈请免职，据称在12日。岂预知将举□□为委员而先为免职之罪名耶？况他人公举□□何能为□□之罪？

五、……□□充教育部佥事、社会教育司科长，与女师大停办与否，职守上毫无关系，故对于女师大停办命令从未一字陈述意见，亦实无陈述之职责。既未陈述，既无违反命令举动及言论可知。乃章士钊反以未陈述意见指为抗违命令，其理由何在？且又以未陈述意见即为违反服务令第一、二、四等条，其理由又安在？殊不可解。岂官吏须出位陈述职守以外之意见方为遵守服务令耶？何悖谬至此！

六、该答辩谓“本部原拟循例呈请惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈恶，难以平息，不得已呈请免职。”查以教长权力整顿一女校，何至形势严重？依法免部员职，何至迫不及待？风潮难平，事系学界？何至用非常处分。此等饰词，殊属可笑。且所谓行政处分原以合法为范围。凡违法令之行政处分当然无效。此《官吏服务令》所明白规定者。今章士钊不依法惩戒，殊属身为长官，弁髦法令。

**** 国务总理贾德耀签署了给教育总长的训令（临时执政训令第十三号）
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art6
     :END:

     - Note taken on [2019-11-06 三 22:51] \\
       格式有点问题，「国务总理贾德耀教育总长」与「中华民国十五年三月三十一日」当右对齐。
据平政院院长汪大燮呈，审理前教育部佥事周树人陈诉不服教育部呈请免职之处分，指为违法，提起行政诉讼一案，依法裁决教育部之处分应予取消等语，著交教育部查照执行。

此令

国务总理贾德耀

教育总长

中华民国十五年三月三十一日


**** 答KS君
     :PROPERTIES:
     :CUSTOM_ID: chap1sec2art7
     :END:
     - Note taken on [2019-11-06 三 22:58] \\
       董大中的[[https://books.google.com.hk/books?id=wY4BRZYJPwIC&pg=PA261&lpg=PA261&dq=%25E7%25AD%2594KS%25E5%2590%259B+%25E8%25B0%2581%25E6%2598%25AF+KS%25E5%2590%259B&source=bl&ots=UMX_1D7kuz&sig=ACfU3U0rghsRR2kYvkR17t3tApiC1vOW0g&hl=zh-CN&sa=X&redir_esc=y#v=onepage&q=%25E7%25AD%2594KS%25E5%2590%259B%2520%25E8%25B0%2581%25E6%2598%25AF%2520KS%25E5%2590%259B&f=false][《魯迅日記箋釋》]]也说 KS 君未详，我也就不考究了。原载《莽原》1925年8月28日周刊第19期

KS兄：

我很感谢你的殷勤的慰问，但对于你所愤慨的两点和几句结论，我却并不谓然，现在略说我的意见——

第一，章士钊将我免职，我倒并没有你似的觉得诧异，他那对于学校的手段，我也并没有你似的觉得诧异，因为我本就没有预期章士钊能做出比现在更好的事情来。我们看历史，能够据过去以推知未来，看一个人的已往的经历，也有一样的效用。你先有了一种无端的迷信，将章士钊当作学者或智识阶段的领袖看，于是从他的行为上感到失望，发生不平，其实是作茧自缚；他这人本来就只能这样，有着更好的期望倒是你自己的误谬。使我较为感到有趣的倒是几个向来称为学者或教授的人们，居然也渐次吞吞吐吐地来说微温话了，什么“政潮”咧，“党”咧，仿佛他们都是上帝一样，超然象外，十分公平似的。谁知道人世上并没有这样一道矮墙，骑着而又两脚踏地，左右稳妥，所以即使吞吞吐吐，也还是将自己的魂灵枭首通衢，挂出了原想竭力隐瞒的丑态。丑态，我说，倒还没有什么丢人，丑态而蒙着公正的皮，这才催人呕吐。但终于使我觉得有趣的是蒙着公正的皮的丑态，又自己开出帐来发表了。仿佛世界上还有光明，所以即便费尽心机，结果仍然是一个瞒不住。

第二，你这样注意于《甲寅周刊》，也使我莫明其妙。《甲寅》第一次出版时，我想，大约章士钊还不过熟读了几十篇唐宋八大家文，所以模仿吞剥，看去还近于清通。至于这一回，却大大地退步了，关于内容的事且不说，即以文章论，就比先前不通得多，连成语也用不清楚，如“每下愈况”之类。尤其害事的是他似乎后来又念了几篇骈文，没有融化，而急于挦撦，所以弄得文字庞杂，有如泥浆混着沙砾一样。即如他那《停办北京女子师范大学呈文》中有云，“钊念儿女乃家家所有良用痛心为政而人人悦之亦无是理”，旁加密圈，想是得意之笔了。但比起何《齐姜醉遣晋公子赋》的“公子固翩翩绝世未免有情少年而碌碌因人安能成事”来，就显得字句和声调都怎样陋弱可哂。何比他高明得多，尚且不能入作者之林，章士钊的文章更于何处讨生活呢？况且，前载公文，接着就是通信，精神虽然是自己广告性的半官报，形式却成了公报尺牍合璧了，我中国自有文字以来，实在没有过这样滑稽体式的著作。这种东西，用处只有一种，就是可以借此看看社会的暗角落里，有着怎样灰色的人们，以为现在是攀附显现的时候了，也都吞吞吐吐的来开口。至于别的用处，我委实至今还想不出来。倘说这是复古运动的代表，那可是只见得复古派的可怜，不过以此当作讣闻，公布文言文的气绝罢了。

所以，即使真如你所说，将有文言白话之争，我以为也该是争的终结，而非争的开头，因为《甲寅》不足称为敌手，也无所谓战斗。倘要开头，他们还得有一个更通古学，更长古文的人，才能胜对垒之任，单是现在似的每周印一回公牍和游谈的堆积，纸张虽白，圈点虽多，是毫无用处的。


