#+LATEX_HEADER: \usepackage{ctex}
#+STARTUP: showall
* 鲁迅笔仗集

** 编辑手记
  :PROPERTIES:
  :CUSTOM_ID: intro
  :END:

*** <2020-11-06 五>
 [[https://book.douban.com/subject/1797710/][《一个都不宽恕》]]缺点有二——大缺点是编排不当，要互相比对鲁迅与论敌之间的交锋不容易，小缺点是编者立场出发的胡说八道。

 我重新安排文章顺序，方便比对双方观点。但整体依然会按照《一个都不宽恕》的架构划分章节。

*** <2019-11-07 四> 

发现编排有个问题，理论上来说，我希望能够按照时间来编排，但是《一个都不宽恕》里面编排的顺序不是这样的，比如《批「甲寅」》一章，鲁迅跟章士钊打了大半年官司，中间穿插了不少笔墨战争。所以我决定先寻找 org-mode item 排序的方案，再决定编目方案。

另外我发现，还需要研究鲁迅的日记和书信，才能彻底补完。

其实是可以按照 properties 来排序的，所以决定每篇文章的 custom_id 都是文章的刊发日期——希望鲁迅不会勤奋到同一天写两篇文章骂不同的人吧，我不知道 custom_id 是否要求全局唯一（还是说同一个 parent 下唯一就行了？），第一章第一节的 custom_id 需要修改一下。


** 与复古派的论争 
   :PROPERTIES:
   :CUSTOM_ID: chap1
   :END:

*** 估「学衡」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec1
    :END:
    - Note taken on [2019-11-05 二 22:22] \\
      [[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1%25E6%25B4%25BE][学衡派]]其实颇为松散，想不到陈寅恪也在其中。[[https://zh.wikipedia.org/wiki/%25E5%25AD%25B8%25E8%25A1%25A1][《学衡》]]1922年创刊，1933年停刊，共发行79期。

**** 《学衡》弁言
     :PROPERTIES:
     :CUSTOME_ID: 19190101
     :END:

     - Note taken on [2019-11-05 二 23:19] \\
       原载《学衡》1922年1月第1期

杂志迩例。弁以宣言。综其旨要。不逾二辙。自则夸饰。斥人则底词。句必盈天。字或累万。同人优劣。谢未能也。出版之始。谨矢四义。

一诵述中西先哲之精言。以翼学。

二解析世宙名著之共性。以邮思。

三籀绎之作必趋雅音。以崇文。

四平心而言。不事谩骂。以培俗。

揭示真理不趋众好。自勉勉人。期于是而已。庄生有言。瞽者无以与乎文章之观。聋者无以与乎钟鼓之声。岂惟形骸聋盲哉。夫知亦有之。同人不敏。求知不敢懈。第祝斯志之出。不聋盲吾国人。则幸矣。

**** 《评尝试集》匡谬
     :PROPERTIES:
     :CUSTOM_ID: 19220204
     :END:

     - Note taken on [2019-11-05 二 23:21] \\
       原刊于一九二二年二月四日《晨报副刊》第三版。周作人作。
南京高师教员所办的《学衡》第一期里，有一篇胡先驌君的《评〈尝试集〉》，是对付胡适之个人而作的。听说这胡君便是胡适之在《新青年》上嘲笑过的「翡翠衾寒，鸳鸯瓦冷，..早丁字檐前，繁霜飞舞」的好词的著者，但现在却异其面目，据了中外古今的大道理，来批评新诗了。评新诗原很好，只可惜他太「聋盲吾国人」了，随意而言，很有几个背谬的处所，不合于「学者之精神」。我因此也不辞「翻胔剔骼」之讥，略加匡正，窃取「不事嫚骂」与「必趋雅音」之二义，题曰「《评〈尝试集〉》匡谬」。

一、梅光迪君在《评提倡新文化者》文中，痛骂「彼等」「言文学则袭晚近之堕落派」，而胡君的文章却劈头就引「辛蒙士」的议论。难道胡君竟不知辛蒙士正是一个大名鼎鼎的「堕落派」么？倘使胡君肯买一本辛蒙士的论文来一查，便不至于被同志的梅君掌嘴了。大约他只购求了 Eve-ryman’s Library里的一本《辜勒律己之文学传记》，一见卷头的序文，便以为定是一位文学正宗的老博士所作，赶忙引用起来，岂料他竟是威尔士的一个堕落派呢？于是便上了这一个老大的当了。像他那样于欧西文化有「广博精粹之研究」的学者，尚且不免「所知既浅…束书不观，中乃空虚无有。」可见「新文化」之真不易讲了。

二、胡君说，「乔路但时之英德意文。与今日之英德意文较，则与中国之周秦古文。与今日之文字较相若」。今日之「文字」是什么？是指用汉字所写的文言，还是指用汉字所写的白话呢？照道理讲起来，所说的当然是后者。但即使依彼等的「诡辩」，以为所谓今日之文字是指文言，那么正与今日之英德意人的不用乔路但时之英德意文「相若」，今日之中国人也应至少不用周秦古文了。然而《学衡》上《国学摭谭》的序里第一句便说「粤稽我炎夏」，请问这是什么时候的古文？胡君知道这粤字在今日之文字中只用作广东的别称么？

三、胡君说，「今日人提倡以日本文作文学，其谁能指其非。」我真料不到胡君会发这样通达之论，他明明是赞成胡适之的提倡废弃古文而用白话文了。因为日人提倡以日本文作文学，不但是废弃汉文，乃是废弃日本的古文而用日本的白话！这件事实也并非什么僻典，只要稍读日本近代文学史的都知道。胡君倘若预先一查英国阿斯敦的《日本文学史》（美国 Appleton书店有翻板），便不至于闹出这场笑话来了。刘伯明君在《学者之精神》上说，「真正学者，不敢自欺欺人，必俟确有把握，而后敢以问世。」这几句话很像是对于好朋友的诤言，看了不禁代为惶愧。我并不如梅君一样，贸贸然断定胡君是伪学者，不过忠告几句，万不可不有「学者之精神」，倘若他有志变成真学者。

四、胡君说，「陀司妥夫士忌戈尔忌之小说，死文学也，不以其轰动一时遂得不死不朽也。」我们倘要捏造一句不堪的话，用栽赃的文法去诬陷他，使他失了人格，再也不能想出比他自己所说的这一句更为厉害的话了。陀司妥夫士忌的文学，正是马相伯先生的所谓良心的结晶，凡是有良心的人都不能不敬爱他，正如人们之对于耶稣和佛陀，即使并不是他们的教徒。世上宣言反对陀司妥夫士忌的，只有俄帝国的「沙」与其检查官军警及法官——然而现在也没有了。我们对于胡君，觉得实在不忍下什么断语，虽然他自己已经招承了。

其馀还有什么话可说呢！

**** 估《学衡》
     :PROPERTIES:
     :CUSTOM_ID: 19220209
     :END:

     - Note taken on [2019-11-05 二 23:37] \\
       原载《晨报副刊》1922年2月9日，署名风声
我在二月四日的《晨报副刊》上看见式芬先生的[[#19220204][杂感]]，很诧异天下竟有这样拘迂的老先生，竟不知世故到这地步，还来同《学衡》诸公谈学理。夫所谓《学衡》者，据我看来，实不过聚在「聚宝之门」，左近的几个假古董所放的假毫光；虽然自称为「衡」，而本身的称星尚且未曾钉好，更何论于他所衡的轻重的是非。所以，决用不着较准，只要估一估就明白了。

《弁言》说，「籀绎之作必趋雅音以崇文」，「籀绎」如此，述作可知。夫文者，即使不能「载道」，却也应该「达意」，而不幸诸公虽然张皇国学，笔下却未免欠亨，不能自了，何以「衡」人。这实在是一个大缺点。看罢，诸公怎么说：《弁言》云，「杂志迩例弁以宣言」，按宣言即布告，而弁者，周人戴在头上的瓜皮小帽一般的帽子，明明是顶上的东西，所以「弁言」就是序，异于「杂志迩例」的宣言，并为一谈，太汗漫了。《评提倡新文化者》文中说，「或操笔以待。每一新书出版。必为之序。以尽其领袖后进之责。顾亭林曰。人之患在好为人序。其此之谓乎。故语彼等以学问之标准与良知。犹语商贾以道德。娼妓以贞操也。」原来做一篇序「以尽其领袖后进之责」，便有这样的大罪案。然而诸公又何以也「突而弁兮」的「言」了起来呢？照前文推论，那便是我的质问，却正是「语商贾以道德。娼妓以贞操也」了。《中国提倡社会主义之商榷》中说，「凡理想学说之发生。皆有其历史上之背影。决非悬空虚构。造乌托之邦。作无病之呻者也。」查「英吉之利」的摩耳，并未做 Pia of Uto，虽曰之乎者也，欲罢不能，但别寻古典，也非难事，又何必当中加楦呢。于古未闻「睹史之陀」，在今不云「宁古之塔」，奇句如此，真可谓「有病之呻」了。

《国学摭谭》中说，「虽三皇寥廓而无极。五帝搢绅先生难言之。」人而能「寥廓」，已属奇闻，而第二句尤为费解，不知是三皇之事，五帝和搢绅先生皆难言之，抑是五帝之事，从后说，然而太史公所谓「搢绅先生难言之」者，乃指「百家言黄帝」而并不指五帝，所以翻开《史记》，便是赫然的一篇《五帝本纪》，又何尝「难言之」。难道太史公在汉朝，竟应该算是下等社会中人么？

《记白鹿洞谈虎》中说，「诸父老能健谈。谈多称虎。当其摹示抉噬之状。闻者鲜不色变。退而记之。亦资诙噱之类也。」姑不论其「能」「健」「谈」「称」，床上安床，「抉噬之状」，终于未记，而「变色」的事，但「资诙噱」，也可谓太远于事情。倘使但「资诙噱」，则先前的闻而色变者，简直是呆子了。记又云，「伥者。新鬼而膏虎牙者也。」刚做新鬼，便「膏虎牙」，实在可悯。那么，虎不但食人，而且也食鬼了。这是古来未知的新发见。

《渔丈人行》的起首道：「楚王无道杀伍奢。覆巢之下无完家。」这「无完家」虽比「无完卵」新奇，但未免颇有语病。假如「家」就是鸟巢，那便犯了复，而且「之下」二字没有着落，倘说是人家，则掉下来的鸟巢未免太沉重了。除了大鹏金翅鸟（出《说岳全传》），断没有这样的大巢，能够压破彼等的房子。倘说是因为押韵，不得不然，那我敢说：这是「挂脚韵」。押韵至于如此，则翻开《诗韵合璧》的「六麻」来，写道「无完蛇」「无完瓜」「无完叉」，都无所不可的。

还有《浙江采集植物游记》，连题目都不通了。采集有所务，并非漫游，所以古人作记，务与游不并举，地与游才相连。匡庐〔13〕峨眉，山也，则曰纪游，采硫访碑，务也，则曰日记。虽说采集时候，也兼游览，但这应该包举在主要的事务里，一列举便不「古」了。例如这记中也说起吃饭睡觉的事，而题目不可作《浙江采集植物游食眠记》。

以上不过随手拾来的事，毛举起来，更要费笔费墨费时费力，犯不上，中止了。因此诸公的说理，便没有指正的必要，文且未亨，理将安托，穷乡僻壤的中学生的成绩，恐怕也不至于此的了。

总之，诸公掊击新文化而张皇旧学问，倘不自相矛盾，倒也不失其为一种主张。可惜的是于旧学并无门径，并主张也还不配。倘使字句未通的人也算在国粹的知己，则国粹更要惭惶然人！「衡」了一顿，仅仅「衡」出了自己的铢两来，于新文化无伤，于国粹也差得远。

我所佩服诸公的只有一点，是这种东西也居然会有发表的勇气。

*** 批「甲寅」
    :PROPERTIES:
    :CUSTOM_ID: chap1sec2
    :END:

**** 评新文化运动（节选）
     :PROPERTIES:
     :CUSTOM_ID: 19230800
     :END:

夫语以耳辨。徒资口谈。文以目辨。更贵成诵。则其取音之繁简连截。有其自然。不可强混。如园有桃。笔之于书。词义俱完。今曰此于语未合也。必曰园里有桃子树。二桃杀三士。谱之于诗。节奏甚美。今曰此于白话无当也。必曰两个桃子杀了三个读书人。是亦不可以已乎。

**** 对于北京女子师范大学风潮宣言
     :PROPERTIES:
     :CUSTOM_ID: 19250527
     :END:

     - Note taken on [2019-11-10 日 14:30] \\
       署名的有：马裕藻，沈尹默，周树人，李泰棻，钱玄同，沈兼士，周作人

溯本校不安之状，盖已半载有余，时有隐显，以至现在，其间亦未见学校当局有所反省，竭诚处理，使之消弭，迨五月七日校内讲演时，学生劝校长杨荫榆先生退席后，杨先生乃于饭馆召集教员若干燕饮，继即以评议部名义，将学生自治会职员六人（文预科四人理预科一人国文系一人）揭示开除，由是全校然，有坚拒杨先生长校之事变，而杨先生亦遂遍送感言，又驰书学生家属，其文甚繁，第观其已经公表者，则大概谆谆以品学二字立言，使不谙此事始末者见之，一若此次风潮，为校长整饬风纪之所致，然品性学业，皆有可征，六人学业，俱非不良，至于品性一端，平素尤绝无惩戒记过之迹，以此与开除并论，而又若离若合，殊有混淆黑白之嫌，况六人俱为自治会职员，倘非长才，众人何由公举，不满于校长者倘非公意，则开除之后，全校何至然？所罚果当其罪，则本系之两主任何至事前并不与闻，继遂相率引退，可知公论尚在人心，曲直早经显见，偏私谬戾之举，究非空言曲说所能掩饰也，同人忝为教员，因知大概，义难默尔，敢布区区，惟关心教育者察焉。

**** 闲话（粉刷茅厕）
     :PROPERTIES:
     :CUSTOM_ID: 19250530
     :END:
     - Note taken on [2019-11-10 日 14:02] \\
       不知道是不是全文。来自[[https://www.zhihu.com/question/53888731/answer/276821126][知乎某个答案]]。



“以前学校闹风潮，学生几乎没有对的，现在学校闹风潮，学生几乎没有错的。这可以说是今昔言论界ia的一种信条。在我这种喜欢怀疑的人看来，这两种观念都无非是迷信。女师大的风潮，究竟学生是对的还是错的，反对校长的是少数还是多数，我们没有调查详细的事实，无从知道。我们只觉得这次闹得太不像样了。同系学生同时登两个相反的启事已经发现了。学生把守校门，误认了一个缓缓驶行的汽车为校长回校而群起包围它的笑话，也到处流传了。校长不能在校开会，不得不借邻近饭店招集教员会议的奇闻，也见于报章了，学校的丑态既然毕露，教育界的面目也就丢尽。到了这种时期，实在旁观的人也不能再让它酝酿下去，好像一个臭毛厕，人人都有扫除的义务。在这时候劝学生们不为过甚，或是劝校长辞职引退，都无非粉刷毛厕，并不能解决根本的问题。我们以为教育当局应当切实的调查这次风潮的内容，如果过在校长，自应立即更换，如果过在学生，也少不得加以相当的惩罚，万不可再敷衍姑息下去，以至将来要整顿也没有了办法。　　

闲话正要付印的时候，我们在报纸上看见女师大七教员的宣言。以前我们常常听说女师大的风潮，有在北京教育界占最大势力的某籍某系的人在暗中鼓励，可是我们总不敢相信。这个宣言语气措辞，我们看来，未免过于偏袒一方，不大平允，看文中最精彩的几句就知道了。　　

“至于品性一端，平素尤绝无惩戒记过之迹，以此与开除并论，而又若离若合，殊有混淆黑白之嫌，况六人俱为自治会职员，倘非长才，众人何由公举，不满于校长者倘非公意，则开除之后，全校何至哗然？所罚果当其罪，则本系之两主任何至事前并不与闻，继遂相率引退，可知公论尚在人心，曲直早经显见，偏私谬戾之举，究非空言曲说所能掩饰也。”　

这是很可惜的。我们自然还是不信我们平素所很尊敬的人会暗中挑剔风潮，但是这篇宣言一出，免不了流言更加传布得厉害了。”

**** 为北京女师大学生拟呈教育部文二件
     :PROPERTIES:
     :CUSTOM_ID: 19250603
     :END:

     - Note taken on [2019-11-10 日 14:32] \\
       本篇据手稿编入，原无标题、标点。第一件呈文曾发表于1925年6月3日北京女子师范大学学生自治会编辑出版的《驱杨运动特刊》，题为《学生自治会上教育部呈文》。第二件呈文鲁迅生前未曾发表。

***** 一

呈为校长溺职滥罚，全校冤愤，恳请迅速撤换，以安学校事。窃杨荫榆到校一载，毫无设施，本属尸位素餐，贻害学子，屡经呈明大部请予查办，并蒙派员莅校彻查在案。从此杨荫榆即忽现忽隐，不可究诘，自拥虚号，专恋惰金，校务遂愈形败坏，其无耻之行为，为生等久所不齿，亦早不觉尚有杨荫榆其人矣。不料“五七”国耻在校内讲演时，忽又然临席，生等婉劝退去，即老羞成怒，大呼警察，幸经教员阻止，始免流血之惨。下午即借宴客为名，在饭店召集不知是否合法之评议员数人，于杯盘狼藉之余，始以开除学生之事含糊相告，亦不言学生为何人。至九日，突有开除自治会职员……等六人之揭示贴校内。夫自治会职员，乃众所公推，代表全体，成败利钝，生等固同负其责。今乃倒行逆施，罚非其罪，欲乘学潮汹涌之时，施其险毒阴私之计，使世人不及注意，居心下劣，显然可知！继又停止已经预告之运动会，使本校失信于社会，又避匿不知所往，使生等无从与之辩诘，实属视学子如土芥，以大罚为儿戏，天良丧失，至矣尽矣！可知杨荫榆一日不去，即如刀俎在前，学生为鱼肉之不暇，更何论于学业！是以全体冤愤，公决自失踪之日起，即绝对不容其再入学校之门，以御横暴，而延残喘。为此续呈大部，恳即□□明令迅予撤换，拯本校于阽危，出学生于水火。不胜迫切待命之至！

***** 二

呈为续陈杨荫榆氏行踪诡秘，心术叵测，败坏学校，恳即另聘校长，迅予维持事。窃杨氏失踪，业已多日。曾干五月十二日具呈□□大部，将其阴险横暴实情，沥陈梗概，请予撤换在案。讵杨氏怙恶不悛，仍施诡计。先谋提前放假，又图停课考试。术既不售，乃愈设盛筵，多召党类，密画毁校之策，冀复失位之仇。又四出请托，广播谣诼，致函学生家长，屡以品性为言，与开除时之揭示，措辞不同，实属巧设谰言，阴伤人格，则其良心何在，不问可知。倘使一任诪张，诚为学界大辱，盖不独（生等）身受摧残，学校无可挽救而已。为此合词续恳即下明令，速任贤明，庶校务有主持之人，暴者失蹂躏之地，学校幸甚！教育幸甚！

谨呈

教育部总长

**** 停办北京女子师范大学呈文
     :PROPERTIES:
     :CUSTOM_ID: 19250808
     :END:

     - Note taken on [2019-11-06 三 13:42] \\
       原载《甲寅周刊》第1卷4号（1925年8月8日）。本文录自[[http://www.cnthinkers.com/thinkerweb/index][中国思想与文化名家数据库]]。
呈为国立大学，师生互哄，纷纠难理，拟恳查照术专门学校成例，将该大学暂行停办，以资整顿而维风纪事：北京女子师范大学校长杨荫榆，为校内一部分学生所反对，呈词互讦，由来已久。本部前任次长马叙伦、总长王九龄，均以办理棘手，迁延未决。迨士钊兼部，日在辞职或未实行负责之中，亦复未暇顾及。查此事之起，由于该校学生，设有自治会，倡言不认杨荫榆为校长，并于公开讲演之时，群起侮辱。该校长乃于素喜滋事之学生中，革除蒲振声、张平江、刘和珍、姜伯谛、许广平、郑德音等六人。该生等不服，联合校内男女各生，大施反抗运动。非但革生不肯出校，转而驱逐校长，锁闭办公室，阴止校长及办事人等入内，以致全校陷入无政府状态。由五月至今，三四月间，学生跳梁于内，校长侨置于外，为势僵然，一筹莫展。迩者士钊奉令调署，正拟切实查办，适该校长杨荫榆，拟具改组四班计划，请示前来。当以该校长职责所存，批令妥善办理。顷据该校长呈报：八月一日到校，顽劣学生，手持木棍砖石，志存殴辱，叫骂追逐，无所不至。又复撕毁布告，易以学生求援宣言，并派人驻守校门，禁阻校员出入，其余则乘坐汽车，四出求助。旋有男生多人，来校恫吓，并携带快镜，各处摄影。种种怪状，见者骇然等情。学生暴乱如此，迥出情理之外。窃思比年学风，嚣张已极。政府既乏长策，社会复无公评。四方不逞之徒，又从而扇发之，狙使青年男女，顽抗部校命令。是非颠例，一无准裁。该校长以一女流，明其职守，甘任劳怨，期有始终。虽其平时措置，未必尽当，平心而论，似亦为所难能。士钊每得该校长之谤书，思此辄为太息。或谓师生之情过伤，处置难期妥惬，原案虽不能易，人选似可通融。不知京师各校，以革除学生而谋逐校长，已非一次，其后因缘事变，借口调停，大抵革生留而校长去。胜负之数，伏于事先，横逆之生，惯如饮食，乖风流衍，以迄今兹，纲纪荡然，泰半由此。今若谬种相仍，再误三误，此其选软羞当世之士，其失小；公然纵子弟为恶，其失大。士钊详加考虑，此着断不可行。默察该校情形，各系教员，植党构扇，势甚强固，不可爬梳。而诸生荒学逾闲，恣为无忌，道路以目，亲者痛心。该校长任事以来，一切要害之政，并尚未能董理，而已怨毒之甚，一日难居。倘仍其旧贯，环境依然，即别求一人为继，度亦无能为役。士钊少负不羁之名，长习自由之说，名邦大学，负笈分驰，男女同班，亦尝亲与，所有社会交际、两性衔接之机缄缔构，一一考求。其中流以上之家，凡未成年之女子，殆无不惟家长阿保之命是从，文质彬彬，至可敬爱。从未见有不受检制，竟体忘形，啸聚男生，蔑视长上，家族不知所出，浪士从而推波，伪托文明，肆为驰骋，谨愿者尽丧所守，狡黠者毫无忌惮，学纪大紊，礼教全荒，如吾国今日女学之可悲叹者也。以此兴学，直是灭学。以此尊重女子，直是摧辱女子。钊念儿女乃家家所有，良用痛心，为政而人人悦之，亦无是理，该师范大学，号为全国女子最高学府，强自取柱，柔自取束，立表不正，其影可知。当此女教绝续之秋，宜为根本改图之计，拟请查照马前次长处理美术专门学校成例，将该大学暂行停办。该校长杨荫榆调部任用，一面遴选专家，妥速筹画。务期重立宏规，树之模楷，以副执政与民更始不遗女子之至意。是否有当，理合具文，仰祈钧鉴施行。再：该校学生，半由各省考送，家长戚族，未必在京，责令即时解散，亦未便操之过急。日者士钊曾偕部员，亲赴该校视察，见留校女生二十余人，起居饮食，诸感困苦。迹其行为，宜有惩罚，观其情态，亦甚可矜。当由部派员，商同各该保证人，妥为料理，无须警察干预。外传警察殴伤学生各节，全属讹言。此后校事部了，尤不至有学警冲突之虞。合并陈明。

**** 章士钊致段祺瑞呈文
     :PROPERTIES:
     :CUSTOM_ID: 19250812
     :END:


     - Note taken on [2019-11-06 三 22:37] \\
       此文1925年8月12日呈段祺瑞。实在搜不到，只能在《一个都不宽恕》里面复制粘贴。然后13日鲁迅就被免职。

敬折呈者，窃查官吏服务，首在恪守本分，服从命令。兹有本部佥事周树人，兼任国立女子师范大学教员，于本部下令停办该校以后，结合党徒，附和女生，倡设校务维持会，充任委员，似此违法抗令，殊属不合，应请明令免去本职，以示惩戒（并请补交高等文官惩戒委员会核议，以完法律手续）。是否有当，理合呈请鉴核施行。谨呈临时执政。

**** 鲁迅呈平政院状
     :PROPERTIES:
     :CUSTOM_ID: 19250822
     :END:
     - Note taken on [2019-11-06 三 22:40] \\
       1925年8月22日，鲁迅向平政院投递诉状，原文找不到，从《一个都不宽恕》中复制粘贴——然而《一》书本身就是从平政院的裁决书中抄的。

树人充教育部佥事，已十有四载，恪恭将事，故任职以来屡获奖叙。讵教育总长章士钊竟无故将树人呈请免职。查文官免职，系属惩戒处分之一。依《文官惩戒条例》第十八条之规定，须先交付惩戒始能依法执行。乃竟滥用职权，擅自处分，无故将树人免职，显违《文官惩戒条例》第一条及《文官保障法草案》第二条之规定。此种违法处分，实难自甘缄默。

**** 答KS君
     :PROPERTIES:
     :CUSTOM_ID: 19250828
     :END:
     - Note taken on [2019-11-06 三 22:58] \\
       董大中的[[https://books.google.com.hk/books?id=wY4BRZYJPwIC&pg=PA261&lpg=PA261&dq=%25E7%25AD%2594KS%25E5%2590%259B+%25E8%25B0%2581%25E6%2598%25AF+KS%25E5%2590%259B&source=bl&ots=UMX_1D7kuz&sig=ACfU3U0rghsRR2kYvkR17t3tApiC1vOW0g&hl=zh-CN&sa=X&redir_esc=y#v=onepage&q=%25E7%25AD%2594KS%25E5%2590%259B%2520%25E8%25B0%2581%25E6%2598%25AF%2520KS%25E5%2590%259B&f=false][《魯迅日記箋釋》]]也说 KS 君未详，我也就不考究了。原载《莽原》1925年8月28日周刊第19期

KS兄：

我很感谢你的殷勤的慰问，但对于你所愤慨的两点和几句结论，我却并不谓然，现在略说我的意见——

第一，章士钊将我免职，我倒并没有你似的觉得诧异，他那对于学校的手段，我也并没有你似的觉得诧异，因为我本就没有预期章士钊能做出比现在更好的事情来。我们看历史，能够据过去以推知未来，看一个人的已往的经历，也有一样的效用。你先有了一种无端的迷信，将章士钊当作学者或智识阶段的领袖看，于是从他的行为上感到失望，发生不平，其实是作茧自缚；他这人本来就只能这样，有着更好的期望倒是你自己的误谬。使我较为感到有趣的倒是几个向来称为学者或教授的人们，居然也渐次吞吞吐吐地来说微温话了，什么“政潮”咧，“党”咧，仿佛他们都是上帝一样，超然象外，十分公平似的。谁知道人世上并没有这样一道矮墙，骑着而又两脚踏地，左右稳妥，所以即使吞吞吐吐，也还是将自己的魂灵枭首通衢，挂出了原想竭力隐瞒的丑态。丑态，我说，倒还没有什么丢人，丑态而蒙着公正的皮，这才催人呕吐。但终于使我觉得有趣的是蒙着公正的皮的丑态，又自己开出帐来发表了。仿佛世界上还有光明，所以即便费尽心机，结果仍然是一个瞒不住。

第二，你这样注意于《甲寅周刊》，也使我莫明其妙。《甲寅》第一次出版时，我想，大约章士钊还不过熟读了几十篇唐宋八大家文，所以模仿吞剥，看去还近于清通。至于这一回，却大大地退步了，关于内容的事且不说，即以文章论，就比先前不通得多，连成语也用不清楚，如“每下愈况”之类。尤其害事的是他似乎后来又念了几篇骈文，没有融化，而急于挦撦，所以弄得文字庞杂，有如泥浆混着沙砾一样。即如他那《停办北京女子师范大学呈文》中有云，“钊念儿女乃家家所有良用痛心为政而人人悦之亦无是理”，旁加密圈，想是得意之笔了。但比起何《齐姜醉遣晋公子赋》的“公子固翩翩绝世未免有情少年而碌碌因人安能成事”来，就显得字句和声调都怎样陋弱可哂。何比他高明得多，尚且不能入作者之林，章士钊的文章更于何处讨生活呢？况且，前载公文，接着就是通信，精神虽然是自己广告性的半官报，形式却成了公报尺牍合璧了，我中国自有文字以来，实在没有过这样滑稽体式的著作。这种东西，用处只有一种，就是可以借此看看社会的暗角落里，有着怎样灰色的人们，以为现在是攀附显现的时候了，也都吞吞吐吐的来开口。至于别的用处，我委实至今还想不出来。倘说这是复古运动的代表，那可是只见得复古派的可怜，不过以此当作讣闻，公布文言文的气绝罢了。

所以，即使真如你所说，将有文言白话之争，我以为也该是争的终结，而非争的开头，因为《甲寅》不足称为敌手，也无所谓战斗。倘要开头，他们还得有一个更通古学，更长古文的人，才能胜对垒之任，单是现在似的每周印一回公牍和游谈的堆积，纸张虽白，圈点虽多，是毫无用处的。

**** 「碰壁」之餘
     :PROPERTIES:
     :CUSTOM_ID: 19250921
     :END:
     - Note taken on [2019-11-10 日 14:12] \\
       本文就是在怼陈西滢之余顺带提一笔章士钊，编在这一节其实不是很合适。
     - Note taken on [2019-11-10 日 14:10] \\
       高仁山　江苏江阴人，当时任北京大学教授。他在一九二五年五月三十一日《晨报》“时论”栏发表的《大家不管的女师大》一文中说：“最奇怪的就是女师大的专任及主任教授都那里去了？学校闹到这样地步，何以大家不出来设法维持？诸位专任及主任教授，顶好同学生联合起来，商议维持学校的办法，不要让教一点两点钟兼任教员来干涉你们诸位自己学校的事情。”
     - Note taken on [2019-11-10 日 14:08] \\
       想不到《女师大观剧的经验》的作者就是李四光，这篇也找不到。
     - Note taken on [2019-11-10 日 13:56] \\
       这是一篇署名为“一个女读者”给《现代评论》记者的信，载于该刊第一卷第十五期（一九二五年三月二十一日）。主要意思是说：女师大学生迭次驱杨的“那些宣言书中所列举杨氏的罪名，既大都不能成立罪名……而这回风潮的产生和发展，校内校外尚别有人在那里主使。”又说“女师大是中国唯一的女子大学；杨氏也是充任大学校长的唯一的中国女子……我们应否任她受教育当局或其他任何方面的排挤攻击？我们女子应否自己还去帮着摧残她？”
     - Note taken on [2019-11-10 日 13:55] \\
       从维基文库粘贴过来的，所以是繁体字。

女師大事件在北京似乎竟頗算一個問題，號稱「大報」如所謂《現代評論》者，居然也「評論」了好幾次。據我所記得的，是先有「一個女讀者」的一封信，無名小女卒，不在話下。此後是兩個作者的「評論」了：陳西瀅先生在[[*%E9%97%B2%E8%AF%9D%EF%BC%88%E7%B2%89%E5%88%B7%E8%8C%85%E5%8E%95%EF%BC%89][《闲话》]]之間評為「臭毛廁」，李仲揆先生的《在女師大觀劇的經驗》裡則比作戲場。我很吃驚於同是人，而眼光竟有這麼不同；但究竟同是人，所以意見也不無符合之點：都不將學校看作學校。這一點，也可以包括楊蔭榆女士的「學校猶家庭」和段祺瑞執政的「先父兄之教」。

陳西瀅先生是「久已夫非一日矣」的《閒話》作家，那大名我在報紙的廣告上早經看熟了，然而大概還是一位高人，所以遇有不合自意的，便一氣呵成屎橛，而世界上蛆蟲也委實太多。至於李仲揆先生其人也者，我在《女師風潮紀事》上才識大名，是八月一日擁楊蔭榆女士攻入學校的三勇士之一；到現在，卻又知道他還是一位達人了，庸人以為學潮的，到他眼睛裡就等於「觀劇」：這是何等逍遙自在。

據文章上說，這位李仲揆先生是和楊女士「不過見面兩次」，但卻被用電話邀去看「名振一時的文明新戲」去了，幸而李先生自有腳踏車，否則，還要用汽車來迎接哩。我真自恨福薄，一直活到現在，壽命已不可謂不長，而從沒有遇見過一個不大認識的女士來邀「觀劇」；對於女師大的事說了幾句話，尚且因為不過是教一兩點功課的講師，「碰壁之後」，還很恭聽了些高仁山先生在《晨報》上所發表的偉論。真的，世界上實在又有各式各樣的運氣，各式各樣的嘴，各式各樣的眼睛。

接著又是西瀅先生的《閒話》：「現在一部分報紙的篇幅，幾乎全讓女師風潮占去了。現在大部分愛國運動的青年的時間，也幾乎全讓女師風潮占去了。……女師風潮實在是了不得的大事情，實在有了不得的大意義。」臨末還有頗為俏皮的結論道：「外國人說，中國人是重男輕女的。我看不見得吧。」

我看也未必一定「見得」。正如人們有各式各樣的眼睛一樣，也有各式各樣的心思，手段。便是外國人的尊重一切女性的事，倘使好講冷話的人說起來，也許以為意在於一個女性。然而侮蔑若干女性的事，有時也就可以說意在於一個女性。偏執的弗羅特先生宣傳了「精神分析」之後，許多正人君子的外套都被撕碎了。但撕下了正人君子的外套的也不一定就是「小人」，只要並非自以為還鑽在外套裡的不顯本相的腳色。

我看也未必一定「見得」。中國人是「聖之時者也」教徒，況且活在二十世紀了，有華道理，有洋道理，輕重當然是都隨意而無不合於道的：重男輕女也行，重女輕男也行，為了一個女性而重一切女性或輕若干女性也行，為了一個男人而輕若干女性或男性也行……。所可惜的是自從西瀅先生看出底細之後，除了啞吧或半陰陽，就都墜入弗羅特先生所掘的陷坑裡去了。

自己墜下去的是自作自受，可恨者乃是還要帶累超然似的局外人，例如女師大——對不起，又是女師大——風潮，從有些眼睛看來，原是不值得提起的，但因為竟占去了許多可貴的東西，如「報紙的篇幅」「青年的時間」之類，所以，連《現代評論》的「篇幅」和西瀅先生的時間也被拖累著占去一點了，而尤其罪大惡極的是觸犯了什麼「重男輕女」重女輕男這些大秘密。倘不是西瀅先生首先想到，提出，大概是要被含胡過去了的。

我看，奧國的學者實在有些偏激，弗羅特就是其一，他的分析精神，竟一律看待，不讓誰站在超人間的上帝的地位上。還有那短命的Otto Weininger，他的痛駡女人，不但不管她是校長，學生，同鄉，親戚，愛人，自己的太太，太太的同鄉，簡直連自己的媽都罵在內。這實在和弗羅特說一樣，都使人難於利用。不知道咱們的教授或學者們，可有方法補救沒有？但是，我要先報告一個好消息：Weininger早用手槍自殺了。這已經有劉百昭率領打手痛打女師大——對不起，又是女師大——的「毛丫頭」一般「痛快」，他的話也就大可置之不理了罷。

還有一個好消息。「毛丫頭」打出之後，張崧年先生引「羅素之所信」道，「因世人之愚，許多問題或終於不免只有武力可以解決也！」（《京副》二五○號）又據楊蔭榆女士，章士釗總長者流之所說，則搗亂的「毛丫頭」是極少數，可見中國的聰明人還多著哩，這是大可以樂觀的。

忽而想談談我自己的事了。

我今年已經有兩次被封為「學者」，而發表之後，也就即刻取消。第一次是我主張中國的青年應當多看外國書，少看，或者竟不看中國書的時候，便有論客以為素稱學者的魯迅不該如此，而現在竟至如此，則不但決非學者，而且還有洋奴的嫌疑。第二次就是這回僉事免職之後，我在《莽原》上發表了答KS君信，論及章士釗的腳色和文章的時候，又有論客以為因失了「區區僉事」而反對章士釗，確是氣量狹小，沒有「學者的態度」；而且，豈但沒有「學者的態度」而已哉，還有「人格卑污」的嫌疑云。

其實，沒有「學者的態度」，那就不是學者嘍，而有些人偏要硬派我做學者。至於何時封贈，何時考定，卻連我自己也一點不知道。待到他們在報上說出我是學者，我自己也借此知道了原來我是學者的時候，則已經同時發表了我的罪狀，接著就將這體面名稱革掉了，雖然總該還要恢復，以便第三次的藉口。

據我想來，僉事——文士詩人往往誤作簽事，今據官書正定——這一個官兒倒也並不算怎樣「區區」，只要看我免職之後，就頗有些人在那裡鑽謀樸缺，便是一個老大的證據。至於又有些人以為無足重輕者，大約自己現在還不過做幾句「說不出」的詩文，所以不知不覺地就來「慷他人之慨」了罷，因為人的將來是想不到的。然而，慚愧我還不是「臣罪當誅兮天王聖明」式的理想奴才，所以竟不能「盡如人意」，已經在平政院對章士釗提起訴訟了。

提起訴訟之後，我只在答KS君信裡論及一回章士釗，但聽說已經要「人格卑污」了。然而別一論客卻道是並不大罵，所以魯迅究竟不足取。我所經驗的事委實有點希奇，每有「碰壁」一類的事故，平時回護我的大抵願我設法應付，甚至於暫圖苟全。平時憎惡我的卻總希望我做一個完人，即使敵手用了卑劣的流言和陰謀，也應該正襟危坐，毫無憤怨，默默地吃苦；或則戟指嚼舌，噴血而亡。為什麼呢？自然是專為顧全我的人格起見嘍。

夠了，我其實又何嘗「碰壁」，至多也不過遇見了「鬼打牆」罷了。

**** 章士钊答状
     :PROPERTIES:
     :CUSTOM_ID: 19251013
     :END:
     - Note taken on [2019-11-06 三 22:43] \\
       继续从《一个都不宽恕》中抄录，本答辩当年10月13日送到鲁迅处。

查周树人免职理由，本部上执政呈文业经声叙明白，兹更为贵院述之：本年八月十日，本部遵照执政训令停办国立女子师范大学，当委部员刘百昭等前往接收，不意本部佥事周树人，原系社会司第一科科长，地位职务均极重要，乃于本部执行令准停办该校，正属行政严重之时，竟敢勾结该校教员、捣乱分子及少数不良学生，谬托校务维持会名义，妄自主张，公然与所服务之官署悍然立于反抗地位。据接收委员会报告，入校办公时亲见该员盘踞校舍，集众开会，确有种种不合之行为。又该伪校务维持会，擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政，既情理之所难容，亦法律之所不许。查《官吏服务令》第一条：凡官吏应竭尽忠勤，服从法律命令以行职务。第二条：长官就其范围以内所发命令，属员有服从之义务。第四条：属官对于长官所发命令如有意见，得随时陈述。第二十九条：凡官吏有违上开各条者，该管长官依其情节，分别训告，或付惩戒。规定至为明切。今周树人既未将意见陈述，复以本部属员不服从本部长官命令，实已违反《文官服务令》第一第二第四各条之规定。本部原拟循例呈请交付惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈烈，难以平息，不得已于八月十二日呈请执政将周树人免职。十三日由执政明令照准，此周树人免职经过之实在情形也。查原诉状内有无故免职等语，系欲以无故二字遮掩其与女师大教习学生集会违令各行为，希图脱免。至追加理由所称本部呈请执政将周树人免职稿件倒填日月一节，实因此项免职事件情出非常，本部总长系于十二日面呈执政，即日明令发表，随后再将呈稿补发存案。即日补发，无所谓倒填，情势急迫，本部总长应有权执行此非常处分，周树人不得引为口实。兹特详叙事实答辩如右。

**** 鲁讯互辩书
     :PROPERTIES:
     :CUSTOM_ID: 19251016
     :END:

     - Note taken on [2019-11-06 三 22:46] \\
       鲁迅博物馆现存一份鲁迅亲自收藏的互辩书草稿。写作日期是1925年10月16日。节录如下。

一、查总长妄称□□（按“树人”二字。下同）以部员资格勾结该校教员捣乱分子及少数不良学生，谬托校务维持会名义，妄有主张等语，全不明言去勾结何等捣乱分子及不良学生何人，□□主张何事，信口虚捏，全无事实证据，殊不称长官体统，有玷人格。况各部职员兼任国立各校教员不下数百人，□□为女师大兼任教员之一。在部则为官吏，在校则为教员。两种资格，各有职责、不容牵混。……

二、□□平日品性人格，向不干预外事，社会共晓。此次女师大应否解散尤与□□无涉。故该总长对于该校举动是否合宜，□□从不过问。现该答辩内有“周树人既未将意见陈述”一言可知从未干预。至□□在女师大担任教员职务，一方关于教课，固为个人应负责；一方关于公众，又为团体共负之责。若由团体发表之事件，应由团体负责，尤不能涉及个人，更不能专诬□□一人而加以非法（处分）。譬如现北大与教育部脱离关系。公然反抗，是为团体行动，岂北大教员之兼教部职员者将共负其责耶？

三、该答辩称“据接收委员报告云确有种种不法行为”，试问报告委员何人？报告何在？□□盘踞何状？不合何事？概未明言，即入人罪。且说教员维持校务为伪托，伪者何在？抑凡为教员者于法不得维持校务耶？

四、答辩又称“该伪校务维持会擅举该员为委员，该员又不声明否认，显系有意抗阻本部行政”。查校务维持会公举□□为委员，系在8月13日，而该总长呈请免职，据称在12日。岂预知将举□□为委员而先为免职之罪名耶？况他人公举□□何能为□□之罪？

五、……□□充教育部佥事、社会教育司科长，与女师大停办与否，职守上毫无关系，故对于女师大停办命令从未一字陈述意见，亦实无陈述之职责。既未陈述，既无违反命令举动及言论可知。乃章士钊反以未陈述意见指为抗违命令，其理由何在？且又以未陈述意见即为违反服务令第一、二、四等条，其理由又安在？殊不可解。岂官吏须出位陈述职守以外之意见方为遵守服务令耶？何悖谬至此！

六、该答辩谓“本部原拟循例呈请惩戒，乃其时女师大风潮最剧，形势严重，若不即时采取行政处分，一任周树人以部员公然反抗本部行政，深恐群相效尤，此项风潮愈演愈恶，难以平息，不得已呈请免职。”查以教长权力整顿一女校，何至形势严重？依法免部员职，何至迫不及待？风潮难平，事系学界？何至用非常处分。此等饰词，殊属可笑。且所谓行政处分原以合法为范围。凡违法令之行政处分当然无效。此《官吏服务令》所明白规定者。今章士钊不依法惩戒，殊属身为长官，弁髦法令。

**** 从胡须说到牙齿（节录）
     :PROPERTIES:
     :CUSTOM_ID: 19251109
     :END:

     - Note taken on [2019-11-07 四 19:26] \\
       我觉得本文跟甲寅没有什么关系，只是刚好跟章士钊打官司，不放过攻击他的机会而已。《太阳晒屁股赋》现在是找不到了，如果去图书馆翻《晶报》的微缩胶片可能还能找到。

一翻《呐喊》，才又记起我曾在中华民国九年双十节的前几天做过一篇《头发的故事》；去年，距今快要一整年了罢，那时是《语丝》出世未久，我又曾为它写了一篇《说胡须》。

实在似乎很有些章士钊之所谓“每况愈下”了，——自然，这一句成语，也并不是章士钊首先用错的，但因为他既以擅长旧学自居，我又正在给他打官司，昕以就栽在他身上。当时就听说，——或者也是时行的“流言”，——一位北京大学的名教授就愤慨过，以为从胡须说起，一直说下去，将来就要说到屁股，则于是乎便和上海的《晶报》一样了。为什么呢？这须是熟精今典的人们才知道，后进的“束发小生”是不容易了然的。因为《晶报》上曾经登过一篇《太阳晒屁股赋》，屁股和胡须又都是人身的一部分，既说此部，即难免不说彼部，正如看见洗脸的人，敏捷而聪明的学者即能推见他一直洗下去，将来一定要洗到屁股。所以有志于做gentleman者，为防微杜渐起见，应该在背后给一顿奚落的。——如果说此外还有深意，那我可不得而知了。

昔者窃闻之：欧美的文明人讳言下体以及和下体略有渊源的事物。假如以生殖器为中心而画一正圆形，则凡在圆周以内者均在讳言之列；而圆之半径，则美国者大于英。中国的下等人，是不讳言的；古之上等人似乎也不讳，所以虽是公子而可以名为黑臀。讳之始，不知在什么时候；而将英美的半径放大，直至于口鼻之间或更在其上，则于一千九百二十四年秋。

文人墨客大概是感性太锐敏了之故罢，向来就很娇气，什么也给他说不得，见不得，听不得，想不得。道学先生于是乎从而禁之，虽然很像背道而驰，其实倒是心心相印。然而他们还是一看见堂客的手帕或者姨太太的荒冢就要做诗。我现在虽然也弄弄笔墨做做白话文，但才气却仿佛早经注定是该在“水平线”之下似的？所以看见手帕或荒冢之类，倒无动于中；只记得在解剖室里第一次要在女性的尸体上动刀的时候，可似乎略有做诗之意，——但是，不过“之意”而已，并没有诗，读者幸勿误会，以为我有诗集将要精装行世，传之其人，先在此预告。后来，也就连“之意”都没有了，大约是因为见惯了缘故罢，正如下等人的说惯一样。否则，也许现在不但不敢说胡须，而且简直非“人之初性本善论”或“天地玄黄赋”便不屑做。遥想土耳其革命后，撕去女人的面幕，是多么下等的事？呜呼，她们已将嘴巴露出，将来一定要光着屁股走路了！

**** 十四年的“读经”
     :PROPERTIES:
     :CUSTOM_ID: 19251127
     :END:

自从章士钊主张读经以来，论坛上又很出现了一些论议，如谓经不必尊，读经乃是开倒车之类。我以为这都是多事的，因为民国十四年的“读经”，也如民国前四年，四年，或将来的二十四年一样，主张者的意思，大抵并不如反对者所想像的那么一回事。

尊孔，崇儒，专经，复古，由来已经很久了。皇帝和大臣们，向来总要取其一端，或者“以孝治天下”，或者“以忠诏天下”，而且又“以贞节励天下”。但是，二十四史不现在么？其中有多少孝子，忠臣，节妇和烈女？自然，或者是多到历史上装不下去了；那么，去翻专夸本地人物的府县志书去。我可以说，可惜男的孝子和忠臣也不多的，只有节烈的妇女的名册却大抵有一大卷以至几卷。孔子之徒的经，真不知读到那里去了；倒是不识字的妇女们能实践。还有，欧战时候的参战，我们不是常常自负的么？但可曾用《论语》感化过德国兵，用《易经》咒翻了潜水艇呢？儒者们引为劳绩的，倒是那大抵目不识丁的华工！

所以要中国好，或者倒不如不识字罢，一识字，就有近乎读经的病根了。“瞰亡往拜”“出疆载质”的最巧玩艺儿，经上都有，我读熟过的。只有几个胡涂透顶的笨牛，真会诚心诚意地来主张读经。而且这样的脚色，也不消和他们讨论。他们虽说什么经，什么古，实在不过是空嚷嚷。问他们经可是要读到像颜回，子思，孟轲，朱熹，秦桧（他是状元），王守仁，徐世昌，曹锟；古可是要复到像清（即所谓“本朝”），元，金，唐，汉，禹汤文武周公，无怀氏，葛天氏？他们其实都没有定见。他们也知不清颜回以至曹锟为人怎样，“本朝”以至葛天氏情形如何；不过像苍蝇们失掉了垃圾堆，自不免嗡嗡地叫。况且既然是诚心诚意主张读经的笨牛，则决无钻营，取巧，献媚的手段可知，一定不会阔气；他的主张，自然也决不会发生什么效力的。

至于现在的能以他的主张，引起若干议论的，则大概是阔人。阔人决不是笨牛，否则，他早已伏处牖下，老死田间了。现在岂不是正值“人心不古”的时候么？则其所以得阔之道，居然可知。他们的主张，其实并非那些笨牛一般的真主张，是所谓别有用意；反对者们以为他真相信读经可以救国，真是“谬以千里”了！

我总相信现在的阔人都是聪明人；反过来说，就是倘使老实，必不能阔是也。至于所挂的招牌是佛学，是孔道，那倒没有什么关系。总而言之，是读经已经读过了，很悟到一点玩意儿，这种玩意儿，是孔二先生的先生老聃的大著作里就有的，此后的书本子里还随时可得。所以他们都比不识字的节妇，烈女，华工聪明；甚而至于比真要读经的笨牛还聪明。何也？曰：“学而优则仕”故也。倘若“学”而不“优”，则以笨牛没世，其读经的主张，也不为世间所知。

孔子岂不是“圣之时者也”么，而况“之徒”呢？现在是主张“读经”的时候了。武则天做皇帝，谁敢说“男尊女卑”？多数主义虽然现称过激派，如果在列宁治下，则共产之合于葛天氏，一定可以考据出来的。但幸而现在英国和日本的力量还不弱，所以主张亲俄者，是被卢布换去了良心。

我看不见读经之徒的良心怎样，但我觉得他们大抵是聪明人，而这聪明，就是从读经和古文得来的。我们这曾经文明过而后来奉迎过蒙古人满洲人大驾了的国度里，古书实在太多，倘不是笨牛，读一点就可以知道，怎样敷衍，偷生，献媚，弄权，自私，然而能够假借大义，窃取美名。再进一步，并可以悟出中国人是健忘的，无论怎样言行不符，名实不副，前后矛盾，撒诳造谣，蝇营狗苟，都不要紧，经过若干时候，自然被忘得干干净净；只要留下一点卫道模样的文字，将来仍不失为“正人君子”。况且即使将来没有“正人君子”之称，于目下的实利又何损哉？

这一类的主张读经者，是明知道读经不足以救国的，也不希望人们都读成他自己那样的；但是，耍些把戏，将人们作笨牛看则有之，“读经”不过是这一回耍把戏偶尔用到的工具。抗议的诸公倘若不明乎此，还要正经老实地来评道理，谈利害，那我可不再客气，也要将你们归入诚心诚意主张读经的笨牛类里去了。

以这样文不对题的话来解释“俨乎其然”的主张，我自己也知道有不恭之嫌，然而我又自信我的话，因为我也是从“读经”得来的。我几乎读过十三经。

衰老的国度大概就免不了这类现象。这正如人体一样，年事老了，废料愈积愈多，组织间又沉积下矿质，使组织变硬，易就于灭亡。一面，则原是养卫人体的游走细胞（Wanderzelle）渐次变性，只顾自己，只要组织间有小洞，它便钻，蚕食各组织，使组织耗损，易就于灭亡。俄国有名的医学者梅契尼珂夫（EliasMetschnikov）特地给他别立了一个名目：大嚼细胞（Fresserzelle）。据说，必须扑灭了这些，人体才免于老衰；要扑灭这些，则须每日服用一种酸性剂。他自己就实行着。

古国的灭亡，就因为大部分的组织被太多的古习惯教养得硬化了，不再能够转移，来适应新环境。若干分子又被太多的坏经验教养得聪明了，于是变性，知道在硬化的社会里，不妨妄行。单是妄行的是可与论议的，故意妄行的却无须再与谈理。惟一的疗救，是在另开药方：酸性剂，或者简直是强酸剂。

不提防临末又提到了一个俄国人，怕又有人要疑心我收到卢布了罢。我现在郑重声明：我没有收过一张纸卢布。因为俄国还未赤化之前，他已经死掉了，是生了别的急病，和他那正在实验的药的有效与否这问题无干。

**** 学界的三魂
     :PROPERTIES:
     :CUSTOM_ID: 19260201
     :END:

     - Note taken on [2019-11-07 四 19:34] \\
       这篇是从维基文库复制粘贴过来的，见 https://zh.wikisource.org/zh/%E5%AD%B8%E7%95%8C%E7%9A%84%E4%B8%89%E9%AD%82 。其实我觉得鲁迅在这里只是顺手骂章士钊而已。

從《京報副刊》上知道有一種叫《國魂》的期刊，曾有一篇文章說章士釗固然不好，然而反對章士釗的「學匪」們也應該打倒。我不知道大意是否真如我所記得？但這也沒有什麼關係，因為不過引起我想到一個題目，和那原文是不相干的。意思是，中國舊說，本以為人有三魂六魄，或云七魄；

國魂也該這樣。而這三魂之中，似乎一是「官魂」，一是「匪魂」，還有一個是什麼呢？也許是「民魂」罷，我不很能夠決定。又因為我的見聞很偏隘，所以未敢悉指中國全社會，只好縮而小之曰「學界」。

中國人的官癮實在深，漢重孝廉而有埋兒刻木，宋重理學而有高帽破靴，清重帖括而有「且夫」「然則」。總而言之：那魂靈就在做官，——行官勢，擺官腔，打官話。頂著一個皇帝做傀儡，得罪了官就是得罪了皇帝，於是那些人就得了雅號曰「匪徒」。學界的打官話是始於去年，凡反對章士釗的都得了「土匪」，「學匪」，「學棍」的稱號，但仍然不知道從誰的口中說出，所以還不外乎一種「流言」。

但這也足見去年學界之糟了，竟破天荒的有了學匪。以大點的國事來比罷，太平盛世，是沒有匪的；待到群盜如毛時，看舊史，一定是外戚，宦官，奸臣，小人當國，即使大打一通官話，那結果也還是「嗚呼哀哉」。當這「嗚呼哀哉」之前，小民便大抵相率而為盜，所以我相信源增先生的話：

「表面上看只是些土匪與強盜，其實是農民革命軍。」（《國民新報副刊》四三）那麼，社會不是改進了麼？並不，我雖然也是被諡為「土匪」之一，卻並不想為老前輩們飾非掩過。農民是不來奪取政權的，源增先生又道：「任三五熱心家將皇帝推倒，自己過皇帝癮去。」但這時候，匪便被稱為帝，除遺老外，文人學者卻都來恭維，又稱反對他的為匪了。

所以中國的國魂裡大概總有這兩種魂：官魂和匪魂。這也並非硬要將我輩的魂擠進國魂裡去，貪圖與教授名流的魂為伍，只因為事實仿佛是這樣。社會諸色人等，愛看《雙官誥》，也愛看《四傑村》，望偏安巴蜀的劉玄德成功，也願意打家劫舍的宋公明得法；至少，是受了官的恩惠時候則豔羨官僚，受了官的剝削時候便同情匪類。但這也是人情之常；

倘使連這一點反抗心都沒有，豈不就成為萬劫不復的奴才了？

然而國情不同，國魂也就兩樣。記得在日本留學時候，有些同學問我在中國最有大利的買賣是什麼，我答道：「造反。」

他們便大駭怪。在萬世一系的國度裡，那時聽到皇帝可以一腳踢落，就如我們聽說父母可以一棒打殺一般。為一部分士女所心悅誠服的李景林先生，可就深知此意了，要是報紙上所傳非虛。今天的《京報》即載著他對某外交官的談話道：

「予預計於舊曆正月間，當能與君在天津晤談；若天津攻擊竟至失敗，則擬俟三四月間捲土重來，若再失敗，則暫投土匪，徐養兵力，以待時機」云。但他所希望的不是做皇帝，那大概是因為中華民國之故罷。

所謂學界，是一種發生較新的階級，本該可以有將舊魂靈略加湔洗之望了，但聽到「學官」的官話，和「學匪」的新名，則似乎還走著舊道路。那末，當然也得打倒的。這來打倒他的是「民魂」，是國魂的第三種。先前不很發揚，所以一鬧之後，終不自取政權，而只「任三五熱心家將皇帝推倒，自己過皇帝癮去」了。

惟有民魂是值得寶貴的，惟有他發揚起來，中國才有真進步。但是，當此連學界也倒走舊路的時候，怎能輕易地發揮得出來呢？在烏煙瘴氣之中，有官之所謂「匪」和民之所謂匪；有官之所謂「民」和民之所謂民；有官以為「匪」而其實是真的國民，有官以為「民」而其實是衙役和馬弁。所以貌似「民魂」的，有時仍不免為「官魂」，這是鑒別魂靈者所應該十分注意的。

話又說遠了，回到本題去。去年，自從章士釗提了「整頓學風」的招牌，上了教育總長的大任之後，學界裡就官氣彌漫，順我者「通」，逆我者「匪」，官腔官話的餘氣，至今還沒有完。但學界卻也幸而因此分清了顏色；只是代表官魂的還不是章士釗，因為上頭還有「減膳」執政在，他至多不過做了一個官魄；現在是在天津「徐養兵力，以待時機」了。我不看《甲寅》，不知道說些什麼話：官話呢，匪話呢，民話呢，衙役馬弁話呢？……

附記

今天到東城去教書，在新潮社看見陳源教授的信，在北京大學門口看見《現代評論》，那《閒話》裡正議論著章士釗的《甲寅》，說「也漸漸的有了生氣了。可見做時事文章的人官實在是做不得的，……自然有些『土匪』不妨同時做官僚，……」這麼一來，我上文的「逆我者『匪』」，「官腔官話的餘氣」云云，就又有了「放冷箭」的嫌疑了。現在特地聲明：我原先是不過就一般而言，如果陳教授覺得痛了，那是中了流彈。要我在「至今還沒有完」之後，加一句「如陳源等輩就是」，自然也可以。至於「順我者『通』」的通字，卻是此刻所改的，那根據就在章士釗之曾稱陳源為「通品」。別人的褒獎，本不應拿來譏笑本人，然而陳源現就用著「土匪」的字樣。有一回的《閒話》（《現代評論》五十）道：「我們中國的批評家實在太宏博了。他們……在地上找尋竊賊，以致整大本的剽竊，他們倒往往視而不見。要舉個例嗎？還是不說吧，我實在不敢再開罪『思想界的權威』。」按照他這回的慷慨激昂例，如果要免於「卑劣」且有「半分人氣」，是早應該說明誰是土匪，積案怎樣，誰是剽竊，證據如何的。現在倘有記得那括弧中的「思想界的權威」六字，即曾見於《民報副刊》廣告上的我的姓名之上，就知道這位陳源教授的「人氣」有幾多。

從此，我就以別人所說的「東吉祥派」、「正人君子」、「通品」等字樣，加于陳源之上了，這回是用了一個「通」字；我要「以眼還眼以牙還牙」，或者以半牙，以兩牙還一牙，因為我是人，難於上帝似的銖兩悉稱。如果我沒有做，那是我的無力，並非我大度，寬恕了加害於我的敵人。還有，有些下賤東西，每以穢物擲人，以為人必不屑較，一計較，倒是你自己失了人格。我可要照樣的擲過去，要是他擲來。但對於沒有這樣舉動的人，我卻不肯先動手；而且也以文字為限，「捏造事實」和「散佈『流言』」的鬼蜮的長技，自信至今還不屑為。在馬弁們的眼裡雖然是「土匪」，然而「盜亦有道」的。記起一件別的事來了。

前幾天九校「索薪」的時候，我也當作一個代表，因此很會見了幾個前「公理維持會」即「女大後援會」中人。幸而他們倒並不將我捆送三貝子花園或運入深山，「投畀豺虎」，也沒有實行「割席」，將板凳鋸開。終於「學官」「學匪」，都化為「學丐」，同聚一堂，大討其欠帳，——

自然是討不來。記得有一個洋鬼子說過：中國先是官國，後來是土匪國，將來是乞丐國。單就學界而論，似乎很有點上這軌道了。想來一定有些人要後悔，去年竟抱了「有奶不是娘」主義，來反對章士釗的罷。

一月二十五日東壁燈下寫。

**** 国务总理贾德耀签署了给教育总长的训令（临时执政训令第十三号）
     :PROPERTIES:
     :CUSTOM_ID: 19260331
     :END:

     - Note taken on [2019-11-06 三 22:51] \\
       格式有点问题，「国务总理贾德耀教育总长」与「中华民国十五年三月三十一日」当右对齐。
据平政院院长汪大燮呈，审理前教育部佥事周树人陈诉不服教育部呈请免职之处分，指为违法，提起行政诉讼一案，依法裁决教育部之处分应予取消等语，著交教育部查照执行。

此令

国务总理贾德耀

教育总长

中华民国十五年三月三十一日



**** 再来一次
     :PROPERTIES:
     :CUSTOM_ID: 19260610
     :END:

去年编定《热风》时，还有绅士们所谓“存心忠厚”之意，很删削了好几篇。但有一篇，却原想编进去的，因为失掉了稿子，便只好从缺。现在居然寻出来了；待《热风》再版时，添上这篇，登一个广告，使迷信我的文字的读者们再买一本，于我倒不无裨益。但是，算了罢，这实在不很有趣。不如再登一次，将来收入杂感第三集，也就算作补遗罢。

这是关于章士钊先生的——两个桃子杀了三个读书人

章行严先生在上海批评他之所谓“新文化”说，“二桃杀三士”怎样好，“两个桃子杀了三个读书人”便怎样坏，而归结到新文化之“是亦不可以已乎？”

是亦大可以已者也！「[[#19230800][二桃杀三士]]」并非僻典，旧文化书中常见的。但既然是“谁能为此谋？相国齐晏子。”我们便看看《晏子春秋》罢。

《晏子春秋》现有上海石印本，容易入手的了，这古典就在该石印本的卷二之内。大意是“公孙接田开疆古冶子事景公，以勇力搏虎闻，晏子过而趋，三子者不起，”于是晏老先生以为无礼，和景公说，要除去他们了。那方法是请景公使人送他们两个桃子，说道：“你们三位就照着功劳吃桃罢。”呵，这可就闹起来了：

“公孙接仰天而叹曰，‘晏子，智人也，夫使公之计吾功者，不受桃，是无勇也。士众而桃寡，何不计功而食桃矣？接一搏猏而再搏虎，若接之功，可以食桃而无与人同矣。’援桃而起。

“古冶子曰，‘吾尝从君济于河，鼋衔左骖以入砥柱之流。当时也，冶少不能游，潜行逆流百步，顺流九里，得鼋杀之，左操骖尾，右挈鼋头，鹤跃而出。津人皆曰，河伯也；若冶视之，则大鼋之首。若冶之功，可以食桃而无与人同矣！二子何不反桃？’抽剑而起。”

钞书太讨厌。总而言之，后来那二士自愧功不如古冶子，自杀了；古冶子不愿独生，也自杀了：于是乎就成了“二桃杀三士”。

我们虽然不知道这三士于旧文化有无心得，但既然书上说是“以勇力闻”，便不能说他们是“读书人”。倘使《梁父吟》说是“二桃杀三勇士”，自然更可了然，可惜那是五言诗，不能增字，所以不得不作“二桃杀三士”，于是也就害了章行严先生解作“两个桃子杀了三个读书人”。

旧文化也实在太难解，古典也诚然太难记，而那两个旧桃子也未免太作怪：不但那时使三个读书人因此送命，到现在还使一个读书人因此出丑，“是亦不可以已乎”！

去年，因为“每下愈况”问题，我曾经很受了些自以为公平的青年的教训，说是因为他革去了我的“签事”，我便那么奚落他。现在我在此只得特别声明：这还是一九二三年九月所作，登在《晨报副刊》上的。那时的《晨报副刊》，编辑尚不是陪过泰戈尔先生的“诗哲”，也还未负有逼死别人，掐死自己的使命，所以间或也登一点我似的俗人的文章；而我那时和这位后来称为“孤桐先生”的，也毫无“睚眦之怨”。那“动机”，大概不过是想给白话的流行帮点忙。

在这样“祸从口出”之秋，给自己也辩护得周到一点罢。或者将曰，且夫这次来补遗，却有“打落水狗”之嫌，“动机”就很“不纯洁”了。然而我以为也并不。自然，和不多时以前，士钊秘长运筹帷幄，假公济私，谋杀学生，通辑异己之际，“正人君子”时而相帮讥笑着被缉诸人的逃亡，时而“孤桐先生”“孤桐先生”叫得热剌剌地的时候一比较，目下诚不免有落寞之感。但据我看来，他其实并未落水，不过“安住”在租界里而已：北京依旧是他所豢养过的东西在张牙舞爪，他所勾结着的报馆在颠倒是非，他所栽培成的女校在兴风作浪：依然是他的世界。

在“桃子”上给一下小打击，岂遂可与“打落水狗”同日而语哉？！

但不知怎的，这位“孤桐先生”竟在《甲寅》上辩起来了，以为这不过是小事。这是真的，不过是小事。弄错一点，又何伤乎？即使不知道晏子，不知道齐国，于中国也无损。农民谁懂得《梁父吟》呢，农业也仍然可以救国的。但我以为攻击白话的豪举，可也大可以不必了；将白话来代文言，即使有点不妥，反正也不过是小事情。

我虽然未曾在“孤桐先生”门下钻，没有看见满桌满床满地的什么德文书的荣幸，但偶然见到他所发表的“文言”，知道他于法律的不可恃，道德习惯的并非一成不变，文字语言的必有变迁，其实倒是懂得的。懂得而照直说出来的？便成为改革者；懂得而不说，反要利用以欺瞒别人的，便成为“孤桐先生”及其“之流”。他的保护文言，内骨子也不过是这样。

如果我的检验是确的，那么，“孤桐先生”大概也就染了《闲话》所谓“有些志士”的通病，为“老婆子女”所累了，此后似乎应该另买几本德文书，来讲究“节育”。


** 与现代评论派的论争
   :PROPERTIES:
   :CUSTOM_ID: chap2
   :END:

*** 与现代评论派的论争
    :PROPERTIES:
    :CUSTOM_ID: chap2sec1
    :END:

**** 並非閒話
     :PROPERTIES:
     :CUSTOM_ID: 19250601
     :END:

     - Note taken on [2019-11-11 一 00:37] \\
       《闲话》：陈在《现代评论》第一卷第二十五期（一九二五年五月三十日）的《闲话》中说：“《闲话》正要付印的时候，我们在报纸上看见女师大七教员的宣言。以前我们常常听说女师大的风潮，有在北京教育界占最大势力的某籍某系的人在暗中鼓动，可是我们总不敢相信。这个宣言语气措辞，我们看来，未免过于偏袒一方，不大公允，看文中最精采的几句就知道了。（摘句略）这是很可惜的。我们自然还是不信我们平素所很尊敬的人会暗中挑剔风潮，但是这篇宣言一出，免不了流言更加传布得厉害了。”按某籍，指浙江；某系指当时北京大学国文系。发表宣言的七人除李泰盞外，都是浙江人和北京大学国文系教授。
     - Note taken on [2019-11-11 一 00:35] \\
       《女师大的学潮》，见[[file:the_fights_of_luxun.org::*%E3%80%8C%E7%A2%B0%E5%A3%81%E3%80%8D%E4%B9%8B%E9%A4%98][「碰壁」之餘]]
     - Note taken on [2019-11-11 一 00:33] \\
       幾句感慨：《忽然想到》之七
凡事無論大小，只要和自己有些相干，便不免格外警覺。

即如這一回女子師範大學的風潮，我因為在那裡擔任一點鐘功課，也就感到震動，而且就發了幾句感慨，登在五月十二的《京報副刊》上。自然，自己也明知道違了「和光同塵」的古訓了，但我就是這樣，並不想以騎牆或陰柔來買人尊敬。

三四天之後，忽然接到一本《現代評論》十五期，很覺得有些稀奇。這一期是新印的，第一頁上目錄已經整齊（初版字有參差處），就證明著至少是再版。我想：為什麼這一期特別賣的多，送的多呢，莫非內容改變了麼？翻開初版來，校勘下去，都一樣；不過末葉的金城銀行的廣告已經杳然，所以一篇《女師大的學潮》就赤條條地露出。我不是也發過議論的麼？自然要看一看，原來是贊成楊蔭榆校長的，和我的論調正相反。做的人是「一個女讀者」。

中國原是玩意兒最多的地方，近來又剛鬧過什麼「琴心是否女士」問題，我於是心血來潮，忽而想：又搗什麼鬼，裝什麼佯了？但我即刻不再想下去，因為接著就起了別一個念頭，想到近來有些人，凡是自己善於在暗中播弄鼓動的，一看見別人明白質直的言動，便往往反噬他是播弄和鼓動，是某黨，是某系；正如偷漢的女人的丈夫，總願意說世人全是忘八，和他相同，他心裡才覺舒暢。這種思想是卑劣的；我太多心了，人們也何至於一定用裙子來做軍旗。我就將我的念頭打斷了。

此後，風潮還是拖延著，而且展開來，於是有七個教員的[[*%E5%AF%B9%E4%BA%8E%E5%8C%97%E4%BA%AC%E5%A5%B3%E5%AD%90%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6%E9%A3%8E%E6%BD%AE%E5%AE%A3%E8%A8%80][宣言]]發表，也登在五月二十七日的《京報》上，其中的一個是我。

這回的反響快透了，三十日發行（其實是二十九日已經發賣）的《現代評論》上，西瀅先生就在《閒話》的第一段中特地評論。但是，據說宣言是「《閒話》正要付印的時候」才在報上見到的，所以前半隻論學潮，和宣言無涉。後來又做了三大段，大約是見了宣言之後，這才文思泉湧的罷，可是《閒話》付印的時間，大概總該頗有些耽誤了。但後做而移在前面，也未可知。那麼，足見這是一段要緊的「閒話」。

《閒話》中說，「以前我們常常聽說女師大的風潮，有在北京教育界占最大勢力的某籍某系的人在暗中鼓動，可是我們總不敢相信。」所以他只在宣言中摘出「最精彩的幾句」，加上圈子，評為「未免偏袒一方」；而且因為「流言更加傳佈得厲害」，遂覺「可惜」，但他說「還是不信我們平素所很尊敬的人會暗中挑剔風潮」。這些話我覺得確有些超妙的識見。例如「流言」本是畜類的武器，鬼蜮的手段，實在應該不信它。

又如一查籍貫，則即使裝作公平，也容易啟人疑竇，總不如「不敢相信」的好，否則同籍的人固然憚于在一張紙上宣言，而別一某籍的人也不便在暗中給同籍的人幫忙了。這些「流言」和「聽說」，當然都只配當作狗屁！

但是，西瀅先生因為「未免偏袒一方」而遂歎為「可惜」，仍是引用「流言」，我卻以為是「可惜」的事。清朝的縣官坐堂，往往兩造各責小板五百完案，「偏袒」之嫌是沒有了，可是終於不免為胡塗蟲。假使一個人還有是非之心，倒不如直說的好；否則，雖然吞吞吐吐，明眼人也會看出他暗中「偏袒」那一方，所表白的不過是自己的陰險和卑劣。宣言中所謂「若離若合，殊有混淆黑白之嫌」者，似乎也就是為此輩的手段寫照。而且所謂「挑剔風潮」的「流言」，說不定就是這些伏在暗中，輕易不大露面的東西所製造的，但我自然也「沒有調查詳細的事實，不大知道」。可惜的是西瀅先生雖說「還是不信」，卻已為我輩「可惜」，足見流言之易於惑人，無怪常有人用作武器。但在我，卻直到看見這《閒話》之後，才知道西瀅先生們原來「常常」聽到這樣的流言，並且和我偶爾聽到的都不對。可見流言也有種種，某種流言，大抵是奔湊到某種耳朵，寫出在某種筆下的。

但在《閒話》的前半，即西瀅先生還未在報上看見七個教員的宣言之前，已經比學校為「[[#19250530][臭毛厕]]」，主張「人人都有掃除的義務」了。為什麼呢？一者報上兩個相反的啟事已經發現；二者學生把守校門；三者有「校長不能在學校開會，不得不借鄰近的飯店招集教員開會的奇聞」。但這所述的「臭毛廁」的情形還得修改些，因為層次有點顛倒。據宣言說，則「飯店開會」，乃在「把守校門」之前，大約西瀅先生覺得不「最精彩」，所以沒有摘錄，或者已經寫好，所以不及摘錄的罷。現在我來補摘幾句，並且也加些圈子，聊以效顰——

「……迨五月七日校內講演時，學生勸校長楊蔭榆先生退席後，楊先生乃于飯館召集校員若干燕飲，繼即以評議會名義，將學生自治會職員六人揭示開除，由是全校譁然，有堅拒楊先生長校之事變。……」

《閒話》裡的和這事實的顛倒，從神經過敏的看起來，或者也可以認為「偏袒」的表現；但我在這裡並非舉證，不過聊作插話而已。其實，「偏袒」兩字，因我適值選得不大堂皇，所以使人厭觀，倘用別的字，便會大大的兩樣。況且，即使是自以為公平的批評家，「偏袒」也在所不免的，譬如和校長同籍貫，或是好朋友，或是換帖兄弟，或是叨過酒飯，每不免於不知不覺間有所「偏袒」。這也算人情之常，不足深怪；但當侃侃而談之際，那自然也許流露出來。然而也沒有什麼要緊，局外人那裡會知道這許多底細呢，無傷大體的。

但是學校的變成「臭毛廁」，卻究竟在「飯店招集教員」之後，酒醉飯飽，毛廁當然合用了。西瀅先生希望「教育當局」打掃，我以為在打掃之前，還須先封飯店，否則醉飽之後，總要拉矢，毛廁即永遠需用，怎麼打掃得乾淨？而且，還未打掃之前，不是已經有了「流言」了麼？流言之力，是能使糞便增光，蛆蟲成聖的，打掃夫又怎麼動手？姑無論現在有無打掃夫。

至於「萬不可再敷衍下去」，那可實在是斬釘截鐵的辦法。

正應該這樣辦。但是，世上雖然有斬釘截鐵的辦法，卻很少見有敢負責任的宣言。所多的是自在黑幕中，偏說不知道；替暴君奔走，卻以局外人自居；滿肚子懷著鬼胎，而裝出公允的笑臉；有誰明說出自己所觀察的是非來的，他便用了「流言」來作不負責任的武器：這種蛆蟲充滿的「臭毛廁」，是難於打掃乾淨的。丟盡「教育界的面目」的醜態，現在和將來還多著哩！

**** 我的「籍」和「系」
     :PROPERTIES:
     :CUSTOM_ID: 19250605
     :END:

     - Note taken on [2019-11-11 一 00:22] \\
       不相识的青年先生赐信指署名“瞎嘴”写于一九二五年三月五日的致作者的信。这封信攻击作者的《青年必读书》，其中说：“我诚恳的希望：一、鲁迅先生是感觉‘现在青年最要紧的是“行”，不是“言”’，所以敢请你出来作我们一般可怜的青年的领袖先搬到外国（连家眷）去，然后我要做个摇旗呐喊的小卒。二、鲁迅先生搬家到外国后，我们大家都应马上搬去。”（按着重号系原件所有），但是这封信估计很难找了。
     - Note taken on [2019-11-11 一 00:21] \\
       从维基文库粘贴过来的，所以是繁体字。
雖然因為我勸過人少——或者竟不——讀中國書，曾蒙一位不相識的青年先生賜信要我搬出中國去，但是我終於沒有走。而且我究竟是中國人，讀過中國書的，因此也頗知道些處世的妙法。譬如，假使要掉文袋，可以說說「桃紅柳綠」，這些事是大家早已公認的，誰也不會說你錯。如果論史，就贊幾句孔明，罵一通秦檜，這些是非也早經論定，學述一回決沒有什麼差池；況且秦太師的黨羽現已半個無存，也可保毫無危險。至於近事呢，勿談為佳，否則連你的籍貫也許會使你由可「尊敬」而變為「可惜」的。

我記得宋朝是不許南人做宰相的，那是他們的「祖制」，只可惜終於不能堅持。至於「某籍」人說不得話，卻是我近來的新發見。也還是女師大的風潮，我說了幾句話。但我先要聲明，我既然說過，頗知道些處世的妙法，為什麼又去說話呢？那是，因為，我是見過清末搗亂的人，沒有生長在太平盛世，所以縱使頗有些涵養工夫，有時也不免要開口，客氣地說，就是大不「安分」的。於是乎我說話了，不料陳西瀅先生早已常常聽到一種「流言」，那大致是「女師大的風潮，有北京教育界占最大勢力的某籍某系的人在暗中鼓動」。現在我一說話，恰巧化「暗」為「明」，就使這常常聽到流言的西瀅先生代為「可惜」，雖然他存心忠厚，「自然還是不信平素所很尊敬的人會暗中挑剔風潮」；無奈「流言」卻「更加傳布得厲害了」，這怎不使人「懷疑」呢？自然是難怪的。

我確有一個「籍」，也是各人各有一個的籍，不足為奇。但我是什麼「系」呢？自己想想，既非「研究系」，也非「交通系」，真不知怎麼一回事。只好再精查，細想；終於也明白了，現在寫它出來，庶幾乎免得又有「流言」，以為我是黑籍的政客。

因為應付某國某君的囑託，我正寫了一點自己的履歷，第一句是「我於一八八一年生在浙江省紹興府城裡一家姓周的家裡」，這裡就說明了我的「籍」。但自從到了「可惜」的地位之後，我便又在末尾添上一句道，「近幾年我又兼做北京大學，師範大學，女子師範大學的國文系講師」，這大概就是我的「系」了。我真不料我竟成了這樣的一個「系」。

我常常要「挑剔」文字是確的，至於「挑剔風潮」這一種連字面都不通的陰謀，我至今還不知道是怎樣的做法。何以一有流言，我就得沉默，否則立刻犯了嫌疑，至於使和我毫不相干的人如西瀅先生者也來代為「[[*%E9%97%B2%E8%AF%9D%EF%BC%88%E7%B2%89%E5%88%B7%E8%8C%85%E5%8E%95%EF%BC%89][可惜]]」呢？那麼，如果流言說我正在鑽營，我就得自己鎖在房裡了；如果流言說我想做皇帝，我就得連忙自稱奴才了。然而古人卻確是這樣做過了，還留下些什麼「空穴來風，桐乳來巢」的鬼格言。可惜我總不耐煩敬步後塵；不得已，我只好對於無論是誰，先奉還他無端送給我的「尊敬」。

其實，現今的將「尊敬」來佈施和拜領的人們，也就都是上了古人的當。我們的乏的古人想了幾千年，得到一個制馭別人的巧法：可壓服的將他壓服，否則將他抬高。而抬高也就是一種壓服的手段，常常微微示意說，你應該這樣，倘不，我要將你摔下來了。求人尊敬的可憐蟲於是默默地坐著；但偶然也放開喉嚨道「有利必有弊呀！」「彼亦一是非，此亦一是非呀！」「猗歟休哉呀！」聽眾遂亦同聲讚歎道，「對呀對呀，可敬極了呀！」這樣的互相敷衍下去，自己以為有趣。

從此這一個辦法便成為八面鋒，殺掉了許多乏人和白癡，但是穿了聖賢的衣冠入殮。可憐他們竟不知道自己將褒貶他的人們的身價估得太大了，反至於連自己的原價也一同失掉。

人類是進化的，現在的人心　當然比古人的高潔；但是「尊敬」的流毒，卻還不下於流言，尤其是有誰裝腔作勢，要來將這撒去時，更足使乏人和白癡惶恐。我本來也無可尊敬；也不願受人尊敬，免得不如人意的時候，又被人摔下來。更明白地說罷：我所憎惡的太多了，應該自己也得到憎惡，這才還有點像活在人間；如果收得的乃是相反的佈施，於我倒是一個冷嘲，使我對於自己也要大加侮蔑；如果收得的是吞吞吐吐的不知道算什麼，則使我感到將要嘔噦似的噁心。然而無論如何，「流言」總不能嚇啞我的嘴……。


**** 参战
     :PROPERTIES:
     :CUSTOM_ID: 19250829
     :AUTHOR:   陈源
     :END:

张歆海先生有一天晚上在王府井大街走路，忽听得前面一声声的呐喊。他走上前去，看见一个车夫在路边啜泣，说有一个喝醉了的美国兵坐了车，非但不给他钱，还打了他一顿。再走几步，看见一黄衣的巡警躺在烂泥里，挣扎着不得起身。停望前面黑黝黝一片人，还在叫喊着，走近去一看，原来是三四十个人跟在两个美国兵的后面叫着嚷着“打！打！”这两个美国兵不慌不忙地慢慢的走着，有时还立停了转身看看后面的中国人。后面的中国人口中喊着“打！打！”，可是总是隔远着六七丈的距离，美国兵走他们也跟着走，美国兵立停他们也跟着立停。他们的人数愈聚愈多了，一会儿就有了百余人，也有几个警察，可是还只是远远的跟着喊“打！打！”，美国兵走到了东交民巷的一个口上了，他们回返身来，笑着嚷着：“来呀！来呀！”说了奇怪，这喊打的百余人不到两分钟便居然没有影踪了！

打！打！宣战！宣战！这样的中国人，呸！

**** 並非閒話 (二)
     :PROPERTIES:
     :CUSTOM_ID: 19250925
     :END:

向來聽說中國人具有大國民的大度，現在看看，也未必然。但是我們要說得好，那麼，就說好清淨，有志氣罷。所以總願意自己是第一，是唯一，不愛見別的東西共存。行了幾年白話，弄古文的人們討厭了；做了一點新詩，吟古詩的人們憎惡了；做了幾首小詩，做長詩的人們生氣了；出了幾種定期刊物，連別的出定期刊物的人們也來詛咒了：太多，太壞，只好做將來被淘汰的資料。

中國有些地方還在「溺女」，就因為豫料她們將來總是設出息的。可惜下手的人們總沒有好眼力，否則並以施之男孩，可以減少許多單會消耗食糧的廢料。

但是，歌頌「淘汰」別人的人也應該先行自省，看可有怎樣不滅的東西在裡面，否則，即使不肯自殺，似乎至少也得自己打幾個嘴巴。然而人是總是自以為是的，這也許正是逃避被淘汰的一條路。相傳曾經有一個人，一向就以「萬物不得其所」為宗旨的，平生只有一個大願，就是願中國人都死完，但要留下他自己，還有一個女人和一個賣食物的。現在不知道他怎樣，久沒有聽到消息了，那默默無聞的原因，或者就因為中國人還沒有死完的緣故罷。


據說，張歆海先生看見兩個美國兵打了中國的車夫和巡警，於是三四十個人，後來就有百餘人，都跟在他們後面喊「打！打！」，美國兵卻終於安然的走到東交民巷口了，還回頭「笑著嚷道：『來呀！來呀！』說也奇怪，這喊打的百餘人不到兩分鐘便居然沒有影蹤了！」

西瀅先生於是在《閒話》中斥之曰：「打！打！宣戰！宣戰！這樣的中國人，呸！」

這樣的中國人真應該受「呸！」他們為什麼不打的呢，雖然打了也許又有人來說是「拳匪」。但人們那裡顧忌得許多，終於不打，「怯」是無疑的。他們所有的不是拳頭麼？

但不知道他們可曾等候美國兵走進了東交民巷之後，遠遠地吐了唾沫？《現代評論》上沒有記載，或者雖然「怯」，還不至於「卑劣」到那樣罷。

然而美國兵終於走進東交民巷口了，毫無損傷，還笑嚷著「來呀來呀」哩！你們還不怕麼？你們還敢說「打！打！宣戰！宣戰！」麼？這百餘人，就證明著中國人該被打而不作聲！

「這樣的中國人，呸！呸！！！」

更可悲觀的是現在「造謠者的卑鄙齷齪更遠過於章炳麟」，真如《閒話》所說，而且只能「匿名的在報上放一兩枝冷箭」。而且如果「你代被群眾專制所壓迫者說了幾句公平話，那麼你不是與那人有‘密切的關係’，便是吃了他或她的酒飯。在這樣的社會裡，一個報不顧利害的專論是非，自然免不了誹謗叢生，謠諑蜂起。」這確是近來的實情。即如女師大風潮，西瀅先生就聽到關於我們的「流言」，而我竟不知道是怎樣的「流言」，是那幾個「卑鄙齷齪更遠過於章炳麟」者所造。還有女生的罪狀，已見於章士釗的[[#19250808][呈文]]

可是我倒也並不很以「流言」為奇，如果要造，就聽憑他們去造去。好在中國現在還不到「群眾專制」的時候，即使有幾十個人，只要「無權勢」者叫一大群警察，雇些女流氓，一打，就打散了，正無須乎我來為「被壓迫者」說什麼「公平話」。即使說，人們也未必盡相信，因為「在這樣的社會裡」，有些「公平話」總還不免是「他或她的酒飯」填出來的。不過事過境遷，「酒飯」已經消化，吸收，只剩下似乎毫無緣故的「公平話」罷了。倘使連酒飯也失了效力，我想，中國也還要光明些。

但是，這也不足為奇的。不是上帝，那裡能夠超然世外，真下公平的批評。人自以為「公平」的時候，就已經有些醉意了。世間都以「黨同伐異」為非，可是誰也不做「黨異伐同」的事。現在，除了瘋子，倘使有誰要來接吻，人大約總不至於倒給她一個嘴巴的罷。，而那些作為根據的「流言」，也不知道是那幾個「卑鄙齷齪」且至於遠不如畜類者所造。但是學生卻都被打出了，其時還有人在酒席上得意。——但這自然也是「謠諑」。

可是我倒也並不很以「流言」為奇，如果要造，就聽憑他們去造去。好在中國現在還不到「群眾專制」的時候，即使有幾十個人，只要「無權勢」者叫一大群警察，雇些女流氓，一打，就打散了，正無須乎我來為「被壓迫者」說什麼「公平話」。即使說，人們也未必盡相信，因為「在這樣的社會裡」，有些「公平話」總還不免是「他或她的酒飯」填出來的。不過事過境遷，「酒飯」已經消化，吸收，只剩下似乎毫無緣故的「公平話」罷了。倘使連酒飯也失了效力，我想，中國也還要光明些。

但是，這也不足為奇的。不是上帝，那裡能夠超然世外，真下公平的批評。人自以為「公平」的時候，就已經有些醉意了。世間都以「黨同伐異」為非，可是誰也不做「黨異伐同」的事。現在，除了瘋子，倘使有誰要來接吻，人大約總不至於倒給她一個嘴巴的罷。

**** 剽窃与抄袭
     :PROPERTIES:
     :AUTHOR:   陈源
     :CUSTOM_ID: 19251121
     :END:

现在著述界盛行“剽窃”或“抄袭”之风，这是大家公认的事实。一般人自己不用脑筋去思索研究，却利用别人思索或研究的结果来换名易利，到处都可以看到。然而我们也哪能深怪？现在的社会是不是鼓励人们用脑筋的社会？社会的种种方面，总是用心用力的役于人，不用心不用力的役人；心力用得愈多的得到的报酬愈少，心力用得愈少的得到的报酬愈多。那么著述界又哪能特别的立异？要是用自己的脑筋去研究，一年半载也许得不到什么结果，要是利用人家的脑筋，半天就可以写一篇文章，一月就可以草成一种著述。好在中国的读者从不问你的作品质的好坏，只问它量的多少；中国的学生不问你的学问深浅，只问你在副刊上发表文章的多寡。这种办法也无非是依照经济学的原则，用最少的力量得最大的效果罢了。这种风气的结果，乙抄甲，丙又抄乙，永远没有完毕的时候。在健忘的普通读者的眼中，一篇文章虽然读过了三百遍，他还会认它是新著，本无关系，可是一般鸿博的批评家可免不了头痛欲狂了。

所以鸿博的批评家迫不得已的生起气来，我们能够谅解，我们非但谅解，而且同情，非但同情，而且热诚的希望，馨香的祝祷他们的努力。我们相信除了他们的笔锋，没有东西可以挽回上面所说的那条经济原则。

可是，很不幸的，我们中国的批评家有时实在太宏博了。他们俯伏了身躯，张大了眼睛，在地面上寻找窃贼，以致整大本的剽窃，他们倒往往视而不见。要举个例么？还是不说吧，我实在不敢再开罪“思想界的权威”。总之这些批评家不见大处，只见小处；不见小处，只见他们自己的宏博处。例如某宏博批评家说：“某先生大抄史特林堡的名剧《钻石》而标以创作的美名，揭于前文学旬刊已为识者所笑。”不错，我也仿佛记得有这么一回事，可是记得某先生抄的却不是“史特林堡的名剧”，而且“史特林堡的名剧”中我也记不起什么《钻石》来。这足见某先生宏博的程度了。实在许多批评家宏博的程度，深可惊奇。他们叫我们不得不联想到那些宏博的小孩，他们读《三字经》还没有满一句，到处见着“人”，“之”字，便大嚷你瞧，“你瞧！人！人！人！之！之！之！”好像那些写人字之字的都在抄他们的《三字经》！

在我们不宏博的人看来，“剽窃”“抄袭”有一定的意思，不能看见两篇东西稍有相同之点便滥用这样的名字。两个科学家都写爱斯坦的相对论，他们的论调，自然有许多相同处，虽则他们谁也不用“剽窃”。可是，要是一个人说他自己发明了相对论，他是“剽窃”本不用说，他把第二人的书改头换面的付印，也自然是“抄袭”。种种科学都不外如此。

至于文学，界限就不能这样的分明了。许多情感是人类所共有的，他们情之所至，发为诗歌，也免不了有许多共同之点。把好花来比美人，不仅仅中国人有这样的观念，西洋人，印度人也有同样的观念，难道一定要说谁抄袭了谁才称心吗？人类的悲欢离合，总不出几个套数，因为两种作品的套数有些相同，就指为“抄袭”，这种批评家的宏博也不亚于上说的小孩。

“剽窃”“抄袭”的罪名，在文学里，我以为只可以压倒一般蠢才，却不能损伤天才作家的。文学是没有平权的。文学是“只许州官放火，不许百姓点灯”的。为什么蠢才一压便倒呢？因为他剽窃来的东西，在他的作品中，好像马口铁上镶的金刚钻，好像牛粪里插的鲜花，本来太不相称，你把他的金刚钻，鲜花去了，只剩了马口铁与牛粪。至于伟大的天才，有几个不偶然的剽窃？不用说广义的他们心灵受了过去大作家的陶养，头脑里充满了过去大作家的意思，就狭义的说，举起例来也举不胜举。BenJonson的作品里有许多字句是从希腊罗马的作品里整段的翻出来的，而且几乎没有一个希腊罗马的诗人，历史家不曾在他的作品里留下些痕迹。托尔斯泰的杰著《战争与和平》里面讲战事的地方，就有整篇的抄袭。最显著的例莫过于莎士比亚了。他的剧本的事实布局，几乎没有一种不是借自别人。可是，你就指出了他们的剽窃，他们的作品也不会因之减色，BenJonson虽然借了许多名句，他自己作品也自有传世的价值在。托尔斯泰把冷冰冰，毫无生气的纪事，化在他如火如荼的杰作中，无异乎生死人而肉白骨了。莎士比亚在他陶冶天地的大炉中把许多泥塑木雕的傀儡溶化成了英雄美人。幼稚散漫的情节制造成了绝世传奇，要不是经他的借用，还有谁会得听见那些无聊的作品来？

“剽窃”和“抄袭”的罪名固然不足以轻灭他们作品的价值，可是BenJonson究竟“剽窃”过，托尔斯泰究竟“抄袭”过。可是莎士比亚是不受这样的罪名的，因为他的作品已经又是一回事。同样，一个作家也尽可无意的，或竟有意的借用另一作家的布局，只要他运用的方法不同，他周围的空气不同，他人物的个性不同。契诃夫有一篇短篇小说LaCigale是把一个劳苦工作的丈夫同一个没脑筋只管享福的太太做对照的。曼殊斐儿（KatharineMansfield）在她的MarriageaIaMode用同样的主旨。曼殊斐儿是私淑契诃夫的，她曾经看见他的那篇小说，毫无疑问。可是我们万不能说曼殊斐儿是抄袭契诃夫，因为契诃夫的小说里是纯粹的俄国人，曼殊斐儿的是纯粹的英国人，契诃夫的人物有他们特别的个性，曼殊斐儿的人物也有他们的个性，所以，虽然那两篇小说说的是同样的事，读者得的是差不多的感想，它们简直是两件极不相同的东西，同时却是两件同样美丽的东西。自然，要是让宏博的中国批评家看见了，他们又找到了伟大的发见了。幸而宏博的中国批评家是不曾看见的——它们还没有翻译成中文呢。

胡适之先生从上海寄蒋梦麟先生的信中有这样的话：

> 前不多日，我从南京回来，车中我忽得一个感想。我想不教书了，专作著述的事。每日定一个日程要翻译一千字，著作一千字，需时约四个钟头。每年以三百天计，可译三十万字，著三十万字，每年可出五部书，十年可得五十部书，我的书至少有两万人读，这个影响多么大？倘使我能干十年之中介绍二十部世界名著给中国青年，这点成绩，不胜于每日在讲堂上给一百五十学生制造文凭吗？所以我决定脱离教书生活了。

他在给我们的信里还说“我们能批评人家的翻译，而自己不翻译，我们能评人家的著述，而自己不著述，这是根本不对的”（原信不在手边，字句也许有些出入）。我们自然是十分赞成他的计划，希望他能够实行。自然我不信一年六十万字，十年六百万字是能实现的。这样下去，再活五十年，不就写了三千万字了么？胡先生的《中国哲学史大纲》那种书，一定不是可以一天写一千字写成的。他也许一天写了五千字，一万字，也许三个月还不能动一动笔。一天一定写多少字，虽然有那样的作家，如英国小说家AnthonyTrollope，可是大多数人耐不住那种烦，并且这样所写成的作品也许不能特别的出色。我们希望胡先生的，不是平常我们都能写的书，只是与《中国哲学史大纲》那样，和再进一步的著作。这样的著述，不要说一年五部，就是五年一部我们已经很满足的了。

梦麟先生在他的覆信里说：“这种事业，我以为凡有能力的留学生们都应该做的。”可是，非常的不幸，凡应该做的“留学生”却都没有“能力”，因为，我已经说过，中国恐怕只有胡适之，梁任公两位先生有靠他们著作生活的能力。除非中国的著述事业大大的发达，或是做教书匠的有安安稳稳的一碗饭吃，这个希望只好终于希望了。

**** 並非閒話(三)
     :PROPERTIES:
     :CUSTOM_ID: 19251207
     :END:

     - Note taken on [2019-11-14 四 11:04] \\
       陈西滢的《闲话》确实不好找。
西瀅先生這回是義形於色，在《現代評論》四十八期的《閒話》裡很為被書賈擅自選印作品，因而受了物質上損害的作者抱不平。而且賤名也忝列於作者之列：惶恐透了。吃飯之後，寫一點自己的所感罷。至於捏筆的「動機」，那可大概是「不純潔」的。記得幼小時候住在故鄉，每看見紳士將一點騙人的自以為所謂恩惠，頒給下等人，而下等人不大感謝時，則斥之曰「不識抬舉！」我的父祖是讀書的，總該可以算得士流了，但不幸從我起，不知怎的就有了下等脾氣，不但恩惠，連吊慰都不很願意受，老實說罷：我總疑心是假的。這種疑心，大約就是「不識抬舉」的根苗，或者還要使寫出來的東西「不純潔」。

我何嘗有什麼白刃在前，烈火在後，還是釘住書桌，非寫不可的「創作衝動」；雖然明知道這種衝動是純潔，高尚，可貴的，然而其如沒有何。前幾天早晨，被一個朋友怒視了兩眼，倒覺得臉有點熱，心有點酸，頗近乎有什麼衝動了，但後來被深秋的寒風一吹拂，臉上的溫度便復原，——沒有創作。至於已經印過的那些，那是被擠出來的。這「擠」字是擠牛乳之「擠」；這「擠牛乳」是專來說明「擠」字的，並非故意將我的作品比作牛乳，希冀裝在玻璃瓶裡，送進什麼「藝術之宮」。倘用現在突然流行起來了的論調，將青年的急於發表未熟的作品稱為「流產」，則我的便是「打胎」；或者簡直不是胎，是狸貓充太子。所以一寫完，便完事，管他媽的，書賈怎麼偷，文士怎麼說，都不再來提心吊膽。但是，如果有我所相信的人願意看，稱讚好，我終於是歡喜的。後來也集印了，為的是還想賣幾文錢，老實說。

那麼，我在寫的時候沒有虔敬的心麼？答曰：有罷。即使沒有這種冠冕堂皇的心，也決不故意耍些油腔滑調。被擠著，還能嬉皮笑臉，遊戲三昧麼？倘能，那簡直是神仙了。我並沒有在呂純陽祖師門下投誠過。

但寫出以後，卻也不很愛惜羽毛，有所謂「敝帚自珍」的意思，因為，已經說過，其時已經是「便完事，管他媽的」了。誰有心腸來管這些無聊的後事呢？所以雖然有什麼選家在那裡放出他那偉大的眼光，選印我的作品，我也照例給他一個不管。其實，要管也無從管起的。我曾經替人代理過一回收版稅的譯本，打聽得賣完之後，向書店去要錢，回信卻道，舊經理人已經辭職回家了，你向他要去罷；我們可是不知道。這書店在上海，我怎能趁了火車去向他坐索，或者打官司？但我對於這等選本，私心卻也有「竊以為不然」的幾點，一是原本上的錯字，雖然一見就明知道是錯的，他也照樣錯下去；二是他們每要發幾句偉論，例如什麼主義咧，什麼意思咧之類，大抵是我自己倒覺得並不這樣的事。自然，批評是「精神底冒險」，批評家的精神總比作者會先一步的，但在他們的所謂死屍上，我卻分明聽到心搏，這真是到死也說不到一塊兒，此外，倒也沒有什麼大怨氣了。

這雖然似乎是東方文明式的大度，但其實倒怕是因為我不靠賣文營生。在中國，駢文壽序的定價往往還是每篇一百兩，然而白話不值錢；翻譯呢，聽說是自己不能創作而嫉妒別人去創作的壞心腸人所提倡的，將來文壇一進步，當然更要一文不值。我所寫出來的東西，當初雖然很碰過許多大釘子，現在的時價是每千字一至二三元，但是不很有這樣好主顧，常常只好盡些不知何自而來的義務。有些人以為我不但用了這些稿費或版稅造屋，買米，而且還靠它吸煙卷，吃果糖。殊不知那些款子是另外騙來的；我實在不很擅長於先裝鬼臉去嚇書坊老闆，然後和他接洽。我想，中國最不值錢的是工人的體力了，其次是咱們的所謂文章，只有伶俐最值錢。倘真要直直落落，借文字謀生，則據我的經驗，賣來賣去，來回至少一個月，多則一年餘，待款子寄到時，作者不但已經餓死，倘在夏天，連筋肉也都爛盡了，那裡還有吃飯的肚子。

所以我總用別的道兒謀生；至於所謂文章也者，不擠，便不做。擠了才有，則和什麼高超的「煙士披離純」呀，「創作感興」呀之類不大有關係，也就可想而知。倘說我假如不必用別的道兒謀生，則心志一專，就會有「煙士披離純」等類，而產生較偉大的作品，至少，也可以免於獻出剝皮的狸貓罷，那可是也未必。三家村的冬烘先生，一年到頭，一早到夜教村童，不但毫不「時時想政治活動」，簡直並不很「幹著種種無聊的事」，但是他們似乎並沒有《教育學概論》或「高頭講章」的待定稿，藏之名山。而馬克思的《資本論》，陀思妥夫斯奇的《罪與罰》等，都不是啜末加加啡，吸埃及煙捲之後所寫的。除非章士釗總長治下的「有些天才」的編譯館人員，以及討得官僚津貼或銀行廣告費的「大報」作者，于謀成事遂，睡足飯飽之餘，三月煉字，半年鍛句，將來會做出超倫軼群的古奧漂亮作品。總之，在我，是肚子一飽，應酬一少，便要心平氣和，關起門來，什麼也不寫了；即使還寫，也許不過是溫暾之談，兩可之論，也即所謂執中之說，公允之言，其實等於不寫而已。

所以上海的小書賈化作蚊子，吸我的一點血，自然是給我物質上的損害無疑，而我卻還沒有什麼大怨氣，因為我知道他們是蚊子，大家也都知道他們是蚊子。我一生中，給我大的損害的並非書賈，並非兵匪，更不是旗幟鮮明的小人：乃是所謂「流言」。即如今年，就有什麼「鼓動學潮」呀，「謀做校長」呀，「打落門牙」呀這些話。有一回，竟連現在為我的著作權受損失抱不平的西瀅先生也要相信了，也就在《現代評論》（第二十五期）的照例的《閒話》上發表出來；它的效力就可想。譬如一個女學生，與其被若干卑劣陰險的文人學士們暗地裡散佈些關於品行的謠言，倒不如被土匪搶去一條紅圍巾——物質。但這種「流言」，造的是一個人還是多數人？姓甚，名誰？我總是查不出；後來，因為沒有多工夫，也就不再去查考了，僅為便於述說起見，就總稱之曰畜生。

雖然分了類，但不幸這些畜生就雜在人們裡，而一樣是人頭，實際上仍然無從辨別。所以我就多疑，不大要聽人們的說話；又因為無話可說，自己也就不大願意做文章。有時候，甚至於連真的義形於色的公話也會覺得古怪，珍奇，於是乎而下等脾氣的「不識抬舉」遂告成功，或者會終於不可救藥。

平心想起來，所謂「選家」這一流人物，雖然因為容易聯想到明季的制藝的選家的緣故，似乎使人厭聞，但現在倒是應該有幾個。這兩三年來，無名作家何嘗沒有勝於較有名的作者的作品，只是誰也不去理會他，一任他自生自滅。去年，我曾向DF先生提議過，以為該有人搜羅了各處的各種定期刊行物，仔細評量，選印幾本小說集，來紹介於世間；至於已有專集者，則一概不收，「再拜而送之大門之外」。但這話也不過終於是空話，當時既無定局，後來也大家走散了。我又不能做這事業，因為我是偏心的。評是非時我總覺得我的熟人對，讀作品是異己者的手腕大概不高明。在我的心裡似乎是沒有所謂「公平」，在別人裡我也沒有看見過，然而還疑心什麼地方也許有，因此就不敢做那兩樣東西了：法官，批評家。 現在還沒有專門的選家時，這事批評家也做得，因為批評家的職務不但是剪除惡草，還得灌溉佳花，——佳花的苗。譬如菊花如果是佳花，則他的原種不過是黃色的細碎的野菊，俗名「滿天星」的就是。但是，或者是文壇上真沒有較好的作品之故罷，也許是一做批評家，眼界便極高卓，所以我只見到對於青年作家的迎頭痛擊，冷笑，抹殺，卻很少見誘掖獎勸的意思的批評。有一種所謂「文士」而又似批評家的，則專是一個人的御前侍衛，托爾斯泰呀，托她斯泰呀，指東畫西的，就只為一人做屏風。其甚者竟至於一面暗護此人，一面又中傷他人，卻又不明明白白地舉出姓名和實證來，但用了含沙射影的口氣，使那人不知道說著自己，卻又另用口頭宣傳以補筆墨所不及，使別人可以疑心到那人身上去。這不但對於文字，就是女人們的名譽，我今年也看見有用了這畜生道的方法來毀壞的。古人常說「鬼蜮技倆」，其實世間何嘗真有鬼蜮，那所指點的，不過是這類東西罷了。這類東西當然不在話下，就是只做侍衛的，也不配評選一言半語，因為這種工作，做的人自以為不偏而其實是偏的也可以，自以為公平而其實不公平也可以，但總不可「別有用心」於其間的。

書賈也像別的商人一樣，惟利是圖；他的出版或發議論的「動機」，誰也知道他「不純潔」，決不至於和大學教授的來等量齊觀的。但他們除惟利是圖之外，別的倒未必有什麼用意，這就是使我反而放心的地方。自然，倘是向來沒有受過更奇特而陰毒的暗箭的福人，那當然即此一點也要感到痛苦。

這也算一篇作品罷，但還是擠出來的，並非圍爐煮茗時中的閒話，臨了，便回上去填作題目，紀實也。

**** 「管闲事」
     :PROPERTIES:
     :CUSTOM_ID: 19260102
     :AUTHOR:   陈源
     :END:

民国十四年在枪炮声中过去了，十五年也就在枪炮代爆竹声中落下了地。这十五年是不是还得像十四年，那样的混乱不可收拾，我们实在无从预料。不错，十四年来，政局一天混沌一天，小百姓一天困苦一天，我们有了这长久的经验，应当可以猜到这来到的年头不过又是那么一回事了，然而我们还希望着。我们不得不希望着，正因为不希望只有绝望的路了。

“以前种种事，譬如昨日死，以后种种事，譬如今日生。”在新年的时候，一个人是容易有这种决心的。我们不免结一结旧账，过了年好换一本新账簿。前几天，一位我极尊敬的老先生在朋友面前说着我。他说某人真是不得了，他喜欢管闲事，到处惹祸，这样下去，还要惹出大祸来呢。这位老先生生平就是爱管闲事，到处惹祸，他还这样说，足见这话是很有理由的了。我们新年的决心，不如就说以后永远不管人家的闲事吧？

然而仔细想来，我们何尝爱管闲事呢？实在中国爱管闲事的人太少了。欧洲人好像不是这样的。

有一次，我立在伦敦一条街上，候着看新市长就职的行列。大约立了一点钟，我身后的人已有数重，忽然一个中年妇人突来站在我的面前。我自然一声不响的退让了。我两旁的不认识的女子却抱了不平。她们说我站了一点多钟，那妇人不应当抢我的地位。中年妇人听了她们的批评，面红耳热的，逡巡自去。她去后我两旁的人还愤愤的说她无礼。这种事在中国会有吗？谁肯这样无故的开罪他人，何况为了不认识的外国人？然而这样的傻子我自己在英国遇见的就不止一次。法

法国人的公道，我自己虽然没有经历过，然而十九世纪末几年的一桩案件是谁都知道的。法国军队里一个少年犹太军官受了私通敌国的嫌疑，革职定罪。法国人民自然都拍手称快。然而军官的友人竭力为他剖白，引起了几个管闲事人的注意。他们觉得证据不足，要求重审。最初这少数的人为了好管闲事，激动公愤，身家性命都几乎不保。他们却百折不回的继续奋斗，至两年之久，究竟得申冤狱。在那两年中，法国全国人民，分为二派——德雷夫党，和反德雷夫党——就是父子，兄弟，夫妻，朋友都为了它分离反目。不用说，反德雷夫党自然是大多数，知识界阶的人也就不少。然而我们所最倾倒几个近代法国文人如Zola，AnatoleFranceRcmainRoldna却多在被人唾弃的廿数人中为了一个毫不相干的犹太入却费了许多光阴，抛弃了自己的事业，犯了被犹太人收买的嫌疑，冒了身家性命不保的危险，去奔走呼号，主持公道，当然只有傻子才肯干，然而法国居然还有少数这样的傻子。

中国人的毛病就是他们太聪明了。“各人自扫门前雪，莫管他家瓦上霜。”真是一条好格言。本来一个人为什么要管闲事？自己省了许多事，还在众人面前讨了好，何乐而不为呢？如果偶然有些好事人，扰乱他们的安静，只要说他是受人的指使，领人家的津贴，就可以闭了他们的嘴，这本也难怪。谁能相信人家不与自己同样的卑鄙？谁能承认自己有不如人家的地方？

中国人最初不管邻家瓦上霜，久而久之，连自己门前的雪也不管了，如果有人同住的话。所以军阀政客虽然是少数，小百姓虽然受尽了苦，却不肯团结起来反抗他们。学校风潮，只要有十分之一的学生叫嚣捣乱，就可以拆散学校，引起学潮。其余的十分之九心中虽十二分的不愿意，却不能积极的团结起来，阻止那少数分子的胡闹。

生活在这种人中，自然有许多看不过眼的事情，不得不说两句话。这样就常常惹了祸了。可是我们究竟也是中国人，本性何尝爱管闲事呢？并且我们也有自己的生活要维持，还有许多天地间的奇书没有读，那有闲功夫来代人抱不平？这就算我们的新年的决心吧，虽然下次遇到了看不过的眼的事情，能不能忍住不说话，我实在不敢保。

**** 雜論管閒事‧做學問‧灰色等
     :PROPERTIES:
     :CUSTOM_ID: 19260118
     :END:

     - Note taken on [2019-11-14 四 11:10] \\
       这篇文章中提及陈西滢《做学问的工具》，但是在网上找不到。
       
       四书虽然是朱熹搞出来的，但是《论语》《孟子》乃至《大学》《中庸》的文本一直都有，汉代相关研究当然也是有的，鲁迅抓住这点开嘲讽，其实不是很厚道。
**一**
聽說從今年起，陳源（即西瀅）教授要不管閒事了；這豫言就見於《現代評論》五十六期的《閒話》裏。慚愧我沒有拜讀這一期，因此也不知其詳。要是確的呢，那麼，除了用那照例的客套說聲「可惜」之外，真的倒實在很詫異自己之糊塗：年紀這麼大了，竟不知道陽曆的十二月三十一日和一月一日之交在別人是可以發生這樣的大變動。我近來對於年關頗有些神經過鈍了，全不覺得怎樣。其實，倘要覺得罷，可是也不勝其覺得。大家挂上五色旗，大街上搭起幾坐彩坊，中間還有四個字道：「普天同慶」，據說這算是過年。大家關了門，貼到府神，爆竹畢剝砰的放起來，據說這也是過年。要是言行真跟著過年為轉移，怕要轉移不迭，勢必至於成為轉圈子。所以，神經過鈍雖然有落伍之慮，但有弊必有利，卻也很佔一點小小的便宜的。

但是，還有些事我終於想不明白：即如天下有閒事，有人管閒事之類。我現在覺得世上是仿佛沒有所謂閒事的，有人來管，便都和自己有點關係；即便是愛人類，也因為自己是人。假使我們知道了火星裏張龍和趙虎打架，便即大有作為，請酒開會，維持張龍，或否認趙虎，那自然是頗近於管閒事了。然而火星上事，既然能夠「知道」，則至少必須已經可以通信，關係也密切起來，算不得閒事了。因為既能通信，也許將來就能交通，他們終於會在我們的頭頂上打架。至於咱們地球之上，即無論那一處，事事都和我們相關，然而竟不管者，或因不知道，或因管不著，非以其「閒」也。譬如英國有劉千昭雇了愛爾蘭老媽子在倫敦拉出女生，在我們是閒事似的罷，其實並不，也會影響到我們這裡來。留學生不是多多，多多了麼？倘有合宜之處，就要引以為例，正如文學上的引用什麼莎士比亞呀，塞文狄斯呀，芮恩施呀一般。

（不對，錯了。芮恩施是美國的駐華公使，不是文學家。我大約因為在講什麼文藝學術的一篇論文上見過他的名字，所以一不小心便帶出來了。合即訂正於此，尚希讀者諒之。）

即使是動物，也怎能和我們不相干？青蠅的腳上有一個霍亂菌，蚊子唾沫裏有兩個瘧疾菌，就說不定會鑽進誰的血裏去。管到「鄰貓生子」，很有人以為笑談，其實卻正與自己大有相關。譬如我的院子裏，現在就有四匹鄰貓常常吵架了，倘使這些太太們之一又誕育四匹，則三四月後，我就得常聽到八匹貓們常常吵鬧，比現在加倍地心煩。

所以我就有了一種偏見，以為天下本無所謂閒事，只因為沒有這許多遍管的精神和力量，於是便只好抓一點來管。為什麼獨抓這一點呢？自然是最和自己相關的。大則因為同是人類，或是同類，同志；小則，因為是同學，親戚，同鄉，--至少，也大概叨光過什麼，雖然自己的顯在意識上並不了然，或者其實了然，而故意裝癡作傻。

但陳源教授據說是去年卻管了閒事了，要是我上文所說的並不錯，那就確是一個超人。今年不問世事，也委實是可惜之至，真是斯人不管，「如蒼生何」了。幸而陰曆的過年又快到了，除夕的亥時一過，也許又可望心回意轉的罷。

**二**

昨天下午我從沙灘回家的時候，知道大琦君來訪過我了。這使我很高興，因為我是猜想他進了病院的了，現在知道並沒有。而尤其使我高興的是他還留贈我一本《現代評論增刊》，只要一看見封面上畫著的一枝細長的蠟燭，便明白這是光明之象，更何況還有許多名人學者的著作，更何況其中還有陳源教授的一篇《做學問的工具》呢？這是正論，至少可以賽過「閒話」的；至少，是我覺得賽過「閒話」，因為它給了我許多東西。

我現在才知道南池子的「政治學會圖書館」去年「因為時局的關係，借書的成績長進了三至七倍」了，但他「家翰笙」卻還「用'平時不燒香，臨時抱佛腳'十個字形容當今學術界大部分的狀況」。這很改正了我許多誤解。我先已說過，現在的留學生是多多，多多了，但我總疑心他們大部分是在外國租了房子，關起門來燉牛肉吃的，而且在東京實在也看見過。那時我想：燉牛肉吃，在中國就可以，何必路遠迢迢，跑到外國來呢？雖然外國講究畜牧，或者肉裏面的寄生蟲可以少些，但燉爛了，即使多也就沒有關係。所以，我看見回國的學者，頭兩年穿洋服，後來穿皮袍，昂頭而走的，總疑心他是在外國親手燉過幾年牛肉的人物，而且即使有了什麼事，連「佛腳」也未必肯抱的。現在知道並不然，至少是「留學歐美歸國的人」並不然。但可惜中國的圖書館裏的書太少了，據說北京「三十多個大學，不論國立私立，還不及我們私人的書多」雲。這「我們」裏面，據說第一要數「溥儀先生的教師莊士敦先生」，第二大概是「孤桐先生」即章士釗，因為在德國柏林時候，陳源教授就親眼看見他兩間屋裏「技乎滿床滿架滿桌滿地，都是關於社會主義的德文書」。現在呢，想來一定是更多的了。這真教我欣羨佩服。記得自己留學時候，官費每月三十六元，支付衣食學費之外，簡直沒有贏余，混了幾年，所有的書連一壁也遮不滿，而且還是雜書，並非專而又專，如「都是關於社會主義的德文書」之類。

但是很可惜，據說當民眾「再毀」這位「孤桐先生」的「寒家」時，「好像他們夫婦兩位的藏書都散失了」。想那時一定是拉了幾十車，向各處走散，可惜我沒有去看，否則倒也是一個壯觀。

所以「暴民」之為「正人君子」所深惡痛絕，也實在有理由，即如這回之「散失」了「孤桐先生」夫婦的藏書，其加於中國的損失，就在毀壞了三十多個國立及私立大學的圖書館之上。和這一比較，劉百昭司長的失少了家藏的公款八千元，要算小事件了，但我們所引為遺憾的是偏是章士釗劉百昭有這麼多的儲藏，而這些儲藏偏又全都遭了劫。

在幼小時候曾有一個老於世故的長輩告誡過我：你不要和沒出息的擔子和攤子為難，他會自己摔了，卻誣賴你，說不清，也賠不完。這話于我似乎到現在還有影響，我新年去逛火神廟的廟會時，總不敢擠近玉器攤去，即使它不過擺著寥寥的幾件。怕的是一不小心，將它碰倒了，或者摔碎了一兩件，就要變成寶貝，一輩子賠不完，那罪孽之重，會在毀壞一坐博物館之上。而且推而廣之，連熱鬧場中也不大去了，那一回的示威運動時，雖有「打落門牙」的「流言」，其實卻躺在家裏：託福無恙。但那兩屋子「關於社會主義的德文書」以及其他從「孤桐先生」府上陸續散出的壯觀，卻也因此「交臂失之」了。這實在也就是所謂「有一利必有一弊」，無法兩全的。

現在是收藏洋書之富，私人要數莊士敦先生，公團要推「政治學會圖書館」了，只可惜一個是外國人，一個是靠著美國公使芮恩施竭力提倡出來的。「北京國立圖書館」將要擴張，實在是再好沒有的事，但聽說所依靠的還是美國退還的賠款，常年經費又不過三萬元，每月二千余。要用美國的賠款，也是非同小可的事，第一，館長就必須學貫中西，世界聞名的學者。據說，這自然只有梁啟超先生了，但可惜西學不大貫，所以配上一個北大教授李四光先生做副館長，湊成一個中外兼通的完人。然而兩位的薪水每月就要一千多，所以此後也似乎不大能夠多買書籍。這也就是所謂「有利必有弊」罷，想到這裡，我們就更不能不痛切地感到「孤桐先生」獨力購置的幾房子好書慘遭散失之可惜了。

總之，在近幾年中，是未必能有較好的「做學問的工具」的，學者要用功，只好是自己買書讀，但又沒有錢。聽說「孤桐先生」倒是想到了這一節，曾經發表過文章，然而下臺了，很可惜。學者們另外還有什麼法子呢，自然「也難怪他們除了說說'閒話'便沒有什麼可幹」，雖然北京三十多個大學還不及他們「私人的書多」。為什麼呢？要知道做學問不是容易事，「也許一個小小的題目得參考百十種書」，連「孤桐先生」的藏書也未必夠用。陳源教授就舉著一個例：「就以'四書'來說」罷，「不研究漢宋明清許多儒家的注疏理論，'四書'的真正意義是不易領會的。短短的一部'四書'，如果細細的研究起來，就得用得了幾百幾千種參考書」。

這就足見「學問之道，浩如煙海」了，那「短短的一部'四書」'，我是讀過的，至於漢人的「四書」注疏或理論，卻連聽也沒有聽到過。陳源教授所推許為「那樣提倡風雅的封藩大臣」之一張之洞先生在做給「束髮小生」們看的《書目答問》上曾經說：「'四書'，南宋以後之名。」我向來就相信他的話，此後翻翻《漢書藝文志》，《隋書經籍志》之類，也只有「五經」，「六經」，「七經」，「六藝」，卻沒有「四書」，更何況漢人所做的注疏和理論。但我所參考的，自然不過是通常書，北京大學的圖書館裏就有，見聞寡陋，也未可知，然而也只有這樣就算了，因為即使要「抱」，卻連「佛腳」都沒有。由此想來，那能「抱佛腳」的，肯「抱佛腳」的。的確還是真正的福人，真正的學者了。他「家翰笙」還慨乎言之，大約是「《春秋》責備賢者」之意罷。

完

現在不高興寫下去了，只好就此完結。總之：將《現代評論增刊》略翻一遍，就覺得五光十色，正如看見有一回廣告上所開列的作者的名單。例如李仲揆教授的《生命的研究》呀，胡適教授的《譯詩三首》呀，徐志摩先生的譯詩一首呀，西林氏的《壓迫》呀，陶孟和教授的要到二○二五年才發表而必須我們的玄孫才能全部拜讀的大著作的一部分呀……。但是，翻下去時，不知怎的我的眼睛卻看見灰色了，於是乎拋開。

現在的小學生就能玩七色板，將七種顏色涂在圓板上，停著的時候，是好看的，一轉，便變成灰色，--本該是白色的罷，可是涂得不得法，變成灰色了。收羅許多著名學者的大著作的大報，自然是光怪陸離，但也是轉不得，轉一週，就不免要顯出灰色來，雖然也許這倒正是它的特色。

**** 有趣的消息
     :PROPERTIES:
     :CUSTOM_ID: 19260119
     :END:

雖說北京像一片大沙漠，青年們卻還向這裡跑；老年們也不大走，即或有到別處去走一趟的，不久就轉回來了，仿佛倒是北京還很有什麼可以留戀。厭世詩人的怨人生，真是“感慨系之矣”，然而他總活著；連祖述釋迦牟尼先生的哲人勗本華爾也不免暗地裡吃一種醫治什麼病症的藥，不肯輕易“涅槃”。俗語說：“好死不如惡活”，這當然不過是俗人的俗見罷了，可是文人學者之流也何嘗不這樣。所不同的，只是他總有一面辭嚴義正的軍旗，還有一條尤其義正辭嚴的逃路。

真的，倘不這樣，人生可真要無聊透頂，無話可說了。

北京就是一天一天地百物昂貴起來；自己的“區區僉事”，又因為“妄有主張”，被章士釗先生革掉了。向來所遭遇的呢，借了安特來夫的話來說，是“沒有花，沒有詩”，就只有百物昂貴。然而也還是“妄有主張”，沒法回頭；倘使有一個妹子，如《晨報副刊》上所豔稱的“閒話先生”的家事似的，叫道：“阿哥！”那聲音正如“銀鈴之響于幽谷”，向我求告，“你不要再做文章得罪人家了，好不好？”我也許可以借此撥轉馬頭，躲到別墅裡去研究漢朝人所做的“四書”注疏和理論去。然而，惜哉，沒有這樣的好妹子；“女媭之嬋媛兮，申申其詈予，曰：鯀婞直以亡身兮，終然殀乎羽之野。”

連有一個那樣凶姊姊的幸福也不及屈靈均。我的終於“妄有主張”，或者也許是無可推託之故罷。然而這關係非同小可，將來怕要遭殃了，因為我知道，得罪人是要得到報應的。

話要回到釋迦先生的教訓去了，據說：活在人間，還不如下地獄的穩妥。做人有“作”就是動作（＝造孽），下地獄卻只有“報”（＝報應）了；所以生活是下地獄的原因，而下地獄倒是出地獄的起點。這樣說來，實在令人有些想做和尚，但這自然也只限於“有根”（據說，這是“一句天津話”）的大人物，我卻不大相信這一類鬼畫符。活在沙漠似的北京城裡，枯燥當然是枯燥的，但偶然看看世態，除了百物昂貴之外，究竟還是五花八門，創造藝術的也有，製造流言的也有，肉麻的也有，有趣的也有……這大概就是北京之所以為北京的緣故，也就是人們總還要奔湊聚集的緣故。可惜的是只有一些小玩意，老實一點的朋友就難於給自己豎起一杆辭嚴義正的軍旗來。

我一向以為下地獄的事，待死後再對付，只有目前的生活的枯燥是最可怕的，於是便不免于有時得罪人，有時則尋些小玩意兒來開開笑口，但這也就是得罪人。得罪人當然要受報，那也只好準備著，因為尋些小玩意兒來開開笑口的是更不能豎起辭嚴義正的軍旗來的。其實，這裡也何嘗沒有國家大事的消息呢，“關外戰事不日將發生”呀，“國軍一致擁段”哪，有些報紙上都用了頭號字煌煌地排印著，可以刺得人們頭昏，但於我卻都沒有什麼鳥趣味。人的眼界之狹是不大有藥可救的，我近來覺得有趣的倒要算看見那在德國手格盜匪若干人，在北京率領三河縣老媽子一大隊的武士劉百昭校長居然做駢文，大有偃武修文之意了；而且“百昭海邦求學，教部備員，多藝之譽愧不如人，審美之情差堪自信”，還是一位文武全才，我先前實在沒有料想到。第二，就是去年肯管閒事的“學者”，今年不管閒事了，在年底結清帳目的辦法，原來不止是掌櫃之于流水簿，也可以適用於“正人君子”的行為的。或者，“阿哥！”這一聲叫，正在中華民國十四年十二月卅一日的夜間十二點鐘罷。

但是，這些趣味，刹那間也即消失了，就是我自己的思想的變動，也誠然是可恨。我想，照著境遇，思想言行當然要遷移，一遷移，當然會有所以遷移的道理。況且世界上的國慶很不少，古今中外名流尤其多，他們的軍旗，是全都早經豎定了的。前人之勤，後人之樂，要做事的時候可以援引孔丘墨翟，不做事的時候另外有老聃，要被殺的時候我是關龍逄，要殺人的時候他是少正卯，〔有些力氣的時候看看達爾文赫胥黎的書，要人幫忙就有克魯巴金的《互助論》，勃朗甯夫婦豈不是講戀愛的模範麼，勗本華爾和尼采又是咒詛女人的名人，……歸根結蒂，如果楊蔭榆或章士釗可以比附到猶太人特萊孚斯去，則他的篾片就可以等於左拉等輩了。這個時候，可憐的左拉要被中國人背出來；幸而楊蔭榆或章士釗是否等於特萊孚斯，也還是一個大疑問。然而事情還沒有這麼簡單，中國的壞人（如水平線下的文人和學棍學匪之類），似乎將來要大吃其苦了，雖然也許要在身後，像下地獄一般。但是，深謀遠慮的人，總還以從此小心，不要多說為穩妥。你以為“閒話先生”真是不管閒事了麼？並不然的。據說他是要“到那天這班出鋒頭的人們脫盡了銳氣的日子，我們這位閒話先生正在從容的從事他那‘完工的拂拭’（The finishing touch），笑吟吟的擎著他那枝從鐵杠磨成的繡針，諷刺我們情急是多麼不經濟的一個態度，反面說只有無限的耐心才是天才唯一的憑證”。（《晨報副刊》一四二三）

後出者勝於前者，本是天下的平常事情，但除了墮落的民族。即以衣服而論，也是由裸體而用會陰帶或圍裙，於是有衣裳，袞冕。我們將來的天才卻特異的，別人系了圍裙狂跳時，他卻躲在繡房裡刺繡，——不，磨繡針。待到別人的圍裙全數破舊，他卻穿了繡花衫子站出來了。大家只好說道“阿！”可憐的性急的野蠻人，竟連圍裙也不知道換一條，怪不得銳氣終於脫盡；脫盡猶可，還要看那“笑吟吟”的“諷刺”的“天才”臉哩，這實在是對於靈魂的鞭責，雖說還在遼遠的將來。

還有更可怕的，是我們風聞二○二五年一到，陶孟和教授要發表一部著作。內容如何，只有百年後的我們的曾孫或玄孫們知道罷了，但幸而在《現代評論增刊》上提前發表了幾節，所以我們竟還能“管中窺豹”似的，略見這一部新書的大概。那是講“現代教育界的特色”的，連教員的“兼課”之多也說在內。他問：“我的議論太悲觀，太刻薄，太荒誕嗎？我深願受這個批評，假使事實可以證明。”這些批評我們且俟之百年之後，雖然那時也許無從知道事實；典籍呢，大概也只有“笑吟吟的”佳作留傳。要是當真這樣，那大半是“英雄所見略同”的，後人總不至於以為刻薄罷。但我們也難於懸揣，不過就今論今，似乎頗有些“孔子作《春秋》，而亂臣賊子懼”之意了。人們不逢如此盛事者，蓋已將二千四百年云。

總之，百年以內，將有陳源教授的許多（？）書，百年以後，將有陶孟和教授的一部書出現。內容雖然不知道怎樣，但據目下所走漏的風聲看起來，大概總是諷刺“那班出鋒頭的人們”，或“馳驅九城”的教授的。

我常常感歎，印度小乘教的方法何等厲害：它立了地獄之說，借著和尚，尼姑，念佛老嫗的嘴來宣揚，恐嚇異端，使心志不堅定者害怕。那訣竅是在說報應並非眼前，卻在將來百年之後，至少也須到銳氣脫盡之時。這時候你已經不能動彈了，只好聽別人擺佈，流下鬼淚，深悔生前之妄出鋒頭；

而且這時候，這才認識閻羅大王的尊嚴和偉大。

這些信仰，也許是迷信罷，但神道設教，于“挽世道而正人心”的事，或者也還是不無裨益。況且，未能將壞人“投界豺虎”於生前，當然也只好口誅筆伐之於身後，孔子一車兩馬，倦遊各國以還，抽出鋼筆來作《春秋》，蓋亦此志也。

但是，時代遷流了，到現在，我以為這些老玩意，也只好騙騙極端老實人。連鬧這些玩意兒的人們自己尚且未必信，更何況所謂壞人們。得罪人要受報應，平平常常，並不見得怎樣奇特，有時說些宛轉的話，是姑且客氣客氣的，何嘗想借此免於下地獄。這是無法可想的，在我們不從容的人們的世界中，實在沒有那許多工夫來擺臭紳士的臭架子了，要做就做，與其說明年喝酒，不如立刻喝水；待廿一世紀的剖撥戮屍，倒不如馬上就給他一個嘴巴。至於將來，自有後起的人們，決不是現在人即將來所謂古人的世界，如果還是現在的世界，中國就會完！

**** 陈源致周作人
     :PROPERTIES:
     :AUTHOR:   徐志摩
     :CUSTOM_ID: 19260120
     :END:

启明我兄：

绑了你的文章，读了你的信，又得了你的书，过好几天不曾回你，有罪有罪。你小伤风想早好了，借因在家中躲躲，也是好的。我想回南，偏逢道路难，这里俱乐部的重担就比是一件湿衣穿上了身再也脱不下来，同时人家在旁边笑话，苦脑得狠。你要我报答，给《语丝》一点东西，我还不敢随口答应，一来这副刊真不了每期得逼，这几时又特别来得笨，什么思想都凑和不上来，就想西湖看梅花去；二来我
不敢自信，我如其投稿不致再遭《语丝》同人的嫌（上回的耳朵！）；三来似乎曾听说《语丝》有它一致的文体，象我这烂拖拖的怕也镶不上。再说吧，也许有兴致给你们一碟杂碎，只是我得预先求你们诸大法家的宽容：

我妄想解围做和事老，谁想两头都碰钉子，还是你一边的软些，你只说无围可解；那一边可是大不高兴，唬得我再也不敢往下问，改天许还看得见闲话，等着看罢。同时我却还有一句老实话，启明兄以为是否？谑固然不碍，但不当近虐；新近有许多东西玩笑开得似乎太凶了。说来我还是不明白我们这几个少数人何以一定有吵架的必要。我呢，也许是这无怀氏之民的脾胃，老是想把事情的分别看小看没了的。就说西滢吧，我是完全信得过他的，就差笔头太尖酸些不肯让人，启明兄你如其信得过我，按我说，也就不该对西滢怀疑，说来还不是彼此都是朋友？也许真是我笨，你们争执的分量我始终不曾看清楚。等吧，下文还有哪，我想。

见到凤举盼代问《国民新报》的副刊可否送我看看？

志摩候候

方才看了半农的俏皮，别的我不管，有一条甚使我不安，就是凌女士那张图案，我不早就在《京副》上声明那完全是我疏忽之咎，与她毫不相干，事实如此，人家又是神经不比蠢男子冥玩，屡次来向我问罪，这真叫我狼狈万分。启明兄，你有法子替我解解围否？如有，万分的感谢。

**** 闲话的闲话之闲话引出来的几封信
     :PROPERTIES:
     :CUSTOM_ID: 19260130
     :AUTHOR:   陈源
     :END:

志摩：

前面几封信里说起了几次周岂明先生的令兄：鲁迅，即教育部佥事周树人先生的名字。这里似乎不能不提一提。其实，我把他们一口气说了，真有些冤屈了我们的岂明先生。他与他的令兄比较起来，真是小巫遇见了大巫。有人说，他们兄弟俩都有他们贵乡绍兴的刑名师爷的脾气。这话，岂明先生自己也好像曾有部分的承认。不过，我们得分别，一位是没有做过官的刑名师爷，一位是做了十几年官的刑名师爷。

鲁迅先生一下笔就想构陷人家的罪状。他不是减，就是加，不是断章取义，便捏造些事实。他是中国“思想界的权威者”，轻易得罪不得的。我既然说了这两句话，能不拿些证据来。可是他的文章，我看过了就放进了应该去的地方——说句体己话，我觉得它们就不应该从那里出来——手边却没有。只好随便举一两个例吧。好在他每篇文章都可以做很好的证据，要是你要看的话。

远一些的一个例。他说我同杨荫榆女士有亲戚朋友的关系，并且吃了她许多的酒饭。实在呢，我同杨女士非但不是亲戚，简直就完全不认识。直到前年在女师大代课的时候，才在开会的时候见过她五六面。从去年二月起我就没有去代课。我从那时起直到今天，也就没有在任何地方碰到过杨女士。近一些的一个例。我在《现代评论增刊》里泛论图书的重要。我说孤桐先生在他未下台以前发表的两篇文章里，这一层“他似乎没看到”（增刊六三页）。鲁迅先生在前一两星期的《语丝》里就轻轻的代我改为“听说孤桐先生倒是想到了这一节，曾经发表过文章，然而下台了，很可惜。”你看见吗，那刀笔吏的笔尖？

再举一个与我无关的例吧。李仲揆先生是我们相识人中一个最纯粹的学者，你是知道的。新近国立京师图书馆聘他为副馆长。他因为也许可以在北京弄出一个比较完美的科学图书馆来，也就答应了。可是北大的章程，教授不得兼差的。虽然许多教授兼二三个以至五六个重要的差使，李先生却向校长去告一年的假，在告假期内不支薪。他现在正在收束他的功课。他的副馆长的月薪不过二百五十元。你想一想，有几个肯这样干。然而鲁迅先生却一次再次的说他是“北大教授兼国立京师图书馆长，月薪至少五六百元的李四光。”

好了，不举例了。不过你要知道，就是这位鲁迅先生，他是中国“思想界的权威者”，“青年叛徒的首领”。

有人同我说，鲁迅先生缺乏的是一面大镜子，所以永远见不到他的尊容。我说他说错了，鲁迅先生的所以这样，正因为他有了一面大镜子。你见过赵子昂——是不是他？——画马的故事罢？他要画一个姿势，就对镜伏地做出那个姿势来。鲁迅先生的文章也是对了他的大镜子写的，没有一句骂人的话不能应用在他自己的身上。要是你不信，我可以同你打一个赌。

不是有一次一个报馆访员称我们为“文士”吗？鲁迅先生为了那名字几乎笑掉牙。可是后来某报天天鼓吹他是“思想界的权威者”，他倒又不笑了。

他没有一篇文章里不放几枝冷箭，但是他自己常常的说人“放冷箭”，并且说“放冷箭”是卑劣的行为。

他常常“散布流言”和“捏造事实”，如上面举出来的几个例，但是他自己又常常的骂人“散布流言”，“捏造事实”，并且承认那样是“下流”。

他常常的无故骂人，要是那人生气，他就说人家没有“幽默”。可是要是有人侵犯了他一言半语，他就跳到半天空，骂得你体无完肤——还不肯罢休。

他常常挖苦别人家抄袭。有一个学生抄了沫若的几句诗，他老先生骂得刻骨镂心的痛快。可是他自己的《中国小说史略》却就是根据日本人盐谷温的《支那文学概论讲话》里面的《小说》一部分。其实拿人家的著述做你自己的蓝本，本可以原谅，只要你书中有那样的声明。可是鲁迅先生就没有那样的声明。在我们看来，你自己做了不正当的事也就罢了，何苦再挖苦一个可怜的学生，可是他还尽量的把人家刻薄。“窃钩者诛，窃国者侯”，本是自古已有的道理。

他在《出了象牙之塔》的《后记》里，说起不愿译《文学者和政治家》一文的理由。他说“和中国现在的政客官僚们讲论此事，却是对牛弹琴；至于两方面的接近，在北京却时常有，几多丑态和恶行，都在这新而黑暗的阴影中开演，不过还想不出作者所说似的好招牌。”你看这才不愧为“青年叛徒的领袖”！他那种一见官僚便回头欲呕的神情，活现在纸上。可是啊，可是他现任教育部的佥事。据他自己的自传，他从民国元年便做了教育部的官，从没脱离过。所以袁世凯称帝，他在教育部，曹锟贿选，他在教育部，“代表无耻的彭永彝”做总长，他也在教育部，甚而至于“代表无耻的章士钊”免了他的职后，他还大嚷“佥事这一个官儿倒也并不算怎样的‘区区’”，怎么有人在那里钻谋补他的缺，怎样以为无足轻重的人是“慷他人之慨”，如是如是，这样这样……这像“青年叛徒的领袖”吗？其实一个人做官也不大要紧，做了官再装出这样的面孔来可叫人有些恶心吧了。现在又有人送他“土匪”的名号了。好一个“土匪”。

志摩，你看，这才是中国“青年叛徒的领袖”，中国的青年叛徒也可想而知了。这才是中国“思想界的权威者”，中国的思想界也就可想而知了。这才是中国的“土匪”……我不得不也来庆祝中国的土匪！

志摩，不要以为我又生气了。我不过觉得鲁迅先生是我们中间很可研究的一位大人物，所以不免扯了一大段吧了。可惜我只见过他一次，不能代他画一幅文字的像——这也是一种无聊的妄想罢了，不要以为我自信能画得出这样心理繁复的人物来。

说起画像，忽然想起了本月二十三日《京报副刊》里林语堂先生画的《鲁迅先生打叭儿狗图》。要是你没有看见过鲁迅先生，我劝你弄一份看看。你看他面上八字胡子，头上皮帽，身上厚厚的一件大氅，很可以表出一个官僚的神情来。不过林先生的打叭儿狗的想象好像差一点。我以为最好的想象是鲁迅先生张着嘴立在泥潭中，后面立着一群悻悻的狗，“一犬吠影，百犬吠声”，不是俗语么？可是千万不可忘了那叭儿狗，因为叭儿狗能今天跟了黑狗这样叫，明天跟了白狗那样叫，黑夜的时候还能在暗中猛不防的咬人家一口。

不写了，不写了。无聊的话也说够了。以上的二三千字已经够支持人家半年的攻击了。我现在也要说几句正经话了。

常常有人来问我，人家天天攻击我，他们不懂为什么。人家为什么攻击，我也不十分明了为什么。可是我为什么不回答，我是有理由的。

中国人私人相骂，谁的声音高就是谁的理由足。所以我宁可受些委屈，不愿意也不能与人相骂。打笔墨官司的时候，谁写得多，骂得下流，捏造得新奇就谁的理由大。所以我也宁可吃些亏，不愿意也不能与人家打官司。第一，我们不会捏造无中生有的事。第二，我们想不起那样的下流的字眼。第三，人家有的是闲功夫，好在衙门里没有别的事可做，我们不做事便没有饭吃。第四，人家能造种种的假名，看来好像人多势众，就是你所谓朋友也可用了假名来放两枝冷箭，我们却做不出这样的勾当。第五，他们的喽罗也实在多，我们虽然不是不认识人，可是他们既然对我们有几分信任，我们总不肯亦不忍鼓励他们去做这种无聊的事情。第六，他们有的是欢迎谩骂的报纸，我们觉得自己办的一个报纸如只能谩骂，还不如没有。

可是，志摩，还有一个顶大的原因。就是你所说的“漆黑一团”很容易把你围进去。我常常觉得我们现在走的是条狭窄险阻的小路，左面是一个广漠无际的泥潭，右面也是一片广漠无际的浮砂，前面是遥遥茫茫荫在薄雾的里面的目的地。泥潭里有的是已经陷下去的人，有的在浅处，有的已经没到了口鼻。他们在号着，叫着，笑着，骂着。你要是忍不住他们的诬辱，一停足，一回头，也许就会忘了你的目的地。你要是同他们一较量，你不能不失足，那时你再不设法拔你的脚出来，你也许会陷，陷，陷，直到没头没顶才完毕。这就是我一向不爱与人较量的理由。我觉得我们的才具虽小，我们的学问虽浅薄，究竟也有它们的适当的用处。烛火虽然没有多大的光，可是不能因为有了太阳便妄自菲薄，何况还没有太阳。所以我一向总想兢兢业业的向前走，总想不让暴戾之气占据我的心。可是，志摩，这次也危险得很了！这一次我想，我已经踏了两脚泥！我觉悟了。我大约不再打这样的笔墨官司了。

昨晚因为写另一篇文章，睡迟了，今天似乎有些发热。今天写了这封信，已经疲乏了。就打住吧。希望你恳切的指导我。

**** 我還不能「帶住」
     :PROPERTIES:
     :CUSTOM_ID: 19260207
     :END:

一月三十日《晨報副刊》上滿載著一些東西，現在有人稱它為「攻周專號」，真是些有趣的玩意兒，倒可以看見紳士的本色。不知怎的，今天的《晨副》忽然將這事結束，照例用通信，李四光教授開場白，徐志摩「詩哲」接後段，一唱一和，甩道「帶住！讓我們對著混鬥的雙方猛喝一聲，帶住！」了。還「聲明一句，本刊此後不登載對人攻擊的文字」云。

他們的什麼「閒話……閒話」問題，本與我沒有什麼鳥相干，「帶住」也好，放開也好，拉攏也好，自然大可以隨便玩把戲。但是，前幾天不是因為「令兄」關係，連我的「面孔」都攻擊過了麼？我本沒有去「混鬥」，倒是株連了我。現在我還沒有怎樣開口呢，怎麼忽然又要「帶住」了？從紳士們看來，這自然不過是「侵犯」了我「一言半語」，正無須「跳到半天空」，然而我其實也並沒有「跳到半天空」，只是還不能這樣地謹聽指揮，你要「帶住」了，我也就「帶住」。

對不起，那些文字我無心細看，「詩哲」所說的要點，似乎是這樣鬧下去，要失了大學教授的體統，丟了「負有指導青年重責的前輩」的醜，使學生不相信，青年不耐煩了。可憐可憐，有臭趕緊遮起來。「負有指導青年重責的前輩」，有這麼多的醜可丟，有那麼多的醜怕丟麼？用紳士服將「醜」層層包裹，裝著好面孔，就是教授，就是青年的導師麼？中國的青年不要高帽皮袍，裝腔作勢的導師；要並無偽飾，——

倘沒有，也得少有偽飾的導師。倘有戴著假面，以導師自居的，就得叫他除下來，否則，便將它撕下來，互相撕下來。撕得鮮血淋漓，臭架子打得粉碎，然後可以談後話。這時候，即使只值半文錢，卻是真價值；即使醜得要使人「噁心」，卻是真面目。略一揭開，便又趕忙裝進緞子盒裡去，雖然可以使人疑是鑽石，也可以猜作糞土，縱使外面滿貼著好招牌，法蘭斯呀，蕭伯訥呀，……毫不中用的！

李四光教授先勸我「十年讀書十年養氣」。還一句紳士話罷：盛意可感。書是讀過的，不止十年，氣也養過的，不到十年，可是讀也讀不好，養也養不好。我是李教授所早認為應當「投畀豺虎」者之一，此時本已不必溫言勸諭，說什麼「弄到人家無故受累」，難道真以為自己是「公理」的化身，判我以這樣巨罰之後，還要我叩謝天恩麼？還有，李教授以為我「東方文學家的風味，似乎格外的充足，……所以總要寫到露骨到底，才盡他的興會。」我自己的意見卻絕不同。我正因為生在東方，而且生在中國，所以「中庸」「穩妥」的餘毒，還淪肌浹髓，比起法國的勃羅亞——他簡直稱大報的記者為「蛆蟲」來——，真是「小巫見大巫」，使我自慚究竟不及白人之毒辣勇猛。即以李教授的事為例罷：一，因為我知道李教授是科學家，不很「打筆墨官司」的，所以只要可以不提，便不提；只因為要回敬貴會友一杯酒，這才說出「兼差」的事來。二，關於兼差和薪水一節，已在《語絲》（六五）上答覆了，但也還沒有「寫到露骨到底」。

我自己也知道，在中國，我的筆要算較為尖刻的，說話有時也不留情面。但我又知道人們怎樣地用了公理正義的美名，正人君子的徽號，溫良敦厚的假臉，流言公論的武器，吞吐曲折的文字，行私利己，使無刀無筆的弱者不得喘息。倘使我沒有這筆，也就是被欺侮到赴訴無門的一個；我覺悟了，所以要常用，尤其是用於使麒麟皮下露出馬腳。萬一那些虛偽者居然覺得一點痛苦，有些省悟，知道技倆也有窮時，少裝些假面目，則用了陳源教授的話來說，就是一個「教訓」。

只要誰露出真價值來，即使只值半文，我決不敢輕薄半句。但是，想用了串戲的方法來哄騙，那是不行的；我知道的，不和你們來敷衍。

「詩哲」為援助陳源教授起見，似乎引過羅曼羅蘭的話，大意是各人的身上都有鬼，但人卻只知道打別人身上的鬼。

沒有細看，說不清了，要是差不多，那就是一併承認了陳源教授的身上也有鬼，李四光教授自然也難逃。他們先前是自以為沒有鬼的。假使真知道了自己身上也有鬼，「帶住」的事可就容易辦了。只要不再串戲，不再擺臭架子，忘卻了你們的教授的頭銜，且不做指導青年的前輩，將你們的「公理」的旗插到「糞車」上去，將你們的紳士衣裝拋到「臭毛廁」裡去，除下假面具，赤條條地站出來說幾句真話就夠了！

**** 不是信
     :PROPERTIES:
     :CUSTOM_ID: 19260208
     :END:

一個朋友忽然寄給我一張《晨報副刊》，我就覺得有些特別，因為他是知道我懶得看這種東西的。但既然特別寄來了，姑且看題目罷：《關於下面一束通信告讀者們》。署名是：志摩。哈哈，這是寄來和我開玩笑的，我想；趕緊翻轉，便是幾封信，這寄那，那寄這，看了幾行，才知道似乎還是什麼「閒話……閒話」問題。這問題我僅知道一點兒，就是曾在新潮社看見陳源教授即西瀅先生的信，說及我「捏造的事實，傳佈的『流言』 ，本來已經說不勝說」。不禁好笑；人就苦於不能將自己的靈魂砍成醬，因此能有記憶，也因此而有感慨或滑稽。記得首先根據了「流言」，來判決楊蔭榆事件即女師大風潮的，正是這位西瀅先生，那大文便登在去年五月三十日發行的《現代評論》上。我不該生長「某籍」又在「某系」教書，所以也被歸入「暗中挑剔風潮」者之列，雖然他說還不相信，不過覺得可惜。在這裡聲明一句罷，以免讀者的誤解：「某系」雲者，大約是指國文系，不是說研究系。

那時我見了「流言」字樣，曾經很憤然，立刻加以駁正，雖然也很自愧沒有「十年讀書十年養氣的工夫」。不料過了半年，這些「流言」卻變成由我傳佈的了，自造自己的「流言」，這真是自己掘坑埋自己，不必說聰明人，便是傻子也想不通。倘說這回的所謂「流言」，並非關於「某籍某系」的，乃是關於不信「流言」的陳源教授的了，則我實在不知道陳教授有怎樣的被捏造的事實和流言在社會上傳佈。說起來慚愧煞人，我不赴宴會，很少往來，也不奔走，也不結什麼文藝學術的社團，實在最不合式於做捏造事實和傳佈流言的樞紐。只是弄弄筆墨是在所不免的，但也不肯以流言為根據，故意給它傳佈開來，雖然偶有些「耳食之言」，又大抵是無關大體的事；要是錯了，即使月久年深，也決不惜追加訂正，例如對於汪原放先生「已作古人」一案，其間竟隔了幾乎有兩年。——但這自然是只對於看過《熱風》的讀者說的。

這幾天，我的「捏……言」罪案，仿佛只等於曇花一現了，《一束通信》的主要部分中，似乎也承情沒有將我「流」進去，不過在後屁股的《西瀅致志摩》是附帶的對我的專論，雖然並非一案，卻因為親屬關係而滅族，或文字獄的株連一般。滅族呀，株連呀，又有點「刑名師爺」口吻了，其實這是事實，法家不過給他起了一個名，所謂「正人君子」是不肯說的，雖然不妨這樣做。此外如甲對乙先用流言，後來卻說乙製造流言這一類事，「刑名師爺」的筆下就簡括到只有兩個字：「反噬」。嗚呼，這實在形容得痛快淋漓。然而古語說，「察見淵魚者不祥」，所以「刑名師爺」總沒有好結果，這是我早經知道的。

我猜想那位寄給我《晨報副刊》的朋友的意思了：來刺激我，譏諷我，通知我的，還是要我也說幾句話呢？終於不得而知。好，好在現在正須還筆債，就用這一點事來搪塞一通罷，說話最方便的題目是《魯迅致bb》，既非根據學理和事實的論文，也不是「笑吟吟」的天才的諷刺，不過是私人通信而已，自己何嘗願意發表；無論怎麼說，糞坑也好，毛廁也好，決定與「人氣」無關。即不然，也是因為生氣發熱，被別人逼成的，正如別的副刊將被《晨報副刊》「逼死」一樣。我的鏡子真可恨，照出來的總是要使陳源教授嘔吐的東西，但若以趙子昂——「是不是他？」——畫馬為例，自然恐怕正是我自己。自己是沒有什麼要緊的，不過總得替bb想一想。現在不是要談到《西瀅致志摩》麼，那可是極其危險的事，一不小心就要跌入「泥潭中」，遇到「悻悻的狗」，暫時再也看不見「笑吟吟」。至少，一關涉陳源兩個字，你總不免要被公理家認為「某籍」，「某系」，「某党」，「嘍羅」，「重女輕男」……等；而且還得小心記住，倘有人說過他是文士，是法蘭斯，你便萬不可再用「文士」或「法蘭斯」字樣，否則，——自然，當然又有「某籍」……等等的嫌疑了，我何必如此陷害無辜，《魯迅致bb》決計不用，所以一直寫到這裡，還沒有題目，且待寫下去看罷。

我先前不是剛說我沒有「捏造事實」麼？那封信裡舉的卻有。說是我說他「同楊蔭榆女士有親戚朋友的關係，並且吃了她許多的酒飯」了，其實都不對。楊蔭榆女士的善於請酒，我說過的，或者別人也說過，並且偶見於新聞上。現在的有些公論家，自以為中立，其實卻偏，或者和事主倒有親戚，朋友，同學，同鄉，……等等關係，甚至於叨光了酒飯，我也說過的。這不是明明白白的麼，報社收津貼，連同業中也互訐過，但大家仍都自稱為公論。至於陳教授和楊女士是親戚而且吃了酒飯，那是陳教授自己連結起來的，我沒有說曾經吃酒飯，也不能保證未曾吃酒飯，沒有說他們是親戚，也不能保證他們不是親戚，大概不過是同鄉罷，但只要不是「某籍」，同鄉有什麼要緊呢。紹興有「刑名師爺」，紹興人便都是「刑名師爺」的例，是只適用於紹興的人們的。

我有時泛論一般現狀，而無意中觸著了別人的傷疤，實在是非常抱歉的事。但這也是沒法補救，除非我真去讀書養氣，一共廿年，被人們騙得老死牖下；或者自己甘心倒掉；或者遭了陰謀。即如上文雖然說明了他們是親戚並不是我說的話，但因為列舉的名詞太多了，「同鄉」兩字，也足以招人「生氣」，只要看自己憤然於「流言」中的「某籍」兩字，就可想而知。照此看來，這一回的說「叭兒狗」（《莽原半月刊》第一期），怕又有人猜想我是指著他自己，在那裡「悻悻」了。其實我不過是泛論，說社會上有神似這個東西的人，因此多說些它的主人：闊人，太監，太太，小姐。本以為這足見我是泛論了，名人們現在那裡還有肯跟太監的呢，但是有些人怕仍要忽略了這一層，各各認定了其中的主人之一，而以「叭兒狗」自命。時勢實在艱難，我似乎只有專講上帝，才可以免於危險，而這事又非我所長。但是，倘使所有的只是暴戾之氣，還是讓它儘量發出來罷，「一群悻悻的狗」，在後面也好，在對面也好。我也知道將什麼之氣都放在心裡，臉上筆下卻全都「笑吟吟」，是極其好看的；可是掘不得，小小的挖一個洞，便什麼之氣都出來了。但其實這倒是真面目。

第二種罪案是「近一些的一個例」，陳教授曾「泛論圖書館的重要」，「說孤桐先生在他未下臺以前發表的兩篇文章裡，這一層『他似乎沒看到』 。」我卻輕輕地改為「聽說孤桐先生倒是想到了這一節，曾經發表過文章，然而下臺了，很可惜」了。而且還問道：「你看見嗎，那刀筆吏的筆尖？」「刀筆吏」是不會有漏洞的，我卻與陳教授的原文不合，所以成了罪案，或者也就不成其為「刀筆吏」了罷。《現代評論》早已不見，全文無從查考，現在就據這一回的話，敬謹改正，為「據說孤桐先生在未下臺以前發表的文章裡竟也沒想到；現在又下了台，目前無法補救了，很可惜」罷。這裡附帶地聲明，我的文字中，大概是用別人的原文用引號，舉大意用「據說」，述聽來的類似「流言」的用「聽說」，和《晨報》大將文例不相同。

第三種罪案是關於我說「北大教授兼京師圖書館副館長月薪至少五六百元的李四光」的事，據說已告了一年的假，假期內不支薪，副館長的月薪又不過二百五十元。別一張《晨副》上又有本人的聲明，話也差不多，不過說月薪確有五百元，只是他「只拿二百五十元」，其餘的「捐予圖書館購買某種書籍」了。此外還給我許多忠告，這使我非常感謝，但願意奉還「文士」的稱號，我是不屬於這一類的。只是我以為告假和辭職不同，無論支薪與否，教授也仍然是教授，這是不待「刀筆吏」才能知道的。至於圖書館的月薪，我確信李教授（或副館長）現在每月「只拿二百五十元」的現錢，是美國那面的；中國這面的一半，真說不定要拖欠到什麼時候才有。但欠帳究竟也是錢，別人的兼差，大抵多是欠帳，連一半現錢也沒有，可是早成了有些論客的口實了，雖然其缺點是在不肯及早捐出去。我想，如果此後每月必發，而以學校欠薪作比例，中國的一半是明年的正月間會有的，倘以教育部欠俸作比例，則須十七年正月間才有，那時購買書籍來，我一定就更正，只要我還在做「官僚」，因為這容易得知，我也自信還有這樣的記性，不至於今年忘了去年事。但是，倘若又被章士釗們革掉，那就莫明其妙，更正的事也只好作罷了。可是我所說的職銜和錢數，在今日卻是事實。

第四種的罪案是……。陳源教授說，「好了，不舉例了。」

為什麼呢？大約是因為「本來已經說不勝說」，或者是在矯正「打筆墨官司的時候，誰寫得多，罵得下流，捏造得新奇就是誰的理由大」的惡習之故罷，所以就用三個例來概其全般，正如中國戲上用四個兵卒來象徵十萬大軍一樣。此後，就可以結束，漫駡——「正人君子」一定另有名稱，但我不知道，只好暫用這加於「下流」人等的行為上的話——了。原文很可以做「正人君子」的真相的標本，刪之可惜，扯下來粘在後面罷——

「有人同我說，魯迅先生缺乏的是一面大鏡子，所以永遠見不到他的尊容。我說他說錯了。魯迅先生的所以這樣，正因為他有了一面大鏡子。你聽見過趙子昂——是不是他？——畫馬的故事罷？他要畫一個姿勢，就對鏡伏地做出那個姿勢來。魯迅先生的文章也是對了他的大鏡子寫的，沒有一句罵人的話不能應用在他自己的身上。要是你不信，我可以同你打一個賭。」

這一段意思很了然，猶言我寫馬則自己就是馬，寫狗自己就是狗，說別人的缺點就是自己的缺點，寫法蘭斯自己就是法蘭斯，說「臭毛廁」自己就是臭毛廁，說別人和楊蔭榆女士同鄉，就是自己和她同鄉。趙子昂也實在可笑，要畫馬，看看真馬就夠了，何必定作畜生的姿勢；他終於還是人，並不淪入馬類，總算是僥倖的。不過趙子昂也是「某籍」，所以這也許還是一種「流言」，或自造，或那時的「正人君子」所造都說不定。這只能看作一種無稽之談。倘若陳源教授似的信以為真，自己也照樣做，則寫法蘭斯的時候坐下做一個法姿勢，講「孤桐先生」的時候立起作一個孤姿勢，倒還堂哉皇哉；可是講「糞車」也就得伏地變成糞車，說「毛廁」即須翻身充當便所，未免連臭架子也有些失掉罷，雖然肚子裡本來滿是這樣的貨色。

「不是有一次一個報館訪員稱我們為『文士』 嗎？魯迅先生為了那名字幾乎笑掉了牙。可是後來某報天天鼓吹他是『思想界的權威者』 他倒又不笑了。

「他沒有一篇文章裡不放幾枝冷箭，但是他自己常常的說人『放冷箭』 ，並且說『放冷箭』 是卑劣的行為。

「他常常『散佈流言』 和『捏造事實』 ，如上面舉出來的幾個例，但是他自己又常常的罵人『散佈流言』 『捏造事實』 ，並且承認那樣是『下流』 。

「他常常的無故罵人，要是那人生氣，他就說人家沒有『幽默』 。可是要是有人侵犯了他一言半語，他就跳到半天空，罵得你體無完膚——還不肯甘休。」

這是根據了三條例和一個趙子昂故事的結論。其實是稱別個為「文士」我也笑，稱我為「思想界的權威者」我也笑，但牙卻並非「笑掉」，據說是「打掉」的，這較可以使他們快意些。至於「思想界的權威者」等等，我連夜夢裡也沒有想做過，無奈我和「鼓吹」的人不相識，無從勸止他，不像唱雙簧的朋友，可以彼此心照；況且自然會有「文士」來罵倒，更無須自己費力。我也不想借這些頭銜去發財發福，有了它於實利上是並無什麼好處的。我也曾反對過將自己的小說采入教科書，怕的是教錯了青年，記得曾在報上發表；

不過這本不是對上流人說的，他們當然不知道。冷箭呢，先是不肯的，後來也放過幾枝，但總是對於先「放冷箭」用「流言」的如陳源教授之輩，「請君入甕」，也給他嘗嘗這滋味。不過雖然對於他們，也還是明說的時候多，例如《語絲》上的《音樂》就說明是指徐志摩先生，《我的籍和系》和《並非閒話》也分明對西瀅即陳源教授而發；此後也還要射，並無悔禍之心。至於署名，則去年以來只用一個，就是陳教授之所謂「魯迅，即教育部僉事周樹人」就是。但在下半年，應將「教育部僉事」五字刪去，因為被「孤桐先生」所革；今年卻又變了「暫署僉事」了，還未去做，然而豫備去做的，目的是在弄幾文俸錢，因為我祖宗沒有遺產，老婆沒有奩田，文章又不值錢，只好以此暫且糊口。還有一個小目的，是在對於以我去年的免官為「痛快」者，給他一個不舒服，使他恨得扒耳搔腮，忍不住露出本相。至於「流言」，則先已說過，正是陳源教授首先發明的專賣品，獨有他聽到過許多；在我呢，心術是看不見的東西，且勿說，我的躲在家裡的生活即不利於作「捏……言」的樞紐。剩下的只有「幽默」問題了，我又沒有說過這些話，也沒有主張過「幽默」，也許將這兩字連寫，今天還算第一回。我對人是「罵人」，人對我是「侵犯了一言半語」，這真使我記起我的同鄉「刑名師爺」來，而且還是弄著不正經的「出重出輕」的玩意兒的時候。這樣看來，一面鏡子確是該有的，無論生在那一縣。還有罪狀哩——

「他常常挖苦別人家抄襲。有一個學生鈔了沫若的幾句詩，他老先生罵得刻骨鏤心的痛快，可是他自己的《中國小說史略》，卻就是根據日本人鹽谷溫的《支那文學概論講話》裡面的『小說』 一部分。其實拿人家的著述做你自己的藍本，本可以原諒，只要你在書中有那樣的聲明，可是魯迅先生就沒有那樣的聲明。在我們看來，你自己做了不正當的事也就罷了，何苦再去挖苦一個可憐的學生，可是他還儘量的把人家刻薄。『竊鉤者誅，竊國者侯』 ，本是自古已有的道理。」

這「流言」早聽到過了；後來見於《閒話》，說是「整大本的摽竊」，但不直指我，而同時有些人的口頭上，卻相傳是指我的《中國小說史略》。

我相信陳源教授是一定會幹這樣勾當的。但他既不指名，我也就只回敬他一通駡街，這可實在不止「侵犯了他一言半語」。這回說出來了；我的「以小人之心」也沒有猜錯了「君子之腹」。但那罪名卻改為「做你自己的藍本」了，比先前輕得多，仿佛比自謙為「一言半語」的「冷箭」鈍了一點似的。鹽穀氏的書，確是我的參考書之一，我的《小說史略》二十八篇的第二篇，是根據它的，還有論《紅樓夢》的幾點和一張《賈氏系圖》，也是根據它的，但不過是大意，次序和意見就很不同。其他二十六篇，我都有我獨立的準備，證據是和他的所說還時常相反。例如現有的漢人小說，他以為真，我以為假；唐人小說的分類他據森槐南，我卻用我法。六朝小說他據《漢魏叢書》，我據別本及自己的輯本，這工夫曾經費去兩年多，稿本有十冊在這裡；唐人小說他據謬誤最多的《唐人說薈》，我是用《太平廣記》的，此外還一本一本搜起來……。其餘分量，取捨，考證的不同，尤難枚舉。自然，大致是不能不同的，例如他說漢後有唐，唐後有宋，我也這樣說，因為都以中國史實為「藍本」。我無法「捏造得新奇」，雖然塞文狄斯的事實和「四書」合成的時代也不妨創造。但我的意見，卻以為似乎不可，因為歷史和詩歌小說是兩樣的。詩歌小說雖有人說同是天才即不妨所見略同，所作相像，但我以為究竟也以獨創為貴；歷史則是紀事，固然不當偷成書，但也不必全兩樣。說詩歌小說相類不妨，歷史有幾點近似便是「摽竊」，那是「正人君子」的特別意見，只在以「一言半語」「侵犯」「魯迅先生」時才適用的。好在鹽穀氏的書聽說（！）已有人譯成（？）

中文，兩書的異點如何，怎樣「整大本的摽竊」，還是做「藍本」，不久（？）就可以明白了。在這以前，我以為恐怕連陳源教授自己也不知道這些底細，因為不過是聽來的「耳食之言」。不知道對不對？（鹽谷教授的《支那文學概論講話》的譯本，今年夏天看見了，將五百余頁的原書，譯成了薄薄的一本，那小說一部份，和我的也無從對比了。廣告上卻道「選譯」。措辭實在聰明得很。十月十四日補記。）

但我還要對於「一個學生鈔了沫若的幾句詩」這事說幾句話；「罵得刻骨鏤心的痛快」的，似乎並不是我。因為我于詩向不留心，所以也沒有看過「沫若的詩」，因此即更不知道別人的是否鈔襲。陳源教授的那些話，說得壞一點，就是「捏造事實」，故意挑撥別人對我的惡感，真可以說發揮著他的真本領。說得客氣一點呢，他自說寫這信時是在「發熱」，那一定是熱度太高，發了昏，忘記裝腔了，不幸顯出本相；並且因為自己爬著，所以覺得我「跳到半天空」，自己抓破了皮膚或者一向就破著，卻以為被我「罵」破了。——但是，我在有意或無意中碰破了一角紙糊紳士服，那也許倒是有的；此後也保不定。彼此迎面而來，總不免要擠擦，碰磕，也並非「還不肯甘休」。

紳士的跳踉醜態，實在特別好看，因為歷來隱藏蘊蓄著，所以一來就比下等人更濃厚。因這一回的放泄，我才悟到陳源教授大概是以為揭發叔華女士的剽竊小說圖畫的文章，也是我做的，所以早就將「大盜」兩字掛在「冷箭」上，射向「思想界的權威者」。殊不知這也不是我做的，我並不看這些小說。「琵亞詞侶」的畫，我是愛看的，但是沒有書，直到那「剽竊」問題發生後，才刺激我去買了一本Art of A. Beardsley來，化錢一元七。可憐教授的心目中所看見的並不是我的影，叫跳竟都白費了。遇見的「糞車」，也是境由心造的，正是自己腦子裡的貨色，要吐的唾沫，還是靜靜的咽下去罷。

太費紙張了，雖然我不至於嬌貴到會發熱，但也得趕緊的收梢。然而還得粘上一段大罪狀——

「據他自己的自傳，他從民國元年便做了教育部的官，從沒脫離過。所以袁世凱稱帝，他在教育部，曹錕賄選，他在教育部，『代表無恥的彭允彝做總長，他也在教育部，甚而至於『代表無恥的章士釗』 免了他的職後，他還大嚷『僉事這一個官兒倒也並不算怎樣的「區區」』 ，怎樣有人在那裡鑽謀補他的缺，怎樣以為無足輕重的人是『慷他人之慨』 ，如是如是，這樣這樣……這像『青年叛徒的領袖』 嗎？

「其實一個人做官也不大要緊，做了官再裝出這樣的面孔來可叫人有些噁心吧了。

「現在又有人送他『土匪』 的名號了。好一個『土匪』 。」

苦心孤詣給我加了上去的「土匪」的惡名，這一回忽又否認了，可見唾沫還是靜靜的咽下去好，免得後來自己舐回去。但是，「文士」別有慧心，那裡會給我便宜呢，自然即代以自「袁世凱稱帝」以來的罪惡，仿佛「稱帝」「賄選」那類事，我既在教育部，即等於全由我一手包辦似的。這是真的，從那時以來，我確沒有帶兵獨立過，但我也沒有冷笑雲南起義，也沒有希望國民軍失敗；對於教育部，其實是脫離過兩回，一是張勳復辟時，一就是章士釗長部時，前一回以教授的一點才力自然不知道，後一回卻忘卻得有些離奇。我向來就「裝出這樣的面孔」，不但毫不顧忌陳源教授可「有些噁心」，對於「孤桐先生」也一樣。要在我的面孔上尋出些有趣來，本來是沒頭腦的妄想，還是去看別的面孔罷。

這類誤解似乎不止陳源教授，有些人也往往如此，以為教員清高，官僚是卑下的。真所謂「得意忘形」，「官僚官僚」的罵著。可悲的就在此，現在的罵官僚的人裡面，到外國去炸大過一回而且做教員的就很多：所謂「鑽謀補他的缺」的也就是這一流，那時我說「僉事這一個官兒倒也並不算怎樣的『區區』 」，就為此人的乘機想做官而發，刺他一針，聊且快意，不提防竟又被陳教授「刻骨鏤心」的記住了，也許又疑心我向他在「放冷箭」了罷。

我並非因為自己是官僚，定要上儕于清高的教授之列，官僚的高下也因人而異，如所謂「孤桐先生」，做官時辦《甲寅》，佩服的人就很多，下臺之後，聽說更有生氣了。而我「下臺」時所做的文章，豈不是不但並不更有生氣，還招了陳源教授的一頓「教訓」，而且罪孽深重，延禍「面孔」了麼？

這是以文才和面孔言；至於從別一方面看，則官僚與教授就有「一丘之貉」之歎，這就是說：錢的來源。國家行政機關的事務官所得的所謂俸錢，國立學校的教授所得的所謂薪水，還不是同一來源，出於國庫的麼？在曹錕政府下做國立學校的教員，和做官的沒有大區別。難道教員的是捐給了學校，所以特別清高了？袁世凱稱帝時代，陳源教授或者還在外國的研究室裡，是到了曹錕賄選前後才做教授的，比我到北京遲得多，福氣也比我好得多。曹錕賄選，他做教授，「代表無恥的彭允彝做總長」，他做教授，「甚而至於『代表無恥的章士釗』 做總長」，他自然做教授，我可是被革掉了，甚而至於待到那「甚而至於『代表無恥的章士釗』 」不做總長了，他自然還做教授，歸國以來，一帆風順，一個小釘子也沒有碰。這當然是因為有適宜的面孔，不「叫人有些噁心」之故嘍。看他臉上既無我一樣的可厭的「八字鬍子」，也可以說沒有「官僚的神情」，所以對於他的面孔，卻連我也並沒有什麼大「噁心」，而且仿佛還覺得有趣。這一類的面孔，只要再白胖一點，也許在中國就不可多得了。

不免招我說幾句費話的不過是他對鏡裝成的姿勢和「爆發」出來的蘊蓄，但又即刻掩了起來，關上大門，據說「大約不再打這樣的筆墨官司」了。前面的香車既經杳然，我且不做叫門的事，因為這些時候所遇到的大概不過幾個家丁；而且已是往「國立北京女子師範大學複校紀念會」的時候了，就這樣的算收束。

**** 新文学运动以来的十部著作（上）
     :PROPERTIES:
     :AUTHOR:   陈源
     :CUSTOM_ID: 19260417
     :END:

十年以来——从民国六年一月《新青年》发表《文学改良刍议》起，直到现在，不是已经十年了吗？新文学的作品，要算短篇小说的出产顶多，也要算它的成绩顶好了。我要举的代表作品是郁达夫先生的《沉沦》，和鲁迅先生的《呐喊》。郁先生的作品，严格的说起来，简直是生活的片断，并没有多少短篇小说的格式。里面的主人，大都是一个放浪的，牢骚的，富于感情的，常常是坠落的青年。一篇文字开始时，我们往往不知道为什么那时才开始，收来时，也不知道为什么到那时就结束，因为在开始以先，在结束以后，我们知道还是有许多同样的情调，只要作者继续的写下去，几乎可以永远不绝的。所以有一次他把一篇没有写完的文章发表了，读书也不感缺少。有时他有意的想写一个有力的结束，好像《沉沦》那一篇，我们反感觉非常的不自然。他的小说虽然未免因此有些单调，可是他的力量也就在这里。他的小说里的主人翁可以说是现代的青年的一个代表，同时又是一个自有他生命的个性极强的青年。我们谁都认识他。鲁迅先生描写他回忆中的故乡的人民风物，都是很好的作品。可是《孔乙己》，《风波》，《故乡》里面的乡下人，虽然口吻举止，惟妙惟肖，还是一种外表的观察，皮毛的描写。我们记忆中的乡下人，许多就是那样的，虽然我们没有那本领写下来。到了《阿Q正传》就大不相同了。阿Q不仅是type，而且是一个活泼泼的人。他是与李逵，鲁智深，刘老老同样生动，同样有趣的人物，将来大约会同样的不朽的。（我不能因为我不尊敬鲁迅先生的人格，就不说他的小说好，我也不能因为佩服他的小说，就称赞他其余的文章。我觉得他的杂感，除了《热风》中二三篇外，实在没有一读的价值）

**** 無花的薔薇之三
     :PROPERTIES:
     :CUSTOM_ID: 19260517
     :END:

**１**

積在天津的紙張運不到北京，連印書也頗受戰爭的影響，我的舊雜感的結集《華蓋集》付印兩月了，排校還不到一半。

可惜先登了一個預告，以致引出陳源教授的「反廣告」來——

「我不能因為我不尊敬魯迅先生的人格，就不說他的小說好，我也不能因為佩服他的小說，就稱讚他其餘的文章。我覺得他的雜感，除了《熱風》中二三篇外，實在沒有一讀之價值。」（《現代評論》七十一，《閒話》。）

這多麼公平！原來我也是「今不如古」了；《華蓋集》的銷路，比起《熱風》來，恐怕要較為悲觀。而且，我的作小說，竟不料是和「人格」無關的。「非人格」的一種文字，像新聞記事一般的，倒會使教授「佩服」，中國又仿佛日見其光怪陸離了似的，然則「實在沒有一讀之價值」的雜感，也許還要存在罷。

**２**

做那有名的小說《Don Quijote》的M.de Cervantes先生，窮則有之，說他像叫化子，可不過是一種特別流行於中國學者間的流言。他說Don Quijote看遊俠小說看瘋了，便自己去做俠客，打不平。他的親人知道是書籍作的怪，就請了間壁的理髮匠來檢查；理髮匠選出幾部好的留下來，其餘的便都燒掉了。大概是燒掉的罷，記不清楚了；也忘了是多少種。想來，那些入選的「好書」的作家們，當時看了這小說裡的書單，怕總免不了要面紅耳赤地苦笑的罷。

中國雖然似乎日見其光怪陸離了。然而，烏乎哀哉！我們連「苦笑」也得不到。

**３**

有人從外省寄快信來問我平安否。他不熟於北京的情形，上了流言的當了。

北京的流言報，是從袁世凱稱帝，張勳復辟，章士釗「整頓學風」以還，一脈相傳，歷來如此的。現在自然也如此。

第一步曰：某方要封閉某校，捕拿某人某人了。這是造給某校某人看，恐嚇恐嚇的。

第二步曰：某校已空虛，某人已逃走了。這是造給某方看，煽動煽動的。

又一步曰：某方已搜檢甲校，將搜檢乙校了。這是恐嚇乙校，煽動某方的。

「平生不作虧心事，夜半敲門不吃驚。」乙校不自心虛，怎能給恐嚇呢？然而，少安毋躁罷。還有一步曰：乙校昨夜通宵達旦，將赤化書籍完全焚燒矣。

於是甲校更正，說並未搜檢；乙校更正，說並無此項書籍云。

**４**

於是連衛道的新聞記者，圓穩的大學校長也住進六國飯店，講公理的大報也摘去招牌，學校的號房也不賣《現代評論》：大有「火炎昆岡，玉石俱焚」之概了。

其實是不至於此的，我想。不過，謠言這東西，卻確是造謠者本心所希望的事實，我們可以借此看看一部分人的思想和行為。

**５**

中華民國九年七月直皖戰爭開手；八月，皖軍潰滅，徐樹錚等九人避入日本公使館。這時還點綴著一點小玩意，是有一些正人君子——不是現在的一些正人君子——去遊說直派武人，請他殺戮改革論者了。終於沒有結果；便是這事也早從人們的記憶上消去。但試去翻那年八月的《北京日報》，還可以看見一個大廣告，裡面是什麼大英雄得勝之後，必須廓清邪說，誅戮異端等類古色古香的名言。

那廣告是有署名的，在此也無須提出。但是，較之現在專躲在暗中的流言家，卻又不免令人有「今不如古」之感了。

我想，百年前比現在好，千年前比百年前好，萬年前比千年前好……特別在中國或者是確鑿的。

**６**

在報章的角落裡常看見對青年們的諄諄的教誡：敬惜字紙咧；留心國學咧；伊卜生這樣，羅曼羅蘭那樣咧。時候和文字是兩樣了，但含義卻使我覺得很耳熟：正如我年幼時所聽過的耆宿的教誡一般。

這可仿佛是「今不如古」的反證了。但是，世事都有例外，對於上一節所說的事，這也算作一個例外罷。


